kamailio/kamailio

Makefile
For some reason, I sometimes have obsolete `modules` -subdirectory in top level source directory.
It seems to happen after going back and forth in Kamailio 4.x git branches and then back to 5.x.
When that happens, Makefile target "modules" does not correctly start building:
```
$ gmake modules
gmake: 'modules' is up to date.
```
Proposed patch tries to draw attention into such situation:
```
$ gmake modules
Makefile:14: "old Kamailio modules directory found, you should clean that"
gmake: 'modules' is up to date.
```
I think `git clean` could clean such leftovers but I am not brave enough to propose running that automatically.
Tested on FreeBSD 11.2 (GNU Make 4.2.1) and Ubuntu 16.04 (GNU Make 4.1).
=> Makefile: give warning when old modules directory is found

src/modules/ipops/detailed_ip_type.c
Fixed typo in 172.16.0.0/12 network mask
=> ipops: Fixed mask for 172.16.0.0/12 network

src/modules/auth/api.h, src/modules/auth_ephemeral/authorize.c
This pull request adds AUTH_USERNAME_EXPIRED auth api return code and uses it in ephemeral authentication when username has expired.  Script can then tell the user about the expiration with a suitable response.
=> AUTH_USERNAME_EXPIRED auth api return code

src/modules/dialplan/dp_repl.c
If an AVP is used as subst_exp then each contained value is evaluated against the string.
In case a value doesn't match, a noisy error line was printed in the log. The patch fix this behavior in the following way:
- printing just a debug line per each not matching value
- printing an error line only if all the values fail the match
Additionally fixed the improper usage of match_exp instead of subst_exp when both values contain an AVP.
=> Small fixes to dialplan module when an avp is used as subst_exp

src/modules/http_async_client/README, src/modules/http_async_client/doc/http_async_client_admin.xml
Just small notes on $http_req(timeout) usage.
=> Small notes on $http_req(timeout) usage.

src/lib/srdb1/schema/location.xml, utils/kamctl/db_redis/kamailio/location
manual schema changes introduced at c9f2aa71b2e0d4a4f71b3da92f97306e86f93eea were lost by regeneration at 5e0440aa27154c263fc883f3a7cb9680805af6c3
This change sets the types changes at location for db_redis
=> db_redis: fix schema

src/modules/tls/Makefile, src/modules/tls/doc/tls.xml, src/modules/tls/utils/openssl_mutex_shared/Makefile, src/modules/tls/utils/openssl_mutex_shared/README.md, src/modules/tls/utils/openssl_mutex_shared/openssl_mutex_shared.c
Preloaded library to make libssl 1.1 use pthread locks with process shared option.
=> Preloaded library for openssl v1.1 process shared locking

src/modules/ndb_mongodb/mongodb_client.c
- Initialize mongodb c driver before any other mongo api call.
Without this, kamailio would crash with a segmentation fault.
This probably won't happen if a module was also already
being used with a db_mongodb setup.
This issue was initially reported here: https://lists.kamailio.org/pipermail/sr-users/2019-April/105382.html
=> ndb_mongodb: fix initialization crash

src/core/tcp_main.c
- [✓] Commit message has the format required by CONTRIBUTING guide
- [✓] Commits are split per component
- [✓] Each component has a single commit
- [✓] No commits to README files for modules
- [✓] Small bug fix (non-breaking change which fixes an issue)
- [✓] Tested changes locally
- [✓] Related to issue #1765
Macro constant UINT32_MAX is defined in <stdint.h>.
GCC and Clang does not complain on Ubuntu 16
GCC and Clang complains on FreeBSD 11.
Backporting not needed, PROXY feature only in development branch 5.3.
=> core: fix compilation error

src/modules/dialplan/dialplan.c, src/modules/dialplan/doc/dialplan_admin.xml
In commit 99d5da8d595961063249f871a5d150474fa6f317 a mechanism for basic safety in case of  concurent rpc reload were added. This works fine but it is limiting our test scenarios where multiple changes should happen quickly.
The new dialplan paramenter reload_delta allows everyone to configure rpc reload rate limit to the preferred number of seconds.
In case the parameter is not specified. the default value is 5 seconds.
=> dialplan: add reload_delta parameter

src/modules/usrloc/udomain.c
- [] Related to issue #XXXX (replace XXXX with an open issue number)
9757bb8c0e2fea5173f4fa3dd7798d61759f04af introduced a memory leak due to not cleaning all the ucontacts created at get_urecord() so every time that there are expired contacts in the db we will leave some ucontacts in shared mem and will be never free
This only happens on DB_ONLY mode
=> usrloc: udomain_contact_expired_cb fix memory leak

src/modules/siptrace/doc/siptrace_admin.xml, src/modules/siptrace/siptrace.c
New additions to siptrace module broke previous functionality.
If sip_trace was used with no param and destination uri was not set
then the current message would not have been traced to database. The
current fix traces always the current message if siptrace function
was called.
=> siptrace: fix tracing messages to database when destination uri not set

src/modules/dialplan/dialplan.c, src/modules/dialplan/dp_repl.c
```
INFO: <script>: SET_DST trying to get dialplan from dpid:101000 - ci'1cf77cbb5baebdbd0e8635e1116aa713@PBX-2797.xpbx.foehn.co.uk'
DEBUG: dialplan [dialplan.c:232]: dp_get_ivalue(): searching 15
DEBUG: dialplan [dialplan.c:240]: dp_get_ivalue(): dpid is 101000 from pv argument
DEBUG: dialplan [dialplan.c:249]: dp_get_svalue(): searching 7 
DEBUG: dialplan [dialplan.c:345]: dp_translate_f(): input is 0034654205681
DEBUG: dialplan [dp_repl.c:606]: dp_translate_helper(): regex operator testing over [0034654205681]
DEBUG: dialplan [dp_repl.c:681]: dp_translate_helper(): found a matching rule 0x7f065c2818d0: pr 1, match_exp ^00([1-9][0-35-9]|[1-35-9][0-9])[0-9]+$
DEBUG: dialplan [dp_repl.c:688]: dp_translate_helper(): the rule's attrs are cli=+34654205682;action=0
DEBUG: dialplan …
```
=> dialplan: don't try to translate on dp_match()

src/modules/ims_qos/ims_qos_mod.c
Upon receiving of the response with SDP __ims_qos__ performs AAA/AAR transaction 
where it puts IP address found in the original request. Sometimes this IP is wrong due to 
ims_qos reusing stale internal state that has a copy of original request.
This PR changes check to verify if response belongs to the saved request or internal state needs to be updated.
=> ims_qos: use msg_ctx_id_t to detect same msg/transaction processing

src/modules/siptrace/doc/siptrace_admin.xml, src/modules/siptrace/siptrace.c
Before this data was serialized in order to fit a normal AVP and
be passed to DLGCB_CREATED callback. Moreover for transaction tracing
data was allocated in current process memory which would have crashed
if the reply were to be recieved in a different process. With the
current implementation data is allocated in shared memory, all processes
having access to it.
For dialogs data is passed through xavp to dlgcb created. From
there all dialog callbacks are registered and they receive argument
the pointer to siptrace info. For transactions the pointer is passed
as dialog callback parameter.
=> siptrace: use xavps to pass data for the duration of transaction/dialog

src/modules/registrar/regpv.c
I was creating avp variables at route_event[usrloc:contact-expired] and shared memory was always growing I think this is the same issue #1391 and solved by ad46b115bedec01c52c5a9dcde0756db85ee61ec
=> registrar: clean avp/xavp created at 'usrloc:contact-expired' route_event

src/modules/usrloc/ul_rpc.c
release_urecord() needs to be called in order to clean ucontacts created on get_urecord() when mode is DB_ONLY
=> usrloc: fix memory leak on DB_ONLY mode on RPC commands

src/modules/dialog/dialog.c, src/modules/dialog/dlg_handlers.c, src/modules/dialog/dlg_handlers.h, src/modules/dialog/dlg_hash.c, src/modules/dialog/dlg_hash.h, src/modules/dialog/doc/dialog_admin.xml
The setting "keep_proxy_rr" will add the Record-Route headers added by the
proxy to the route_set stored in the dialog. When in use, sending locally
generated in-dialog requests will loop back to the proxy with a proper
Record-Route header, including any parameters.
=> dialog: Add setting to loop BYE through proxy

src/modules/evapi/evapi_dispatch.c
Right now, if there is no evapi client to send message then no logs are getting printed. This make us to not set the alert if send failed. After this changes if there is no evapi client we are going to get that in line like send_failed.
=> evapi:return code and log fixed for no evapi client while sending

src/modules/async/async_mod.c, src/modules/async/async_sleep.c, src/modules/async/async_sleep.h, src/modules/async/doc/async_admin.xml
- new ms_timer parameter to enable millisecond precision timer
- new async_ms_route and async_ms_sleep functions with milliseconds as a param
- implementation:
Each async_ms_sleep adds an entry to a linked list sorted by expiry time.
List is checked every ms_timer ms for expired entries.
All expired entries are pushed for execution on a pool of async workers.
This allows easy implementation of request traffic shaping with an external leaky bucket microservice
Assuring a maximum rate with no dropped requests by introducing delay.
=> async: added support for millisecond resolution sleep

src/core/cfg/cfg.c
What the affected line of code really wants to achieve is: if an
accepted inputs type mask is not specified then default to accepting
only the actual variable type. So we must mask the var type first,
then shift it by `CFG_INPUT_SHIFT`, before or-ing it with the rest.
What happened before was that the entire type was shifted, and that
included var type, input type and flags. What we end up with is some
additional higher bits set (for flags). I actually discovered this while
adding an additional flag that was meant to mark variables as private,
only accessible through an internal API (not available to modules such
as cfg_rpc).
=> core: Fix the cfg framework variable input type default

src/modules/rtpengine/rtpengine_db.c
Right now, if there is no rtpengine in the list while reload we are not freeing the memory for rtpengine handle.
=> Module:rtpengine: memory leak is fixed, if no rtpengine in list

src/modules/rtpengine/rtpengine.c
WIthout this fix, set_rtpengine_set(set1, set2) sets set1 twice and set2 not at all.
=> modules/rtpengine: set_rtpengine_set fix

src/modules/dialog/dlg_db_handler.c
When using a backend not supporting "NULL", like Redis, which store it as an empty string, xdata.s can be not null (it contains '\0'). This leads to an error trying to read it as a json document.
Not really a bug, but it leads to the error
"invalid json doc [[]]"
being printed each time a dialog is loaded from db (Redis).
=> dialog: check xdata length when loading profile from db

src/modules/dialog/dialog.c, src/modules/dialog/dlg_cb.c, src/modules/dialog/dlg_cb.h, src/modules/dialog/dlg_db_handler.c
When a specific dialog is loaded from db via dlg_db_load_callid, the load callbacks are not executed so, for example, a CDR is not generated.
No sure if this should considered a new feature or a bug (and so eventually be backported).
=> dialog: run DLGCB_LOADED callbacks when loading dialog from db

src/core/xavp.c
stop adding plus signs when serializing empty strings
github issue #2067
=> core: fix xavp_serialize_fields

src/core/xavp.c, src/core/xavp.h, src/modules/pv/doc/pv_admin.xml, src/modules/pv/pv.c
proposal for `xavp_copy()`
param1: source xavp name
param2: source xavp index
param3: destination xavp name
The command will copy only one specific xavp from the stack.
If the destination xavp stack exist it will append else it will create a new one, it seems to be more or less compatible to what we do with XAVP in general.
We can now reorder xavp stack like in the following example :
```
route[TEST] {
$xavp(a=>x) = "a-0-x";
$xavp(a[0]=>y) = "a-0-y";
$xavp(a=>x) = "a-1-x";
$xavp(a[0]=>y) = "a-1-y";
xinfo("$$xavp(a[0]) = [$xavp(a[0]=>x)][$xavp(a[0]=>y)]\n");
xinfo("$$xavp(a[1]) = [$xavp(a[1]=>x)][$xavp(a[1]=>y)]\n");
$var(src_idx) = 1;
$var(v) = "b";
xavp_copy("a", "$var(src_idx)", "$var(v)");
$var(src_idx) = 0;
xavp_copy("a", …
```
=> pv: adding xavp_copy

src/modules/ims_ipsec_pcscf/ipsec.c
Fixed that if `mnl_socket_bind` return error, the socket is leaking.
=> ims_ipsec_pcscf: fix non-close mnl_socket when a bind error

src/modules/kafka/Makefile, src/modules/kafka/doc/Makefile, src/modules/kafka/doc/kafka.xml, src/modules/kafka/doc/kafka_admin.xml, src/modules/kafka/kafka_mod.c, src/modules/kafka/kfk.c, src/modules/kafka/kfk.h
Module to produce and send messages to a Kafka server busing librdkafka library.
I copy part of README file here:
Chapter 1. Admin Guide
Table of Contents
1. Overview
2. Dependencies
2.1. Kamailio Modules
2.2. External Libraries or Applications
2.3. Parameters
2.3.1. brokers (string)
2.3.2. configuration (string)
2.3.3. topic (string)
2.4. Functions
2.4.1. kafka_send(topic, msg)
2.5. RPC Commands
2.5.1. kafka.stats
2.5.2. kafka.stats_topic
1. Overview
This module produces and sends messages to a Kafka server.
2. Dependencies
2.1. Kamailio Modules
2.2. External Libraries or Applications
2.3. Parameters
2.3.1. brokers (string)
2.3.2. configuration (string)
2.3.3. topic (string)
2.4. Functions
2.4.1. kafka_send(topic, msg)
2.5. RPC …
=> kafka: module to produce and send messages to a Kafka server

src/modules/ims_ipsec_pcscf/cmd.c
- fix leak socket when error handling errors in creation or destruction ipsec tunnel
Fixed socket leak on error during ipsec tunnel creation or destruction.
=> ims_ipsec_pcscf: closing mnl_socket in some exceptional situations

src/modules/ims_registrar_scscf/registrar_notify.c, src/modules/ims_registrar_scscf/usrloc_cb.c
- added a new line to the end of some debug logs for
better formatting.
=> ims_registrar_scscf: added '\n' for debug messages

src/modules/acc/acc_api.h, src/modules/acc/acc_cdr.c, src/modules/acc/acc_cdr.h, src/modules/acc/acc_logic.c, src/modules/acc/acc_logic.h, src/modules/acc/acc_mod.c, src/modules/acc_json/acc_json_mod.c, src/modules/acc_json/acc_json_mod.h, src/modules/acc_json/doc/acc_json_admin.xml
These commits create a CDR addressed engine, similar to the one that acc module exports for acc message accounting. Such an engine made an extension module like acc_json possible. This CDR engine is then used in acc_json to write the functionality for logging CDRs in JSON format.
I have added functions to the API exported by acc module instead of creating another separate CDR API, as I thought this is cleaner.
I only implemented the acc_json logging to syslog (no message queue support yet).
=> Adding CDR as JSON functionality 

src/core/parser/msg_parser.h, src/core/parser/parse_fline.c, src/core/parser/parse_fline.h
http_async_client module needs to parse http replies. Currently HTTP/2 is not supported by the core parser.
=> core: add support for parsing http/2 replies parsing

utils/db_berkeley/kambdb_recover.c
kambdb_recover.c: In function 'load_metadata_columns':
kambdb_recover.c:819:6: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
819 |  int ret,n,len;
|      ^~~
Fixed not used vars on Fedora 31
=> utils/db_berkeley: fixed unused var

src/modules/db_redis/redis_dbase.c
Previous version did not allow deletion of all rows in the table although this is allowed as described in section [9.2.9](http://www.asipto.com/pub/kamailio-devel-guide/#c09f_delete) of the Kamailio SIP Server v3.2.0 Development Guide. Former code always assumed filters would be involved so this change skips the filter matching if no filter is applied.
=> db_redis: allow deletion of all rows

src/core/error.h, src/modules/tm/uac.c
Currently it is not possible to drop a local generated message in tm:local-request event route because there is no context associated when running the event route. With this PR I tried to solve this introducing a new returned error (E_DROP) and a context into t_run_local_req.
=> tm: add support for dropping messages in local-request event route

utils/kamctl/kamdbctl
The POSIX sh(1) specification says that strings are compared with
test(1) (also "[") with "=".  Bash accepts "==" and this leads to
non-portable code.  This commit simply changes "==" within test/[ to
"=".
This changes instances of "==" as a an operator to test(1) to "=".
I have not yes tested running the script, because I am still working through issues to package kamailio in pkgsrc.  However, this patch avoids a lint-type warning from pkgsrc about non-portable shell script constructs.
=> utils: Change sh(1) "test ==" usage to "="

src/modules/registrar/doc/registrar_admin.xml, src/modules/registrar/lookup.c
Add path value to xavp_rcd. This is needed when checking if a subscriber is still registered
with a certain parameter in the path.
=> registrar: add path value to xavp_rcd

src/modules/dialog/dialog.c, src/modules/dialog/doc/dialog_admin.xml
- new dlg_reset_property() function is added to disable the previously enabled dialog module behaviour.
e.g. stop sending keep-alive OPTIONS messages.
=> dialog: add new dlg_reset_property function

src/modules/rtpengine/doc/rtpengine_admin.xml
=> rtpengine: doc typos

src/modules/tls/doc/params.xml, src/modules/tls/tls_cfg.c, src/modules/tls/tls_cfg.h, src/modules/tls/tls_config.c, src/modules/tls/tls_config.h, src/modules/tls/tls_domain.c, src/modules/tls/tls_domain.h, src/modules/tls/tls_mod.c, src/modules/tls/tls_rpc.c, src/modules/tls/tls_verify.c, src/modules/tls/tls_verify.h
Note: See below for more info about motivation of this feature.
- [ * ] Commit message has the format required by CONTRIBUTING guide
- [ * ] Commits are split per component (core, individual modules, libs, utils, ...)
- [ * ] Each component has a single commit (if not, squash them into one commit)
- [ * ] No commits to README files for modules (changes must be done to docbook files
- [ * ] New feature (non-breaking change which adds new functionality)
- [ * ] Tested changes locally
This feature aims to replace require_certificate and verify_certificate params with a single option, verify_client: 
* Provides flexibility: require_certificate and verify_certificate are both booleans, so there are only 4 max combinations of params, and …
=> tls: add verify_client support

src/modules/registrar/doc/registrar_admin.xml, src/modules/registrar/lookup.c, src/modules/registrar/lookup.h, src/modules/registrar/registrar.c, src/modules/registrar/registrar.h, src/modules/registrar/reply.c
As discussed on #2162 with this change it's possible to decide witch xavp_rcd values will be stored using the new module parameter xavp_rcd_mask
Using the same helper function on build_contact() so the behavior is consistant. Before only ruid and expires where stored when build_contact() was called.
=> registrar: add new xavp_rcd_mask parameter

src/modules/keepalive/api.h, src/modules/keepalive/doc/keepalive.xml, src/modules/keepalive/doc/keepalive_admin.xml, src/modules/keepalive/keepalive.h, src/modules/keepalive/keepalive_api.c, src/modules/keepalive/keepalive_core.c, src/modules/keepalive/keepalive_mod.c
added new function del_destination that deletes sip address from list
added add_destination module functions for kamailio.cfg
added counter parameter for attempt count. after count pass, module dont try until it adds again.
added kemi interfaces both of them
added lock to stack
added find_destination function
=> keepalive : added new function del_destination and added cfg functions

src/modules/tm/doc/functions.xml, src/modules/tm/t_serial.c, src/modules/tm/t_serial.h, src/modules/tm/tm.c
Extended t_load_contacts function with the parameter 'mode'.
It can be used to define the algorithm to use for ordering the contacts.
If 0, or missing, the standard algorithm with be used.
If 1, the new weight-based algorithm will be used.
The new algorithm uses the q value as the weight of the branch.
Higher is the q value, higher is the probability to be tried as first. Equals q values means equals probability to be tried.
Branches with q values equals to 0 or lower are not considered by the ordering algorithm, but just added at the end of the list as backup option if all other branches fail.
=> tm: new weight-based call-termination distribution

src/modules/ims_ipsec_pcscf/cmd.c, src/modules/ims_ipsec_pcscf/cmd.h, src/modules/ims_ipsec_pcscf/doc/ims_ipsec_pcscf_admin.xml, src/modules/ims_ipsec_pcscf/ims_ipsec_pcscf_mod.c
- added a new optional parameter in ipsec_forward()
to set or not 'send force socket' for request
messages. Useful for ipsec and tcp connections.
If set to 1 - send requests through existing
ipsec tunnel when tcp is used. In combination
with tcp_reuse_port=yes.
=> ims_ipsec_pcscf: new parameter in ipsec_forward()

src/modules/dmq_usrloc/dmq_usrloc.c, src/modules/dmq_usrloc/doc/dmq_usrloc_admin.xml, src/modules/dmq_usrloc/usrloc_sync.c
- replicate_socket_info using dmq through a new modparam
- useful for anycast scenarios
=> dmq_usrloc: replicate_socket_info using dmq

src/core/ppcfg.c, src/core/ppcfg.h, src/main.c
If the config doesn't have the same amount of if[n]def endif directives, don't start it
=> core: stop start if ifdef check fails

src/modules/avpops/avpops.c, src/modules/avpops/doc/avpops_admin.xml
Allow pvar as second parameter of avp_subst() function
=> avpops: avp_subst() support pvar as subst parameter

src/modules/xhttp_rpc/doc/xhttp_rpc_admin.xml
- The documentation in the README file had the
wrong module name in the modparam in the
example for the xhttp_rpc_buf_size parameter.
Corrected this in section 4.2.
=> xhttp_rpc: documentation correction

src/modules/tm/t_suspend.c
- t_continue() - do not print error and return error code.
- change func to log INFO so errors are not printed twice (once by tm and once by func call)
=> tm: t_continue() - do not print error and return error code

misc/examples/ims/pcscf/kamailio.cfg, misc/examples/ims/pcscf/pcscf.cfg.sample
Changes to example files for PCSCF in misc/examples/ims to make funcitional with current stable version.
Changes to example files for PCSCF in misc/examples/ims to make funcitional with current stable version.
Changes: 
- Loading IPsec module prior to IMS Usrloc PCSCF (Now required)
- removed modparam("ims_usrloc_pcscf", "hashing_type", 2) from example (This parameter was removed some time ago)
- Fix to formatting of single MySQL connection to work in current version
- Bind to any IP by default
- Dispatcher parameters only loaded if required
=> misc: examples; ims: Update kamailio.cfg example to function out of the box on current releases

src/modules/sipcapture/hep.c, src/modules/sipcapture/sipcapture.c
`$hep(...)` pseudovariable returns wrong values for keys `src_ip`, `dst_ip` and `0x001`. This patch removes the keys `src_ip` and `dst_ip` (`$si` resp. `$Ri` can be used for these values). `0x001` now correctly returns IP protocol family (`AF_INET`, `AF_INET6` ...).
Needs doc fixes on pseudovariable wiki page.
=> Sipcapture fix hep attributes

src/core/parser/msg_parser.c, src/modules/corex/corex_lib.c
Do the same for reset_path_vector() in core msg parser.
Hi,
Please have a look on this old discussion: https://lists.kamailio.org/pipermail/sr-dev/2018-July/047190.html
We have been using the shm_address_in() since then and no other apparent issue found since then.
Please let me know what you think. Also let me know if I can backport this to 5.3.
Thank you,
Stefan
=> corex: check not in SHM before PKG free for path

src/modules/registrar/config.c, src/modules/registrar/config.h, src/modules/registrar/doc/registrar_admin.xml, src/modules/registrar/lookup.c, src/modules/registrar/registrar.c
Allow/Disallow the usage of the expired contacts.
Useful when some problems happen with new REGISTERs; allow the usage
of old REGISTERed contacts.
Default value is 0 meaning "disallow the usage of the expired contacts".
(no changes to existing behavior)
Value can be set dinamically via:
kamcmd cfg.set_now_int registrar use_expired_contacts 1
=> registrar: add use_expired_contacts config param

src/modules/siptrace/doc/siptrace_admin.xml, src/modules/siptrace/siptrace.c, src/modules/siptrace/siptrace_hep.c
Allow duplicating messages via HEP over any configured protocol.
=> siptrace: duplicate via HEP with any protocol

src/modules/p_usrloc/config.c, src/modules/p_usrloc/doc/p_usrloc_admin.xml, src/modules/p_usrloc/location.sql, src/modules/p_usrloc/p_usrloc_mod.c, src/modules/p_usrloc/p_usrloc_mod.h, src/modules/p_usrloc/ucontact.c, src/modules/usrloc/usrloc.h
Add also new "uniq" column.
The new update function will use this new column.
=> p_usrloc: add new update function

src/modules/presence/doc/presence_admin.xml, src/modules/presence/hash.c, src/modules/presence/hash.h, src/modules/presence/presence.c
We have some user agents that make another subscribe with the same callid, when IP changes. Need to delete the old subscription in that case.
=> presence: add delete_same_subs modparam

src/Makefile.defs
- [ x] Each component has a single commit (if not, squash them into one commit)
- [ x] No commits to README files for modules (changes must be done to docbook files
- [ x] Small bug fix (non-breaking change which fixes an issue)
- [ x] PR should be backported to stable branches (5.3 would be nice; earlier doesn't help me)
This PR has two changes for building on NetBSD.
One is simply adding -lm to the link line for kamailio, as math functions are used.
The other is changing the use of -ldl to a variable, leaving that at -ldl most places, and setting it to empty on NetBSD.  (NetBSD does …
=> Small portability fixes (NetBSD)

src/modules/ratelimit/ratelimit.c
In our setup, we need one more ratelimit queue (in addition to the default of 10).
In this pull request, I am increasing the default number of ratelimit queus to 16.
Please let me know if this pull request is ok, or if I should do it via a modparam and dynamic allocation of ```static rl_queue_t queues```.
=> ratelimit: increase default number of queues

src/modules/kex/pkg_stats.c
Minor addition to output of RPC command pkg.stats, the description available next to PID and its memory utilization will help during monitoring of memory utilization(or leaks) by specific modules. Without name printed the PID was required to be matched with the output of "kamctl ps"
**Old output**:
```
{
entry: 2
pid: 13723
used: 2616752
free: 13180048
real_used: 3597168
total_size: 16777216
total_frags: 2
}
```
**New output:**
```
{
entry: 14
pid: 29413
rank: -1
used: 2615808
free: 13181200
real_used: 3596016
total_size: 16777216
total_frags: 1
desc: USRLOC Timer
}
```
=> kex: added process description for rpc command pkg.stats

src/modules/siptrace/siptrace.c
=> siptrace flag fixes

src/modules/dialog/dialog.c, src/modules/dialog/doc/dialog_admin.xml
alternative command to output dialogs data to file, far much faster than
dlg.list
This command can output 100K dialogs in less than a second.
Almost the exact same format as dlg.list, except no using arrays for `variables` and `profiles`
since they can have a mixture of values and key / value pairs.
```
{
"h_entry": 16383,
"h_id": 4428,
"ref": 2,
"call_id": "ehm839mk6HwtIXfCpluxkNlbDq8H9im2",
"from_uri": "sip:voip_perf@147.75.65.147",
"to_uri": "sip:12063722016@52.42.112.121",
"state": 4,
"start_ts": 1585863821,
"init_ts": 1585863821,
"end_ts": 0,
"timeout": 1585885421,
"lifetime": 21600,
"dflags": 1539,
"sflags": 0,
"iflags": 0,
"caller": {
"tag": "KK4KtrhQ--OjGMBNCvpXfKX-tinxQ3EK",
"contact": …
```
=> dialog: adding dlg.dump

src/modules/siptrace/siptrace.c
Testing with moderate load I had a crash in siptrace, in the newly added check for ACK for negative replies. Analyzing the core, the crash was caused by the invite transaction being 0x0 when t_gett is called after t_lookup_request. I was not able to reproduce it (how can t_lookup_request return 1 and then the transaction being 0x0?), but I've added a check to avoid crashing.
=> siptrace: safety check for transaction when checking ACK

src/modules/app_python3/Makefile
This commit
- removes the python calls whose output is never actually used.
- changes the include discovery to use python3(.x)-config. This is
preferable because it also works for cross-compiling. Calling
python3(.x) directly will always provide host flags, which for
cross-compiling is not feasible.
- updates LDFLAGS discovery to also work with >= Python 3.8. To
achieve this python3(.x)-config is first run with the argument
"--embed". If this does not succeed (exit status 1)
python3(.x)-config is run again without "--embed". This is the
method suggested by Python upstream to provide backwards
compatibility. See [1] for more details.
[1] https://docs.python.org/3/whatsnew/3.8.html
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net> …
=> app_python3: update Python3 detection mechanism

src/core/kemi.c, src/core/kemi.h, src/modules/app_lua/app_lua_api.c
Added ARRAY and DICT data types and implement support in app_lua
=> KEMI: add support for array and dict datatypes

src/modules/tls/tls_select.c
* Small bugfix
* Changes Tested locally
In addressing Daniel's comments on https://github.com/kamailio/kamailio/pull/2268#issuecomment-609935161, I realized that I misunderstood how select variables get resolved to data structures.
This patch fixes the sel_ssl_cert() implementation so that $sel(@tls.my.raw_cert), $sel(@tls.my.urlencoded_cert), $sel(@tls.peer.raw_cert), and $sel(@tls.peer.urlencoded_cert) all evaluate to expected outputs.
=> tls: fix raw vs urlencoded behavior in sel_ssl_cert()

src/modules/tls/tls_select.c
* New Feature
* Changes Tested Locally
This sel variable allows a kam script to get access to not just the peer certificate (at index 0), but when a certificate is successfully verified, the entire chain of certificates that were used to verify the peer certificate (at index 1, 2, 3, etc).
This functionality is provided by OpenSSL's SSL_get0_verified_chain() function, which is only available in OpenSSL 1.1.0+ (which is why there is an #if for this feature)
This is important when a server trusts many CAs - without this addition, I don't think that it is definitively possible to tell which CA signed the verified certificate, leading to security issues if one of the trusted CAs was compromised and was used to sign certificates that look like they were signed by another issuing CA.
=> tls: add sel for tls verified cert chain (requires OpenSSL 1.1+)

src/modules/ims_registrar_scscf/registrar_notify.c, src/modules/ims_registrar_scscf/registrar_notify.h
- Prevent multiple contacts for NOTIFY message in
Message body <registration> tag after
RE-REGISTRATION procedure.
=> ims_registrar_scscf: fix multiple contacts in NOTIFY

src/modules/siptrace/siptrace.c
When tracing a faked reply (like 200 for CANCEL), the sip msg used to retrieve the tracing parameters is the transaction's uas one (uas.request) which might have the from header parsed or not, depending on the routing script actions (by default, if I'm not wrong, it is not parsed). If the header is not parsed, calling get_from in trace_onreply_out function will lead to a memory leak, beacause the header is parsed in pkg memory not freed when the transaction is deleted.
=> siptrace: siptrace: fix memory leak in fake replies tracing

src/core/tcp_main.c
In case the first lookup (with tcp id) is not successful, the second
attempt should have been performed without a tcp id.
Issue was introduced with dc43750644 (new global parameter
tcp_connection_match) in 5.3.
=> core: do not use tcp id for lookup if not needed

src/modules/keepalive/doc/keepalive_admin.xml, src/modules/keepalive/keepalive_core.c
Recently a new parameter `delete_counter` was added. There is no way to ignore it, (just set a really big number could serve as a workaround).
This is a small change to ignore it if `delete_counter` if is set to 0.
=> keepalive: ignore delete_counter if it is set to 0

src/modules/drouting/drouting.c, src/modules/keepalive/api.h, src/modules/keepalive/doc/keepalive.xml, src/modules/keepalive/doc/keepalive_devel.xml, src/modules/keepalive/keepalive.h, src/modules/keepalive/keepalive_api.c, src/modules/keepalive/keepalive_core.c, src/modules/keepalive/keepalive_mod.c, src/modules/keepalive/keepalive_rpc.c
- This functionality it's just available when using api.h bindings. For exported functions current value ka_ping_interval is used.
- Modified add_destination function to provide this new parameter.
- Now we have one timer per destination, instead of multiple, so we don't need to iterate over all destinations. Timers are cleaned when destinations are removed.
With this code, you can have a different pinging timeout for each destination, instead of the fixed (default 30 seconds) one. 
This change is compatible (not breaking) with .cfg or kemi invocations, but it's breaking developers api.
=> keepalive: custom pinging interval per destination

src/modules/ndb_redis/redis_client.c
from https://github.com/redis/hiredis#using-replies
> The standard replies that redisCommand are of the type redisReply. The type field in the redisReply should be used to test what kind of reply was received:
> 
> - REDIS_REPLY_STATUS:
>   The command replied with a status reply. The status string can be accessed using reply->str. The length of this string can be accessed using reply->len.
> 
>  - REDIS_REPLY_ERROR:
>     The command replied with an error. The error string can be accessed identical to REDIS_REPLY_STATUS.
adding checks for the reply type to detect command errors
=> ndb_redis: redis_cmd() check reply type to detect command errors

src/modules/ims_registrar_scscf/lookup.c
- Generate AoR in lookup() from parsed uri user and
host. Skipping all user's and host's parameters.
=> ims_registrar_scscf: fix aor generation in lookup()

src/modules/ndb_redis/redis_client.c
This PR replicates sentinel logic added in initial redis connection (via cc8e621) into reconnection function.
This way, in case of loosing connection with Redis, Kamailio will be able to reconnect to redis asking to sentinel servers defined in modparams.
=> ndb_redis: add sentinel support to reconnection logic

src/modules/keepalive/keepalive.h, src/modules/keepalive/keepalive_api.c, src/modules/keepalive/keepalive_core.c
- Current code takes some time to start checking (ping_interval). So, if someone sets a really high ping_interval it takes a while to get destination status. This change fires the first OPTIONS check just 3 seconds (fixed) after the destination is added. The checks would be done with the pace defined in ping_interval.
Current code takes some time to start checking (ping_interval). So, if someone sets a really high ping_interval it takes a while to get destination status. This change fires the first OPTIONS check just 3 seconds (fixed) after the destination is added. The checks would be done with the pace defined in ping_interval.
=> keepalive: early start of OPTIONS checking

src/modules/ims_registrar_scscf/registrar_notify.c, src/modules/ims_registrar_scscf/registrar_notify.h, src/modules/ims_registrar_scscf/reply.c, src/modules/ims_registrar_scscf/reply.h, src/modules/ims_registrar_scscf/save.c, src/modules/ims_registrar_scscf/usrloc_cb.c
- Prevent sending of multiple contacts in 200OK reply
for UE Re-Registration. Now S-CSCF replies with the
exact contact for Re-Registration.
=> ims_registrar_scscf: fix multiple contacts in 200OK

src/modules/dispatcher/dispatch.c, src/modules/dispatcher/dispatch.h, src/modules/dispatcher/dispatcher.c, src/modules/dispatcher/doc/dispatcher_admin.xml
Expands the rpc 'add' command allowing to specify the "attrs" body.
=> dispatcher: add attrs param to rpc 'add' call

src/core/pvar.h, src/core/receive.c, src/core/xavp.c, src/core/xavp.h, src/modules/pv/doc/pv_admin.xml, src/modules/pv/pv.c, src/modules/pv/pv_xavp.c, src/modules/pv/pv_xavp.h, src/modules/tm/h_table.c, src/modules/tm/h_table.h, src/modules/tm/t_hooks.c, src/modules/tm/t_reply.c
This change introduces a new type of variable $xavi - eXtended Attribute Value Insensitive case.
It's like a $xavp but keys are case insensitive:
```
$xavi(WhatEver=>fOo) = 1;
if($xavi(whatever[0]=>foo) == 1) {
....
}
```
=> $xavi(...) 

src/core/pvapi.c, src/core/pvar.h, src/modules/pv/pv_core.c
if index is 0 there were no way to know if the index was there
$x_hdr(A) = "value" needs to append a value
$(x_hdr(A)[0]) = "value" needs to set the value
pv_parse_spec(str *s, pv_spec_p p) was always setting p->pvp.pvi.type
to 0 == PV_IDX_INT
=> core: PV_IDX_NONE to point that pv had no index

misc/tools/kemi/python_mock/README.md, misc/tools/kemi/python_mock/kemi_mock.py, misc/tools/kemi/python_mock/test.py
=> tools/kemi: add script to generate mock api for kemi python testing

src/modules/acc/acc_cdr.c, src/modules/acc/acc_mod.c, src/modules/acc/acc_mod.h, src/modules/acc/doc/acc_admin.xml
This PR allows excluding certain calls from CDRs in Kamailio route logic:
-  adds a new modparam called _cdr_skip_ to **acc** module
- dialogs ended with chosen dlg_var set (no matter the value) won't generate a CDR even though _cdr_enable_ modparam is set.
- both database and log CDR will be prevented.
=> acc: new skip_cdr modparam to prevent cdr generation

src/modules/dmq_usrloc/dmq_usrloc.c, src/modules/dmq_usrloc/doc/dmq_usrloc.xml, src/modules/dmq_usrloc/doc/dmq_usrloc_admin.xml, src/modules/dmq_usrloc/usrloc_sync.c
in high volume systems with ephemeral user location data (e.g. very low expiration times on user location records), the user location delete action can cause a high amount of DMQ traffic when UAs unregister. This new parameter allows the user location `delete` action to be disabled from being shared across DMQ nodes which helps reduce DMQ traffic on systems with high register/unregister rates and low expiration times.
=> dmq_usrloc: add new parameter `usrloc_delete` to disable synchronizing delete actions

src/modules/dialog/dlg_handlers.c
adding the call-id will allow users to better trace when they see the warning message:
```WARNING: dialog [dlg_handlers.c:1322]: dlg_onroute(): unable to find dialog...```
=> dialog: improve warning message to help better identify dialog lookup failures

src/modules/mohqueue/mohq_funcs.c
make sure transaction exists with `t_newtran()` and use `t_release_transaction()` instead of `t_release()`
=> mohqueue: use t_newtran() if transaction does not exist

src/modules/dispatcher/doc/dispatcher.cfg, src/modules/dispatcher/doc/dispatcher.xml, src/modules/dispatcher/doc/dispatcher_admin.xml, src/modules/dispatcher/doc/dispatcher_faq.xml
I have
- fixed DocBook validator warnings;
- space formatting;
- simplified route[WITHINDLG]
=> dipatcher: dockbook and config formatting

src/modules/mqueue/Makefile, src/modules/mqueue/doc/mqueue.xml, src/modules/mqueue/doc/mqueue_admin.xml, src/modules/mqueue/mqueue_api.c, src/modules/mqueue/mqueue_api.h, src/modules/mqueue/mqueue_db.c, src/modules/mqueue/mqueue_db.h, src/modules/mqueue/mqueue_mod.c
- adding support for persistent mqueue in a DB
```
modparam("mqueue", "db_url", "sqlite:////kamailio_db/mqueue.sqlite")
modparam("mqueue", "mqueue", "name=acc_events;size=1000000;dbmode=1")
modparam("acc_json", "output_mqueue", "acc_events")
```
=> mqueue: add support for db persistency

src/modules/tcpops/tcpops_mod.c
Adding the additional flag PV_TYPE_INT fixed the issue i reported on https://github.com/kamailio/kamailio/issues/2382
=> tcpops: target variable passed on tcp_get_conid function was empty

src/core/dset.c, src/core/dset.h, src/modules/nathelper/doc/nathelper_admin.xml, src/modules/nathelper/nathelper.c
add support for trimming an already existing alias parameter when calling `set_contact_alias()`
=> nathelper: add optional set_contact_alias([trim]) parameter

src/core/receive.c
when handling non sip messages in a module thru the callback, if we return `NONSIP_MSG_DROP` the tcp/websocket connection is closed. this was observed when receiving non sip messages with websocket module.
=> core: don't close tcp connection for dropped non sip messages

src/core/events.c, src/core/events.h, src/modules/websocket/ws_conn.c
allow kamailio modules to be notified when a websocket is closed without depending on script callbacks.
this allows for multiple independent modules to subscribe to new core event `SREV_TCP_WS_CLOSE`
=> core websocket close event

src/modules/p_usrloc/p_usrloc_mod.c, src/modules/p_usrloc/p_usrloc_mod.h, src/modules/p_usrloc/ul_db.c, src/modules/p_usrloc/ul_db_watch.c, src/modules/p_usrloc/ul_db_watch.h
- simplify general implementation
- avoid deadlock due to a process trying to acquire same lock twice
On a timer, checking the availability of the master db used for writing and setting a status variable accordingly. In case the mdb_availability_control option is set, this status variable is consulted with no synchronization by each process when trying to do a write to the master db. As error mitigation, in case the per process handle associated with master db is NULL, p_usrlock recreates it. In case the per process handle is not NULL, Kamailio will try to recreate a broken connection by itself.
=> p_usrloc: reworking mdb_availability_control

src/core/cfg.lex, src/core/cfg.y, src/core/cfg_core.c, src/core/cfg_core.h, src/core/parser/msg_parser.c, src/core/parser/parse_fline.c, src/core/receive.c
when handling non sip messages, parser errors are logged at core level which defaults to ERR.
since this may induce in error sysops or log scanners, sometimes the core level is set to debug just to omit these
messages from log, which is not good since other messages are omitted too.
this commit adds a new core variable to set the log level for message parsing errors.
this way, we can explicitly set the log level for message parsing while leaving the core level at ERR.
=> core: add sip_parser_log core variable

src/modules/ims_registrar_scscf/cxdx_callbacks.c, src/modules/ims_registrar_scscf/reg_rpc.c, src/modules/ims_registrar_scscf/registrar_notify.c, src/modules/ims_registrar_scscf/registrar_notify.h, src/modules/ims_registrar_scscf/save.c, src/modules/ims_registrar_scscf/usrloc_cb.c, src/modules/ims_usrloc_scscf/impurecord.c, src/modules/ims_usrloc_scscf/udomain.c, src/modules/ims_usrloc_scscf/usrloc.h
=> Ims scscf notify improvements

src/modules/pua/pua_db.c
* only relevant when db_mode is PUA_DB_ONLY
* call_id/to_tag/from_tag values can be "", for instance with
DIALOG_PUBLISH.* records. Then **ALL** records get version
field update
* update_vesion_puadb() is called from send_publish() and pres->id
value is valid after a call to get_record_puadb()
=> pua: update_version_puadb() use pres_id to select record

src/modules/siptrace/siptrace.c
`ctx` was not getting initialized with the result of `run_top_route()` execution preventing `drop();` to work in the `siptrace:msg` event route
=> siptrace: fix drop() usage in siptrace:msg event route

src/modules/ims_ipsec_pcscf/cmd.c, src/modules/ims_ipsec_pcscf/cmd.h, src/modules/ims_ipsec_pcscf/doc/ims_ipsec_pcscf_admin.xml, src/modules/ims_ipsec_pcscf/ims_ipsec_pcscf_mod.c, src/modules/ims_ipsec_pcscf/ipsec.c, src/modules/ims_ipsec_pcscf/ipsec.h, src/modules/ims_usrloc_pcscf/dlist.c
=> Ims ipsec delete unused tunnels

src/modules/async/async_mod.c
async_ms_route currently does not work, because w_async_ms_route calls ki_async_route instead of ki_async_ms_route.
This PR also exports ki_async_ms_route to kemi.
I've noticed that other async functions (async_sleep and async_ms_sleep) are not exposed via kemi. Should they be added?
=> async: fix async_ms_route and export it to kemi

src/modules/acc/acc.c, src/modules/acc/acc_api.h, src/modules/acc/acc_logic.c
When doing t_reply/send_reply stateful, the ACC module will not add the to-tag to the ACC events.
This patch will fix this and ensure that we get the to-tag that was locally generated used in the reply.
example :
```
modparam("acc", "acc_prepare_always", 1)
modparam("acc_json", "acc_missed_flag", 6)
failure_route[test] {
setflag(6); // MISSED_ACC, the failure will be recorded by ACC
t_flush_flags(); // This will set the flags in the newly created transaction
t_reply("500", "Service Unavailable");
}
```
This does generate an ACC event, however the to-tag is not populated, my guess this is because the TM callback is done before the to-tag is generated.
This patch will populate the to-tag immediately.
=> acc: add to-tag for locally generated replies

src/modules/keepalive/keepalive.h, src/modules/keepalive/keepalive_api.c, src/modules/keepalive/keepalive_core.c, src/modules/keepalive/keepalive_mod.c
- This avoids a race condition that may happen processing tm_request callbacl
- Allows to identify uniquely a ka_dest record
Check issue
=> keepalive: added uuid to ka_dest structure to avoid passing the whole struct to tm

src/modules/dialog/dlg_hash.c
Based on the email thread :
```
[SR-Users] Dialog - timeout for dlg with CallID
```
Several users are facing unexpected dialog disconnection caused by no-ack timer.
Using a modified version of the dialog module to improve debug-ability 
https://github.com/kamailio/kamailio/pull/2483
I was able to confirm at least one problem and after looking at the trace, it seems like dialog mismatch with a serial forking scenario :
- log line 3 is telling us that a NO-ACK disconnection should be triggered
- log line 1-2 is telling us what happened when the ACK was received in dlg_onroute(), oddly enough state 5 was old and new, could it be a mismatch/confusio with the previous dialog, looking in this direction ...
```
1: 2020-09-25T16:30:16.896: …
```
=> dialog: dlg_cell, always check for a to-tag match

src/modules/dispatcher/dispatch.c
training of the latency estimator
minor issue with the estimator initialization / training
=> dispatcher: fix an error in initialisation 

README.md, src/lib/srdb1/schema/carrierfailureroute.xml, src/modules/app_jsdt/duktape.c, src/modules/avp/avp.xml, src/modules/carrierroute/doc/carrierroute_db.xml, src/modules/counters/counters.c, src/modules/cplc/doc/cplc_admin.xml, src/modules/db_mongodb/doc/db_mongodb_admin.xml, src/modules/drouting/doc/drouting_admin.xml, src/modules/ims_qos/rx_aar.c, src/modules/sca/NOTES, src/modules/tm/doc/functions.xml, src/modules/websocket/doc/websocket_admin.xml, src/modules/xmpp/doc/xmpp_admin.xml
Remove consecutive ocurrences of 'the' across the repo
=> Fix typos: Remove consecutive occurrences of 'the'

src/modules/nathelper/doc/nathelper_admin.xml, src/modules/nathelper/nathelper.c
- GH #2459
fix_nated_sdp() function with flags 0x02 and 0x08 and an IP address as argument (or without one) does modify the media line and the connection line. In addition it will modify IP address in "a=rtcp" parameter (rfc3605) in case if there is one. If a=rtcp param is not found the function doesn't return -1, but prints a DBG message and continues to execute (changing c= or o= lines)
=> nathelper: fix_nated_sdp added support for a=rtcp param RFC3605

src/modules/registrar/doc/registrar_admin.xml, src/modules/registrar/registrar.c, src/modules/registrar/registrar.h, src/modules/registrar/save.c
This feature was made half year ago. We would like to have inside location record address of the host where kamailio is installed. However when we installed it behind NAT we got private address in this field. 
This feature introduces possibility to set a socket string which will be written into location record. It could be public address instead address on which the register request was received. The default value is NULL and it works as usual. The feature was installed on our production servers in April and since that time it works well. I would like to propose this feature to others, because it could be useful.
=> registrar: added new parameter sock_addr

src/core/ip_addr.h, src/core/tcp_conn.h, src/core/tcp_read.c, src/core/tcp_read.h, src/core/tls_hooks.h, src/modules/tls/tls_server.c, src/modules/tls/tls_server.h
Redefine some flags as enum instead of separate define. This makes it easier to see what flags are accepted by functions and with the right compiler flags, the compiler will warn when the wrong flags are used.
No functional changes are intended.
=> core: Redefine flags as enum

src/modules/textops/textops.c
append after last eader occurance
=> textops: fix append_hf function

src/modules/jansson/doc/jansson_admin.xml, src/modules/jansson/jansson_funcs.c, src/modules/jansson/jansson_funcs.h, src/modules/jansson/jansson_mod.c, src/modules/jansson/jansson_utils.c, src/modules/jansson/jansson_utils.h
Add functions to encode and decode JSON from/to an xavp
=> jansson: Add en-/decode to/from xavp

src/modules/misc_radius/radius.h
freeradius-client removed the `VENDOR()` definition after commit https://github.com/FreeRADIUS/freeradius-client/commit/50d78bb53f4f341aa708e196b8955cacbae59669, since a new way was added in the library to separate vendor attributes. Currently `(((x) >> 8) & 0xffffff)` to determine vendor id works but is considered old-style. This PR adds the `VENDOR()` definition back if the freeradius-client library we are linking against is after 50d78b.
=> auth_radius, misc_radius: Adds VENDOR() definition if the freeradius-client.h does not contain one

src/modules/sl/sl_stats.c
The struct_add() method was getting 4 values but only 3 "d".
=> sl: Fix 3xx stats RPC marshalling

src/modules/dispatcher/dispatch.c, src/modules/dispatcher/dispatch.h, src/modules/dispatcher/doc/dispatcher_admin.xml
Previously discussed in the mailing list  : 
**“13” - latency optimized dispatching .** 
- The algorithm will load balance using round-robin prioritizing the gateways with the highest priority.
- If ds_ping_latency_stats is active the algorithm will adjust the priority of the gateway automatically,
the priority will be lowered by 1 point every time the latency ms is as high as the priority.
- If the attribute 'cc=1' is set, the latency used is congestion ms : estimate (current latency ms) - average (normal condition latency ms).
Using this simple formula :
`ADJUSTED_PRIORITY = PRIORITY - (ESTIMATED_LATENCY/PRIORITY)`
GATEWAY | PRIORITY | ESTIMATED_LATENCY | ADJUSTED_PRIORITY | LOAD DISTRIBUTION
-- | -- | -- | -- | --
1 | 30 | 21 | 30 | 33%
2 | 30 | 91 | 27 | 0%
3 | 30 | 61 | 28 | 0%
4 | …
=> dispatcher: algorithm 13 latency optimized round-robin with failover

src/modules/rtpengine/doc/rtpengine_admin.xml, src/modules/rtpengine/rtpengine.c, src/modules/rtpengine/rtpengine.h
=> rtpengine: add CRC32 hash algo

src/modules/lost/doc/lost_admin.xml
Fixed type in lost module example.
Param `location_type`.
=> lost: fixed typo

src/modules/rtpengine/doc/rtpengine_admin.xml, src/modules/rtpengine/rtpengine.c
This modification is to provide access to the new exposed metrics.
RTPengine is now keeping track of RTT per call leg
https://github.com/sipwise/rtpengine/pull/1116
I also corrected the documentation as the RTT was always in microseconds not milliseconds.|
```
Kamailio config :
modparam("rtpengine", "mos_B_label_pv", "$avp(mos_B_label)")
modparam("rtpengine", "mos_max_roundtrip_B_pv", "$avp(mos_max_roundtrip_B)");
modparam("rtpengine", "mos_average_roundtrip_B_pv", "$avp(mos_average_roundtrip_B)");
modparam("rtpengine", "mos_average_roundtrip_leg_B_pv", "$avp(mos_average_roundtrip_leg_B)");
modparam("rtpengine", "mos_A_label_pv", "$avp(mos_A_label)")
modparam("rtpengine", "mos_max_roundtrip_A_pv", "$avp(mos_max_roundtrip_A)");
modparam("rtpengine", "mos_average_roundtrip_A_pv", …
```
=> rtpengine: query rtt per call leg

src/modules/keepalive/keepalive.h, src/modules/keepalive/keepalive_mod.c
- Fixed the way the module is initialized, causing problems when using
destination mod parameter because when invoking this parameter some
utilities are not initialized (timers).
Fixed the way the module is initialized, causing problems when using destination mod parameter because when invoking this parameter some utilities are not yet initialized (timers).
=> keepalive: fix initialization when using destination mod param

src/modules/lost/utilities.c
Caller LIS server may use namepace prefix `gml` or any other.
When created LOST request, then `location-info` payload created from `pidf-lo` and `p2` prefix namespace not used.
I suggest make some code cleanup and remove not used strings.
=> lost: removed not used namespace

src/modules/rtpengine/rtpengine.c
This patch fix wrong parsing the pair of IPv6 addr:port in rtpengine module, when loading node information from database.
=> Fix in parsing IPv6 address:port

src/core/socket_info.c
Without the first commit, on my setup - which has lots of interfaces with lots of addresses - auto_bind_ipv6 will make kamailio stuck on startup. It actually happens in get_flags, where data sent back from kernel can't fit into 8K anymore.
Second commit is fixing obvious typo while we're at it.
=> Fix 2 issues that prevent auto_bind_ipv6 from happening on my setup

src/core/xavp.c, src/core/xavp.h
Also added a function called by the three "*_serialize_fields" to reduce code duplication.
The interface is not modified.
Small pull request that adds a function "xavu_serialize_fields" (with same interface as "xavp_serialize_fields" and "xavi_serialize_fields"), and an internal helper function to reduce code duplication.
=> core: added xavu_serialize_fields function

src/core/xavp.c
This fixes the following issue:
https://github.com/kamailio/kamailio/issues/2604
When called to remove a specific index from a given xavp, function xavp_rm_by_index removes the index (as expected) but also all others before it.
E.g :
If called with idx = 1, it removes indexes 0 and 1.
Likewise if invoked with idx = 2 => the first 3 elements are removed.
This bug is located in function xavp_rm_internal. An assignment was missing when looping over the xavp list.
Same for xavi_rm_internal.
=> core: fix to xavp_rm_internal (#2604)

src/modules/tm/t_reply.c
- [x ] Breaking change (fix or feature that would change existing functionality)
- [x ] Tested changes locally -- tested at 5.1.6
Problem:
Forwarding of 200 OK while sent 488 waits for ACK, destroys the UAS send buffer
Scenario:
During suspension of 200 OK by ims_qos module function Rx_AAR() at terminating PCSCF,
The PCRF sends an AA Answer with result code DIAMETER_TOO_BUSY (3004), which triggers
the PCSCF to send a 488 …
=> tm: 200 OK not processed correctly by Proxy after final non-2xx

src/modules/dispatcher/dispatch.c
I found that zero servers are being logged, even though they are (ignore the line numbers, the file is slightly modified):
```
0(15681) DEBUG: dispatcher [dispatch.c:919]: ds_load_list(): found [0] dest sets
0(15681) DEBUG: dispatcher [dispatch.c:222]: ds_log_dst_cb(): dst>> 1031 sip:127.0.0.1:5182 0 0 (,0,0,0)
0(15681) DEBUG: dispatcher [dispatch.c:222]: ds_log_dst_cb(): dst>> 1011 sip:127.0.0.1:5180 0 0 (,0,0,0)
0(15681) DEBUG: dispatcher [dispatch.c:222]: ds_log_dst_cb(): dst>> 1021 sip:127.0.0.1:5181 0 0 (,0,0,0)
```
Therefore, I moved the logging of the dest sets after updating variable and this fixed the error.
=> dispatcher: Log dest sets after variable update

src/modules/rtpengine/rtpengine.c
When rtpengine answers with error-reason 'Ran out of ports' adopt the same behavor that when node answers 'Parallel session limit reached'
- [ x] Each component has a single commit (if not, squash them into one commit)
- [ x] No commits to README files for modules (changes must be done to docbook files
- [x ] New feature (non-breaking change which adds new functionality)
Backport of the 'sessions limit' behavor for the 'Ran out of ports' error-reason.
=> rtpengine : add node fallback if node ran out of ports

src/modules/htable/htable.c, src/modules/topos/doc/topos.xml, src/modules/topos/doc/topos_admin.xml, src/modules/topos/tps_msg.c, src/modules/topos/tps_storage.c, src/modules/topos/tps_storage.h, src/modules/topos_redis/doc/topos_redis.xml, src/modules/topos_redis/topos_redis_storage.c
- [x ] New feature (non-breaking change which adds new functionality)
topos_redis: support SUBSCRIBE dialog
topos: SUBSCRIBE dialog
topos: documentation for SUBSCRIBE dialog
topos: add description for dialog_expire key
Add support for dialog subscribe when using topos.
When a Subscribe is received, a Subscribe dialog is created. …
=> support subscribe dialog (topos + topos_redis)

src/modules/cplc/cpl_run.c
- a permanently registered contact has an "expires" value of 0 in usrloc
when processing lookup, cplc module checks that contacts are not expired by
checking that the "expires" value of the contact is not lower than current
time
as a consequence, permanently registered contact are alsways skipped and
never targeted
when an address-of-record has a permanent contact set, and when a cpl is set, the lookup function of the cplc module skips the permanent contact and no branch to this contact is created. When no cpl is set, usrloc lookup will create the expected branch. So there is a different behavior depending on the presence of a cpl.
the proposed fix will correct this behavior : the cplc module will create a branch to the permanent …
=>  cplc: permanent contact not skipped by lookup anymore

src/modules/stirshaken/Makefile, src/modules/stirshaken/doc/Makefile, src/modules/stirshaken/doc/stirshaken.xml, src/modules/stirshaken/doc/stirshaken_admin.xml, src/modules/stirshaken/stirshaken_mod.c
This module uses libstirshaken to implement STIR-Shaken authentication and verification functions (STI-AS/VS).
It allows for easy verification of a SIP call containing PASSporT wrapped into SIP Identity Header using a specific certificate,
or a specific key, or by performing complete check on PASSporT including downloading certificate referenced in it's x5u header,
and optionally checking it against trusted root certificates (X509 cert path check). Certificates may be cached and loaded from disk.
Example usage:
loadmodule "stirshaken"
modparam("stirshaken", "as_default_key", "/path/to/key")
modparam("stirshaken", "vs_verify_x509_cert_path", 1)
modparam("stirshaken", "vs_ca_dir", "/path/to/ca")
modparam("stirshaken", …
=> modules: Add stirshaken module

src/modules/rtpengine/rtpengine.c
rtpengine: IPv6 address in square brackets interpreted as FQDN.
- After loading from DB, rn_address is in form:` [x:x:x:x:x:x:x:x]:nnnn`, getaddrinfo function expect ipv6 in node argument without square brackets, otherwise, the argument is interpreted as FQDN.
=> rtpengine: remove square brackets from IPv6 address for getaddrinfo

src/core/tags.h
Since totag suffix generation was updated in 5.3 to increase randomness, the third element of the array in both parts - via1 branch and call-id - have never been included. The result is that for any given host/port the generated totag is always the same, causing issues with some UAs - specifically relating to presence subscriptions in the cases identified.
=> core: use third array element when generating totag suffix

src/modules/http_async_client/doc/http_async_client_admin.xml, src/modules/http_async_client/http_async_client_mod.c, src/modules/http_async_client/http_multi.c, src/modules/http_async_client/http_multi.h
add curl_follow_redirect module parameter to http_async_client to set CURLOPT_FOLLOWLOCATION during libcurl init, allowing libcurl to follow 3xx HTTP redirect responses.
=> http_async_client: add curl_follow_redirect parameter

src/modules/cplc/cpl_db.c, src/modules/cplc/cpl_env.h, src/modules/cplc/cpl_loader.c, src/modules/cplc/cpl_proxy.h, src/modules/cplc/cpl_run.c, src/modules/cplc/cpl_switches.h, src/modules/cplc/cplc.c, src/modules/cplc/doc/cplc.xml, src/modules/cplc/doc/cplc_admin.xml, src/modules/pua_dialoginfo/doc/pua_dialoginfo.xml, src/modules/pua_dialoginfo/doc/pua_dialoginfo_admin.xml, src/modules/pua_dialoginfo/pua_dialoginfo.c, src/modules/pua_dialoginfo/pua_dialoginfo.h
- [x ] New feature (non-breaking change which adds new functionality)
cplc: add a configuration route before redirected call (key: redirect_route)
same behaviour as proxy_route
cplc: deactivate 3XX responses handling (key: ignore3xx)
cplc: time based cpl did not work if several are set
cplc: add return result to kamcmd commands …
=> cplc and pua_dialoginfo enhancement

src/modules/acc_json/acc_json_mod.c, src/modules/acc_json/doc/acc_json_admin.xml
New parameter to add json in an accounting/CDR field and prevent unwanted json escaping.
Example:
```
modparam("acc_json", "acc_extra", "json_data=$avp(json_data);")
modparam("acc_json", "acc_json_pre_encoded_prefix", "json_")
...
$avp(json_data) = '{"b":2, "c":3}';
...
```
=> acc_json: param to accept pre-encoded json values

src/core/parser/parse_body.c, src/modules/http_client/curl_api.c, src/modules/http_client/curl_api.h, src/modules/http_client/functions.c, src/modules/http_client/functions.h, src/modules/lost/doc/lost.xml, src/modules/lost/doc/lost_admin.xml, src/modules/lost/functions.c, src/modules/lost/lost.c, src/modules/lost/naptr.c, src/modules/lost/naptr.h, src/modules/lost/pidf.c, src/modules/lost/response.c, src/modules/lost/response.h, src/modules/lost/utilities.c, src/modules/lost/utilities.h
lost: new features, attributes and a new function to dereference location
- features: LoST redirect, dynamic HELD url resolving (#2574), LoST NAPTR,
POST request to dereference loation 
- attributes: reponse_time (-1:emergencyDispatch, 0:emergencyRouting, >0[ms]);
post_request (POST method to dereference location #2641); recursion (1:yes/0:no);
location_profile (PIDF/LO profile selection: 0:first/1:last/2:geo/3:civic);
verbose 0/1 (detailed LoST response as log INFO);
geoheader_type (filter schema: 0:any/1:cid/2:http/3:https);
geoheader_order (0:first/1:last)
- function: lost_held_dereference (specific function to dereference location
using POST method); attributes are url (r;string), resp.-time (r;string),
resp.-type (r;string), …
=> extensions to lost and http_client modules

src/modules/domain/hash.c
- [*] Small bug fix (non-breaking change which fixes an issue)
- [*] PR should be backported to stable branches
I observed this when glancing over commit https://github.com/kamailio/kamailio/commit/f50177003c21f53564be6349c0bb4935be184e2d
The invalid access is pretty clear, and so is the fix.
Cheers!
=> domain: fix use after free on domain reload

src/modules/tls/tls_domain.c
Addresses #2716. Also see https://bugs.python.org/issue29697.
- [X ] Tested changes locally
For OpenSSL 1.1.x initialization of EC SSL contexts has changed — we shouldn't be using the < 1.0.2 technique on OpenSSL 1.1+. This addresses a corner case where a TLS client(OpenSSL 1.1.1) with P-256 cert would not handshake with a TLS server with a P-521 cert. Adopted from the way that Python `_ssl.c` does initialization. Python, in turn, took this from Apache's `mod_ssl`.
=> [tls] Don't use OpenSSL<1.0.2 fallback on 1.1+

src/modules/uac/doc/uac_admin.xml, src/modules/uac/uac.c
Allow configuring the hash table size. The default(4) is hardly usable
on anything but a test system.
=> uac: Add reg_hash_size parameter

src/modules/ims_ipsec_pcscf/cmd.c, src/modules/ims_ipsec_pcscf/ipsec.c, src/modules/ims_ipsec_pcscf/ipsec.h
- add aes-cbc, des-ede3-cbc ipsec encryption algoriyhms
- improve nlmsg_seq choice for concurrent multi UEs Registrations at
same time
- before sending replies over IPsec check the existing
of opened TCP sockets
=> ims_ipsec_pcscf: more algorithms, SA improvements

src/core/ut.c
There's an regression after 42228552b72267786561704f120e3da3aac5fd89 
`pike.so` was affected by the commit. RPC `pike.top` and `pike.list` commands didn't work.
`str_casesearch()` had returned NULL while text and needle were equal.
=> core: ut - fixed str_casesearch()

src/modules/pike/ip_tree.c
There's an regression in 5.5 on `pike.so`. After c9dc0336a33a0ecfe776975be7fbfab8f3c91b48 the module has stopped to work. `mark_node()` had returned a NULL on every IP-address.
=> pike: fixed regression

src/modules/pv/pv_core.c
pv: fixed error "pv_get_method(): no CSEQ header"
when sent HTTP request like
```
HTTP/1.1 200 OK
Sia: SIP/2.0/TCP 8.8.8.8:39813
Content-Type: application/json
Server: kamailio
Content-Length: 49
{"data":{"status-code":200,"reason-phrase":"OK"}}
```
=> pv: fixed error "pv_get_method(): no CSEQ header"

src/core/receive.h, src/modules/sl/sl_funcs.c
HTTP request do not trigger `SREV_NET_DATA_RECV` (please check [`receive_msg`](https://github.com/kamailio/kamailio/blob/0e806316b84be8388dad670e964e54011000b4a4/src/core/receive.c#L321))
This PR adds the same behavior for HTTP responces.
=> sl: disabled SREV_NET_DATA_SENT for HTTP responses

src/modules/rtpengine/rtpengine.c
since mos 0 is unnitialized this can happen when RTP engine does not have a valid RTT (or missing one leg).
RTP engine MOS is never < 1
=> rtpengine: ignore mos 0 when selecting min-mos

src/modules/statsd/doc/statsd_admin.xml, src/modules/statsd/lib_statsd.c, src/modules/statsd/lib_statsd.h, src/modules/statsd/statsd.c
adding support for histograms
```
Histograms
The histograms are also a measure of time, but they are calculated at the server side. As the data exported by the client is the same, this is just an alias for the Timer type.
<metric name>:<value>|h
```
=> statsd: adding support for histograms

src/modules/nathelper/nathelper.c
Examples from RFC3605:
>    m=audio 49170 RTP/AVP 0
>    a=rtcp:53020
>
>    m=audio 49170 RTP/AVP 0
>    a=rtcp:53020 IN IP4 126.16.64.4
>
>    m=audio 49170 RTP/AVP 0
>    a=rtcp:53020 IN IP6 2001:2345:6789:ABCD:EF01:2345:6789:ABCD
fix #2768
don't fail if there's no IP info if line is 'a=rtcp'
=> nathelper: don't fail if 'a=rtcp' has no IP

pkg/kamailio/obs/kamailio.spec
EPEL  now includes a openssl11 package for CentOS 7. This feature is for users who want to build kamailio-tls with OpenSSL 1.1.1 instead of OpenSSL 1.0.2.
It is implemented as a `--with=openssl11` conditional (the default is off), so should not affect/change the regular CentOS 7 builds as distributed by kamailio.org.
This is for adventurous users on CentOS 7 willing to maintain their own OpenSSL 1.1.1-enabled TLS package. EPEL dependencies( openssl11-libs, openssl11-devel) are required at runtime and for build.
=> Enable CentOS 7 to build with OpenSSL 1.1.1 package from EPEL

src/modules/rtpengine/doc/rtpengine_admin.xml, src/modules/rtpengine/rtpengine.c
When using rtpengine_allow_op param, return node for ongoing calls only if rtpengine is manually disabled.
When a rtpengine instance is disabled, rtpengine_allow_op will allow the indialog requests to be processed through that rtpengine. 
But it's not desirable to return the node when the rtpengine has unexpectedly crashed or has any undesired issues, because the rtp commands attempted cause congestion problem in the kamailio.
So with this patch we only return the node if the rtpengine has been manually disabled and it's still supposed to be working.
- [ x] Small bug fix (non-breaking change which fixes an issue)
=> rtpengine: rtpengine_allow_op return node logic

src/modules/rr/record.c
Until this fix, only the function record_route() considered the
value of the custom user AVP (if present). The functions
record_route_preset() and record_route_advertised_address(),
on the other hand, ignored the value of the custom user AVP,
even if it was presnt.
Now all three functions, record_route(), record_route_preset()
and record_route_advertised_address(), consider the value of the
custom user VP, if it is present.
=> rr: all "record_route_...()" functions consider custom user AVP

src/modules/outbound/doc/outbound_admin.xml, src/modules/outbound/outbound_mod.c
- calculate ob_key as SHA1(flow_token_secret) if specified
- keep old behavior with randomly generated ob_key if not specified
Adds ``flow_token_secret``(string) parameter for **outbound** module to give the ability to use persistent ob_key which is used for flow tokens validation.
Useful for cluster configurations with floating IP and ensures successful validation of the previously generated flow tokens after the **kamailio** restart.
=> outbound: add flow_token_secret param

src/modules/tm/t_lookup.c, src/modules/tm/t_reply.c, src/modules/tm/t_suspend.c, src/modules/tm/timer.c, src/modules/tm/timer.h
- Mention when FR timeout is reached, and which of FR timers expired
- Log when starting FR/RETR timers
- log when changing default timeouts to user-set values
- log when resetting fr/retr timers on provisional replies
The main reason for these changes is that we haven't found any possibility to distinguish which of `fr` timeouts expires. The rest of the logs are also helpful, but secondary. 
As they all are under `ifdef TIMEOUT_DEBUG` I hope it is not a big deal.
=> tm: enhance fr/retr timers logging

src/core/parser/sdp/sdp.c, src/core/parser/sdp/sdp.h, src/modules/textops/textops.c
some user agents send a=sendonly as a session attribute and is_audio_on_hold() returns false when it should return true.
- changed sdp_session_cell struct in sdp.h to add sendrecv_mode and is_on_hold
- changed parse_sdp_session in sdp.c to iterate session attributes and call extract_sendrecv_mode for assigment to session
- changed ki_is_audio_on_hold in textops.c to look for session sendrecv_mode if its not set in media
=> Rfc3264 on session

src/modules/tm/uac.c
setting via xavp in tm:local-request has no effect
```
xavp_via_params = "via"
event_route[tm:local-request]
{
$xavp(via=>xi) = "something"
via_add_xavp_params("1");
}
reply_route {
$var(vd) = $sel(via.params["xi"]);
xlog("L_INFO", "$ci|log|core|reply $rm this should be true => ('$var(vd)' == 'something')\n");
}
```
changed t_run_local_req and moved restore xavps & flags to the end, after the messages changes are applied.
=> tm: restore xavps & flags after rebuilding message

src/modules/kazoo/kz_amqp.c
success events should be routed to onreply_route[]
failure events should be routed to failure_route[]
Kazoo cfg files use onreply_route[]  and failure_route[] to handle the replies from AMQP and the module was sending the replies to the main route and therefore the scripts were not receiving the responses
=> kazoo : fix routing of reply events

src/modules/lcr/doc/lcr_admin.xml, src/modules/lcr/lcr_mod.c
A simple change, which allows to check, if a coming request matches
not only by an IP address and a transport protocol,
but also using the source port of a request.
Improvements are done for the following functions of the lcr module:
- from_any_gw()
- from_gw()
Back compatibility provided, hence it does not affect already existing behavior.
=> lcr: source port check for from_any_gw() and from_gw().

src/core/dprint.c, src/core/dprint.h, src/main.c
See the feature request in #2797 
I've provided similar implementation in reSIProcate binaries, Kurento and GStreamer pull requests so they can all share the identical CEE schema.
Tested like this:
```
make
src/kamailio -f ./misc/examples/ims/pcscf/kamailio.cfg --log-engine=json:U -D -dddd -E
```
I copied one of the JSON log lines to a file and parsed it like this to check it is valid JSON:
```
python -m json.tool /tmp/kamailio.json 
{
"appname": "kamailio",
"file!line": 97,
"file!name": "core/mem/pkg.c",
"hostname": "ws.example.org",
"msg": "destroying memory manager: q_malloc\n",
"native!function": "pkg_destroy_manager",
"pname": "kamailio",
"pri": "DEBUG",
"proc!id": "16264",
"proc!tid": 140525261209856,
"subsys": "core",
"time": …
```
=> core: logging: JSON: add CEE schema support

src/modules/mqueue/doc/mqueue_admin.xml, src/modules/mqueue/mqueue_mod.c, src/modules/rtimer/doc/rtimer_admin.xml, src/modules/rtimer/rtimer_mod.c
Add 2 new mqueue module parameters to simplify config queue definition.
Add 1 new rtimer module parameter to set default timeout if not present.
Updated docs.
=> mqueue: add two new module parameters

src/modules/tls/doc/hsm_howto.xml, src/modules/tls/tls_mod.c
tls_init.c calls OPENSSL_init_ssl(); this initializes the
global engine linked-list and this cannot be reset in the child.
To avoid linked-list corruption we manually instantiate
the engine object required for loading private keys instead of
relying on CONF_modules_load_file().
Updates to doc/.
Addresses #2839
The call to `OPENSSL_init_ssl()` in `tls_init.c` results in the creation of the engine linked-list in the parent.
This affects per-child engine private keys as there is no api to reinitialize the engine linked-list in the child.
This PR removes the call to `CONF_modules_load_file()` which causes linked-list corruption and replaces
the initialization of engine private keys in the child with with other api calls which do not …
=> tls: fix OpenSSL engine in child processes

src/modules/xlog/doc/xlog_admin.xml, src/modules/xlog/xlog.c
allows pv_format specifier in prefix param
add `prefix_mode` param to xlog to optionally interpret `prefix` as a `pv_format` specifier.
`config`: 
```
mod_param("xlog", "prefix", "$_s([$(cfg(file):$cfg(line)] $ci $(cfg(route){s.tolower}) )")
mod_param("xlog", "prefix_mode", 1)
...
xlog("L_INFO", "hello")
...
```
`output:`
<pre><code>
66(307) INFO: <b>[my-file.cfg:5]</b> 62795aa2-9696c27c <b>my_route</b> hello
</code>
</pre>
=> xlog: add prefix_mode

src/core/dprint.c
The JSON CEE output from ```stderr``` is OK
When the messages are sent through Syslog, they need this extra prefix ```@cee:``` before the JSON string
Tested with ```rsyslog-omelasticsearch``` and [OpenSearch Dashboard (replacement for Kibana)](https://opensearch.org/)
```
module(load="mmjsonparse")
local5.* :mmjsonparse:
template(name="isJSON" type="list") {
property(name="$!all-json")
}
module(load="omelasticsearch")
local5.* action(type="omelasticsearch"
template="isJSON"
server="some-server"
serverport="9200"
searchIndex="log"
searchType="_doc/"
uid="admin"
pwd="admin")
```
=> core: logging: JSON: CEE: add the @cee prefix in Syslog messages

src/modules/lcr/lcr_mod.c
Improve binary search in the lcr module and add a possibility
to do a matching not only based on an IP address of a GW, but also using a source port.
When a possibility to use 'src_port' parameter in from_gw() and from_any_gw()
was introduced here: 14e6fc80b3d2389567c73c4a2196bf8e6d92d8d2
the bsearch() remained untouched, and hence the matching (iteration through existing GWs)
is now done only based on an IP address.
This leads to the issue, when there are more than one GW with the same IP address in gws table,
and from_gw() and from_any_gw() functions are used with the 'src_port' parameter,
it can happen that a wrong GW is picked out by bsearch() from gws table (lcr_gw) and
a check by from_gw() and from_any_gw() returns False.
Hence …
=> lcr: improve binary search to support a match including src port

src/modules/tm/config.c, src/modules/tm/config.h, src/modules/tm/doc/params.xml, src/modules/tm/t_lookup.c, src/modules/tm/tm.c
Enable transaction matching using callid and cseq values
instead of via md5 value.
Hello,
We had an issue with kamailio that the generated tm p_cell->md5 was not sent out in Via "branch=" parameter. Instead, other value was sent. Thus when comparing the replies Via "branch=" md5 value back to p_cell->md5, the transactions mismatched and dialogs were not setup. This happened for the most of the transactions/dialogs.
We could not really figure out why the above was happening. Because this was an isolated system, we decided to do this workaround using callid and cseq matching for transactions, and it helped. Now most of the dialogs are setup.
Let me know what you think, if other had this problem and if this PR helps.
Thank you,
Stefan
=> tm: Add callid_cseq_matching param

src/modules/statsd/lib_statsd.c, src/modules/statsd/lib_statsd.h, src/modules/statsd/statsd.c
When the module is loaded the messages have '\r\n'
> INFO: statsd [statsd.c:87]: mod_init(): Statsd init ip value 127.0.0.1 #015
> INFO: statsd [statsd.c:93]: mod_init(): Statsd init port value 8125#015
> INFO: statsd [statsd.c:101]: mod_init(): Statsd: success connection to statsd server
while at it, format the code with our clang-format definition
=> statsd: remove '\r\n' from xlog messages

src/core/route.c
When Kamailio goes to shutdown then routing hash table cleaned properly.
=> core: fixed route hash table cleanup

src/core/dprint.h, src/modules/auth_identity/auth_identity.c, src/modules/cdp/routing.c, src/modules/db_redis/redis_dbase.c, src/modules/ims_charging/ims_ro.c, src/modules/ims_dialog/dlg_handlers.c, src/modules/ims_icscf/scscf_list.c, src/modules/ims_registrar_pcscf/notify.c, src/modules/ims_registrar_pcscf/save.c, src/modules/ims_registrar_scscf/registrar_notify.c, src/modules/ims_registrar_scscf/save.c, src/modules/ims_usrloc_scscf/impurecord.c, src/modules/nat_traversal/nat_traversal.c, src/modules/xhttp_pi/xhttp_pi_fnc.c
libcs are implementing changes to fix the year 2038 issue on 32 bit
platforms (see [1]). musl libc already went ahead and implemented it,
starting with musl-1.2.0 (see [2]).
This commit adds a new definition to src/core/dprint.h:
TIME_T_INT_FMT
If __USE_TIME_BITS64 is defined (by a time64 libc, see [1]), it is set
to the proper conversion for type int64_t, PRId64.  If __USE_TIME_BITS64
is not defined, the status quo remains unchanged ("%ld" is used).
Note: In some places kamailio uses "%li" instead of "%ld". But in the
context of printf etc. there is no difference, so this commit replaces
"%li" with "%ld".
The new definition is used in the different parts of kamailio, where
appropriate.
These changes get rid of the new warnings that appeared with musl-1.2.0.
Below an example warning:
In …
=> time: add support for time64 libc

src/modules/presence/doc/presence_admin.xml, src/modules/presence/presence.c, src/modules/presence/presence.h, src/modules/presence/subscribe.c
RFC 6665 [says](https://datatracker.ietf.org/doc/html/rfc6665#section-8.3.1):
> Implementations conformant with the current specification MUST treat an incoming 202 response as identical to a 200 response and MUST NOT generate 202 response codes to SUBSCRIBE or NOTIFY requests.
I'm not sure if Kamailio is supposed to conform to the older RFC, so this change might not be _acceptable_.
=> presence: add option to return 200 instead of 202 on subscriptions

src/modules/kazoo/doc/kazoo_admin.xml, src/modules/kazoo/kazoo.c, src/modules/kazoo/kz_amqp.c, src/modules/kazoo/kz_amqp.h
- implements GH #2895
Allows adding additional AMQP-headers in the format header1=value1;header2=value2;...
Remark: 
I decided to re-use the definition 
`{"kazoo_publish", (cmd_function) kz_amqp_publish_ex, 4, fixup_kz_amqp, fixup_kz_amqp_free, ANY_ROUTE},`
resp. to modify the existing method signature
`int kz_amqp_publish_ex(struct sip_msg* msg, char* exchange, char* routing_key, char* payload, char* _pub_flags)`
to 
`int kz_amqp_publish_ex(struct sip_msg* msg, char* exchange, char* routing_key, char* payload, char* _pub_flags)`
as the param _pub_flags is neither described in the docs, nor it was evaluated/used, and thus was useless anyhow.
=> kazoo: Allow optional AMQP-headers in kazoo_query and kazoo_publish

src/modules/tls/tls_domain.c
In commit 27904530d1f8efd26e2b96fa5f18a3aad887919b we attempt to detect OpenSSL 1.1.0+ to fix initialization of EC.
The wrong macro `OPENSSL_VERSION_1_1` was used; this is not actually defined in the OpenSSL headers.
Use the correct macro `OPENSSL_VERSION_NUMBER`.
=> tls: fix wrong macro used to detect OpenSSL 1.1.0+

src/modules/nats/nats_mod.c, src/modules/nats/nats_mod.h
This update moves the nats urls into a `nats_connection_ptr` struct. This will allow the nats_urls to be extended into a linked-list (to allow simultaneous connections) while still maintaining nats built-in failover connectivity which comes included in the libnats
=> nats: move nats connection handling into a struct in order to extend features

src/modules/tls/tls_domain.c
For OpenSSL 3.x, this will fix a deprecation warning.
Update DH initialization with appropriate API for OpenSSL >= 1.1.1. This also fixes a deprecation warning with OpenSSL 3.x.
=> tls: update DH initialization for OpenSSL 1.1.x

src/modules/tm/doc/params.xml
Currently, the documentation states the unmatched_cancel parameter accepts a string input, but it only accepts an integer input. Fixing documentation to match the code's expectations.
https://github.com/kamailio/kamailio/blob/b6cebaa76eaa4b98bbba6e271c50dbfa14a8f9f7/src/modules/tm/config.c#L159
=> Fix TM Module Doc unmatched_cancel param from string to integer

src/modules/dispatcher/dispatch.c
If ds_probing_mode is set to 3, flag in the dispatcher entry needs to include 8
for probing to happen.
Changing a destination to not include this anymore while the destination do
not respond to OPTIONS will cause the probing flag to be re-added because of the
delayed response. A restart will fix it.
We need to check against the probing flag in the CB function to determine if
we should continue probing this destination. If probing is deativated while
waiting for a reply, we should abort.
=> dispatcher: Not possible to deactivate probing of destination by reload

INSTALL, src/Makefile.groups
- Add sqlite as an option to Makefile.groups
- Add sqlite to INSTALL documentation
db_sqlite couldn't be enable previously using group_include=sqlite. This fixes that.
=> sqlite: module group creation

src/core/cfg.lex, src/core/ppcfg.h
Add new preprocessor keywords `trydefenv` and `trydefenvs` that work like `defenv` and `defenvs` respectively, with the difference that if the environmental variable is not defined, then the value in Kamailio will not be defined.
For example:
```
#!KAMAILIO
loadmodule "xlog"
loadmodule "pv"
#!trydefenv EXTRALOG
request_route {
#!ifdef EXTRALOG
xlog("L_I", "Some Extra Logging here\n");
#!endif
forward ();
}
```
If the environmental variable `$EXTRALOG` is defined, the log line will be written.  If the environmental variable is not set, then in Kamailio `EXTRALOG` will not be defined and the `#!ifdef` section will not be loaded.
=> core: cfg.lex support for undefned env vars

src/modules/dialog/dialog.c, src/modules/dialog/doc/dialog_admin.xml
allows to filter out non local dialogs from stats using a new argument
fix #2920
=> dialog: add local_only paramter to RPC dlg.stats_active

src/modules/ldap/ldap_connect.c, src/modules/ldap/ldap_connect.h, src/modules/ldap/ldap_mod.c
```
When compiling against openldap 2.6.0 kamailio's private ldap_connect() clashes
with openldap's own. curl dealt with a similar issue earlier (see [1]).
Simply rename the function to avoid the issue.
In file included from ldap_api_fn.c:37:
ldap_connect.h:34:12: error: conflicting types for 'ldap_connect'; have 'int(char *)'
34 | extern int ldap_connect(char *_ld_name);
|            ^~~~~~~~~~~~
In file included from ldap_api_fn.c:33:
/home/sk/tmp/sdk/openwrt-sdk-ath79-generic_gcc-11.2.0_musl.Linux-x86_64/staging_dir/target-mips_24kc_musl/usr/include/ldap.h:1555:1: note: previous declaration of 'ldap_connect' with type 'int(LDAP *)' {aka 'int(struct ldap *)'}
1555 | ldap_connect( LDAP *ld );
| ^~~~~~~~~~~~
make[5]: *** [../../Makefile.rules:100: ldap_api_fn.o] Error 1
make[4]: *** …
```
=> ldap: rename private function ldap_connect

src/core/tcp_conn.h, src/core/tcp_main.c, src/core/tcp_read.c
We faced an issue that tcp:close (timeout and reset) event routes don't execute in rare cases. Debugging and testing show that in the case when a connection is marked as BAD or write timeout etc our event routes don't execute. 
I found that executing event routes is in the read function only. So in case when a connection is destroyed triggered by other reasons we don't have a notification about this. 
I propose to do this in main file every time when we destroy connections. But in this case, we don't have I reason to destroy (timeout reset or EOF).
In our lab with these changes issue is gone. But sure this is just a concept.
=> tcpclose event_routes issue

src/core/cfg.lex, src/core/cfg.y, src/core/core_cmd.c, src/core/ip_addr.h, src/core/socket_info.c, src/modules/corex/corex_rpc.c, src/modules/ims_ipsec_pcscf/ims_ipsec_pcscf_mod.c
A new option to "listen" has been added called "virtual". This sets a flag on the listening socket to modify the behaviour of grep_sock_info. When this flag is set, grep_sock_info will only consider the listening IP a match if the IP is found in the system's current list of local IP addresses. If the IP is not currently local, then the matching IP is ignored.
If the virtual flag is not set on the socket then existing behaviour used instead.
This feature is intended for scenarios where you have two Kamailio nodes in active/active setup, with virtual IPs, where you need to be able to listen on a virtual IP but it may not always be active locally. With this flag applied to a `listen=` socket, Kamailio will only consider traffic destined …
=> core: Add virtual flag to listen config to ignore inactive ip addresses

src/modules/dispatcher/dispatch.c
Alg 13 did try to distribute calls to inactive destinations.
If the highest priority destination is inactive, hash is not updated
and the xavp is not set. This is resulting in failover mechanism
not working at all for the given call.
When the hash variable is not updated, it makes alg 13 behave like
round robin if the scenario above occurs. If you got two destinations
and the highest priority is out of service, 50% of the calls will fail.
Now I tried a more simple approach updating hash with the first
entry of the sorted list.
Also fixed a typo in a variable name.
=> dispatcher: Fix handling of inactive destination for alg 13

src/modules/presence_conference/add_events.c, src/modules/presence_conference/doc/presence_conference_admin.xml, src/modules/presence_conference/presence_conference.c, src/modules/presence_conference/presence_conference.h, src/modules/presence_dialoginfo/add_events.c, src/modules/presence_dialoginfo/doc/presence_dialoginfo_admin.xml, src/modules/presence_dialoginfo/presence_dialoginfo.c, src/modules/presence_dialoginfo/presence_dialoginfo.h, src/modules/presence_mwi/add_events.c, src/modules/presence_mwi/doc/presence_mwi_admin.xml, src/modules/presence_mwi/presence_mwi.c, src/modules/presence_mwi/presence_mwi.h, src/modules/presence_profile/add_events.c, src/modules/presence_profile/doc/presence_profile_admin.xml, src/modules/presence_profile/presence_profile.c, src/modules/presence_profile/presence_profile.h, src/modules/presence_reginfo/add_events.c, src/modules/presence_reginfo/doc/presence_reginfo_admin.xml, src/modules/presence_reginfo/presence_reginfo.c, src/modules/presence_reginfo/presence_reginfo.h, src/modules/presence_xml/add_events.c, src/modules/presence_xml/doc/presence_xml_admin.xml, src/modules/presence_xml/presence_xml.c, src/modules/presence_xml/presence_xml.h
=> presence : add default_expires and use in the presence* modules

src/modules/phonenum/Makefile, src/modules/rtp_media_server/Makefile, src/modules/websocket/Makefile
`websocket` and `phonenum` are not build on FreeBSD environment.
The proposed patch fixes it and makes modules are consistent with the rest of modules.
=> Fix PHONENUM, RTP_MEDIA_SERVER and WEBSOCKET for build on FreeBSD

src/modules/smsops/smsops_impl.c
- Add capability to set RPData originator
and destination addresses flags.
Default values 0x91.
=> smsops: extend rpdata params manipulation

src/Makefile
Building ``kamcmd`` twice was not only a (marginal) waste of build time, but also created a race condition where the first linking sometimes failed due to reading the incomplete file from the ongoing second build of ``kamcmd.o``:
https://buildd.debian.org/status/fetch.php?pkg=kamailio&arch=s390x&ver=5.5.3-1&stamp=1638905109&raw=0
```
gcc -pthread -DKSR_PTHREAD_MUTEX_SHARED -Wall -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DVERSION_NODATE    -DNAME='"kamcmd"' -DSRNAME='"kamailio"' -DVERSION='"1.5"' -D__OS_linux -DRUN_DIR='"/var/run/kamailio/"'  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DMOD_NAME="utils/kamcmd" -c kamcmd.c -o kamcmd.o
...
gcc -pthread -DKSR_PTHREAD_MUTEX_SHARED -Wall -Wdate-time …
```
=> src/Makefile: Also stop compiling kamcmd from here

src/modules/dialog/dialog.c, src/modules/dialog/dlg_handlers.c, src/modules/dialog/dlg_req_within.c, src/modules/dialog/doc/dialog_admin.xml
Skip keepalive check if dialog is not local, do the same in case of dialog timeout
=> dialog keep-alive only for own records

src/modules/erlang/pv_atom.c, src/modules/erlang/pv_pid.c, src/modules/erlang/pv_ref.c, src/modules/erlang/pv_xbuff.c
The Erlang module is not working at all with newer Kamailio versions.   One of the issues was already found in #2069 but no code was submitted.   The second one I believe is related to https://github.com/kamailio/kamailio/commit/7bb2669528a819ec29a8193eebc9c641edd69993 in that the erlang module assumes that pvi.type is zero and uses that field to type the custom fields it manages and this commit starts populating pvi.type with a 4. 
I don't have a solid grasp on pvapi.c so if the experts have a better way to fix this up I am all ears.  These two commits do get the module working properly and I am able to use both the custom erlang PV terms and the RPC feature from my proxy now.
=> Erlang: Fixes to get the module functional again

src/modules/app_jsdt/app_jsdt_api.c, src/modules/app_jsdt/app_jsdt_api.h, src/modules/app_jsdt/duk_module_node.c, src/modules/app_jsdt/duk_module_node.h
I can not remember the last time I wrote any C which was likely a class assignment last century.  Anyways I came across this issue and it seemed in reach to get the ball rolling.  I know this PR needs more work but my goal is to share my progress to help move this feature forward.
Based on https://github.com/svaarala/duktape/tree/master/extras/module-node
added:
- duk_module_node.h
- duk_module_node.c
updated:
- app_jsdt_api.h
- app_jsdt_api.c
Included the extra header and initialize the bindings after 'load JS context' was created.
added `cb_resolve_module` to resolve the full file system path for requested_id and parent_id
added `cb_load_module` function which uses `jsdt_load_file` to load resolved file
With absolute and relative …
=> add duk_module_node to module app_jsdt

src/core/parser/sdp/sdp.c, src/core/parser/sdp/sdp.h, src/core/parser/sdp/sdp_helpr_funcs.c, src/core/parser/sdp/sdp_helpr_funcs.h
Commits are separated per change dedication, even though they concern the same component.
- core: add support of ICE media options to SDP parser
- core: improve an existing data structures cloning in the SDP parser
---
core: add support of ICE media options to SDP parser
In the current implementation only parsing of ICE candidate
attributes is supported, which makes it Possible to work
with ICE candidates and parameters specifically related per
candidate, but makes it Impossible to work
with ICE options of the media stream level (ICE options which
have an impact on the whole specific media stream).
ICE candidate attributes and ICE media options have different
dedication.
In order to target this matter, a new linked list is introduced …
=> core: improve SDP parser to support ICE media stream options / improve existing data structures cloning in the SDP parser

src/modules/cplc/cpl_switches.h
cplc: manage case where TZ environment variable is not set.
When TZ environment variable was not set, only the first time based CPL worked correctly.
=> cplc: manage case where TZ environment variable is not set.

src/modules/tm/config.c, src/modules/tm/config.h, src/modules/tm/doc/params.xml, src/modules/tm/tm.c, src/modules/tm/uac.c, src/modules/uac/doc/uac_admin.xml, src/modules/uac/uac_send.c
This PR adds 1 UAC module function and 1 TM module modparam. It enables "uac:reply" event route trigger on timeout or non-2xx replies. Basically it:
- adds TMCB_ON_FAILURE callback for UAC
- copies the TM uac content into uas; thus failure route will have the uas to work with. => this part of the code was already there, i just enabled it via (another) modparam. 
So far, is basically tested on our side, without any apparent issues. More testing will follow.
Please have a look on this and tell me what you think about it.
Thank you,
Stefan
=> uac: enable "uac:reply" event route for UAC SIP message timeouts

src/modules/siptrace/siptrace.c, src/modules/siptrace/siptrace_data.h, src/modules/siptrace/siptrace_send.c
- Correctly freeng pkg memory in core callbacks when body modifications take place with X-Siptrace headers,
also fix potential pkg_free with not dynamicaly allocated objects.
Releated to [57b1d5375927b987b162fcf0e2c99a39b717bd65](https://github.com/kamailio/kamailio/commit/57b1d5375927b987b162fcf0e2c99a39b717bd65)
=> siptrace: fix pkg memory leak when module configured with core callbacks

src/modules/stirshaken/doc/stirshaken_admin.xml, src/modules/stirshaken/stirshaken_mod.c
- added vs_certsubject_pvname and vs_pptgrants_pvname config params
- adjusted log level of load/unload events
The stirshaken module currently does not allow any access to the information provided in the Identity header.  These changes allow key components of a signed call to be available in user-specified pseudo variables.
Specifically, the Subject of the certificate used to sign the call will be written to the PV specified in vs_certsubject_pvname and the JWT payload that has been verified will be written to the PV specified in vs_pptgrants_pvname.
There is no change to any behaviour whether these configuration options are set or not other than to write the appropriate values into the indicated PVs.
=> stirshaken: Add PVs to allow access to x509 subject and ppt grants

src/modules/pv_headers/doc/functions.xml, src/modules/pv_headers/doc/pv_headers.xml, src/modules/pv_headers/pv_headers.c, src/modules/pv_headers/pvh_func.c, src/modules/pv_headers/pvh_func.h
- To be used with headers containing values separated by commas
- pvh_header_param_exists() check if the value is present to a given header
- pvh_remove_header_param() remove the value from the given header or the entire header if no other value is present
Previously, to remove a parameter from a header it was needed to create a complex method on the configuration file for each header/parameter. This modification moves this complexity to the 'pv_headers' module.
Two new functions:
* pvh_header_param_exists
* pvh_remove_header_param
Both functions take as parameters the name of the header and the name of the parameter.
It returns '-1' if the combination header/parameter:
- is not found (pvh_header_param_exists)
- couldn't be removed …
=> pv_headers: Add support to remove a specific value from a header

src/modules/htable/ht_db.c
"%*.s"  used instead of "%.*s"
"%*.s"  used instead of "%.*s": "The result is padded with space characters" (https://en.cppreference.com/w/cpp/io/c/fprintf)
Probably harmless (but still wrong) if the string ends with '\0'.
=> htable: wrong printf format

src/modules/ims_registrar_scscf/cxdx_sar.c, src/modules/tm/t_lookup.c, src/modules/tm/t_suspend.c, src/modules/tm/t_suspend.h, src/modules/tm/tm_load.c, src/modules/tm/tm_load.h
This is done because IMS third party registration requests would be skipped because
t_continue would get called on the transaction _way_ before the timer timeout.
All this resulted in the correct route not being called.
=> add function t_continue_skip_timer to enable skipping of timer checks

src/core/crypto/sha256.c, src/core/crypto/sha256.h
- [*] Small bug fix (non-breaking change which fixes an issue)
Fix for the following compiler warnings:
```
core/crypto/sha256.c:548:32: warning: argument 1 of type ‘sha2_byte[]’ {aka ‘unsigned char[]’} with mismatched bound [-Warray-parameter=]
548 | void sr_SHA256_Final(sha2_byte digest[], SHA256_CTX* context) {
|                      ~~~~~~~~~~^~~~~~~~
In file included from core/crypto/sha256.c:36: …
```
=> core/crypto: fix several mismatched bound warnings

src/modules/pv_headers/pvh_func.c
- remove a variable creation
Put two variable accessible to the entire function, renaming one to have some clarity. 
Remove the useless variable.  
- Remove from snprintf that fills the string
This fix possible a memory overflow while using `snprintf`. This also add a \0 at the end of the structure.
- change the destination of an allocated space being smaller than the source
Elements were being put into a smaller string, this commit makes the destination bigger then the source.
=> pv_headers: fix possible mem. overflow issue and wrong size string

src/modules/userblocklist/db_userblocklist.c
Spotted this ERRORs on kamailio restart:
```
ERROR: <core> [db.c:481]: db_use_table(): invalid connection parameter
ERROR: userblocklist [db.c:123]: db_reload_source(): cannot use db table 'globalblocklist'
ERROR: userblocklist [userblocklist.c:425]: load_source(): cannot load source from 'globalblocklist
```
Debugging it further, seen that the above ERRORs appear on ```check_allowlist()``` function fixup. This was happening because db connection is closed in mod_init and re-done in child_init. But the fixups happen before child_init and they need db connection.
Decided to not close the db connection after mod_init because it is later, first closed and then re-opened, in each child. Figured out this fix after checked where each …
=> userblocklist: fix restart errors

src/modules/siptrace/siptrace_send.c
Possibility to switch to other then UDP transport protocol in diplicate_uri
Sometimes it's preferable to do the duplication over TCP or another transport, this little fix removes the hard-coded UDP from the diplicate_uri module parameter.
=> siptrace: fix hardcoded PROTO_UDP in duplicate_uri module parameter

src/core/cfg.lex, src/core/cfg.y, src/core/tcp_main.c, src/core/tcp_options.c, src/core/tcp_options.h
We have seen that in deployments where there are strict port requirements on both side, there are tcp connections in TIME_WAIT state causing no fresh TCP connections possible until the TIME_WAIT is gone. In a lot of these case the clients are sending from them self a RST after they send a FIN,ACK from there side but some aren't doing this. The basic idea of this PR is to give an extra option for the tcp configuration from the cfg to trigger always an RST on connection close from Kamailio side. This currently done by enabling SO_LINGER with a value of 0 just before close.
=> core: add an option to trigger also an RST on tcp connection close

src/modules/ims_qos/rx_aar.c
- release the dialog reference even for aar updates as the dialog was
already referenced when issuing the aar request
=> ims_qos: rx_aar - unreference dialog in case of aar update

src/modules/lost/Makefile
`lost` is not build on FreeBSD environment.
The proposed patch fixes it and makes the module is consistent with the rest of modules.
=> Fix LOST for build on FreeBSD

src/modules/auth/api.c, src/modules/auth/api.h, src/modules/auth/auth_mod.c, src/modules/auth/doc/auth_functions.xml, src/modules/auth/nc.c, src/modules/auth/nc.h, src/modules/auth/nonce.c, src/modules/auth/nonce.h
This change modifies `pv_www_authenticate` and related functions to add flag 32. If the flag is set and `nonce_count` is enabled then we skip updating nc in `pre_auth`. On success we call `check_nonce` once more to do the nc update. This can be used to chain calls to authenticate against multiple passwords.
=> auth: Add flag for not invalidating nc on auth failure

src/modules/pua_dialoginfo/doc/pua_dialoginfo_admin.xml, src/modules/pua_dialoginfo/pua_dialoginfo.c, src/modules/pua_dialoginfo/pua_dialoginfo.h
Changes from Sipwise flavor:
- refresh_pubruri_avps_flag: if enabled, this message flag indicates whether to refresh R-Uri from avps before sending the PUBLISH requests.
- improvement for use_pubruri_avps: use locking to avoid crashes since we are using shared memory
- local_identity_dlg_var: reporting dialog-information will use the value of the dialog variable if exists
=> pua dialoginfo: improvements

src/modules/ims_registrar_scscf/doc/ims_registrar_scscf_admin.xml, src/modules/ims_registrar_scscf/ims_registrar_scscf_mod.c, src/modules/ims_registrar_scscf/save.c
Added corrections for 200OK reply on Re-Registration
according to RFC3261 - registrar respond with multiple bindings in case
of multiple bindings.
Added a new parameter skip_multiple_bindings_on_reg_resp
for 200OK reply used for Re-Registration. Default value is 0.
If set to 1 - registrar replies only with current contact, not with
multiple bindings.
=> ims_registrar_scscf: 200OK changes according to RFC3261

src/modules/topos/tps_msg.c
Topos is adding Contact header to the 407 reply
Related to https://github.com/kamailio/kamailio/pull/3149 even with https://github.com/kamailio/kamailio/commit/414c7dd608584df18f871b42e05f401e21ba775d applied
=> topos: don't insert contact header for 4xx replies

src/modules/nats/defs.h, src/modules/nats/doc/nats_admin.xml, src/modules/nats/nats_mod.c, src/modules/nats/nats_mod.h, src/modules/nats/nats_pub.c, src/modules/nats/nats_pub.h
- add `event_callback` KEMI param like in other modules
- expose `KSR.nats.publish`
I can fix module doc if it looks good. How to generate docs locally btw?
=> nats: add KEMI publish function and event_callback param

src/modules/tls/tls_select.c
- [  ] Small bug fix (non-breaking change which fixes an issue)
- [  ] New feature (non-breaking change which adds new functionality)
Certificate serial numbers can be large integers (> 2^64). Parse them as BIGNUM and store the string
in pv; we cannot store as integer anymore. The original code handles 2^64 with a static buffer of 19.
We upsize to 2^256 with a static buffer of 80.
**May break configurations** that try to extract the sn pv as an integer
(does anyone actually do this?)
Addresses #3168.
=> tls: cert serial number can exceed uint64

src/core/crypto/sha256.c, src/core/crypto/sha256.h
This adds `core/` support for SHA-512/256.
This is required for adding the SHA-512/256(&ldquo;SHA-512-256&rdquo;) digest algorithm to the `auth` module.
References:
* [RFC8760](https://datatracker.ietf.org/doc/html/rfc8760)
* [RFC7616](https://datatracker.ietf.org/doc/html/rfc7616) and [errata](https://www.rfc-editor.org/errata_search.php?rfc=7616&rec_status=0) — the example given in RFC7616 for SHA-512-256 is incorrect (it truncated SHA-512 to 64 bytes instead of using the correct implementation of SHA-512/256 which has a different set of initial hash values)
* [SHA-512/256 initial hash values](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf)
=> core: crypto add support for SHA-512/256 for RFCs 8760/7616

src/modules/presence/notify.c
This is a small performance improvement, the goal is to avoid issuing rollbacks if not necessary.
On my setup, Kamailio presence executes a lot of ROLLBACKS in MariaDB since function process_dialogs() runs repeatedly.
What see inside MariaDB logs is the following
```
SET autocommit=0
select `presentity_uri`,`callid`,`to_tag`,`from_tag`,`event` from `active_watchers` where `updated`=3 AND `event`<>'presence.winfo'\G
ROLLBACK
```
Maybe we can improve this behaviour telling presence to do autocommit to do not execute them if the select returns zero elements?
=> presence: No autocommit+rollback if no active watchers

src/lib/srdb1/schema/pr_watchers.xml, utils/kamctl/db_sqlite/presence-create.sql, utils/kamctl/mysql/presence-create.sql, utils/kamctl/oracle/presence-create.sql, utils/kamctl/postgres/presence-create.sql
Function ps_watchers_db_timer_clean() inside src/modules/presence/subscribe.c is called repeatedly on my setup.
Each time is called it performs a delete inside table watchers comparing columns inserted_time and status which are not indexed:
```
MariaDB [kamailio]> explain delete from `watchers` where `inserted_time`<1656252889 AND `status`=2;
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+
| id   | select_type | table    | type | possible_keys | key  | key_len | ref  | rows | Extra       |
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+
|    1 | SIMPLE      | watchers | ALL  | NULL          | NULL | NULL    | NULL | 1    | Using …
```
=> kamctl:Index "inserted_time"+"status" in watchers

src/modules/siptrace/doc/siptrace_admin.xml, src/modules/siptrace/siptrace.c
While testing this module, I've seen it doesn't trace in-dialog ACKs.
Found this old maillist discussion: https://lists.kamailio.org/pipermail/sr-users/2015-June/088731.html 
Added a condition to trace also the in-dialog ACKs. Is it ok to keep it as default or should I guard it via a modparam?
Thanks,
Stefan
=> siptrace: Trace in-dialog ACK and spiraled dialogs

src/core/sr_module.c
There's a problem after upgrade to 5.6 on FreeBSD. Kamailio isn't starting successful.
```
14:19:20.540514 kamailio 40921 - - DEBUG: <core> [core/cfg.y:1964]: yyparse(): loading module tls.so
14:19:20.540893 kamailio 40921 - - DEBUG: <core> [core/sr_module.c:513]: ksr_locate_module(): found module to load </usr/local/lib/kamailio/modules/tls.so>
14:19:20.540912 kamailio 40921 - - DEBUG: <core> [core/sr_module.c:563]: load_module(): trying to load </usr/local/lib/kamailio/modules/tls.so>
14:19:20.543301 kamailio 40921 - - ERROR: <core> [core/sr_module.c:352]: ksr_version_control(): no version info in module </usr/local/lib/kamailio/modules/tls.so>: Undefined symbol "_nss_cache_cycle_prevention_function"
```
The problem is in …
=> Fix ksr_version_control() for FreeBSD build

src/modules/dialog/dialog.c
Per the DB issue in #3218:
I've determined the commit where dialog with db_mode SHUTDOWN stopped working is 1ff86ffceede46c7a67fec92c8319c34c916a545.
This is the change where  `PROC_POSTCHILDINIT` was enabled/used.
In dialog.c `child_init()`, there is code that resets the DB mode to NONE if not running in the main process:
```c
/* in DB_MODE_SHUTDOWN only PROC_MAIN will do a DB dump at the end, so
* for the rest of the processes will be the same as DB_MODE_NONE */
if (dlg_db_mode==DB_MODE_SHUTDOWN && rank!=PROC_MAIN)
dlg_db_mode = DB_MODE_NONE;
```
However, because PROC_POSTCHILDINIT has now been enabled for the module, this code effectively disables DB persistence as PROC_POSTCHILDINIT is called in the main process after PROC_MAIN.
I …
=> dialog: dont reset dlg_db_mode in POSTCHILDINIT for DB_MODE_SHUTDOWN

src/modules/usrloc/dlist.c, src/modules/usrloc/doc/usrloc_admin.xml, src/modules/usrloc/ul_keepalive.c
- Fixes GH #3178. Sets TCP connection id for keepalive based on the value in the database
If unset, tcpconn_id will remain 0 and keepalives will work the same as they do today
- Update documentation to clarify when it will use received vs AOR for keepalive
Updated usrloc module to re-use an active TCP session (if it exists).  I marked this breaking only because the current code will use a UDP OPTIONS keepalive method even if the device is registered over TCP.  I doubt that's what anyone would be expecting so I think the change is ok.
=> usrloc: re-use TCP connections for keepalive

src/modules/topos/doc/topos_admin.xml, src/modules/topos/topos_mod.c, src/modules/topos/tps_msg.c, src/modules/topos/tps_msg.h
Topos module always put a single Via header with multiple comma separated values.
Even if this behaviour is RFC compliant there should a possibilty to disable that behaviour four uas that dont support/handle that.
this pull request adds a new parameter topos module to disable that behaviour if needed otherwise the default topos compact form is used.
```
modparam("topos", "separate_header_values", 1) # for Via only 
modparam("topos", "separate_header_values", 2) # for Record-Route only 
modparam("topos", "separate_header_values", 4) # for Route only 
modparam("topos", "separate_header_values", 7) # for Via, Record-Route  and Route 
The following options are available:
(1) - disable multiple comma separated values for Via  header
(2) - disable multiple comma separated values for …
```
=> topos: disable multiple comma separated values in One Single Via, Record-Route or Route header if needed

src/modules/pv/pv_time.c
Sometime is helpful to have a monotonic timer to attach to events in order to discard out-of-order ones on receiving side. Current time values are not ideal since are subject to clock skews, adjustment and so on. Since we have system monotonic clock we can use that value to have a monotonic counter. 
To be 100% fair CLOCK_MONOTONIC can still be skewed only by ntp adjustment, that's why we try to use CLOCK_MONOTONIC_RAW which is linux-only (afaik) that do not suffer from such adjustments.
The new pseudovariable is `$TV(Sm)`, which returns the monotonic counter as a string. Note that even if is based on clock, it starts from an unspecified point in time, so should really be treated as an always increasing counter.
=> pv: add monotonic clock to TimeVal pseudovariable

src/core/parser/msg_parser.c
When I upgraded kamailio version to 5.6.1, some http requests hit msg headers control and failed.
I think ksr_sip_parser_mode check should be added here for backward compatibility.
=> core: added parser mode check

src/modules/dialog/dlg_handlers.c
set context iuid for CANCEL requests to let isflagset function return the right value in case a dialog flag was previously set on the call
Using kamailio 5.4 version, we have seen that dlg_isflagset is not detecting a dialog flag set in the request route for the initial INVITE, when a CANCEL request arrives.
We have applied this change to set the dialog context unique ide for this request. Since it's done on dlg_onreply, dlg_onroute and dlg_ontimeout functions. This way, dlg_get_by_iuid(&dctx->iuid) in the function ki_dlg_isflagset is not NULL and dialog flags are detected.
Is this change correct? Or can it generate any kind of issues?
thanks a lot and regards
David
=> dialog: set context iuid for CANCEL requests

src/modules/rtpengine/doc/rtpengine_admin.xml, src/modules/rtpengine/rtpengine.c
Add receive-from option to flags
receive-from=1.2.3.4
required for managing rtpengine by a kamailio node behind a dispatcher
kamailio node
<pre>
UE behind NAT ------>Dispatcher Kamailio-----> Location & Media management Kamailio ------> C5 SoftSwitch
|                                   |
|                                   V 
|                               RTPENGINE
|
|------------>Location & Media management Kamailio ----------> C5 SoftSwitch
|
V
RTPENGINE
</pre>
In this scenario when the Kamailio behind the  Dispatcher will be getting the $Ri as dispatcher IP and by default that will be passed to RTP Engine for NAT negotiation which will fail.
In this pull merge requst, RTP engine module a new flag is added receive-from=IP which is supposed to be the received IP from the First node …
=> rtpengine module added receive-from option  to flags to managing rtpengine by a kamailio node behind dispatcher

pkg/kamailio/obs/kamailio.spec
The purpose of this pull request is to allow, when generating rpm's, the possibility of history/autocomplete to be seen in the interactive mode of kamcmd.
The proposed solution is to ensure that the readline-devel library is a requirement when building Kamailio, thus ensuring that kamcmd is compiled with this library.
Currently the specfile has as BuildRequires, the pkgconfig library. This library is installed by the readline-devel library (via ncurses-devel dependency), i.e. all existing logic remains unchanged. Furthermore, the readline-devel library is accessible on all distros that use this specfile, namely: Centos, Fedora, OpenSuse, RedHat.
Initially in my testing, I thought I needed to change the Makefile of kamcmd to look at …
=> pkg/kamailio/obs: added readline-devel build dependency

src/modules/dispatcher/dispatch.c
I found how the indexes could get mixed up between the call to ds_sorted_by_priority() and ds_manage_routes_fill_reordered_xavp() resulting in invalid gateway list selection. 
```
// TEST logs
I made some tests with 3 and 6 gateways, disabling one and then two.
Some test data :
INSERT INTO dispatcher VALUES(1,1,'sip:[192.168.0.1:5060](http://192.168.0.1:5060/)',0,12,'','');
INSERT INTO dispatcher VALUES(2,1,'sip:[192.168.0.2:5060](http://192.168.0.2:5060/)',0,12,'','');
INSERT INTO dispatcher VALUES(3,1,'sip:[192.168.0.3:5060](http://192.168.0.3:5060/)',0,12,'','');
INSERT INTO dispatcher VALUES(4,1,'sip:[192.168.0.4:5060](http://192.168.0.4:5060/)',0,12,'','');
INSERT INTO dispatcher …
```
=> dispatcher: fix alog13 gateway selections

src/modules/ims_qos/rx_aar.c
rx_aar: unreference dialog in case of aar update 
release the dialog reference even for aar updates as the dialog was
already referenced when issuing the aar request
=> rx_aar: unreference dialog in case of aar update

.github/workflows/main.yml, .github/workflows/pull_request.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

src/modules/presence_reginfo/Makefile, src/modules/presence_reginfo/add_events.c, src/modules/presence_reginfo/doc/presence_reginfo_admin.xml, src/modules/presence_reginfo/notify_body.c, src/modules/presence_reginfo/notify_body.h, src/modules/presence_reginfo/presence_reginfo.c
Right now the `presence_reginfo` module does not perform any aggregation on presentities from the same AoR. While this is generally ok for new notifies driven by new publishes, when a new subscription is received only the most recent presentity is notified. This PR adds a new parameter, disabled by default to preserve compatibility, which merges all presentities for the same AoR into a single document.
For example, two registrations from the same AoR will create the following document:
```<?xml version="1.0"?>
<reginfo xmlns="urn:ietf:params:xml:ns:reginfo" version="23" state="full">
<registration aor="sip:user2@example.com" id="0x7f9b6bbf9cf8" state="active">
<contact id="0x7f9b6bbf3ea8" state="active" event="created" expires="300" …
```
=> presence_reginfo: Add option for aggregating reginfo presentities

src/modules/mqtt/doc/mqtt_admin.xml, src/modules/mqtt/mqtt_dispatch.c, src/modules/mqtt/mqtt_dispatch.h, src/modules/mqtt/mqtt_mod.c
This is used when a service (like AWS IoT Core) uses one TLS port for multiple services (like https and mqtt), so you have to set the ALPN to 'mqtt' to be able to connect kamailio.
Some services use ALPN to have one single TLS port serving multiple protocols, in order to avoid additional round-trips for negotiating TLS connections. https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation has the details.
One of those services using ALPN is AWS IoT Core, which allows components to send messages both via HTTP and MQTT to AWS for further processing (e.g. logging, analysis, storage to db etc). This patch enables kamailio to communicate with this service by allowing the kamailio admin to set the mqtt.so module mod-param …
=> mqtt: Add tls_alpn module option

src/modules/rtpengine/rtpengine.c
In the two log lines, message id is written instead of rtpengine set id.
=> rtpengine: fixed set id value in log lines

src/modules/siputils/siputils.c
Fix the below warning one gets when compiling siputils for a 32 bit target against a time64 libc (musl).
Also fix a spelling mistake on the same line ("autdated" -> "outdated").
```
siputils.c: In function 'ki_hdr_date_check':
../../core/parser/../dprint.h:321:73: warning: format '%ld' expects argument of type 'long int', but argument 11 has type 'time_t' {aka 'long long int'} [-Wformat=]
321 |                                                         fprintf(stderr, "%2d(%d) %s: %.*s%s%s%s" fmt, \
|                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~
../../core/parser/../dprint.h:345:25: note: in expansion of macro 'LOG_FX'
345 |                         LOG_FX(facility, level, lname, prefix, _FUNC_NAME_, fmt, ## args)
| …
```
=> siputils: fix time_t warning and a typo

src/modules/secfilter/doc/secfilter_admin.xml, src/modules/secfilter/secfilter.c, src/modules/secfilter/secfilter.h, src/modules/secfilter/secfilter_db.c, src/modules/secfilter/secfilter_rpc.c
New params:
- reload_delta: To set the number of seconds that have to be waited before executing a new RPC reload
- cleanup_interval: To set the number of seconds that have to be wait before cleanup the previous values from memory after a RPC reload
The purpose is to avoid problems when accessing data lists while doing an RPC reload.
=> secfilter: cleanup old data after a reload by timer function

src/modules/dialog/dialog.c, src/modules/dialog/doc/dialog_admin.xml
support setting vars for non established dialogs
=> dialog: dlg_set_var() support empty totag parameter

src/modules/ims_usrloc_pcscf/README, src/modules/ims_usrloc_pcscf/doc/ims_usrloc_pcscf_admin.xml, src/modules/ims_usrloc_pcscf/ims_usrloc_pcscf_mod.c, src/modules/ims_usrloc_pcscf/ims_usrloc_pcscf_mod.h, src/modules/ims_usrloc_pcscf/pcontact.c, src/modules/ims_usrloc_pcscf/udomain.c, src/modules/ims_usrloc_pcscf/udomain.h, src/modules/ims_usrloc_pcscf/ul_callback.c, src/modules/ims_usrloc_pcscf/ul_callback.h, src/modules/ims_usrloc_pcscf/ul_rpc.c, src/modules/ims_usrloc_pcscf/usrloc.c, src/modules/ims_usrloc_pcscf/usrloc.h, src/modules/ims_usrloc_pcscf/usrloc_db.c, src/modules/ims_usrloc_pcscf/usrloc_db.h
In order to support a redundant PCSCF configuration - i.e. a logical PCSCF consists of 2 physical nodes (node1 and node2) some enhancements were introduced for handling of contacts. Redundancy means that SIP messages for a client are normally handled by node1 but in case node1 is not reachable SIP messages are redirected to node2. Of course the DB_ONLY mode must work also for single PCSCF node configuration. Important aspects of this implementation are database integrity - i.e. avoid invalid table entries (for example data which are expired long time ago or have invalid states) - and keeping PCSCF cache in sync with database tables. A wrapper was built for method get_pcontact which tries to find the pcontact in cache and if search is not successful tries to download and insert from db …
=> ims_usrloc_pcscf:   implementation of db_mode DB_ONLY (value 3)

src/modules/tm/t_suspend.c
- if t_suspend and t_continue are used for replies and in the called route in t_continue the body of the sip message is parsed the pkg memory of the parsed body is leaked
=> tm: cleanup parsed body at the end t_continue_helper

pkg/kamailio/alpine/APKBUILD
Do not build python2 module with default APKBUILD file due to python2 being sunsetted within Alpine Linux (there is no python2 APK).
=> APKBUILD: remove python2 references

src/modules/sanity/sanity.c
For star Contacts, there are no URIs that can be checked.
If Contact URI should be checked, there is no URI if the Contact is a star Contact [1].
[1] https://www.rfc-editor.org/rfc/rfc3261#section-10.2.2
=> sanity: Prevent segfault related to contact URI check

src/modules/carrierroute/carrierroute.c, src/modules/carrierroute/cr_fixup.c, src/modules/carrierroute/cr_fixup.h, src/modules/carrierroute/cr_func.c, src/modules/carrierroute/cr_func.h, src/modules/carrierroute/doc/carrierroute.xml, src/modules/carrierroute/doc/carrierroute_admin.xml
Following carrierroute module functions are exported to KEMI API.
- cr_load_next_domain ( )
- cr_route ( )
- cr_nofallback_route ( )
Additionally various fix-up free functions added for better memory management. The documentation has been updated to correctly explain various parameters and use cases.
```python3
def route_proxy(self, msg):
KSR.info("==================== route_proxy\n")
rU = KSR.kx.get_ruser()
if rU == None:
return -255
if KSR.carrierroute.cr_route("default", "proxy", rU, rU, "call_id") < 0:
KSR.sl.sl_send_reply(400, "Bad Request")
return -255
```
```python3
def route_registrar(self, msg):
KSR.info("==================== route_registrar\n")
rU = KSR.kx.get_ruser()
if rU == None:
rU = ""
if …
```
=> carrierroute module functions export to kemi

src/modules/websocket/doc/websocket_admin.xml
otherwise the code below always matches:
```
if ($Rp != 80 && $Rp != 443) {
```
=> websocket: example must listen on ports 80 and 443

src/modules/exec/doc/exec_admin.xml
- Added warning about potential for OS Command Injection
- Updated invalid examples
previous example gives the following error:
pv_parse_spec2(): error searching pvar "rU.txt"
Misuse of the exec module functions is a security concern. This PR updates the documentation to help Kamailio administrators use these functions securely.
=> exec: docs - added security warning

src/modules/websocket/doc/websocket_admin.xml, src/modules/websocket/utf8_decode.h
I run Kamailio with
```
log_stderror=yes
/* LOG Levels: 3=DBG, 2=INFO, 1=NOTICE, 0=WARN, -1=ERR, ... */
debug=-1
```
and inspect the output.  Some messages from the websocket module are logged repeatedly at ERROR-level, but they are in no way errors.  This changes moves such periodially logged no-error messages to debug-level INFO.
=> websocket: typos

src/modules/usrloc/udomain.c
previously $ulc(x=>aor) had only the user part even with use_domain set
output after applied the fix
```
│Feb  9 16:47:58.089067 spce proxy[30268]: DEBUG: usrloc [udomain.c:1053]: udomain_contact_expired_cb(): calling contact expired records - cycle [1]
│Feb  9 16:47:58.089100 spce proxy[30268]: DEBUG: usrloc [ul_callback.h:83]: run_ul_callbacks(): contact=0x7f8859ed4f50, callback type 8/8, id 0 entered
│Feb  9 16:47:58.089197 spce proxy[30268]: DEBUG: registrar [regpv.c:734]: reg_ul_expired_contact(): saved contact for <43991002@ce-trunk.lab> in [exp]
│Feb  9 16:47:58.089220 spce proxy[30268]: NOTICE: usrloc:contact-expired <script>: Contact ruid uloc-63e5131a-7639-1 to sip:43991002@192.168.2.177:5160 for user 43991002@ce-trunk.lab …
```
=>  usrloc: correct AOR value on usrloc:contact-expired

src/modules/nathelper/doc/nathelper_admin.xml, src/modules/nathelper/examples/4to6.cfg, src/modules/nathelper/examples/alg.cfg, src/modules/nathelper/nathelper.c, src/modules/nathelper/nhelpr_funcs.c
My experiments show that with
```
modparam("nathelper", "ping_nated_only", 1)
modparam("nathelper", "sipping_bflag", FLB_NATSIPPING)
modparam("usrloc", "nat_bflag", FLB_NATB)
```
when both FLB_NATB and FLB_NATSIPPING branch flags are set, no OPTIONS from Kamailio to UAC is generated, so I assume that nathelper.ping_nated_only=1 does force 4-bytes UDP keepalive.
This change spells the above, as the behaviour currently is not specified.
=> nathelper: ping_nated_only=1 sends SIP-request-based pings

utils/kamctl/kamctl.base
Hide error messages from "which" to avoid polluting kamctl's output (e.g. when a JSON document is returned) in environments where STDOUT and STDERR may be combined into a single stream (e.g. containers).
Without this change, kamctl's output may end up containing error messages, resulting in invalid/unparsable data. This is caused by the stdout & stderr streams being combined into a single stream in some environments, which may be outside the end-user's control (e.g. external cloud provider).
=> kamctl: hide errors raised by "which"

src/modules/auth_ephemeral/auth_ephemeral_mod.c, src/modules/auth_ephemeral/auth_ephemeral_mod.h, src/modules/auth_ephemeral/authorize.c
- proper way to work with shm pointer to secret list
In case of adding secrets at runtime with autheph.add_secret rpc, authentication with new secrets not work,
this is because rpc process modify local pointer to secret list, instead shm.
=> auth_ephemeral: fix authentication with secrets added at runtime

src/modules/ims_registrar_pcscf/doc/ims_registrar_pcscf_admin.xml, src/modules/ims_registrar_pcscf/ims_registrar_pcscf_mod.c, src/modules/ims_registrar_pcscf/notify.c, src/modules/ims_registrar_pcscf/save.c
Enable registration of pcscf contact callback during download from db location table and inserting pcontact (normally this callback is registered during handling of REGISTER). Refuse REGISTER when pcontact is expired since [0 to 20] seconds. Within this time window a NOTIFY is expected from scscf and in order to avoid race time conditions between scscf and pcscf REGISTER will be refused. Refuse REGISTER when pcontact is expired longer than 20 seconds - send PUBLISH (contact expired) to scscf to trigger NOTIFY. In both REGISTER refused scenarios routing script should reply 500 - Deregister in progress.
- [ x] Each component has a single …
=> ims_registrar_pcscf:  changes for ul db_mode DB_ONLY

src/modules/tcpops/tcpops_mod.c
In `tcpops` module, the method `tcp_get_conid()` was missing which may be needed to trace, track and log TCP connections, especially for UDP to TCP reply route in KEMI. The patch is tested to work with `master` and `5.6` and above branches.
=> tcpops: added tcp_get_conid() for kemi

src/modules/tls/tls_select.c
- adds count pv and sel for DNS, EMAIL, IP, URI
- adds ability to access SAN entries by index
fix #3400
Fix issue #3400 that describes that tls module cannot properly handle certificates with multiple SAN entries.
Add ability to access SAN entries by index.
Add ability to get count of supported SAN entries by type of entry.
If index is not provided will return first entry (current behavior to remain backwards compatible.
Tested by creating a self signed SAN cert with 3 DNS entries and confirmed expected results for:
$(tls_peer_san_hostname[2])
$(tls_peer_san_hostname);
$tls_peer_san_count(DNS)
$tls_peer_san_count(URI)
$tls_peer_san_count(EMAIL)
$tls_peer_san_count(IP)
$sel(tls.peer.dns[1])
$sel(tls.peer.dns) …
=> tls: get san entries by index

src/modules/lcr/lcr_mod.c
move the check of lcr_id to the helper so every ``ki_load_gw*()`` will be protected
=> lcr: fix crash be calling load_gw* via KEMI

src/modules/rtpengine/bencode.c
Make sure the pointers we return from our continuous memory buffer is always 64-bit aligned as it's used not only for strings, but also for structs/objects, and such unaligned memory access is undefined on some archs and flagged as such by ASAN.
From https://github.com/sipwise/rtpengine/commit/ade8100d3b10308f1ff63f8cb06fdf292618edca
=> rtpengine: fix unaligned memory access

src/modules/registrar/doc/registrar_admin.xml, src/modules/registrar/regpv.c, src/modules/registrar/save.c
This is adding the variable `tcpconn_id` to `xavp_cfg`
When using Kamailio as a "mid registrar", we need to save the contact in the reply-route (once we have the confirmation from the registrar), one problem I faced was that the tcpconid was the one of the response message coming from the registrar.
I needed a way to save the one of the original request message.
```
modparam("registrar", "xavp_cfg", "reg")
route[REGISTER] {
...
t_on_reply("ON_REPLY_REGISTER");
$xavp(reg=>tcpconn_id) = $conid; // set the TCP connection id to be saved on the reply
....
}
onreply_route[ON_REPLY_REGISTER] {
if (t_check_status("200")) {
if (is_present_hf("Expires") && $hdr(Expires) == "0") {
xinfo("[ON_REPLY_REGISTER][$rm][$ci] registrar …
```
=> registrar: adding tcpconn_id to xavp_cfg

src/core/cfg_core.c, src/core/cfg_core.h, src/core/pvapi.c, src/core/pvapi.h
implemented a way to dump the names of the variables stored in pv_cache this helped me to find out what was filling the pv_cache
=> core: pv_cache_dump

misc/tools/route_graph/route_graph.py
=> tool: port the route_graph.py script to python version 3.x

src/modules/db_redis/Makefile, src/modules/db_redis/db_redis_mod.c, src/modules/db_redis/doc/db_redis.xml, src/modules/db_redis/doc/db_redis_admin.xml, src/modules/db_redis/redis_connection.c, src/modules/db_redis/redis_connection.h, src/modules/ndb_redis/Makefile, src/modules/ndb_redis/doc/ndb_redis.xml, src/modules/ndb_redis/doc/ndb_redis_admin.xml, src/modules/ndb_redis/ndb_redis_mod.c, src/modules/ndb_redis/redis_client.c, src/modules/ndb_redis/redis_client.h
A couple of commits into db_redis and ndb_redis adding TLS support and also password support to db_redis.
This mainly includes checking if proper parameter is provided (for ndb_redis is `tls` option in the DB URL and, for db_redis, a new `opt_tls` parameter) and creates a temporary SSL context that is used to initialise the redis context.
Also added `ca_path` parameter to both modules to be able to define a valid folder containing the root certificates used to validate TLS' certificate chain.
db_redis is also updated with a `db_pass` parameter to provide a DB access password.
TLS support is automatically enabled by checking libhiredis_ssl.so existence in each Makefile and defining a `WITH_SSL` flag that enables all the corresponding …
=> Adding TLS support to db_redis (also password support) and ndb_redis

src/modules/ims_qos/rx_aar.c
Check for NULL sessionId from PCRF, which can lead to kamailio crash.
=> ims_qos: check and log for NULL sessionId

src/modules/nats/nats_mod.c, src/modules/nats/nats_mod.h, src/modules/nats/nats_pub.c, src/modules/nats/nats_pub.h
commit a725b4fd224c27d84a9f5623faa5af3c3873a2e5 seems to make the `nats_publish` function require the `reply.topic` parameter required. The change from that commit breaks backward compatibility and forces the configuration to pass a reply.topic. This PR makes the `reply.topic` optional.
=> nats: nats_publish set reply parameter to be optional

utils/kamctl/kamctl, utils/kamctl/kamctl.base
kamctl: added new options to dispatcher interface
- added a new `rmip` option to delete a specific gateway `ip` in a predefined `setid`
- added a new `rmset` option to delete a specific `setid` completely
=> Add 2 new options to dispatcher management in kamctl

src/modules/rtpproxy/rtpproxy.c
The module has been broken in d00ceda2c04. The code to replace strcpy() did not terminate the target sting with \0.
Discovered by our voiptests rig:
https://github.com/sippy/voiptests/actions/workflows/kamailio.yml
Results in a broken SDP (note garbage around o= attribute:
```
1681	00:00:08.271/GLOBAL/alice_ua: RECEIVED message from [::1]:5060:
1682	SIP/2.0 183 Session Progress
1683	Via: SIP/2.0/UDP [::1]:5061;received=::1;rport=5061;branch=z9hG4bK20a1169c6781e4bfe26554e84d3b4925
1684	Record-Route: <sip:[::1];ftag=l5v4RNY4iYqP.*!0LQUA.MLVq8RX'm!q;lr>
1685	From: "Alice Smith" <sip:alice_2_ipv6@[::1]>;tag=l5v4RNY4iYqP.*!0LQUA.MLVq8RX'm!q
1686	To: <sip:bob_2@[::1]>;tag=c77c4b2c8430cf6c18566bc3d9212ed3
1687	Call-ID: …
```
=> rtpproxy: make sure we null terminate the copy of the string.

.clang-format, .devcontainer/Dockerfile, .devcontainer/devcontainer.json
Initial support of [devcontainers](https://containers.dev/)
Allows to develop inside a container using [vscode](https://code.visualstudio.com/docs/devcontainers/containers)
Next steps:
* configure github actions to build and publish the image in our github repository
https://github.com/devcontainers/ci/blob/main/docs/github-action.md
* include configurations for vscode to build and run kamailio
* investigate how to debug inside vscode
=> Initial support for devcontainers

src/modules/crypto/crypto_uuid.c
From https://www.openssl.org/docs/man3.0/man7/migration_guide.html
> Use of low-level digest functions such as SHA1_Init(3) have been informally
> discouraged from use for a long time. Applications should instead use the
> high level EVP APIs EVP_DigestInit_ex(3), EVP_DigestUpdate(3) and
> EVP_DigestFinal_ex(3), or the quick one-shot EVP_Q_digest(3).
=> crypto: SHA1_Init deprecated at openssl 3.0

src/core/tcp_main.c, src/core/tcp_options.h
Use tcp_send_timeout config option also on listening socket to timeout outbound messages sent on passive inbound connections.
Based on the description of core parameter "tcp_send_timeout" the timeout should also work for sending on forked incoming tcp connections. But sending on a broken connection causes the kernel to use the default values of `tcp_retries1` and `tcp_retries2` , leading to try to send a SIP message for 15 minutes. This makes absolutely no sense in a real time kamailio application.
Following man 7 tcp TCP_USER_TIMEOUT can be used on recent Linux kernels to utilize tcp_send_timeout:
TCP_USER_TIMEOUT (since Linux 2.6.37)
This  option  takes  an  unsigned  int as an argument.  When the value is greater than 0, it …
=> core: Add TCP_USER_TIMEOUT socket option on listening socket.

src/modules/rabbitmq/doc/rabbitmq_admin.xml, src/modules/rabbitmq/rabbitmq.c
Enabling rabbitmq_publish function on any route so we can send events on reply reception.
Also disabling peer verification on the TLS handshake if no CA file is configured.
=> rabbitmq: Enabling rabbitmq_publish for any route and disabling peer verfication

src/modules/dispatcher/dispatch.c, src/modules/dispatcher/dispatch.h, src/modules/dispatcher/dispatcher.c, src/modules/dispatcher/doc/dispatcher_admin.xml
Added new module param to enable retention of call stats for existing destinations when reloading the list from file or database.
Also updated to retain stats for other destinations when adding/removing individual ones via RPC.
=> dispatcher: add option to retain existing latency stats when reloading destinations

src/core/cfg.y
In the XAVPVIAFIELDS block there is the string written to the wrong variable.
The string is stored in _ksr_xavp_via_params.s but the lenght is stored in _ksr_xavp_via_fields.len. This breaks XAVPVIAPARAMS and XAVPVIAFIELDS.
`via_use_xavp_fields("1");` and probably `via_add_xavp_params("1");` are broken because of a typo in parsing the xavp names. The values of xavp_via_params global parameter and xavp_via_fields global parameter are not stored correctly.
=> core: cfg.y typo in parsing XAVPVIAFIELDS

src/modules/tm/config.h, src/modules/tm/dlg.c, src/modules/tm/doc/event_routes.xml, src/modules/tm/doc/functions.xml, src/modules/tm/doc/params.xml, src/modules/tm/doc/tm.xml, src/modules/tm/h_table.c, src/modules/tm/h_table.h, src/modules/tm/select.c, src/modules/tm/sip_msg.c, src/modules/tm/sip_msg.h, src/modules/tm/t_fifo.c, src/modules/tm/t_funcs.c, src/modules/tm/t_funcs.h, src/modules/tm/t_fwd.c, src/modules/tm/t_hooks.c, src/modules/tm/t_hooks.h, src/modules/tm/t_lookup.c, src/modules/tm/t_msgbuilder.c, src/modules/tm/t_msgbuilder.h, src/modules/tm/t_reply.c, src/modules/tm/t_stats.h, src/modules/tm/t_suspend.c, src/modules/tm/timer.c, src/modules/tm/timer.h, src/modules/tm/tm.c, src/modules/tm/uac.c
I removed the word atomic before transaction, since it implies that there are in addition non-atomic ways to create a transaction.
Per https://lists.kamailio.org/mailman3/hyperkitty/list/sr-users@lists.kamailio.org/message/V7ZJEQZMXH7BNGRDI32BTYX742GVAWDB/ t_relay() creates a transaction.
- typos
=> tm: clarify t_relay() can create a transaction

src/modules/statsd/lib_statsd.c, src/modules/statsd/lib_statsd.h, src/modules/statsd/statsd.c
A user reached me to add a way to add the custom labels into the statsd
module, so a better way to report metrics to the observability platform.
I keep the same old functions and add a new parameter to the statsd
modules to both interfaces cfg and kemi.
The full documentation can be found here:
https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics
So, each function can be used like this: ``` statsd_set("fooo", 1,
"inbound"); statsd_gauge("NotFound", "+1", "outbound,carrierFoo");
statsd_gauge("AuthFailed", "+1", "carrier=foo,priority=10"); ```
Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>
Tested-by: Alex Antonevych <alex.antonevych@replicant.ai>
I'm waiting until first review on function arguments to create …
=> statsd: Add labels to metrics.

src/core/forward.c, src/core/socket_info.c, src/core/socket_info.h, src/core/tcp_main.c
fixed incorrect source IP address selection for the SIP messages sending procedure when TCP transport is used or for UDP with the 'mhomed' setting set as 'mhomed=1'.
The current service behavior is as follows: if OS contains several network interfaces and the service has a listening TCP socket (or UDP with 'mhomed=1' setting) on the second (third, fourth and so  on) interface, then the outbound SIP messages will be always sent from the first (default) interface.
These changes make the outbound SIP messages always going through the network_interface/address, which is taken for listening by service.
=> core: fixed wrong network interface selection.

src/modules/ims_qos/doc/ims_qos_admin.xml, src/modules/ims_qos/ims_qos_mod.c, src/modules/ims_qos/rx_aar.c
Currently, when making an AAR, transaction is suspended and then continued. This is because one may want to block call upon AAR failure.
In our use case, we don't want to block any calls, regardless of AAR return code. This makes suspend/continue of the transaction an overhead. Moreover, if the PCRF is slow, transaction blocks untill PCRF responds.
Add a module parameter to control if one wants to suspend or not the tm transaction (default is the current behavior). Local basic tests work ok, more testing will follow.
=> ims_qos: Add suspend_transaction parameter

misc/examples/kemi/kamailio-basic-kemi-lua.lua
A while ago I wanted to adjust my Lua configuration to work with rtpengine and I have adjusted this example accordingly.  I have not tried the example, but if there are no obvious bugs with it, I think it will be useful.
=> examples/kamailio-basic-kemi-lua.lua: Add example for rtpengine

src/modules/presence/notify.c, src/modules/presence/notify.h, src/modules/presence/presence.c
Since some customers are complaining on leftovers at active_watchers. Let's create a cleanup timer for that table too.
=> presence: active_watcher cleanup timer

src/modules/http_client/curlcon.c, src/modules/http_client/curlcon.h, src/modules/http_client/doc/http_client_admin.xml, src/modules/http_client/functions.c, src/modules/http_client/http_client.c, src/modules/http_client/http_client.h
A new parameter timeout_mode is added.
This parameter defines if timeouts are enabled, and in which unit timeout values are expressed.
- 0 - Timeouts are disabled.
- 1 - Timeout values are in seconds (default).
- 2 - Timeout values are in milliseconds.
For reference, see discussion in: https://github.com/kamailio/kamailio/pull/3611
Implementation detail:
```
default global timeout = 0 (unconfigured).
Parse connections as usual. If they have a timeout configured, use it.
In mod_init:
if global timeout == 0 (unconfigured), and timeout_mode is 1 or 2:
if timeout_mode == 1 -> global timeout = 4 (seconds)
if timeout_mode == 2 -> global timeout = 4000 (milliseconds)
for each connection "conn" (fixup):
if timeout_mode is not 1 or 2 -> …
```
=> http_client: Add parameter timeout_mode (timeout in seconds or ms)

src/modules/secsipid/secsipid_mod.c, src/modules/secsipid_proc/secsipid_proc_mod.c
Nightly builds broke due to https://github.com/kamailio/kamailio/commit/c8d56ed3afa19c29279e54fffd40b9810bb0d67c
https://kamailio.sipwise.com/job/kamailiodev-nightly-binaries/2517/console
=> secsipid: fix build errors for older versions of secsipid lib

src/modules/cdp/receiver.c
This was originaly fixed in #3601, but that did not handle the change in #3612 very well.
Fix for undefined symbols when using older/unsupported OpenSSL.
This was originaly fixed in #3601, but that did not handle the change in #3612 very well.
=> cdp: Fix for undefined symbols when using older/unsupported OpenSSL

src/modules/tm/t_suspend.c
I've been testing the ims_charging module which relies on a diameter request and async reply. If there's no available diameter server, Ro_CCR() calls t_cancel_suspend() to cancel suspension of the transaction and return an error.
Based on my understanding, it should now be possible to continue script logic as if the transaction was not suspended at all.
In our case we want the call to go through anyway, as a fallback.
The INVITE is being sent to the destination, but all replies are filtered since the suspended flag is still set.
Tested this change locally, and it's now working according to our needs.
=> tm: T_ASYNC_SUSPENDED flag not removed when cancelling a suspension

src/modules/cdp/diameter.h, src/modules/cdp/routing.c
If an endpoint responds with a CEA (Capabilities-Exchange Answer) indicating support for relaying (application-id 0xffffffff), let this endpoint be used for any application. The DRA will then be responsible for routing the request to the correct destination.
To fully support this, there might be a need for additional changes in some of the modules. That is to make sure subsequent requests for a given session is always routed to the same destination, indicated by Origin-Host in answers from a diameter server. Destination-Host of the new request should then be filled with this value.
A change for the ims_charging module is on the way.
=> cdp: Support for diameter routing agent (DRA) / relaying

utils/kamctl/kamctl
kamctl now sources the kamctlrc from only one location if available in this order: 
1. same folder as kamctl,
2. {intstall_prefix}/etc/kamailio/,
3. ~/.kamctlrc
4. /etc/kamailio/. 
If no kamctlrc is found, it continues just like before. Should it stop?
`kamctl` uses env variables from all the config files above, and retains the env value of the latest config that declares it.
Let's say we have 3 kamctlrc files right now:
```
...
SIP_DOMAIN=kamailio.org
DBENGINE is commented
...
```
```
...
SIP_DOMAIN=kam0.XXXX.net
DBENGINE=MYSQL
...
```
```
...
SIP_DOMAIN is commented
DBENGINE=MYSQL
...
```
Running `{install_prefix}/sbin/kamctl` (before changes in order) it prints :
```
Loading config file …
```
=> kamctl: Source only one kamctlrc

src/modules/topos/tps_msg.c
When caller sent a BYE instead a CANCEL into a non connected call, route are badly reappend by topos.
regression introduced by patch 091dc9a76bcec5c8a4bc73e863ed10b1b9d76c92
topos: fix early-dialog b-side UPDATE requests routing (GH #3437)
=> topos: BYE sent by caller before call was connected was badly managed

src/modules/cdp/acctstatemachine.c, src/modules/cdp/diameter_code_avp.h, src/modules/cdp/peerstatemachine.c, src/modules/cdp/session.c, src/modules/ims_charging/Ro_data.c, src/modules/ims_charging/Ro_data.h, src/modules/ims_charging/ccr.c, src/modules/ims_charging/config.h, src/modules/ims_charging/dialog.c, src/modules/ims_charging/doc/ims_charging_admin.xml, src/modules/ims_charging/ims_charging_mod.c, src/modules/ims_charging/ims_ro.c, src/modules/ims_charging/ims_ro.h, src/modules/ims_charging/ro_db_handler.c, src/modules/ims_charging/ro_db_handler.h, src/modules/ims_charging/ro_session_hash.c, src/modules/ims_charging/ro_session_hash.h, src/modules/ims_charging/ro_timer.c, utils/kamctl/mysql/ims_charging-create.sql
**Use origin-host of CCR response as destination-host of subsequent CCR requests**
When connecting to a diameter node which using relay, it may load balance requests to multiple servers for handling. This change ensures that subsequent requests are sent to the same server.
**Honour AVP_Time_Quota_Threshold in CCR response**
Charging server indicates it want an interim update X number of seconds before all quota has been used.
**Add new modparam «strip_plus_from_e164»**
The existing formatitng routine check if it's a tel: or sip: uri, and sets E.164 or SIP according to that. If it's E.164, it strips "tel:" too. A subscription id with leading "+" is actually of type SIP.
I didn't want to make a breaking change here, so I introduced a …
=> ims_charging: Various improvements to make module compatible to other charging server vendors

src/modules/sca/sca_subscribe.c
From https://github.com/kamailio/kamailio/pull/3569
After initial subscription by the SCA device, if we power off and on again, we won't get an unsubscribe notification and we are getting a new record-route with sca-subscription. In this case kamailio not updating the new record-route for the SCA Device.
=> sca: update rr if necessary for subscriptions

src/core/timer_proc.c
If kamailio is in the shutdown phase proc timers should not be executed since memory objects are getting destroyed and cores could happen
=> core: timer_proc don't execute timers on shutdown phase

src/modules/uac/uac_send.c
This PR fixes the setting of uac_req object's socket length.
=> uac: fix socket length settings

pkg/kamailio/obs/kamailio.init, utils/kamctl/kamctl, utils/kamctl/kamctl.base, utils/kamctl/kamdbctl, utils/kamctl/kamdbctl.base
On Ubuntu, `/bin/sh` defaults to `dash` whose built-in `echo` command does not support the `-e` flag. `printf`, on the other hand, supports backslash escapes by default so we use that instead.
In passing, also clean up some messy ANSI escape codes.
=> utils: Prefer `printf` over `echo -e`.

src/Makefile.groups
Currently dlgs and sworker modules are not packaged. We propose with this PR to add them to the extra modules list.
=> Makefile.groups: add dlgs and sworker to extra modules

src/modules/dialog/dlg_db_handler.c
=> Fixed saving dialogs on shutdown that are already loaded at startup in db_mode 3

src/modules/cdp/cdp_tls.c
This PR fixes the disabled parts of the TLS code in cdp module which resulted in getting an error (**undefined symbol init_ssl_methods**) whenever cdp module was loaded and following openssl version was used.
```
openssl version
OpenSSL 1.1.1f  31 Mar 2020
```
=> cdp: fix disabled parts for openssl version newer than 1.1.0

src/modules/pv/pv_core.c
Before: -1 yielded null and -2 the last element of a header
This PR fixes a bug referenced in #3653.
Before fix `$(hfl(HEADER)[-1]` where `HEADER='Via' | Contact | Route | Record-Route ` produced `null` instead of the last element of header.
=> pv_core: Fix negative index bug for hfl()

src/core/parser/contact/contact.c
- Contacts are now added at the end of the list.
- hfl(Contact)[index] is now returning in the correct order.
Currently, if a sip message contains multiple Contacts or just 2, let's say 
```
Contact: <sip:bob0@example.com>;expires=3600,<sip:bob1@example.com>;expires=3600,<sip:bob2@example.com>;expires=3600
Contact: <sip:bob3@example.com>;expires=3600,<sip:bob4@example.com>;expires=3600,<sip:bob5@example.com>;expires=3600
```
contacts are stored in the reversed order, ie bob2, bob1,bob0 and bob5,bob4,bob3.
This can be seen with a simple config file such as:
```
#kamailio.cfg
...
request_route {
...
xlog("L_INFO", "Contact headers: $hfl(Contact)\n");
xlog("L_INFO", "Contact headers 0: $(hfl(Contact)[0])\n");
xlog("L_INFO", "Contact …
```
=> parser/contact: Change addition order to the end of list

src/modules/http_async_client/http_async_client_mod.c
=> http_async_client: exit mod_init if tm is not loaded

src/Makefile.defs
similar to 87ed3d9c3ae3ecfabe6
GCC 14 will be released in April or May 2024.  Adding this now will avoid backporting the change to the 5.8 branch. (Not that 87ed3d9c3ae3ecfabe6 was backported to 5.7.)
=> src/Makefile.defs: recognize GCC 14 as recent ⇔  not too old compiler

src/modules/dialog/dlg_req_within.c
We've recently been exeperiencing a core dump in dialog module. The core dump was caused by trying to terminate via rpc command a dialog that had just been terminated by one of the parties sending a BYE. That's because send_bye treats a deleted dialog as a non confimed one (https://github.com/kamailio/kamailio/blob/404b47791678c4eaccd4cfc7a83e0bb97a29b5d3/src/modules/dialog/dlg_req_within.c#L387) and tries then to access a transaction that does not exist anymore (https://github.com/kamailio/kamailio/blob/404b47791678c4eaccd4cfc7a83e0bb97a29b5d3/src/modules/dialog/dlg_req_within.c#L391) and crashes.
=> dialog: don't send the BYE if dialog is in deleted state

src/modules/db_unixodbc/dbase.c
The bug report kamailio configuration is using dispatcher + unixodbc and the database driver (tested with MariaDB ODBC, user reports with MS SQL Server(not tested)) inits libssl in rank 0(thread 1).
This PR will init in a thread. This fix is similar to the one done for `outbound` 4742c81.
=> db_unixodbc: init libssl in a thread

src/modules/db_mysql/km_dbase.c
`mod_init()` in configuration can initialise libssl in rank 0(thread#1). User report is with regard to using `db_unixodbc`; however the same errors can be reproduced with `db_mysql` replacing `db_unixodbc`.
This PR inits libssl in a separate thread.
=> db_mysql: init libssl in a thread

src/modules/db_mysql/doc/db_mysql_admin.xml, src/modules/db_mysql/km_my_con.c
When db_mysql is built with mariadb-connector-c it does not use TLS and fails if the server requires TLS. It seems to be related to the fact that the MYSQL object needs to have a minimal non-NULL configuration (unlike MySQL Connector/C).
This is a minimal setting to allow TLS. A more full-featured solution would be to enable db_mysql to read from an external configuration file.
@linuxmaniac, kindly take a look
UPDATE: the flag is MYSQL_OPT_SSL_ENFORCE which uses TLS if server advertises it. It does not make TLS mandatory (i..e doesn't fail if server has no TLS)
UPDATE: reuse module param `opt_ssl_mode` to configure MariaDB Connector/C.
Use existing `opt_ssl_mode` and map as follows.:
1. 0(off), 1(SSL_MODE_DISABLED): …
=> db_mysql: enable TLS when building with mariadb-connector-c

src/modules/file_out/Makefile, src/modules/file_out/doc/Makefile, src/modules/file_out/doc/file_out.xml, src/modules/file_out/doc/file_out_admin.xml, src/modules/file_out/file_out.c, src/modules/file_out/types.c, src/modules/file_out/types.h
This pull request is intended to introduce a new, straightforward module that can efficiently stream output to files while also handling changes based on a specific interval. The module contains only one function that streams a chunk of text to the current output file handle associated with the given file index.
It's not 100% completed but the basic features are there. Any reviews and of course naming of the module, much appreciated.
---
How the module works:
- Set parameter `base_folder` to define where you want your logs to be saved.
- Set `base_filename` (up to 10) to define the names of your files. Each is associated with an index according to the order you defined it. First `base_filename`'s index is 0, second's index is 1 and so …
=> New module/file_out: Module to log custom strings to file

src/core/rthreads.h, src/modules/db_mysql/km_dbase.c, src/modules/db_postgres/km_dbase.c, src/modules/db_unixodbc/dbase.c
This PR audits functions calling libssl  in the  default kamailio.cfg + database using MariaDB and PostgreSQL (including unixODBC variants) and then adds  thread guards to all such functions.
The audit platform is Debian 12.
1. mariadb-client, libmariadb-dev, odbc-mariadb
2. postgresql-15, postgresql-client-15, odbc-postgresql
Thread guards added to:
* `db_XXXX_close()`
*  `db_unixodbc_free_result()`, `db_unixodbc_query`
=> libssl thread guards: audit of kamailio.cfg with MariaDB/PostgreSQL/unixODBC

src/core/rthreads.h, src/modules/db_mysql/km_dbase.c, src/modules/db_postgres/km_dbase.c, src/modules/db_unixodbc/dbase.c
@henningw @miconda this is a draft for the 5.7 stable branch which disables threading for process_no > 0. This restricts thread wrappers to the parent process.
I have done a quick smoke-test in my testlab and this seems to work (i.e. use threads only in process#0)
[Update] audit all libssl calls in default kamailio.cfg with MariaDB/PostgreSQL(and unixODBC variants).  All functions that call libssl have thread guards
=> libssl thread guards: restrict execution to process_no = 0

src/modules/ldap/doc/ldap_admin.xml, src/modules/ldap/ldap_mod.c
This PR aims to give the option for ldap to allow kamailio to start-up even if server is not reachable/available when starting.
It follows similar logic to https://github.com/kamailio/kamailio/commit/2df43b992b1e6932974bd0c928c0465a839b75da for SQL.
A new config parameter for `ldap` module is defined, `connect_mode`, that defaults to 0, preserving the old behavior. If it's set `1`, `kamailio` will not exit and allow `ldap` to try and reconnect when necessary.
=> ldap: option to start even when connecting to ldap server fails

etc/kamailio.cfg, src/core/cfg.lex, src/core/cfg.y, src/core/globals.h, src/core/rthreads.h, src/main.c, src/modules/tls/tls_mod.c
This PR restores the default behaviour of stable branch and makes libssl thread-guard work opt-in.
- user's config from 5.7.3 will run unchanged
- backport tls_threads_mode = 0|1|2 from dev; user must explicitly opt-in to libssl changes
Scenario 1: user does not change 5.7.3 configuration; then libssl thread-guards will be disabled and Kamailio will run as before. `tls.so` runs in `PROC_INIT` — no change
Scenario 2: user sets `tls_threads_mode = 1` in the configuration. libssl thread guards are active and module functions calling libssl will be run in threads in process_no=0; `tls.so` runs in `PROC_SIPINIT`.
Default: `tls_threads_mode = 0` so that stable libssl behaviour is unchanged
=> [5.7] Restore libssl default behaviour on stable; opt-in to libssl thread-guards required

src/modules/tls/doc/rpc.xml, src/modules/tls/doc/tls.xml
This PR updates some of the TLS documentation. 
tls.reload: See #3717 for details and suggestions from core developers.
certificate generation: According to the History section, certificates are no longer generated automatically. Instead, the command `make install-tls-cert` should be used. This was verified to be working as intended and added suggestion in `Quick Start` section.
=> Update TLS docs

src/modules/db_redis/doc/db_redis_admin.xml, src/modules/ndb_redis/doc/ndb_redis_admin.xml
The created ssl context in the `db_redis` and `ndb_redis` modules does not use client certificates [1], [2] which is against the default in current Redis configurations [3]. The used Redis server therefore needs to be configured to not use tls-auth-clients [3]. Without setting this configuration in Redis, no TLS connection to the Redis server can be established, since Redis will not accept unsigned/not-validated client certificates.
There is also a small typo in "ac_path" in both docs which was fixed to "ca_path", added with some more specification to _which_ certificate is validated.
[1]: https://github.com/kamailio/kamailio/blob/8047c958b42ea5af2e8f9ede0152f892ac0eea3a/src/modules/db_redis/redis_connection.c#L168
[2]: …
=> ndb_redis: docs - refine docs regarding client certificates

src/modules/kex/api.c, src/modules/kex/api.h, src/modules/kex/kex_mod.c, src/modules/kex/pkg_stats.c, src/modules/kex/pkg_stats.h, src/modules/xhttp_prom/prom.c, src/modules/xhttp_prom/xhttp_prom.c, src/modules/xhttp_prom/xhttp_prom.h
Enhance xhttp_prom module to export pkgmem stats.
The new stats can be enabled via a new module parameter: `xhttp_prom_pkg_stats`.
Default value for the new module parameter: 0 (no pkg mem stats are generated).
Any value different then 0 will export the pkg mem statistics.
=> xhttp_prom: export pkg mem statistics

src/core/dprint.c
This patch introduces a new "time" field for JSON logging to stderr. The CEE format already includes this field, but the Kamailio-specific format doesn't. If you need timestamps in your structured logs, but don't want to use the CEE format due to its limitations, this patch'd give you the best of both worlds.
I know this comes a little out of the blue, so any feedback is welcome.
=> core: dprint - include time in stderr json log

src/modules/corex/corex_rpc.c
This PR fixes the unknown address family when calling `corex.list_sockets` rpc call by providing the correct argument (address.af) to `get_af_name()` instead of proto.
=> corex: Fix unknown af in list_sockets rpc call

src/modules/app_lua_sr/app_lua_sr_exp.c, src/modules/cfgutils/api.h, src/modules/cfgutils/cfgutils.c, src/modules/cfgutils/doc/cfgutils_admin.xml
expose in config via cfgutils ``core_case_hash`` optional second string key for hashing
=> cfgutils lock

src/modules/rtpengine/rtpengine.c
- freed request.s after sending request to websocket in send_rtpp_command method.
=> rtpengine: fix pkg mem leak in send_rtpp_command()

src/modules/usrloc/urecord.c
When inserting into the database the AOR is split at the @ sign and if there is no @ sign in the AOR only the domain part is filled and the user part is left empty.
But for deleting this is not done and the query failed to be executed and the AOR is not deleted. This PR add this behaviour of only comparing against the domain part if the AOR doesn't contain a @ sign.
=> usrloc: check on db delete the return value of memchr

utils/kamctl/kamctlrc, utils/kamctl/kamdbctl.base, utils/kamctl/kamdbctl.mysql, utils/kamctl/kamdbctl.pgsql
- add support for configuring the DB root host/port connection parameters separate from the ro/rw settings. This allows the user to authenticate over the specific socket configured (tcp/udp/unix) for each connection type (root/ro/rw).
- note that support is added for mysql and postgresql connections. no changes to the other DB engine connection parameters.
=> utils/kamctl: make root host/port configurable

src/modules/statsd/statsd.c
2 issues:
**Issue 1:**
Currently statsd functions return bool: `true` or `false` depending when
the function succeeds or fails respectively.
This value gets implicitly converted to `int`: `true` -> `1`, `false` ->
`0`.
For Kamailio `1` means succesfull execution, but `0` means to stop
processing messages, which is not what we want as statsd should not impact
flow execution. Instead we want to return `-1` which signifies error,
but the flow continues.
**Issue 2:**
statsd_init executes `statsd_connect` which tries to connect to statd
server.
If connection fails then kamailio fails to start.
This is not the desired behaviour as:
1. Kamailio should continue working even if statsd server is down,
metrics should not impact runtime.
2. …
=> modules/statsd: ensure statsd failures do not stop execution

src/modules/ims_registrar_scscf/ims_registrar_scscf_mod.c
A couple small changes to the ims_registrar_scscf which prevents kamailio from crashing on my system.
I would love to have more testing because I only did tests in my single user IMS setup.
=> ims_registrar_scscf: fix uninitialized access of memory, minor refactors

src/modules/sipcapture/doc/sipcapture_admin.xml
The sipcapture module actually uses the DEFAULT_DB_URL instead of "no database at all". When you do not set the parameter, the module will try to connect to the default db. [See source code of parameter](https://github.com/volkland/kamailio/blob/74361cdeacee8864216d309a4842b71fb484a412/src/modules/sipcapture/sipcapture.c#L178).
=> sipcapture: docs - fix default value for parameter

src/modules/db_cluster/dbcl_api.c
This PR aims to update some warning levels used in `db_cluster` module to prevent silent failures.
When `db_cluster` tries to do some action in a `db_connector`, it should log some kind of warning (with `conid` that failed) or error instead of debug.
When iterating on db_connectors and one fails, it will log a warning with `conid` and if all of the available db are not available it will log an error indicating failure.
=> db_cluster: Update log levels and failed connection id

src/modules/p_usrloc/udomain.c
Proposing a small refactoring around code that creates columns parameter for queries in the database when all/most columns are used. If considered useful, this can be adapted for udomain.c file in usrloc module.
=> p_usrloc: use a global p_usrloc_columns variable in db_load* functions

src/modules/usrloc/ucontact.c, src/modules/usrloc/urecord.c
When calling delete_urecord in DB_ONLY mode the location_attrs are not deleted. This fix makes sure to delete location_attrs when calling db_delete_urecord is called.
=> usrloc: delete location_attrs in db_only mode on delete_urecord

src/modules/tm/t_msgbuilder.c
- [ x]  Bug fix (non-breaking change which fixes an issue)
- [ x] Tested changes locally
Add mandatory Max-Forwards header to local ACK
=> tm: add mandatory Max-Forwards header to local ACK

src/modules/permissions/doc/permissions.xml, src/modules/permissions/doc/permissions_admin.xml, src/modules/permissions/permissions.c
Introduce new function: `allow_register_include_port()` to be able to check the whole Contact header including port.
Example, register.deny content is:
```
ALL : "^sip:.*192.168.0.101:5062"
```
If the Contact is: "Contact: <sip:testuser1004@192.168.0.101:5062>" then this will check the Contact hf including port of it.
Otherwise if usual `allow_register()` function is used, then only the "testuser1004@192.168.0.101" will be taken into account, which will lead the regex to be failing and letting the check to pass through.
The func `allow_register_include_port()` works similarly as `allow_register()` except it checks Contact's port.
A separate function was created in order to not complicate things by introducing one more parameter to the …
=> permissions: introduce func `allow_register_include_port()`

src/modules/rtpengine/rtpengine.c
When DTMF events socket is not configured, pkg.stats RPC method returns an empty entry.
{
entry: 13
pid: 0
rank: -128
used: 0
free: 0
real_used: 0
total_size: 67108864
total_frags: 0
desc:
}
Fixes: 26f6e57c8f ("Register a new worker process for dtmf event listener")
=> rtpengine: Fix extra process in pkg.stats

src/modules/uac/doc/uac.xml, src/modules/uac/doc/uac_admin.xml, src/modules/uac/uac.c, src/modules/uac/uac_reg.c
Add support for setting a different RPC reload interval than the reg_gc_interval parameter.  
This allows the cleanup timer to match the user's re-transmission timeout without constraining RPC reload times to a large interval.
=> uac: add reload_delta parameter

src/core/resolve.c, src/core/resolve.h
This PR fixes a crash when `dns_cache_init=off`.
The issue is described in #3350 and the crash is caused when trying to search in `dns_cache.c` [LOCK_DNS_HASH();](https://github.com/kamailio/kamailio/blob/d4629be286fc6d3cf61574e34ee877b2c5e9ee4a/src/core/dns_cache.c#L671). 
When `dns_cache_init=off`, the lock is never initialized and when trying to lock it crashes. 
Per my understanding, when `dns_cache_init=off`, no calls to `dns_cache.c` should be made and instead call the alternative ones from `resolve.c`, since the whole functions are compiled only when USE_DNS_CACHE definition is present.
Just a question to clarify, what is the reasoning behind USE_DNS_CACHE definition and a separate `dns_cache_init` parameter?
=> core/resolve: Check dns_cache_init and choose appropriate functions

src/modules/nathelper/nathelper.c
when receive BYE sip:xxx@xxxx;alias=ip1;alias=ip2 SIP/2.0, handle_ruri_alias_mode(1) doesn't work as documented
=> fixed handle_ruri_alias_mode(1) cannot proper handle multi alias

src/modules/p_usrloc/doc/p_usrloc_admin.xml, src/modules/p_usrloc/ucontact.c
Add a new update/delete function based on contact's uniq uniq. Some devices may use same uniq for multiple contacts, so I needed to restrain it further based on ruid value.
=> p_usrloc: Add update/delete based on uniq

src/modules/pua_dialoginfo/pua_dialoginfo.c
This PR fixes a bug where R-URI couldn't be parsed correctly by assing the correct length to the str variable
=> pua_dialoginfo: Fix ruri length

src/modules/siptrace/siptrace_send.c
For tcp based transports it is need to set SND_F_FORCE_SOCKET flag before msg_send_buffer call, or duplicate will send from wrong addr/port.
=> Siptrace: setting send_sock_name/send_sock_address is ineffective for tcp based transports

src/modules/tls/tls_domain.c
On start:
```
CRITICAL: <core> [core/ip_addr.c:232]: ip_addr2sbuf(): unknown address family 0
NOTICE: tls [tls_domain.c:1176]: ksr_tls_fix_domain(): registered server_name callback handler for socket [:0], server_name='<default>' ...
```
Now it will print:
```
NOTICE: tls [tls_domain.c:1176]: ksr_tls_fix_domain(): registered server_name callback handler for socket [0.0.0.0:0], server_name='<default>' ...
```
=> tls: remove confusing error message when trying to print socket for <default> server

src/modules/textopsx/doc/selects.xml
- [N/A] Tested changes locally
Part of the documentation of the textopsx module (the selectors) was hard to read, since it was missing line-wraps in the example.
- itemizing the list of examples for readability
=> textopsx/doc: fixed hard-to-read documentation for textopsx

src/modules/rtpengine/rtpengine.c
As per issue #3896, "active" is a boolean field that just describes whether the socket will be used, while "disabled" now just describes whether the socket was disabled by an RPC command. Also make "disabled" and "recheck_ticks" fields have a fixed value type of boolean and number respectively.
use `"recheck_ticks": -1` instead of "N/A" as per discussion.
=> add "active" field to rtpengine.show as alternate of "disabled"

src/modules/ims_registrar_scscf/lookup.c
The `ims_registrar_scscf` was not able to function with global-number tel-URIs. This fix prevents a bad AOR to search by from being formed, when the host part of Request-URI is empty.
e.g. INVITE with Request-URI `tel:+123` --> AOR to search by was `tel:+123@` --> not found in `ims_usrloc_scscf`
=> ims_registrar_scscf: fix for location AOR with empty host

src/modules/ims_registrar_scscf/registrar_notify.c
https://datatracker.ietf.org/doc/html/rfc3265#section-3.2.2 says that if a NOTIFY fails, the subscription should be removed. There is one exception only, when a Retry-After is specified.
This is done in order to cleanup state and not keep it around for huge periods of time. This is preferred and the client is the one that should re-subscribe at intervals to fix the situation.
Anyway, I guess I was super annoyed by the huge number of useless notifications that I'm getting for gone IMS clients.
=> ims_registrar_scscf: drop subscription on notification failure

misc/examples/ims/icscf/kamailio.cfg
The I-CSCF routing script was forcing a `+` to be added as prefix to all incoming Request-URIs, if they didn't have one. This was breaking valid IMPUs, e.g. `sip:alice@ims.com` --> `sip:+alice@ims.com`, which wouldn't exist in  HSS.
I don't know why this was valid or useful before. Even if the Request-URI is a tel-URI, one should not blindly transform that, since the meaning of global and local numbers are quite different (so maybe fix the upstreams?).
=> misc/examples/ims/icscf: fix bad prefix added on all incoming requests

src/modules/db_redis/redis_dbase.c
Issue: when using usrloc with db_redis, I get constant WARNING logs for 'delete' via usrloc timer. The real WARNING, in my opinion, is when doing full table scans(which is already logged as so).
Make logs less important when performing table scans using a match key.
=> db_redis: change logs on delete

src/modules/usrloc/udomain.c
This is a refactor aiming to make some queries that return most of the columns of contacts easier to read. Gets rid of repeating local  columns arrays and replaces them with a single global usrloc_columns variable. Similar change was done for p_usrloc module.
=> usrloc: refactor some db queries using global usrloc_columns variable

src/core/ut.h, src/lib/ims/ims_getters.c, src/modules/ims_qos/doc/ims_qos.xml, src/modules/ims_qos/doc/ims_qos_admin.xml, src/modules/ims_qos/ims_qos_mod.c, src/modules/ims_qos/rx_aar.h, src/modules/ims_qos/rx_authdata.h, src/modules/ims_qos/rx_avp.c, src/modules/ims_registrar_pcscf/doc/ims_registrar_pcscf.xml, src/modules/ims_registrar_pcscf/doc/ims_registrar_pcscf_admin.xml, src/modules/ims_registrar_pcscf/ims_registrar_pcscf_mod.c, src/modules/ims_registrar_pcscf/notify.c, src/modules/ims_registrar_pcscf/save.c, src/modules/ims_registrar_pcscf/service_routes.c, src/modules/ims_registrar_pcscf/subscribe.c, src/modules/ims_registrar_pcscf/subscribe.h, src/modules/ims_usrloc_pcscf/udomain.c
Normally, the IMS P-CSCF should identify the clients (UEs) by the received IP address and ports on Rx. The current code is using a mix of that, plus using Contact and Via headers, with arguable potential security issues.
This patch adds a new parameter to `ims_registrar_pcscf` and `ims_qos` modules, allowing for an optional outsource of the IPsec functionality to another element, which is also in charge of checking/enforcing correct UE Via header. The existing code is allowed to work as before, with the default value of the flag being towards that.
List of functional changes:
- `ims_qos`
- added `trust_bottom_via` parameter
- used it on `w_rx_aar_register()`
- `ims_registrar_pcscf`
- added `trust_bottom_via` parameter
- used it on …
=> ims_registrar_pcscf,ims_qos: support for trusting bottom via

src/core/parser/parse_uri.c
Improved URN parsing according to [RFC8141](https://datatracker.ietf.org/doc/html/rfc8141#section-2) that allows an arbitrary number of colons to be present in the URN value. Entire URN NID and NSS parts (except for `urn:` scheme) are stored in the `uri.host` struct field. `rq-components` are not supported.
Example of the parse error when parsing "urn:emergency:service:sos"
```
parse_uri(): bad char ':' in state 3 parsed: urn:emergency:service (21) / urn:emergency:service:sos (25)
```
URN values that have been tested to work:
- `urn:emergency:service:sos`
- `urn:emergency:responder.fire`
- `urn:emergency:media-feature`
=> core: Improved URN parsing according to RFC8141

src/modules/sqlops/doc/sqlops_admin.xml, src/modules/sqlops/sql_api.c, src/modules/sqlops/sqlops.c
This PR Fixes a bug where logging shows a truncated command instead of the original one.
Original query in .cfg:  `sql_query("ca", "UPDATE dialog SET timeout = timeout + 1 WHERE callid = '$ci' AND timeout > 0;`
logged error before fix:
sql_do_query(): cannot do the query [UPDATE dialog SET timeout = timeout + 1 WHERE callid = 'al@there]
logged error after fix:
sql_do_query(): cannot do the query [UPDATE dialog SET timeout = timeout + 1 WHERE callid = 'al@there.com AND timeout > 0;]
=> sqlops: Don't truncated sql command when logging.

src/modules/cdp/transaction.c
If the traction is set to auto drop,
the memory will be freed and with it the next pointer.
The use after free caused on a Load tested system crashes.
Now the next pointer is saved before executing the callback and handle the auto drop.
Then the stored next pointer is used to continue the iteration over the callbacks.
=> cdp: fix use after free in transaction call backs

src/lib/srdb1/db_ut.c, src/modules/htable/ht_db.c, src/modules/permissions/address.c
Adding support for converting unsigned integers from database tables into kamailio pseudo variables usable in the routing config.  
This is quite useful when pulling `int unsigned` fields from a database, in modules that support "extra fields" in their module parameters.
=> multiple subsytems: unsigned integer conversion fixes

src/modules/pua/pua_db.c, src/modules/pua/pua_db.h, src/modules/pua/send_publish.c, src/modules/pua_dialoginfo/doc/pua_dialoginfo.xml, src/modules/pua_dialoginfo/doc/pua_dialoginfo_admin.xml, src/modules/pua_dialoginfo/pua_dialoginfo.c
We are seeing a lot of error messages like:
> ERROR: <null> pua [pua_db.c:895]: get_record_puadb(): Too many rows found (2)
After some investigation I come up with a couple of fixes:
* pua: improve the query to support caller|callee with same pres_id (same dialog)
* pua_dialoginfo: support uuid to generate pres_id to improve randomness
=> pua and pua_dialoginfo improvements

src/modules/tm/t_cancel.c
The `tm` currently does not trigger the `tm:local-request` event for CANCEL requests that are created by the tm.cancel RPC function. This pull request adds support for triggering the tm:local-request event for CANCEL requests.
According to [docs](https://www.kamailio.org/docs/modules/devel/modules/tm#tm.e.local-request) an event `tm:local-request` should be created for every request that is originates from kamailio and creates a transaction.
=> tm: Emit request event when tm.cancel is called

src/modules/topos_redis/topos_redis_storage.c
Small log improvement, in order to make easier to find the origin of redis errors.
Log sample :
```
WARNING: topos_redis [topos_redis_storage.c:834]: tps_redis_load_branch(): invalid redis result type: 6
WARNING: topos [tps_storage.c:626]: tps_storage_record(): no local address - do record routing for all initial requests
ERROR: topos [tps_storage.c:637]: tps_storage_record(): failed to store
```
The root cause is probaly in redis error message and it whould be nice to log it
=> topos_redis : show redis error for post mortem analysis

src/modules/kafka/doc/kafka_admin.xml, src/modules/kafka/kafka_mod.c, src/modules/kafka/kfk.c
Hello, I recently did some tests with kamailio's kafka module, with focus on what happens when kafka broker goes down.
First thing I noticed is that kamailio won't start initially if kafka broker is down. Second thing I noticed syslog overflowing with err logs, when kafka broker is down. Third, I noticed that when it starts, kamailio queries topic metadata and waited up to 100 seconds for any answer. I've added modparams for all these three to change behavior.  Updated doc for all the new modparams.
I've also updated stats errors counting when exposed cfg functions failed for any reason. And some rework to stats function to accept str* instead of char* topic. Also moved librdkafka's poll() function at the begining of the cfg function …
=> kafka: a few additions to the module

src/modules/sca/doc/sca_admin.xml, src/modules/sca/sca.c, src/modules/sca/sca.h, src/modules/sca/sca_call_info.c
Another step to merge the functionality that is already used in Sipwise kamailio flavor:
be able to define a fallback contact to be used when message processed has no contact
=> sca: contact-fallback

src/modules/db_mongodb/mongodb_dbase.c
If the query failed, the result set should not be parsed and used. This results in an empty result set which will most likely lead to unwanted behavior.
Background: While troubleshooting, we detected that domain.reload actually replaces domains with an empty result set if mongodb connectivity fails. This means that if, at the moment when we request domain reloading, our mongodb is unreachable for whatever reason, kamailio will store an empty list as domains and it will remain that way until we request domain reloading again.
```
DEBUG: db_mongodb [mongodb_dbase.c:849]: db_mongodb_store_result(): An error occurred: No suitable servers found (`serverSelectionTryOnce` set): [connection timeout calling ismaster on 'pdb-iop1-wrmg-2:27017'] …
```
=> goto error on cursor error

src/modules/rtpengine/config.c, src/modules/rtpengine/doc/rtpengine_admin.xml
The setup is a kamailio with no available rtpengine. (e.g. has a list with rtpengine urls but those are not reachable)
Recently had a crash similar to #3297, but in an outdated kamailio version (5.5.7). Tried to reproduce this in 5.5.7 and 5.8.3 but could not crash any of them. However, for both of them, I managed to get the logs similar to ones right before the crash happened:
```
2024-10-04T17:39:58.026206+03:00 kamailio[450237]: ERROR: {1 1 INVITE 203-450290@192.168.100.93} <core> [core/action.c:1595]: run_actions(): alert - action [corefunc (16)] cfg [/home/stefan/kamailio.cfg:625] took too long [29310906 us]
```
...directly related to how much rtpengine_manage() function took to execute. So routing of SIP is delayed by that …
=> rtpengine: disable aggressive redetection by default

src/modules/ims_registrar_scscf/config.c, src/modules/ims_registrar_scscf/ims_registrar_scscf_mod.c, src/modules/ims_registrar_scscf/save.c
In case of Emergency-Registrations the S-CSCF was wrongly setting the expires of the `;sos` contacts to `em_min_expires` if they were above `em_max_expires`.
Other smaller related fixes:
- Fixed also another typo in the config params definition.
- Added some code to more easily make sense of which attributes of a struct are set with what.
- Added conditions to respect the parameter documentation which indicate that if set to 0, the expires conditions won't be used.
=> ims_registrar_scscf: fixing em_max_expires

src/modules/siputils/chargingvector.c
- [-] Related to issue #XXXX (replace XXXX with an open issue number)
- icid-value is only 17 characters and not unique 
- Re-parsing of generated PCV with icid-generated is 2 characters too short, cutting generated-by value or creating false warning
Following warning was produced, which shows the problem.
> WARNING: siputils [chargingvector.c:240]: sip_parse_charging_vector(): icid-generated-at is missing icid-> value=4557000A000E52000;icid-generated-a
=> siputils: generated icid-value too short

src/modules/kex/core_stats.c
This pull request expands Kamailio's statistical reporting by adding support for a broader range of SIP 4xx status codes. These changes allow Kamailio to display detailed statistics for additional SIP status codes.
* Expanded the set of SIP status codes included in Kamailio's statistics to cover a more comprehensive range.
* Added status codes : 400, 402-403, 405-406, 408-411, 413-415, 420, 481-485, 487-489, 491 and 493
With these improvements, Kamailio users and administrators gain more granular insight into SIP responses, enabling faster identification and resolution of issues based on the new statistics.
This feature has been tested with simulated SIP responses across various status codes to confirm correct tracking and reporting …
=> core: add other 4xx reply error count stats

src/modules/snmpstats/snmpstats.c, src/modules/snmpstats/sub_agent.c
The former respects the `--atexit=no` from Kamailio command line.
See note on `atexit` in TLS module "Overview".
I'm using `tls` module along with some other modules. On Kamailio termination there are a lot of "freeing already freed pointer" messages from `qm_free()`. Also there may be a corrupted memory report (followed by `abort()`) from `qm_debug_check_frag()`.
I'm aware of `--atexit=no` required for `tls`, and Kamailio is indeed started as `kamailio --atexit=no -m 16 -n 1 -w . -f some.cfg`.
The `tls` module is loaded and configured something like this:
```
disable_core_dump=no
debug=2
memdbg=2
enable_tls=yes
listen=tls:127.0.0.1:5060
mpath="lib64/kamailio/modules"
loadmodule "tls.so"
modparam("tls", "init_mode", 1)
modparam("tls", …
```
=> modules/snmpstats: exit with `ksr_exit()` instead of standard `exit()`

src/modules/kazoo/kazoo.c, src/modules/kazoo/kz_amqp.c, src/modules/kazoo/kz_amqp.h
A response to the amqp query caused a segfault in libc
- Refactored parts of the code to be more readable and DRY
- Split up functions for 3/4/5 arguments passed
- Tested in 5.8.2
The current state of the module was not usable anymore as everything up from 5.5.x caused a segfault when the kazoo_query method was executed. Refactored the module a bit to make sure it is works again 5.8.x
=> Fixed segfault when using kazoo_query in kazoo mod

src/modules/pv/pv_core.c
This PR fixes a bug in pseudo-variables related to "From" and "To" headers and changing the `Display Name` through `$tu/$fu/$fn/$tn`.
According to standard the URI must be enclosed in <> if a `Display Name` is given, but it may or may NOT if no display name is present.
So, if one tries to modify the `from`/`to` header with an initial empty display name and URI that is NOT enclosed in <>, it yields an invalid message.
This PR makes sure that if URI was not enclosed in <> and display name is modified, that will wrap URI in <>.
=> pv: Ensure URI enclosed in <> when changing Display Name

src/modules/cdp/authstatemachine.c, src/modules/cdp/common.c, src/modules/cdp/diameter_peer.c, src/modules/cdp/receiver.c, src/modules/cdp/session.c, src/modules/cdp/session.h
This fixes:
- 4-bytes (typically uint32_t) used for time_t storage (Y2K38)
- print of time_t with %d instead of %ld
- reuse of same loop index variable in a sub-loop
- use of random(), when kam_rand() could theoretically be better
- copy-paste mistake in sp2/sp parameter, where sp2 was meant and sp is probably NULL
=> cdp: fixed issues discovered during static code analysis

src/modules/app_python3/apy_kemi.c, src/modules/app_python3s/apy3s_kemi.c
Python's C interface contract states that C code must *either* raise an exception and return NULL, *or* return a Python object.
Doing both will raise a `SystemError` exception which obscures the original problem. It may also cause a memory leak.
=> Python exception handling fixes

src/modules/http_async_client/http_multi.c
I assume that the crash #4019 happens, because of an issue in libcurl, namely in the `event_cb` function ([in this line](https://github.com/kamailio/kamailio/blob/master/src/modules/http_async_client/http_multi.c#L110)) kamailio removes the pointer to the `cell`  object (which was attached to this `g->multi` curl descriptor earlier), and the `cell` object memory is released [at this line](https://github.com/kamailio/kamailio/blob/master/src/modules/http_async_client/http_multi.c#L110). However, the crash happens when `event_cb` is called when `curl_multi_remove_handle` is called [at this line](https://github.com/kamailio/kamailio/blob/master/src/modules/http_async_client/http_multi.c#L124).
In this fix `cell` object is retrieved from …
=> http_async_client: fixed crash on curl callback

src/modules/uac/doc/uac_admin.xml, src/modules/uac/uac.c, src/modules/uac/uac_reg.c, src/modules/uac/uac_reg.h
This PR exports some new functions for handling registration and deregistration in the uac table without waiting for timer to fire.
All of the following function require the parameters of the already available RPC function call `reg_unregister`:
- `kamcmd uac.reg_register`: Register for kamcmd similar to `uac.reg_unregister`
- `uac_reg_send_register`: Config function to register immediately without waiting for timer
- `uac_reg_send_unregister`: Config funtion to unregister immediately without waiting for timer
- Move required structures/functions to .h
=> uac: Export two new functions for reg/unreg and rpc for reg

src/modules/ims_isc/ims_isc_mod.c, src/modules/ims_isc/ims_isc_mod.h, src/modules/ims_isc/isc.c, src/modules/ims_isc/isc.h, src/modules/ims_isc/mark.c, src/modules/ims_isc/mark.h
The function isc_match_filter uses a local variable "firstflag",
to handle the case of an HSS based terminating unregistered service.
In that case, the S-CSCF exchanges SAR/SAA with the HSS in order
to learn the subscription data and the iFC for an unregistered
user or for a PSI.
The firstflag is necessary to make a distiction between the
FAILURE ROUTE that is used for this case and the FAILURE ROUTE
that is used for transaction failure towards the AS.
The error is, the firstflag is set for the latter case, too,
which leads to a wrong handling of communication errors towards
the AS.
This PR introduces a new function that looks for the old
ISCMARK in the lumps of the stored message and hence can make a
distinction between the SAR/SAA …
=> ims_isc: bugfix: firstflag incorrect in isc_match_filter

src/modules/ims_diameter_server/avp_helper.c
``current_msg_id_repl is only`` changed if ``$diameter_reponse`` is changed by via ``pv_set_response()``. The event_route is executed with a ``fake_msg`` so it will not match if is setted outside anyways.
=> ims_diameter_server: fix retrieval ``$diameter_response`` value

src/modules/htable/ht_api.c
Update item expiration value during de-/incrementation for htables that are configured with autoexpire and updateexpire disabled. Otherwise an item cannot be used until timer cleaned it up.
Using following configuration
```
#!KAMAILIO
listen=udp:127.0.0.1:9999
log_stderror=yes
loadmodule "xlog.so"
loadmodule "pv.so"
loadmodule "sl.so"
loadmodule "htable.so"
modparam("htable", "htable", "foo=>autoexpire=1;updateexpire=0")
request_route {
if ($sht(foo=>bar) == $null) {
$sht(foo=>bar) = 0;
}
$var(foo) = $shtdec(foo=>bar);
xlog("$Ts single value $sht(foo=>bar)\texpire $shtex(foo=>bar)\n");
sl_send_reply("200", "Hello");
}
```
running
```
while true; do sleep 0.3; sipsak -vs sip:localhost:9999 ; done
```
produces following output
``` …
```
=> htable: Fix de-/increment w/ auto expire

src/modules/xhttp_prom/doc/xhttp_prom_admin.xml, src/modules/xhttp_prom/prom.c, src/modules/xhttp_prom/xhttp_prom.c, src/modules/xhttp_prom/xhttp_prom.h
- allows custom tags to be added to prometheus metrics
- Addresses GH issue #4021
This change adds a new parameter `xhttp_prom_tags`. It allows the user to append tags to the prometheus metrics. This makes those metrics a lot more useful when having multiple kamailio instances running on a single host.
This is done by 2 shared memory helper variables which contain the parameter in different formats. This way it is easy to print them out with minimal changes.
=> xhttp_prom: new xhttp_prom_tags parameter

src/Makefile.defs, src/modules/influxdbc/ic.c
`Makefile.defs` is incorrect (`man_dir` should contain `share`) and `influxdbc` is not built (`sockaddr_in` is undefined) on FreeBSD environment.
The proposed patch fixes it and makes the module is consistent with the rest of modules.
=>  Fix Makefile.defs and influxdbc for build on FreeBSD

cmake/compiler-specific.cmake, cmake/defs.cmake, cmake/os-specific.cmake, cmake/os-specific/freebsd.cmake
I've tested cmake-build in the FreeBSD environment, as requested by @miconda in #4099.
And founded some troubles.
First of all are: specific flags for FreeBSD and arch-name for FreeBSD cmake-environment. I've fixed it in the PR.
But there're some unresolved problems I want to discuss...
A `LOCK_METHOD` problem:
There's a `LOCK_METHOD` variable in defs.cmake:
https://github.com/kamailio/kamailio/blob/6b0b8cb84b7d0e965d50bdf0dfa5423004879f55/cmake/defs.cmake#L171-L179
And the explicit usage `LOCK_METHOD` as `USE_FUTEX` in a compile_definitions:
https://github.com/kamailio/kamailio/blob/6b0b8cb84b7d0e965d50bdf0dfa5423004879f55/cmake/defs.cmake#L304-L327
I suppose it's incorrect while some OSs (FreeBSD, ex.) doesn't tested with …
=> cmake: add FreeBSD support

src/modules/htable/ht_api.c, src/modules/htable/ht_api.h
Update cell expiry on assignment for htables w/o updateexpiry (analogue to #4079).
Currently Kamailio does not update expiry when assigning a value to an expired cell if htable's `updateexpire` equals `0`. So expired cells aren't usable as long htable timer cleans up these cells.
Reproduction 1:
```
#!KAMAILIO
listen=udp:127.0.0.1:9999
log_stderror=yes
loadmodule "xlog.so"
loadmodule "pv.so"
loadmodule "sl.so"
loadmodule "htable.so"
modparam("htable", "htable", "foo=>autoexpire=1;updateexpire=0;initval=0")
request_route {
if ($sht(foo=>bar) == $null) {
xlog("it's null, init it\n");
}
$sht(foo=>bar) = $sht(foo=>bar) + 1;
xlog("$Ts value $sht(foo=>bar)\texpire $shtex(foo=>bar)\n");
sl_send_reply("200", "Hello");
}
```
output:
``` …
```
=> htable: Fix expiry on assignment

src/core/tcp_main.c
- Changed the logic for matching a listening TCP/TLS-socket in tcp_reuse_port scenario, now it considers local port as well. With 'tcp_reuse_port' option enabled, the local port is meaningful and helps to differentiate between sockets on the same IP but different ports.
In our installation Kamailio runs multiple SIP-trunks, including TCP/TLS, which may be bound to the same local IP address but different local ports, and it's crucial for us to know exactly which trunk, i.e. local socket/port, was used to receive a SIP message.
Additionally, the option "tcp_reuse_port" is also enabled in our environment to start outbound connections from the same TCP/TLS ports that we are listening at.
The problem we hit is that identifying a trunk …
=> tcp: fix for local TCP/TLS socket matching with 'tcp_reuse_port' enabled

src/core/tcp_main.c, src/modules/outbound/outbound_mod.c
This is an attempt to fix the combination of the outbound/rr modules and ``tcp_accept_haproxy=yes``. This combination is currently broken, as previously reported on the mailing list: https://www.mail-archive.com/sr-users@lists.kamailio.org/msg21854.html
The issue is that the destination address/port combo of the haproxy side is encoded into the flow token. When the rr module decodes the flow token and tries to look up the listening socket using ``find_si``, it cannot be found, because it is given the destination address/port combo of the connection of the haproxy side, not the address/port combo that Kamailio is actually listening on.
This patch fixes the issue by encoding the ``bind_address`` of the socket the connection was received …
=> outbound: encode bind address into flow token as destination

src/modules/janssonrpcc/janssonrpc_server.c
On CentOS, the present build error var may be used uninitialized.
This fixes this.
=> janssonrpcc: fixed warning var may be used uninitialized

src/modules/ims_auth/auth_vector.c, src/modules/ims_registrar_pcscf/subscribe.c
At this time, it's not possible to build Kamailio on `CentOS 7` on `master` or `6.0.0`.
Some code on `ims_auth` and `ims_registrar_pcscf` is not compliant with old `gcc`.
Tested on my own, and build now works just fine.
=> ims_auth|ims_registrar_pcscf: Fix Build for CentOS 7

src/modules/nathelper/doc/nathelper_admin.xml, src/modules/nathelper/nathelper.c
OPTIONS ping is always sent to Path uri, if contact has it set. Add option to ignore this and still send OPTIONS to contact.
=> nathelper: Add modparam to not send ping to Path

src/modules/dispatcher/dispatch.c
Dispatcher timer regularly pings the nodes. Should skip resolving and pinging the no-dns-A flag ones since those node do not have an A record by definition.
Otherwise that no-dns-A flag(state) is overwritten by the pinging process. This leads to node removal from group, after RPC commands e.g. "kamcmd dispatcher.add/remove".
=> dispatcher: skip ping for DS_NODNSARES_DST

src/modules/dmq/dmq.c, src/modules/dmq/dmq.h, src/modules/dmq/doc/dmq_admin.xml, src/modules/dmq/notification_peer.c
Add new parameter for dmq module "remove_inactive" that controls removing nodes behavior. Default value is 1, so the behavior will not changed by default. 
This is useful especially with notification peers that are defined as dns record together with enabled multi_notify option.
=> dmq: added remove_inactive parameter

src/modules/dmq/bind_dmq.c, src/modules/dmq/bind_dmq.h, src/modules/dmq/dmq_funcs.c, src/modules/dmq/dmq_funcs.h, src/modules/dmq_usrloc/dmq_usrloc.c, src/modules/dmq_usrloc/doc/dmq_usrloc_admin.xml, src/modules/dmq_usrloc/usrloc_sync.c, src/modules/dmq_usrloc/usrloc_sync.h
Add new api function to dmq to get local socket. Use that in dmq_usrloc.
Sync dmq_usrloc UL_CONTACT_EXPIRE. Very useful for lost TCP connections, so contacts will be expired on all dmq nodes.
=> dmq and dmq_usrloc additions

src/lib/ims/CMakeLists.txt, src/modules/dialplan/CMakeLists.txt, src/modules/sctp/CMakeLists.txt
Suggest small bugfixes for CMakeLists.txt for modules and libs.
- `lib/ims` - remove libxml2 as not needed as in 5eac8fd5356cc424d87cac4b4102c99e97054414.
- `dialplan` - added pcre2 lib as a depend.
- `sctp` - switched searching for libsctp for linux only after 9b7719a61ab02c93939e3681cb90e9fa04f3ac5d. There's no libsctp in FreeBSD while kernel module exists, example.
=> Cmake: small bugfixes (lib/ims, dialplan, sctp)

src/core/dns_cache.c
Extend the return value of dns_cache_print_entry with the parameter `rr_skip_record` for NAPTR records. The parameter `rr_skip_record` indicates, whether the NAPTR record is skipped due to issues reaching the destinations. Once a NAPTR record is marked as skipped, it will no longer be used.
=> core: Include parameter skip_record in dns_cache_print_entry

src/modules/kex/core_stats.c, src/modules/kex/core_stats.h
KDMQ messages were added as a separate received request method in the statistic.
=> kex: add KDMQ to request statistic

src/modules/tm/doc/params.xml
- Use description found in https://sip-router.org/wiki/ref_manual/timers
Fix documentation according to the description found in https://sip-router.org/wiki/ref_manual/timers. They better reflect the actual procedure.
=> tm: Update docs of fr_timer to match the implementation

src/modules/dispatcher/dispatch.c, src/modules/dispatcher/dispatch.h, src/modules/dispatcher/dispatcher.c, src/modules/dispatcher/doc/dispatcher_admin.xml
- add dispatcher modparam `ds_ping_socket`
- add gateway param `ping_socket`
could be useful for HA use cases where multiple kamailio nodes share a common Virtual IP (e.g.: managed by the VRRP).
we need to route requests using Virtual IP socket configured with `ds_default_sockname`/`socket` and to perform destinations probing using self-IP socket configured with `ds_ping_socket`/`ping_socket`.
=> dispatcher: added ping socket configuration

src/modules/secfilter/secfilter.c, src/modules/secfilter/secfilter.h, src/modules/secfilter/secfilter_db.c, src/modules/secfilter/secfilter_rpc.c
This update introduces new functionality to the `secfilter` module, enabling the removal of entries from both the Blacklist and Whitelist. It also includes automatic detection and removal of duplicate values from these lists.
* Users can now remove specific entries from the Blacklist or Whitelist based on type (e.g., IP, domain, user) and a given value.
* Supports removal of single or multiple matching entries in one operation.
- Improves the usability and flexibility of the `secfilter` module by allowing fine-grained control over list management.
- Ensures that the Blacklist and Whitelist are kept clean and free from redundant entries.
- Enhances performance by reducing unnecessary duplication in the lists.
This feature was tested …
=> secfilter‌: support remove rule in Whitelist and Blacklist

src/modules/dispatcher/dispatch.c
Probing a host correctly needs the tm module to be loaded. This PR adds a check for when adding a target in dispatcher with probing enabled to verify whether tm is loaded. If it's not, it emmits a warning and disable the probing to the target.
=> dispatcher: Check if tm is enabled before probing

src/core/parser/sdp/sdp_helpr_funcs.c
- `len` is first adjusted by the amount of chars consumed so far
- `start` pointer is then adjusted to begin new search
Small logic tweak — we adjust `len` by the amount of chars consumed first, then adjust the `start` pointer to begin the new search.
Existing:
```
start = space + 1;
len = len - (space - start + 1);
// this is a no-op as the pointer was adjusted first
```
Changed:
```
len = len - (space - start + 1);
start = space + 1;
```
=> core: sdp - update start pointer only after len adjustment

doc/tutorials/rpc/kamailio_rpc.xml
- format as well
There was missing information of type identifiers that can be used in [rpc tutorial docs](https://www.kamailio.org/docs/docbooks/5.7.x/rpc_api/rpc_api.html#rpc.data_types). This is an update to those docs. The most recent I could find was for 5.7. 
Maybe there is a need for manual updating the page?
Also during the relevant PR #4227 , we found the `t` identifier is never used in the code. since it can overflow on 64bit systems due to being a `long` and not `int` type when saved/load, maybe we can remove it completely?. One can just cast the `time_t` to the relevant type and use the correct identifier as done in https://github.com/kamailio/kamailio/blob/2081b3aac394223b68b …
=> core: docs: Update type identifiers that can be used in the RPC API

src/core/cfg.lex, src/core/cfg.y, src/core/globals.h, src/core/tcp_main.c, src/core/tls_hooks.h, src/main.c, src/modules/tls/tls_mod.c, src/modules/tls/tls_rpc.c, src/modules/tls/tls_server.c, src/modules/tls/tls_server.h, src/modules/tls_wolfssl/tls_rpc.c, src/modules/tls_wolfssl/tls_server.c, src/modules/tls_wolfssl/tls_server.h, src/modules/tls_wolfssl/tls_wolfssl_mod.c
PR adds new core option `tls_connection_match_domain` with the default value 0 (old behavior)
to solve the problem when we need to have multiple TLS connections with different SNI to the same host:port endpoint.
for example: multiple customers authorized by different TLS certificates for MS Teams on the single kamailio instance.
originally, functions `_tcpconn_find` and `_tcpconn_add_alias_unsafe` use only endpoint and protocol to match connections.
setting `tls_connection_match_domain` to `1` will match additionaly with `tls_domain_str()` output for matched TLS domain.
as a result, we will be able to establish new TLS connections if TLS domain is changed instead of reusing of the existent one with the wrong SNI.
i'm not considering …
=> core: support tls connection domain matching

src/modules/stirshaken/doc/stirshaken_admin.xml, src/modules/stirshaken/stirshaken_mod.c
Currently `stirshaken` module performs x509 certificate path check twice (when enabled): 
- first by calling `stir_shaken_verify_cert_path` directly from the [`stirshaken_mod.c`](https://github.com/kamailio/kamailio/blob/330543f46cbb6bf815ebf77c98378314091197ce/src/modules/stirshaken/stirshaken_mod.c#L626)
- second time from the [`libstirshaken`](https://github.com/signalwire/libstirshaken/blame/cb6ede40b3ce12ab76e370186a14dc141839ef07/src/stir_shaken_verify.c#L445)
`libstirshaken` had the path check built in since approx 2020 ([last commit mentioning it as TODO](https://github.com/signalwire/libstirshaken/blame/552650e31e3dc66806944b6495490bbb98bae4af/src/stir_shaken_verify.c#L362) before the `stir_shaken_verify_cert_path` function …
=> stirshaken: removed repeated x509 certification path check

src/modules/ims_auth/cxdx_mar.c
- fixed log message in MAR Async CDP callback
- fixed executing cfg_action after sending MAR Diameter request
- cfg_action is the callback parameter of the ims_www_challenge function
Based on the description in issue #4205, this PR will fix a bug in ims_auth module related to MAR Diameter request callbacks, by replacing the call to t_continue function with t_continue_skip_timer, after the MAR request is sent, the control will successfully move to the cfg action in Kamailio scripts. Just like what we already have in ims_registrar_scscf module, using t_continue_skip_timer instead of t_continue cause the transaction to be found and resumed.
=> ims_auth: replaced t_continue_skip_timer with t_continue in cxdx_mar.c

.github/workflows/rpm.yml
I have refactored the rpm packaging and am now using the GitHub actions.
Now `tar.gz` archive with rpm packages, source rpm and deps rpm files attached to the release message like.
=> generate rpm packages using github actions

src/modules/pdb/doc/pdb.xml, src/modules/pdb/doc/pdb_admin.xml, src/modules/pdb/pdb.c
Adds RPC command to view and/or change the timeout value for PDB queries. The documentation is also updated accordingly.
=> PDB: new RPC command to get/set the PDB query timeout value

src/modules/tls/tls_rpc.c
- tls_list() add PROTO_WSS to TLS_LIST RPC call to include WSS connections in tls.list
- tls_kill() add PROTO_WSS to handle WSS connections
Co-authored-by: Andreas Tarp <tarp@sipgate.de>
WSS connection is not shown in tls.list RPC command like all other TLS connections.
Also tls_kill does not handle WSS connections. 
This is related to the issue 4167.
=> tls: add WSS to RPC funtions

src/modules/tm/uac.c
- [*] New feature (non-breaking change which adds new functionality)
- [*] PR should be backported to stable branches
- [*] Tested changes locally
- [*] Related to issue #4249 
When sending an INVITE using t_uac_send, the transaction layer automatically generates ACK on final response.  However this ack doesn't invoke the tm:local-request callback.  This patch adds this functionality
=> tm: invoke tm:local-request on generated ACK messages

src/modules/pdb/doc/pdb_admin.xml, src/modules/pdb/pdb.c
Added support for KEMI API in PDB module.
Here is example usage in KEMI Python.
```
if not (KSR.pdb.pdb_query(KSR.pv.gete("$var(pdb_user)"), "$avp(carrier_id)") > 0):
KSR.err(F"""[{HERE()}]: PDB query failed for user '{KSR.pv.get("$var(pdb_user)")}' \n""")
else:
KSR.info(F""" PDB query return carrier_id = '{KSR.pv.getw("$avp(carrier_id)")}' \n""")
```
=> pdb: added KEMI support for PDB module

src/modules/rr/doc/rr_admin.xml, src/modules/rr/loose.c, src/modules/rr/rr_mod.h
`loose_route()` in `rr` checks request src ip/port against ip/port in flow tokens to detect direction and decide whether to apply flow tokens routing:
```
static inline int process_outbound(struct sip_msg *_m, str flow_token)
{
...
} else if(!ip_addr_cmp(&rcv->src_ip, &_m->rcv.src_ip)
|| rcv->src_port != _m->rcv.src_port) {
LM_DBG("\"incoming\" request found. Using flow-token for "
"routing\n");
...
```
there are cases when remote UA changes ip/port for in-dialog messages and this approach does not work.
incoming message has route set with flow tokens and src ip/port different from ones in the flow tokens.
as a result, `loose_route()` routes message back to the client using flow tokens instead of using the normal part of the Route …
=> rr: loose_route_mode: add vmode bit 2 to skip outbound

src/modules/permissions/doc/permissions_admin.xml, src/modules/permissions/hash.c
This PR allows the functions `allow_address_group` and `allow_source_address_group` to search for Longest Prefix Match (LPM) when searching for an IP is in a subnet instead of the first found. 
Since this is a stricter check, i don't think we require an extra param for it, but feel free to suggest otherwise if there are any use-cases that required the first matched.
=> permissions: Perform LPM to find the longest matching subnet

src/modules/topos/doc/topos_admin.xml, src/modules/topos/topos_mod.c
Updated documentation.
Right now if I try to log $sp in event_route[topos:msg-receiving], will have value 0.
Updated documentation too, related to those event routes.
=> topos: expose rcv data in event routes

src/modules/pua_reginfo/usrloc_cb.c
Current implementation of pua_reginfo, when `publish_reginfo` is used, sets a fixed `Expires` value of `3600` in the PUBLISH message, which may lead to many entries in pua db for the same reginfo data if the client registers sin an expiration < 1hr.
For example: a device registers every 2 minutes, in one hour pua db will have 30 entries for the same reg, because they're set to expire after 1hr.
In addition if this info is subscribed by another entity, the entity will receive notifies with a lot of entries for the same reg.
Instead, like is done with the pua_dialoginfo, the Expires of the publish should follow the expire of the registration.
This patch does exactly that, it sets the PUBLISH Expire to the reg expire value.
There's only …
=> pua_reginfo: use expires from contact for publish request

pkg/kamailio/deb/bionic/copyright, pkg/kamailio/deb/bookworm/copyright, pkg/kamailio/deb/bullseye/copyright, pkg/kamailio/deb/buster/copyright, pkg/kamailio/deb/debian/copyright, pkg/kamailio/deb/focal/copyright, pkg/kamailio/deb/jammy/copyright, pkg/kamailio/deb/jessie/copyright, pkg/kamailio/deb/noble/copyright, pkg/kamailio/deb/precise/copyright, pkg/kamailio/deb/sid/copyright, pkg/kamailio/deb/stretch/copyright, pkg/kamailio/deb/trixie/copyright, pkg/kamailio/deb/trusty/copyright, pkg/kamailio/deb/wheezy/copyright, pkg/kamailio/deb/xenial/copyright
Update debian/copyright file collection in pkg/kamailio/deb/.../copyright as suggested by Debian Lintian warnings.
Mostly file path adjustments, one license name clarification.
=> Update Debian copyright file [skip ci]

src/modules/sworker/doc/sworker_admin.xml
Fix minor error in modules/sworker documentation.
=> sworker: fix function name in documentation [skip ci]

src/modules/dialog/dialog.c, src/modules/dialog/dlg_db_handler.c, src/modules/dialog/dlg_hash.h
Dialog script flags (sflags) were not persisting to database, causing 
inconsistent behavior in cluster deployments and after restarts. This 
fix ensures sflags are properly saved when dlg_setflag()/dlg_resetflag() 
are called, making them truly "persistent" as documented.
- Add DLG_FLAG_CHANGED_SFLAGS flag to track sflags changes
- Trigger immediate DB updates in realtime mode
- Support delayed and shutdown database modes
- Fix database update parameters to target sflags column correctly
=> dialog: fix sflags database persistence for dlg_setflag/dlg_resetflag

src/modules/presence/notify.c, src/modules/presence/publish.c, src/modules/presence_dfks/add_events.c, src/modules/presence_dialoginfo/notify_body.c, src/modules/presence_reginfo/notify_body.c, src/modules/presence_xml/add_events.c, src/modules/presence_xml/notify_body.c, src/modules/pua/add_events.c, src/modules/pua_bla/notify.c, src/modules/pua_xmpp/simple2xmpp.c, src/modules/pua_xmpp/xmpp2simple.c
=> remove deprecated xmlMemoryDump() calls
