- modules/siputils/checks.c
> siputils: fix for e164_check()

- modules/db_text/dbt_base.c
- modules/db_text/dbt_res.h
- modules/db_text/dbtext.c
- modules/db_text/dbtext.h
this will allow better interaction with usrloc module param db_check_update
> db_text - add affected rows capability

- modules/db_text/dbt_res.c
this affects the presence package when it queries for active_watchers
> db_text : missing OP_NEQ

- modules/xmlrpc/doc/xmlrpc.xml
- modules/xmlrpc/examples/xmlrpc_test2.py
Hi, 
I don't want to commit directly to other modules ;-) 
- Fix broken links into the xmlrpc doc. 
- Add xmlrpc_test2.py into the doc. 
- Add a small comment into the xmlrpc_test2.py. (Easy to understand how xmlrpc works.)
Regards.
> xmlrpc: Improve doc

- test/travis/build_travis.sh
We should test if the install process is working too
> test/travis: add installation to the test

- modules/erlang/cnode.c
- modules/erlang/cnode.h
- modules/erlang/worker.c
- ensure connect to Erlang node after lost connection or not connected on start
> erlang: Reconnect after lost connection

- Makefile.defs
- mem/mem.c
- mem/mem.h
- modules/pv/pv.c
- modules/pv/pv_branch.c
- modules/pv/pv_branch.h
- modules/rtpengine/doc/rtpengine_admin.xml
- modules/rtpengine/rtpengine.c
Only IPv4 was supported before. Added socket support for IPv6 (link locals included). Also updated documentation.
> Added implementation for force_send_interface to also support IPv6.

- modules/db_text/dbt_base.c
- modules/db_text/dbt_raw_query.c
- modules/db_text/dbt_raw_query.h
- modules/db_text/dbt_raw_util.c
- modules/db_text/dbt_raw_util.h
- modules/db_text/dbtext.h
example
. `select watcher_username, called from active_watchers where expires <> -1`
current limitations
. only select statements
. where clause always uses "and"
> db_text : add db_raw_query support

- modules/erlang/README
- modules/erlang/doc/erlang_admin.xml
- modules/erlang/handle_emsg.c
- modules/erlang/mod_erlang.c
- modules/erlang/pv_atom.c
- modules/erlang/pv_list.c
- modules/erlang/pv_pid.c
- modules/erlang/pv_pid.h
- modules/erlang/pv_tuple.c
- modules/erlang/pv_xbuff.c
- modules/erlang/pv_xbuff.h
- delete unused code
- update documentation
- new pseudo variable pid
> erlang: fixes and new PV

- modules/tls/tls_select.c
improve logging on SSL_get_certificate() / SSL_get_peer_certificate() error
> modules/tls: improve logging

- modules/mohqueue/mohq.c
- modules/mohqueue/mohq.h
- modules/mohqueue/mohq_common.h
- modules/mohqueue/mohq_db.c
- modules/mohqueue/mohq_db.h
- modules/mohqueue/mohq_funcs.c
- modules/mohqueue/mohq_funcs.h
- modules/mohqueue/mohq_locks.c
- modules/mohqueue/mohq_locks.h
* support Route in REFER/BYE
* added stop_stream ()
* updated copyright
* added trailing linefeed to LM_* () messages
* add create call strings into buffer
* drop calls that to respond to REFER
* changed Referred-By to mohqueue
* added TRYING status
* only INVITE can come in w/o to tag
* use TM for first reply on INVITE
* changed the way messages are entered into the queue
* 180 Ringing not sent if not required
> mohqueue v0.11

- modules/db_text/dbt_base.c
- modules/db_text/dbt_raw_query.c
- modules/db_text/dbt_raw_util.c
db_text: memory allocation/release issues in raw query and mark changed only if there was a real change
> db_text : memory allocation/release issues in raw query

- NEWS
- Earlier versions for 3.1 and earlier remain. Newer versions are linked to the Kamailio website.
> core: update release notes in NEWS

- modules/pv/pv.c
- modules/pv/pv_core.c
adn -  auth nonce
adc - auth cnonce
adr - auth response
ado - auth opaque
> pv : add auth digest pseudo variables

- modules/sst/sst_handlers.c
Fixes: #288
Patch by: https://github.com/nbougues
> stt: add refresher param following RFC 4028

- modules/sipcapture/sipcapture.c
- modules/sipcapture/sipcapture.h
ruri_domain, from_domain and to_domain have existed since SQL schema version 3
-> no DB schema changes needed
> modules/sipcapture: adds insertion of request, From, and To URI domain part

- modules/pv/README
- modules/pv/doc/pv_admin.xml
- modules/pv/pv.c
- modules/pv/pv_xavp.c
- modules/pv/pv_xavp.h
Reverse function of pv_var_to_xavp()
> pv: pv_xavp_to_var()

- modules/registrar/README
- modules/registrar/doc/registrar_admin.xml
- modules/registrar/lookup.c
set xavp_rcd at registered() too
> registrar: add contact and received info to xavp_rcd

- modules/acc_radius/acc_radius_mod.c
if we dont free getting memory from extrarstr , can give out of memory. this commit fixes this problem.
> acc_radius : fixes extra attribues memory leak

- modules/misc_radius/functions.c
it helps to understand misc radius errors. i checked "REJECT_RC" never defined.
> misc_radis : more logging

- modules/auth_radius/doc/auth_radius_admin.xml
added information about how to active freeradius-client library
> auth_radius doc: about freeradius-client

- dprint.c
seems to be running nicely here.
to be tested more though.
> set the log_prefix buffer size to 1024b

- modules/ims_charging/ro_session_hash.h
- modules/ims_charging/ro_timer.c
- modules/ims_registrar_scscf/cxdx_sar.c
- modules/ims_usrloc_scscf/hslot.h
low hanging fruits first, other warnings still left
> patches to fix some clang errors and warnings

- modules/sipcapture/README
- modules/sipcapture/doc/sipcapture_admin.xml
- modules/sipcapture/sipcapture.c
- Add support for storing in asynchronous mode if supported
by database backend
> sipcapture: add async support

- .travis.yml
- test/travis/README.md
- test/travis/build_travis.sh
- use jessie as default distribution
> tests/travis: migrate to docker environment

- modules/curl/curl.c
- modules/curl/curl_api.c
- modules/curl/curl_api.h
- modules/curl/functions.c
- modules/curl/functions.h
- Fix invalid check of uri and postdata parameters
- Fix fixup functions
- Refactor curl function to remove dependance on pv/fixup structures
- Export curl_connect through C API
- Fix buffer overflow in curl write function
> Fixes and improvements to curl module

- modules/presence/notify.c
- modules/presence_dialoginfo/add_events.c
- modules/presence_dialoginfo/notify_body.c
when subs_mode <> 3 the notify version is always the same (first watcher) for all watchers
> presence : fix notify version when subs_mode <> 3

- modules/cfgt/README
- modules/cfgt/doc/cfgt_admin.xml
Adds Usage section with .cfg snippet
> cfgt: second pass at documentation update

- modules/db_text/dbt_lib.c
compare DB1_STR, DB1_STRING, DB1_BLOB as equal
> db_text :  column type comparison

- modules/presence/notify.c
adds callid to NOTIFY log
adds log when multiple records are found in process_dialogs
> presence: additional info in logs

- modules/db_text/dbt_base.c
- modules/db_text/dbtext.c
- modules/db_text/dbtext.h
implements replace with update/insert
tries to update, inserts if not found
> db_text: add support for replace

- modules/presence_xml/notify_body.c
we were sending the presence element without the entity attribute.
it seems some UAs dislike this
> presence_xml: fix pres_agg_nbody_empty

- modules/nat_traversal/nat_traversal.c
- modules/statsd/lib_statsd.c
- modules/statsd/lib_statsd.h
Spotted few cases where using C99 bool can remove local typedef and corresponding macros
> Use C99 boolean

- modules/db_text/dbt_base.c
- modules/db_text/dbt_raw_query.c
- modules/db_text/dbt_raw_query.h
- modules/db_text/dbt_raw_util.c
also fixes db_free_result for non select operations
also improves replace by exiting on first match
> db_text: implemented raw query for UPDATE/DELETE/REPLACE

- Makefile.defs
- sr_module.c
- tcp_options.h
Found out that I broke compilation and decided to fix other minor things also.
> OpenBSD fixes

- modules/nsq/doc/nsq_admin.xml
- corrected transformations section, nsq.json usage
> nsq: updated doc

- modules/evapi/doc/evapi_admin.xml
- modules/evapi/evapi_dispatch.c
- modules/evapi/evapi_dispatch.h
- modules/evapi/evapi_mod.c
Hi @miconda 
As we spoke yesterday, this is the PR to add the option about sending EVAPI data to a specific destination instead to all hosts. 
Could you review/add comments? 
Regards and thanks for the help!
> evapi: Added destination address on evapi_relay

- modules/kex/core_stats.c
- modules/kex/core_stats.h
* requests by method
* replies by status code
> kex: add extended core stats

- modules/presence/doc/presence_admin.xml
- modules/presence/notify.c
- modules/presence/presence.c
Similar to local_log_level - controls the syslog facility of certain log entries
> presence: Add local_log_facility configuration parameter

- modules/uac/doc/uac_admin.xml
> uac: uac.reg_refresh doc is supplemented

- modules/call_control/call_control.c
- modules/http_client/http_client.c
- modules/mediaproxy/mediaproxy.c
- modules/rr/record.c
- modules/sipcapture/sipcapture.c
- modules/uid_domain/uid_domain_mod.c
Most found with Clang 3.8 static analyzer.
Full results here: http://mslehto.iki.fi/clang-static-analyzer/kamailio/01/modules/
> Fix variable initialization and NULL pointer dereference issues

- mem/f_malloc.c
- mem/q_malloc.c
Log some errors in case some memory API functions fail.
> mem: Add on-error log messages for q_/f_ functions

- modules/cnxcc/cnxcc_mod.c
This PR is related to GH #563 and probably to some other cnxcc's crashes that have been reported.
> cnxcc: release credit_data in terminate_all_calls

- modules/app_java/java_msgobj.c
- modules/auth_radius/authorize.c
- modules/cdp/diameter_api.h
- modules/cdp/diameter_msg.c
- modules/cdp/peerstatemachine.c
- modules/cdp/peerstatemachine.h
- modules/cdp/session.c
- modules/db_berkeley/km_db_berkeley.c
- modules/ims_auth/cxdx_avp.c
- modules/ims_auth/cxdx_mar.c
- modules/ims_dialog/dlg_handlers.c
- modules/misc_radius/functions.c
- modules/peering/verify.c
- modules/pua_xmpp/xmpp2simple.c
- modules/tls/tls_config.c
fix several compilation warnings #653
> fix compilation warnings

- dprint.h
Fix compile errors in logging macros when building with Solaris Studio
closes #678
> core: fix logging macros for Solaris Studio

- Makefile.defs
- action.c
- atomic/atomic_sparc64.h
- io_wait.h
- ip_addr.h
- modules/counters/counters.c
- modules/ctl/binrpc_run.c
- modules/dialog/dlg_handlers.c
- modules/pdb/common.h
- modules/uid_avp_db/Makefile
- sr_module.h
- tls_hooks.h
This allows building with Solaris Studio, tested with 12.4.
> Fix Solaris Studio build

- endianness.h
- add bswap16() and bswap32() for 16 and 32 bit endianness swap
> core: add generic byte swap macros

- modules/cdp/authstatemachine.c
- modules/cdp/peermanager.c
> cdp: initializing a variable to 0 and checking a return ptr for null

- modules/ims_charging/ccr.c
- modules/ims_charging/ims_ro.c
- modules/ims_charging/ro_session_hash.c
- modules/ims_charging/ro_timer.c
Fixing a set of issues related to IMS Ro interface.
> ims_charging: fix Ro issues

- modules/userblacklist/userblacklist.c
- parser/msg_parser.c
- Fixed confusing debug output in module for global blacklists and whitelists
> userblacklist: little changes in debug output

- modules/uac/doc/uac_admin.xml
- modules/uac/uac.c
- modules/uac/uac_reg.c
- modules/uac/uac_reg.h
- parser/case_min.h
- parser/hf.c
- parser/hf.h
- parser/msg_parser.c
- parser/msg_parser.h
- sip_msg_clone.c
This PR contains my backlog of changes for uac registrations.
Most patches are for making the registrations list fully dynamic (add/remove via RPC)
Some fixes, some cleanups, some features...
> Various improvements to uac registrations

- parser/parse_fline.c
- receive.c
preparing for TCP, UDP hep processing over nonsip_hook.
> core: added more flexible processing for nonsip_hook messages

- modules/rtimer/README
- modules/rtimer/doc/rtimer_admin.xml
- modules/rtimer/rtimer_mod.c
Extend the mode parameter to accept the number of processes that should handle the rtimer.
> Let multiple processes handle an rtimer

- modules/uri_db/checks.c
- modules/uri_db/checks.h
- modules/uri_db/doc/uri_db_admin.xml
- modules/uri_db/uri_db.c
- until now only from and to uri can be checked
- so added a function check_uri to check any uri
> uri_db: added function to check any sip uri

- modules/permissions/hash.c
- modules/permissions/permissions.c
- added array structure when returning multiple address and subnets
> permissions: fixed rpc array

- modules/sipcapture/sipcapture.c
added X-RTP-Stat-T38 and X-RTP-Stat-Add.
> modules/sipcapture: extended X-RTP-Stat types

- modules/tm/uac.c
The first patch does the actual failover part.
Second is for readability.
Third adds onsend_route support for local requests.
This fixes #210.
As this touches tm, a review would be welcomed.
> Implement DNS failover for locally generated requests

- modules/sca/sca_subscribe.c
* try to get r-uri from $ru and fallback to msg value as previously
Fix #777
> sca: sca_handle_subscribe() get actual ruri

- modules/ims_isc/mark.c
- modules/ims_isc/mod.c
- modules/ims_isc/third_party_reg.c
- modules/ims_isc/third_party_reg.h
Add also tel: as header in 3rd party REG towards TAS
> ims_isc: Add tel: associated URI on 3rd party REG

- modules/tmx/t_var.c
porting of the changes done for ims_auth and ims_registrar_scscf modules.
> tmx: fix condition for private copy of the message

- pkg/kamailio/centos/7/README
- pkg/kamailio/centos/7/kamailio.init
- pkg/kamailio/centos/7/kamailio.spec
- pkg/kamailio/centos/7/kamailio.sysconfig
I updated the specs file (see the changelog) to build Kamailio 5.x rpm packages for CentOS 7.2
> Updated the specs file for CentOS 7

- modules/siputils/chargingvector.c
- modules/siputils/chargingvector.h
- modules/siputils/doc/siputils_admin.xml
- modules/siputils/siputils.c
Original purpose was to add new $pcv(...) pseudo variables.
Ended up doing documentation stub, minor bug fix and general housekeeping.
> P-Charging-Vector related updates

- cfg_parser.h
- modules/corex/doc/corex_admin.xml
- modules/db2_ops/doc/db2_ops.xml
- modules/dispatcher/doc/dispatcher_admin.xml
- modules/drouting/doc/drouting_admin.xml
- modules/mohqueue/doc/mohqueue_admin.xml
- modules/rtpproxy/doc/rtpproxy_admin.xml
- modules/tm/doc/functions.xml
- sr_module.h
another lump of documentation or code comment typo fixes I've collected
> documentation fixes

- src/modules/ss7ops/ss7ops_mod.c
Add support for M2PA encapsulation on top of M2UA. It will only
handle data messages as these can contain isup.
> ss7ops: Enable M2PA encapsulation in addition to M2UA

- test/unit/12.cfg
- test/unit/12.sh
- test/unit/18.sh
- test/unit/19.cfg
- test/unit/19.sh
- test/unit/2.cfg
- test/unit/2.sh
- test/unit/20.cfg
- test/unit/20.sh
- test/unit/27.sh
- test/unit/33.cfg
- test/unit/33.sh
- test/unit/34.cfg
- test/unit/34.sh
- test/unit/4.sh
- test/unit/5.sh
- test/unit/7.cfg
- test/unit/7.sh
- test/unit/include/common
- test/unit/presence.cfg
more bashism removal
some mi_fifo to jsonrpcs conversions
> unittest updates

- src/modules/ims_icscf/cxdx_avp.c
- src/modules/ims_icscf/cxdx_avp.h
- src/modules/ims_icscf/scscf_list.c
- src/modules/ims_icscf/scscf_list.h
- src/modules/ims_isc/mark.c
- src/modules/ims_isc/mark.h
- src/modules/ims_registrar_scscf/cxdx_avp.c
- src/modules/ims_registrar_scscf/cxdx_avp.h
- src/modules/ims_usrloc_scscf/bin_utils.c
- src/modules/ims_usrloc_scscf/bin_utils.h
* move inline functions to bin_utils.h
* clang-format bin_utils.* files
> ims_*: fix  inline function xxx declared but never defined

- src/Makefile.groups
Create kpcre group
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
> Add kpcre group

- src/modules/presence/notify.c
discovered when using tlsf memory manager.
> presence: free pointer after usage

- modules/tm/uac.c
this is fixed on master with the new t_run_local_req function
> tm: apply new updates with Via with updated request

- .travis.yml
- test/travis/README.md
- test/travis/build_travis.sh
* move away from my own personal pkg-kamailio-docker repo.
* use the one controlled by the project so not just me is able to contribute
> travis: use kamailio/pkg-kamailio-docker

- src/modules/auth_db/doc/auth_db_admin.xml
added more explanation about error instead of some generic error.
> auth_db : more explanation for generic error

- src/modules/nsq/nsq_mod.c
- src/modules/nsq/nsq_mod.h
> nsq: do not use PROC_SIPINIT rank for consumer workers

- src/modules/pua_reginfo/notify.c
- src/modules/pua_reginfo/usrloc_cb.c
> pua_reginfo: fix memory leak when usrloc is DB_ONLY

- src/core/parser/case_c_inf.h
- src/core/parser/case_call.h
- src/core/parser/hf.c
- src/core/parser/hf.h
- src/core/parser/keys.h
- src/core/parser/msg_parser.c
- src/core/sip_msg_clone.c
- src/modules/sca/sca_call_info.c
- src/modules/sca/sca_call_info.h
- src/modules/sca/sca_subscribe.c
> Call-Info header support

- pkg/kamailio/centos/7/kamailio.spec
A couple of patches for Centos 7 spec file.
> Centos7 spec fixes

- modules/dmq_usrloc/usrloc_sync.c
backport the synchronisation problem fix
> 4.4 dmqfix backport

- src/modules/presence/subscribe.c
fast_notify not used when pres_notifier_processes > 0
> presence : fix fast_notify usage

- utils/pdbt/Makefile
- utils/pdbt/pdbt.c
- use CC environment variable if set
- added missing sys/stat.h header
> utils/pdbt: FreeBSD fix, gcc is hardcoded, header is missing

- src/modules/usrloc/doc/usrloc_admin.xml
- src/modules/usrloc/ucontact.c
- src/modules/usrloc/usrloc_mod.c
- src/modules/usrloc/usrloc_mod.h
db_load: enable/disable loading from the database on mod_init (except when in db_mode 4 /READ_ONLY)
db_insert_update: insert into table, update on duplicate key
> usrloc: adding params

- src/modules/topoh/th_msg.c
Hello,
I have added some extra verifications to the th_unmask* functions from topoh. The changes add statements which verify that headers contain expected prefix (including mask ip) before trying to unmask them. It seems that some of the th_unmask* functions only check that the headers exist, and then they directly call th_mask_decode on the data.
If other messages that are not encoded by topoh are processed by this function, th_mask_decode may not return an error, and instead create an unreadable string and this is added to the message. Therefore I added some additional checks to see that the message has the expected prefix (or when possible check directly that the host IP is the mask_ip set), if the header does not have the expected form then unmasking is not attempted. 
Thanks, …
> topoh: add additional safety checks

- pkg/kamailio/centos/7/kamailio.spec
backport of commit de323d80a9fc76d5bea625b1a3ad28a30dda0ea4
> pkg/kamailio/centos/7: mod kazoo enabled default build

- modules/kazoo/defs.h
- modules/kazoo/kazoo.c
- modules/kazoo/kz_amqp.c
- modules/kazoo/kz_amqp.h
- modules/kazoo/kz_hash.c
- modules/kazoo/kz_json.c
- modules/kazoo/kz_json.h
- modules/kazoo/kz_pua.c
- modules/kazoo/kz_pua.h
lots of fixes needed for proper operation
> kazoo: backports & fixes

- src/modules/rabbitmq/rabbitmq.c
When using the rabbitmq_publish function, there is no need to create
a reply-to queue, because it will never be read. And since there is
never a real consumer, the queue will never be deleted. This
will eventually cloak up the RabbitMQ server with millions of
generic reply queues.
This bug has been fixed in master already, so this is basically a
backport.
> rabbitmq: don't create reply-to queue on publish

- src/modules/pua_dialoginfo/README
- src/modules/pua_dialoginfo/pua_dialoginfo.c
some docs fix & compile error with PUA_DIALOGINFO_DEBUG enabled
> pua dialoginfo

- src/modules/dmq/dmq.c
change status from int to readable text
> dmq: update output format of dmq.list_nodes

- src/modules/evapi/evapi_dispatch.c
Hello, 
We're getting this error message, and I'm not sure why. So I added the error cause in the log.  
Regards.
> evapi: Improved error message

- pkg/kamailio/centos/7/kamailio.spec
Reverts kamailio/kamailio#1194
> Revert "Centos 7 specfile updates"

- src/modules/keepalive/doc/keepalive.xml
- src/modules/keepalive/doc/keepalive_admin.xml
- src/modules/keepalive/doc/keepalive_devel.xml
- provides documentation for internal API 
- GH #1082
> keepalive: improve documentation

- src/modules/carrierroute/cr_config.c
- src/modules/carrierroute/cr_db.c
- src/modules/carrierroute/cr_fifo.c
- src/modules/carrierroute/cr_func.c
- src/modules/carrierroute/parser_carrierroute.c
Fix the following issues found by Coverity:
3c86d68 fixes defect [85605](https://scan8.coverity.com/reports.htm#v32382/p10993/fileInstanceId=17916961&defectInstanceId=6138921&mergedDefectId=85605)
7f603ec fixes defect [86015](https://scan8.coverity.com/reports.htm#v32382/p10993/fileInstanceId=17916961&defectInstanceId=6138739&mergedDefectId=86015)
2772f09 fixes defects [85807](https://scan8.coverity.com/reports.htm#v32382/p10993/fileInstanceId=17916966&defectInstanceId=6138583&mergedDefectId=85807) and [85651](https://scan8.coverity.com/reports.htm#v32382/p10993/fileInstanceId=17916966&defectInstanceId=6138536&mergedDefectId=85651) 
d8fdcb3 fixes defects [153773](https://scan8.coverity.com/reports.htm#v32382/p10993/fileInstanceId=17916 …
> Fix coverity issues in carrierroute module

- src/modules/app_sqlang/Makefile
- src/modules/app_sqlang/squirrel/sqstdlib/Makefile
- src/modules/app_sqlang/squirrel/squirrel/Makefile
- app_sqlang now uses $(MAKE) and $(CC) variables in Makefiles,
so it builds on systems with gnu make named different then make
and compiles with different compiler than gcc
> app_sqlang: fix static make and gcc in Makefiles

- pkg/kamailio/alpine/0001-kamdbctl.base.patch
- pkg/kamailio/alpine/0002-remove-spurious-execinfo.patch
- pkg/kamailio/alpine/0003-src_modules_tls_tls_init_c.patch
- pkg/kamailio/alpine/0004-src_core_tcp_read_c.patch
- pkg/kamailio/alpine/APKBUILD
- pkg/kamailio/alpine/kamailio.cfg
- pkg/kamailio/alpine/kamailio.initd
- pkg/kamailio/alpine/kamailio.pre-install
- pkg/kamailio/alpine/kamailio.pre-upgrade
- pkg/kamailio/alpine/kamctl_build.patch
This scripts will be used for automated docker container builds
> pkg/kamailio/alpine: Added packaging script for Alpine dist.

- src/modules/timer/timer.c
> timer: reset xavp using common function

- src/modules/app_python/Makefile
Reverts kamailio/kamailio#924. Opinion conflict
> Revert "app_python: fix compiler warning"

- src/modules/path/doc/path_admin.xml
- src/modules/path/path.c
- added the possiblity to have the received parameter and flow toke
in the add_path_received function
> path: insert flow token in path header with received

- modules/sipcapture/sipcapture.c
(cherry picked from commit dbd57c3eac30e1de54d98eb2ba8f608a17f7adbf)
> sipcapture: fix HEP3 capture-id >= 2^16

- src/modules/dispatcher/dispatch.c
Fixes compiling error on FreeBSD because there is for UINT32_MAX the <stdint.h> header needed.
> dispatcher: undeclared UINT32_MAX on FreeBSD missing header

- pkg/kamailio/obs/kamailio.service
- pkg/kamailio/obs/kamailio.spec
- pkg/kamailio/obs/meta
- pkg/kamailio/obs/prjconf
pkg/kamailio/obs: git cherry-pick to 5.0 branch
> pkg/kamailio/obs: git cherry-pick to 5.0 branch

- src/modules/evapi/evapi_dispatch.c
> evapi: Change NOTICE logging to DBG

- src/modules/uac/uac_send.c
> uac: increase UAC message size to 32kbytes

- src/modules/db_unixodbc/db_unixodbc.c
- src/modules/db_unixodbc/dbase.c
- src/modules/db_unixodbc/dbase.h
- [X ] Commit message has the format required by CONTRIBUTING guide
- [ X] Tested changes locally
Add async queries support to db_unixodbc through the core async framework.
> db_unixodbc: added support for async queries

- src/modules/nat_traversal/nat_traversal.c
- fix_contact for ipv6 addres,add the [] to the host part of contact header
when we detect the nat, we are using fix_contact to fix the contact header according to nat.but for ipv6, fix_contact doesn't add the [] to ip part of contact header.because of this we are getting bad contact header.we resolved this by adding [] to ipv6 address.
> nat_traversal: fixing ipv6 contact for fix_contact function in cfg.

- pkg/kamailio/obs/kamailio.spec
Reverted commit cb42b9881b3d1f90f3cb54765eef65ce9d773f92
Fixed lua module build
> pkg/kamailio/obs: Fixed lua module build

- src/lib/srdb1/schema/topos_d.xml
- src/lib/srdb1/schema/topos_t.xml
Using topos module in production I have found slow queries in MySQL.
After analyzing it I have add indexes to topos_t and topos_d tables.
> schema: add indexes to topos Mysql tables

- pkg/kamailio/obs/kamailio.spec
- pkg/kamailio/obs/meta
Set Cherry picks of OBS spec update
Added Fedora 27 support
Removed Fedora 24 support
> Set Cherry picks of OBS spec update

- src/modules/auth_radius/sterman.c
- src/modules/db_mongodb/mongodb_dbase.c
- src/modules/sms/libsms_modem.c
- src/modules/uac/uac_reg.c
- src/modules/xmpp/xode.c
- src/modules/xmpp/xode_from.c
- src/modules/xmpp/xstream.c
> fix gcc 7 warnings

- src/modules/pv/pv_branch.c
- some params (like dest uri) were not appended to branch
due to a copy-paste typo
- [ x] Small bug fix (non-breaking change which fixes an issue)
- [ x] PR should be backported to stable branches
- [ x] Tested changes locally
> pv: correct sbranch params appending

- pkg/kamailio/deb/buster/control
- pkg/kamailio/deb/debian/control
- pkg/kamailio/deb/jessie/control
- pkg/kamailio/deb/precise/control
- pkg/kamailio/deb/sid/control
- pkg/kamailio/deb/stretch/control
- pkg/kamailio/deb/trusty/control
- pkg/kamailio/deb/wheezy/control
- pkg/kamailio/deb/xenial/control
fix module names in description of package kamailio-extra-modules
> pkg/kamailio/deb: fix module names in pkg description

- pkg/kamailio/deb/debian/control
- pkg/kamailio/deb/jessie/control
- pkg/kamailio/deb/precise/control
- pkg/kamailio/deb/sid/control
- pkg/kamailio/deb/squeeze/control
- pkg/kamailio/deb/stretch/control
- pkg/kamailio/deb/trusty/control
- pkg/kamailio/deb/wheezy/control
- pkg/kamailio/deb/xenial/control
fix janssonrpc-c module name in description of package kamailio-extra-modules
> pkg/kamailio/deb: fix module name in description [skip ci]

- src/modules/usrloc/doc/usrloc_admin.xml
- src/modules/usrloc/usrloc_mod.c
(cherry picked from commit b933b2a7bf631b157bf81b86afffe6b8a43a0308)
Non-instrusive fix which will let us use a stable branch in production.
> usrloc: partion column name can be set via modparam

- src/modules/nathelper/README
- src/modules/nathelper/doc/nathelper_admin.xml
> nathelper: fix force_socket documentation

- src/modules/sipcapture/sipcapture.c
fixing LM_ERR logging to LM_DBG in the pv_parse_hep_name() function.
> modules/sipcapture fixed LM_ERR to LM_DBG

- src/modules/websocket/ws_frame.c
> websocket: handle unrecognized subprotocol better

- src/modules/websocket/ws_frame.c
> websocket: check bounds before reading mask

- src/modules/ims_usrloc_scscf/subscribe.c
In update_subscriber() function, when the rs is assigned to the subs,
it is missing the record_route component, which leads to core dump in
some scenarios.
(cherry picked from commit 595b8fe06165328366865328e43c14a9ca23c386)
Changes cherry-picked from master branch, same title plus "(5.1)"
> ims_usrloc_scscf: missing assignment of record_route (5.1)

- src/modules/textops/doc/textops_admin.xml
- src/modules/textops/textops.c
Fix a mismatched parenthesis in doc for textops module.
New function in_list_prefix based on  in_list one but it checks if element in list is prefix for subject instead of an exact match.
> Textops in list prefix function

- src/Makefile.groups
- src/modules/acc_json/Makefile
- src/modules/acc_json/acc_json_mod.c
- src/modules/acc_json/acc_json_mod.h
- src/modules/acc_json/doc/Makefile
- src/modules/acc_json/doc/acc_json.xml
- src/modules/acc_json/doc/acc_json_admin.xml
See comments in this PR, https://github.com/kamailio/kamailio/pull/1437
new features are now implemented in the module `acc_json`
```
Total 1000000 INVITE calls sent in 2294479 ms at rate of 435/sec
Total 1000000 responses received in 2295273 ms at rate of 435/sec:
Detailed responses received:
- 200 responses:  1000000     (OK)
------
TOTAL responses:  1000000 (rate=435/sec)
```
> acc_json: adding module

- src/modules/app_python3/README
- src/modules/app_python3/README.TestCase-Loggers
- src/modules/app_python3/doc/Makefile
- src/modules/app_python3/doc/app_python3.xml
- src/modules/app_python3/doc/app_python3_admin.xml
- src/modules/app_python3/python_examples/Loggers.py
- src/modules/app_python3/python_examples/TestCase_Traceback.py
- src/modules/app_python3/python_examples/handler.py
- update documentation and python_examples/ to reflect the new module name
- fix typo arg->args in python_examples/handler.py
Update the documentation for module app_python3 to reflect the new name
> app_python3: update documentation

- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
Added ability to explicitly request usage of DTLS transports UDP/TLS/RTP/SAVP and UDP/TLS/RTP/SAVPF via rtpengine API.
> rtpengine: added support for DTLS transports

- src/modules/presence/presentity.c
> presence: test if event is dialog to avoid unnecessary xml parsing

- src/modules/app_python/app_python_mod.c
- src/modules/app_python/apy_kemi.c
- src/modules/app_python/doc/app_python_admin.xml
- src/modules/app_python/python_exec.c
Script reloading for app_python.
- implements reloading of script
- the version is incremented by RPC and the version check
is performed in each worker on the next invocation of a
Python method
> app_python: implement reloading of script

- src/modules/db_mongodb/mongodb_dbase.c
- [X ] Small bug fix (non-breaking change which fixes an issue)
db_mongodb: Add error logger for failed query
> db_mongodb: add error logger for failed query

- src/modules/ndb_mongodb/mongodb_client.c
Since 1.5.0 mongoc_collection_find() is deprecated
> http://mongoc.org/libmongoc/1.5.0/mongoc_collection_find.html
https://travis-ci.org/kamailio/kamailio/jobs/365964042 (dev-sid)
> CC (clang) [M ndb_mongodb.so]		mongodb_client.o
> mongodb_client.c:290:18: warning: 'mongoc_collection_find' is deprecated [-Wdeprecated-declarations]
>                         rpl->cursor = mongoc_collection_find (rpl->collection,
>                                       ^
> /usr/include/libmongoc-1.0/mongoc-collection.h:155:1: note: 'mongoc_collection_find' has been explicitly marked deprecated here
> mongoc_collection_find (mongoc_collection_t *collection,
> ^
> 1 warning generated.
> ndb_mongodb: fix deprecation warning

- src/modules/htable/htable.c
> Module: htable:: event_callback_mode to int

- misc/examples/kemi/kamailio-basic-kemi-lua.lua
> misc:kemi_lua append_hf to append

- src/modules/ims_diameter_server/avp_helper.c
Diameter request MAR and corresponding response MAA both contain authentication vectors in binary form. Ims_diameter_server lacks functionality to convert binary arrays to json and back. This pr is a couple of minor fixes to rectify the issue:
* when converting Diameter binary vector to json use %02x in sprintf() to form a proper hexdump which is possible to decode on json side. The hexdump is sent in "data" key value pair as string.
* introduce new key value pair "hexdump" in json which will contain hex dump of binary vector formed on json side. ims_diameter_server converts it to Diameter AVP using hex dump to binary transcoding.
> change ims_diameter_server to allow binary data transcoding

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/doc/dispatcher.xml
- src/modules/dispatcher/doc/dispatcher_admin.xml
Presented at Kamailio World 2018, load balancing doing congestion detection
https://www.youtube.com/watch?v=AD0BGaW1g58
More information can be found 
http://www.castmm.com/KW2018.pdf
https://github.com/jchavanton/kam_load_balancing
> dispatcher: congestion detection load balancing

- src/modules/ims_usrloc_scscf/impurecord.c
impurecord.c: corrected small bug in remove_impucontact_from_list()
This is the branch 5.1 pull request, created by cherry-pick from https://github.com/kamailio/kamailio/pull/1562
> ims_usrloc_scscf:bugfix erraneous unlinking of deleted contact

- src/modules/evapi/evapi_mod.c
evapi_async_relay is exported to kemi interface
> Modules: Evapi async_relay export to kemi

- src/modules/app_lua/app_lua_api.c
- [ X] PR should be backported to stable branches
> app_lua : fixing bug for setting set SR lib version for lua 52

- src/modules/rtpengine/rtpengine.c
> kamailio always retries deleted RTPEngine Nodes which generates PDD

- src/core/parser/parse_fline.c
- src/core/parser/parse_fline.h
- bring up to date with new methods added in 4fe95ab
> core: update first line parser to recognize new method IDs

- pkg/kamailio/obs/kamailio.spec
- [ x No commits to README files for modules (changes must be done to docbook files
Defined correct dependences for perl module
> pkg/kamailio: Defined correct dependences for perl module (#1613)

- src/modules/smsops/smsops_impl.c
Support for concatenated SMS messages in smsops module.
The current implementation doesn't handle correctly concatenated SMSes. The patch adds support for them in the smsops module, including dumping a concatenated message to the log and new PVs with SMS message parameters.
There are also small fixes in the indentation - spaces are replaces with tabs, as this seeems to be the preferred approach in the file.
> smsops: Add support for concatenated SMS in decode_3gpp_sms()

- src/core/dprint.h
> core: print log_prefix after loglevel for more intuitive parsing

- src/modules/permissions/address.c
- src/modules/permissions/trusted.c
> permissions: check for db_url being set on reload

- src/modules/pua_reginfo/notify.c
- [ x] PR should be backported to stable branches
- [ x] Related to issue #1579  (replace XXXX with an open issue number)
Fixes in pua_reginfo module that prevents module from crashing up on a register and unregister event.
Use secure sruid generator to avoid duplicated sruids.
Discussed in issue #1579
> pua_reginfo: fix crash and issue during load

- src/modules/drouting/prefix_tree.c
- uri like sip:@host crushed kamailio
> drouting: fix crush for empty username in ruri

- src/modules/kex/core_stats.c
- src/modules/kex/core_stats.h
- ability to count reply groups for each SIP method added.
- statistics for 2xx and 4xx replies on invite added
> kex: Extend kamailio rcv_replies statistics

- src/modules/dispatcher/dispatch.c
relative weight based load distribution, issue #1649
synchronization problem in dispatcher relative weight based distribution
> dispatcher: fix syncronization problem with

- src/modules/db_unixodbc/doc/db_unixodbc_admin.xml
- [ x] Each component has a single commit (if not, squash them into one commit)
- [ x] PR should be backported to stable branches
> db_unixodbc: added section ids, updated application name

- src/modules/sipcapture/sipcapture.c
added RPID header parser to extract URL's user and store to PPI field.
> module_sipcapture: added RPID parser for PPI field

- src/modules/nathelper/nathelper.c
nathelper not obtaininng the IP from sdp correctly
> nathelper: fix call to alter_mediaip

- src/modules/siputils/checks.c
- src/modules/siputils/checks.h
- src/modules/siputils/doc/siputils_admin.xml
- src/modules/siputils/siputils.c
maybe this already exists but i didn't find.
not required to backport but could be useful in 5.1
> siputils: add is_uri function

- src/modules/htable/doc/htable_admin.xml
- src/modules/htable/ht_dmq.c
- src/modules/htable/ht_dmq.h
- src/modules/htable/htable.c
> htable: added startup synchronization over dmq

- pkg/kamailio/obs/kamailio.spec
- pkg/kamailio/obs/meta
> pkg/kamailio/ops: Added MongoDB rpm package

- src/modules/ims_diameter_server/avp_helper.c
> ims_diameter_server: fixing avp nested list #1686

- pkg/kamailio/obs/kamailio.spec
Required backport to `5.2` branch.
> RPM spec update

- src/modules/acc_json/acc_json_mod.c
Quick implementation with a few tests, I just sharing it, but I sleep on it and review before merging.
> acc_json: support for leg_info fields

- src/modules/secfilter/secfilter.c
- src/modules/secfilter/secfilter_hdr.c
secfilter: in check sql injection function initialize str variables to NULL. In get values from headers it is checked if From or To name is empty to avoid false positives
> secfilter: some fixes in check_sqli function and getting from name header value

- src/modules/secfilter/secfilter_rpc.c
Changed char* by str in RPC function params to avoid memory problems
> secfilter: changed char* by str in RPC function params

- src/modules/cnxcc/cnxcc_check.c
- src/modules/cnxcc/cnxcc_mod.c
- src/modules/cnxcc/cnxcc_mod.h
- src/modules/cnxcc/cnxcc_rpc.c
- src/modules/cnxcc/doc/cnxcc.xml
- src/modules/cnxcc/doc/cnxcc_admin.xml
With this changes it is possible to account the connect cost for the call. This is useful for calls to premium numbers that have connection charges.
> cnxcc: New improvement for the cnxcc module

- src/modules/tm/tm.c
- Allows PVs including $avp(...) to be passed to t_check_status
Allows $avp(...) in the parameter to t_check_status
> tm: Add fixup for PVS in fixup_t_check_status

- src/modules/cnxcc/doc/cnxcc_admin.xml
fix example code in doc file adding the new parameter in the cnxcc_set_max_credit() function
> cnxcc: fix example code in doc file adding the new parameter in the cnxcc_set_max_credit() function

- src/modules/tsilo/ts_store.c
> tsilo: add check for empty aor

- src/modules/dispatcher/doc/dispatcher_admin.xml
Update for Readme Dispatcher module. I added some minor comments for dispatcher module, what I think might be useful for somebody. Additionally I added description, what several states means when dispatcher list are executed, as discussed.
> Update for Readme Dispatcher module

- src/modules/sdpops/doc/sdpops_admin.xml
- src/modules/sdpops/sdpops_mod.c
added new function that helps to extract IP address family at c line from SDP body. 
it returns -1 on error , 4 for IP4 , 6 for IP6
> sdpops : added new function named as get_sdp_address_family

- src/modules/phonenum/doc/phonenum_admin.xml
> phonenum: fixing documentation typo

- src/modules/janssonrpcc/doc/janssonrpcc_admin.xml
- src/modules/janssonrpcc/janssonrpc_connect.c
- src/modules/janssonrpcc/janssonrpc_server.h
- src/modules/janssonrpcc/janssonrpc_srv.h
- src/modules/janssonrpcc/janssonrpcc_mod.c
- send periodic tcp keepalive packets to server in order to prevent connection from closing
> janssonrpcc: add new parameter "keep_alive"

- utils/kamctl/kamctl
- utils/kamctl/kamctl.base
- utils/kamctl/kamctl.sqlbase
- utils/kamctl/kamdbctl
Hi all,
I was trying to add entries to a remote database on OpenWrt and kamctl (address add ...) seemed to just hang there. A bit of digging showed that it prompted for a password, but I couldn't see it because it redirected the prompt to /dev/stderr, which doesn't exist on every system. This patch addresses this.
Use portable "#!/bin/sh" shebang. This may still be a symlink to bash
(or some other shell).
Also replace the redirection to "/dev/stderr" with a POSIX redirection
to stderr. "/dev/stderr" is not available on all systems and is also not
recognized by all shells (example: ash). On systems without a working
"/dev/stderr" the user will not see the prompts etc.
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>
> kamctl: keep it POSIX

- src/modules/pipelimit/doc/pipelimit_admin.xml
- src/modules/pipelimit/pipelimit.c
- src/modules/pipelimit/pl_ht.c
- src/modules/pipelimit/pl_ht.h
Add automatic cleanup of pipes that have not been used for a while. Save memory on infrequently used pipes.
> Add automatic pipe cleanup

- src/modules/ims_registrar_pcscf/save.c
if there is a sos parameter on Contact header on saving state in P-CSCF ,P-CSCF dont subscribe to S-CSCF for reg-events.
3GPP TS 24.229 5.2.10.1
Upon receiving the 200 (OK) response to the REGISTER request that completes the emergency registration, as identified by the presence of the "sos" SIP URI parameter in the Contact header field of the 200 (OK) response, the P-CSCF shall not subscribe to the registration event package for any emergency public user identity specified in the REGISTER request.
> ims_registrar_pcscf : added a condition for subscribiton about sos param

- src/modules/htable/doc/htable_admin.xml
- src/modules/htable/htable.c
Empties the entire specified hash table
Add a new RPC comand to flush (empty) a htable.
> htable: Add RPC htable.flush <htable>

- src/modules/dispatcher/dispatch.c
- src/modules/jansson/jansson_funcs.c
- src/modules/jansson/jansson_utils.c
- src/modules/jsonrpcs/jsonrpcs_mod.c
- src/modules/siputils/options.c
Fixes all over. If not all acceptable, please cherry-pick, or let me know so i can remove them.
> Random fixes

- src/modules/registrar/lookup.c
if xavp_clone fails it is still inserted leading to crash
> registrar : check xavp clone result

- src/modules/imc/imc.c
> Fixes to the imc module

- src/modules/sipt/ss7_parser.c
Small fix to proper handling A-F in $sipt(redirection_number)
> sipt: $sipt(redirection_number) evaluates the value as a numerical value

- src/modules/tls/tls_init.c
- utils/kamctl/kamctlrc
> Minor typo fixes

- src/modules/htable/ht_dmq.c
- reported by Enrico Bandiera (GH #1863)
> htable: fix infinite loop during dmq sync of large tables

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/dispatcher.c
- src/modules/dispatcher/doc/dispatcher_admin.xml
- add dispatcher.remove call to remove entry from in-memory dispatcher
list
- allow arguments to callback in ds_iter_set()
> dispatcher: remove destination from in-memory dispatcher set

- src/modules/secfilter/secfilter.c
> secfilter: avoid dereferences null

- src/modules/secfilter/doc/secfilter_admin.xml
- src/modules/secfilter/secfilter.c
- src/modules/secfilter/secfilter.h
- src/modules/secfilter/secfilter_rpc.c
> secfilter: print statistics of blocked and allowed messages using RPC commands

- etc/kamailio.cfg
> etc/kamailio.cfg: detect sipvicious as scanner

- src/modules/db_postgres/Makefile
two commits backported from master
> [5.1] Fixed packaging in opensuse/tumbleweed

- src/modules/sipcapture/hep.c
- src/modules/sipcapture/sipcapture.c
> modules:sipcapture Fixed wrong pointer for payload buffer.

- src/core/timer.c
> core: fix timer typo

- src/modules/secfilter/doc/secfilter_admin.xml
> secfilter: Updated example in README file. Use geoip2 module instead geoip [skip ci]

- src/Makefile.defs
Back ported patch from Alpine Linux dist
[related commit](https://github.com/alpinelinux/aports/commit/20f53ef43230040b6bb5a2b1bdf07b8b1e4a94da#diff-75216d130f5872b5775d4e035eadd419)
> src/Makefile.defs: fix build on mips

- src/modules/ims_registrar_pcscf/save.c
- src/modules/ims_registrar_pcscf/sec_agree.c
- src/modules/ims_registrar_pcscf/sec_agree.h
- Parse 'security verify' header from REGISTER request message
and save updated parameters into the database.
- Added debug messages in save_pendign and save for easy debugging.
> ims_registrar_pcscf: parse security verify header

- src/modules/xhttp_prom/Makefile
- src/modules/xhttp_prom/doc/Makefile
- src/modules/xhttp_prom/doc/xhttp_prom.xml
- src/modules/xhttp_prom/doc/xhttp_prom_admin.xml
- src/modules/xhttp_prom/prom.c
- src/modules/xhttp_prom/prom.h
- src/modules/xhttp_prom/prom_metric.c
- src/modules/xhttp_prom/prom_metric.h
- src/modules/xhttp_prom/xhttp_prom.c
- src/modules/xhttp_prom/xhttp_prom.h
New module to generate Prometheus metrics. It creates user defined metrics and also displays metrics based on Kamailio statistics.
> xhttp_prom: module to generate Prometheus metrics.

- src/modules/ims_ipsec_pcscf/cmd.c
- src/modules/ims_registrar_pcscf/save.c
> Ipsec fix defects

- src/modules/crypto/api.c
- src/modules/crypto/api.h
- src/modules/crypto/crypto_mod.c
- src/modules/crypto/crypto_uuid.c
- src/modules/crypto/crypto_uuid.h
- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
- src/modules/rtpengine/rtpengine.h
The goal was to have a different, more complex hashing algorithm that would offer a better distribution among nodes. We've seen in production that the current algorithm does not perform well under heavy load therefore we decided to add SHA1 hashing. After running performance tests we've decided that we need a cryptographic function in order to have the best results mostly when the callids have small entropy. 
In order to add SHA1, a new API was added in crypto module exporting a function applying SHA1 to a string. The API was used in rtpengine module over the callid. After this operation the hash was calculated as before except for applying 0xFF mask over the hash as it was done before, which restrains the power of this algorithm.
> Extend rtpengine hashing algorithms

- src/modules/userblacklist/doc/userblacklist_admin.xml
The example for check_user_whitelist is named as check_user_blacklist in documentation
> userblacklist: fix double "check_user_blacklist" in module documentation

- src/modules/rtpengine/rtpengine.c
> rtpengine: fix error output on send_rtpp_command()

- src/modules/tcpops/doc/functions.xml
> tcpops: Fix the example documentation for tcp_get_conid

- src/modules/ims_registrar_scscf/doc/ims_registrar_scscf.xml
Document title is fixed
- [ x] No commits to README files for modules (changes must be done to docbook files
Document title is fixed
> ims_registrar_scscf : document title is fixed

- pkg/kamailio/alpine/APKBUILD
- [ x Related to issue #1995
Packaged MongoDB driver for Alpine dist
Need wait utils merged [PR for alpine dist](https://github.com/alpinelinux/aports/pull/9273)
> pkg/kamailio/alpine: packaged MongoDB module

- src/modules/rr/rr_mod.c
- [ X] Tested changes locally
rr module: expose record_route_preset to KEMI
> module rr: KEMI expose record_route_preset

- src/modules/db_redis/doc/db_redis_admin.xml
Small contribution to db_redis module documentation.
> db_redis: add examples about usage with dialog module

- src/lib/srdb1/db_id.c
- src/modules/db_mysql/my_uri.c
- src/modules/db_postgres/pg_uri.c
Added parsing of IPv6 address in config file for DB URL.
> Db ipv6-address parsing in config file

- src/modules/ims_isc/checker.c
- use the RURI from the SIP message in the regex compare, rather
than the regex string from the trigger point
> ims_isc: fixed the RURI trigger point match

- src/modules/dialog/doc/dialog_admin.xml
dialog: Typo in readme of RPC Command dlg.dlg_list example, it should be kamcmd dlg.dlg_list abcdrssfrs122444@192.168.1.1, instead of kamcmd dlg.list abcdrssfrs122444@192.168.1.1
> dialog: Typo in readme of RPC Command dlg.dlg_list example

- utils/kamctl/dbtextdb/dbtextdb.py
- reported by GH #1747
Updated kamctl/dbtextdb to complie with either Python2 or Python3.
> kamctl: Update dbtextdb.py for Python3

- src/modules/usrloc/udomain.c
keep a local urecord in order not to loose ucontacts when calling ul_callbacks
> usrloc: keep a private copy of urecord before running ul_callbacks

- etc/kamailio.cfg
> etc/kamailio.cfg: fix typo

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/doc/dispatcher_admin.xml
adds Bit 3 to mode parameter in ds_list_exists to allow the check of active/inactive entries in a list
> dispatcher: add state to mode in ds_list_exists

- src/modules/ims_usrloc_scscf/subscribe.c
- src/modules/ims_usrloc_scscf/udomain.c
- added a new line to the end of some debug logs for
better formatting.
> ims_usrloc_scscf: added '\n' for debug messages

- src/modules/presence_xml/doc/presence_xml_admin.xml
- src/modules/presence_xml/notify_body.c
- src/modules/presence_xml/presence_xml.c
this allow notify body aggregation with priorities
> presence_xml: adds option to aggregate xml body with priorities

- src/modules/dispatcher/doc/dispatcher_admin.xml
dispatcher: Fixed typo in dispatcher_admin.xml
> dispatcher: Fixed typo in dispatcher_admin.xml

- src/modules/tm/t_fwd.c
Execute TMCB_REQUEST_FWDED cb as BRANCH_ROUTE there's branch_route actions
> tm: execute TMCB_REQUEST_FWDED cb as BRANCH_ROUTE when necessary

- src/modules/ims_ipsec_pcscf/cmd.c
- src/modules/ims_ipsec_pcscf/spi_gen.c
- fixed a defect reported from Coverity Scan - Concurrent data access
violations in spi_gen.c for spi_data->spi_val.
- in create_ipsec_tunnel() return -1 when unable to convert ip address.
- in ipsec_create() go to cleanup instead return -1 when get request
for reply fails. Fixed debug message for that error.
> ims_ipsec_pcscf: fixed defects and warnings:

- src/Makefile.groups
- src/modules/pv_headers/Makefile
- src/modules/pv_headers/README
- src/modules/pv_headers/doc/Makefile
- src/modules/pv_headers/doc/functions.xml
- src/modules/pv_headers/doc/params.xml
- src/modules/pv_headers/doc/pv_headers.xml
- src/modules/pv_headers/doc/pv_headers_admin.xml
- src/modules/pv_headers/pv_headers.c
- src/modules/pv_headers/pv_headers.h
- src/modules/pv_headers/pvh_func.c
- src/modules/pv_headers/pvh_func.h
- src/modules/pv_headers/pvh_hash.c
- src/modules/pv_headers/pvh_hash.h
- src/modules/pv_headers/pvh_hdr.c
- src/modules/pv_headers/pvh_hdr.h
- src/modules/pv_headers/pvh_str.c
- src/modules/pv_headers/pvh_str.h
- src/modules/pv_headers/pvh_xavp.c
- src/modules/pv_headers/pvh_xavp.h
The main goal of the module is to offload the intermediate header
processing into the XAVP dynamic container as well as provide with high
level methods and pseudovariables to simplify SIP message header
modifications.
> pv_headers: Initial commit

- src/modules/cnxcc/doc/cnxcc_admin.xml
> cnxcc: updated readme file [skip ci]

- src/modules/rtpproxy/doc/rtpproxy_faq.xml
Updated FAQ about MSRP support
> src/modules/rtpproxy: Updated FAQ about MSRP support

- src/modules/mqtt/Makefile
- src/modules/mqtt/README
- src/modules/mqtt/doc/Makefile
- src/modules/mqtt/doc/mqtt.xml
- src/modules/mqtt/doc/mqtt_admin.xml
- src/modules/mqtt/mqtt_dispatch.c
- src/modules/mqtt/mqtt_dispatch.h
- src/modules/mqtt/mqtt_mod.c
New Module to participate in a MQTT pub/sub messaging system. 
Initial Features:
- automatic reconnect with connected/disconnected event routes
- support mqtt last will feature
- subscribe and unsubscribe topics via script code
- receive messages via event route
- send messages from script code
- full KEMI support
> mqtt: module to support mqtt pubsub messaging

- src/modules/keepalive/doc/keepalive_admin.xml
- src/modules/keepalive/keepalive_rpc.c
added add/del/get/flush rpc commands
> keepalive: added add/del/get/flush rpc commands

- Makefile
Emacs exposes an environment variable `INSIDE_EMACS` which can be used
to toggle ctags to generate an Emacs-friendly TAGS file.
> Makefile: include flag to generate Emacs-compatible TAGS file

- src/modules/ims_ipsec_pcscf/cmd.c
- src/modules/ims_ipsec_pcscf/doc/ims_ipsec_pcscf_admin.xml
- src/modules/ims_ipsec_pcscf/ims_ipsec_pcscf_mod.c
- added a new config param - ipsec_reuse_server_port - reuse or not
PCSCF server port for UA Re-registration.
- added description for the new parameter in ims_ipsec_pcscf_admin.xml.
parameter ipsec_reuse_server_port.
- in ipsec_forward() add supported and require secagree headers only
for Register reply with code 200.
- in fill_contact() for Request messages set received host, port and
proto from request uri if alias is presented.
> ims_ipsec_pcscf: new config param for ipsec

- src/modules/ims_registrar_scscf/registrar_notify.c
- Added more accurate contact comparison when
sending NOTIFY to a subscriber.
> ims_reqistrar_scscf: Fix bug with multi-notifications

- src/modules/rtpengine/rtpengine.h
These two variables  were copied directly from rtpproxy module but never used by
this module.
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
> rtpengine: Remove unused struct fields

- src/modules/ims_qos/ims_qos_mod.c
- Rx AAR for Terminating direction get identity
from request message if dialog is missing.
> ims_qos: Rx AAR get identity from request for MT

- src/modules/rtjson/doc/rtjson_admin.xml
> update example using IP address reserved for documentation

- utils/pdbt/common.c
Related to 3c07e2351a94e4ff2cf3c6b9b9df4d7462cd5760 commit, but on server side.
Add a message check for pdb server. Related to commit: 3c07e23
> pdbt: add pdb server message check

- src/modules/auth_db/auth_db_mod.c
- src/modules/auth_db/authorize.c
- src/modules/auth_db/authorize.h
- src/modules/auth_db/doc/auth_db_admin.xml
In order to fetch user DB attributes even when user authentication
failed. Default behavior unchanged.
Related to discussion: https://lists.kamailio.org/pipermail/sr-dev/2020-March/055912.html
> auth_db: add force_generate_avps parameter

- src/modules/dialog/dlg_handlers.c
If dialog was deleted while running the event route, update statistics
for early and active dialogs.
Please let me know if I can backport it to 5.3
> dialog: update event route statistics

- src/modules/siptrace/siptrace.c
> siptrace: log correct dialog event

- src/modules/p_usrloc/config.c
- src/modules/p_usrloc/config.h
- src/modules/p_usrloc/doc/p_usrloc_admin.xml
- src/modules/p_usrloc/p_usrloc_mod.c
- src/modules/p_usrloc/p_usrloc_mod.h
- src/modules/p_usrloc/urecord.c
> p_usrloc: add matching_mode modparam

- src/modules/sipcapture/doc/sipcapture_admin.xml
- src/modules/sipcapture/hep.c
- src/modules/sipcapture/sipcapture.c
> sipcapture: fix spelling errors

- src/modules/pv_headers/pvh_func.c
> pv_headers: state header, which could not be split

- src/modules/sipcapture/doc/sipcapture_admin.xml
- src/modules/sipcapture/sipcapture.c
Enable the parsing of broken SIP messages.
@lbalaceanu is the original developer of this patch.
> sipcapture: add new capture_bad_msgs modparam

- src/core/strutils.c
- src/core/strutils.h
- moved from modules/pv/pv_trans.c and exported, so they can be used in other modules
- genericized fn names
> core: strutils - add urlencode and urldecode functions

- src/modules/tls/tls_select.c
- new PVs: $tls_peer_escaped_cert, $tls_my_escaped_cert
- new selects: @tls.peer.escaped_cert, @tls.my.escaped_cert
> tls: add support for escaped cert PVs and select

- src/modules/tls/doc/params.xml
- params.xml: replace "private" with "private_key"
> tls: fix typo in documentation

- src/modules/pv/pv.c
Needs  #2284
Add functions:
__pvx.xavp_get_keys__(_rname_, _idx_): get an array with the keys used in `$xavp(rname[idx])`
__pvx.xavp_getd__(_rname_): get a dictionary with `$xavp(rname)` content
__pvx.xavp_getd_p1__(_rname_, _idx_): get a dictionary with the `$xavp(rname[idx])` content
> pv: add xavp KEMI functions

- src/modules/ims_registrar_scscf/cxdx_callbacks.c
- src/modules/ims_registrar_scscf/reg_rpc.c
- src/modules/ims_registrar_scscf/registrar_notify.c
- src/modules/ims_registrar_scscf/registrar_notify.h
- src/modules/ims_registrar_scscf/save.c
- pass event type as parameter in notify_subscribers()
> ims_registrar_scscf: pass event type as parameter

- src/modules/ims_usrloc_scscf/impurecord.c
- src/modules/ims_usrloc_scscf/subscribe.c
- src/modules/ims_usrloc_scscf/udomain.c
> ims_usrloc_scscf: extend and fix log messages

- src/modules/keepalive/keepalive_rpc.c
Expose current state of keepalive monitor in rpc response so that the response can be parsed easlily and used to populate external dashboards
> keepalive: update rpc response to include current state

- src/core/str_hash.h
Add str_hash_case_get() and str_hash_case_set() functions
> core: add case functions for str_hash get and set

- src/modules/kazoo/doc/kazoo_admin.xml
- src/modules/kazoo/kazoo.c
- src/modules/kazoo/kz_amqp.c
- src/modules/kazoo/kz_amqp.h
- [*] New feature (non-breaking change which adds new functionality)
- [*] Tested changes locally
Added kemi support for
Parameter:
- event_callback
Functions:
- kazoo_subscribe(json_description)  
- kazoo_publish
Documentation:
- added section for event_callback parameter
> Kazoo: added basic kemi support

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatcher.c
Fixed attrs parameters handling i rpc 'add' command.
> dispatcher: rework attrs parameter in rpc 'add' command

- .lgtm.yml
- src/modules/cnxcc/cnxcc.c
- src/modules/cnxcc/cnxcc.h
- src/modules/cnxcc/cnxcc_mod.c
- src/modules/cnxcc/cnxcc_mod.h
- src/modules/cnxcc/cnxcc_redis.c
- src/modules/cnxcc/cnxcc_rpc.c
- src/modules/cnxcc/cnxcc_rpc.h
- src/modules/cnxcc/cnxcc_select.c
- src/modules/cnxcc/cnxcc_select.h
- src/modules/cnxcc/cnxcc_sip_msg_faker.c
- src/modules/cnxcc/cnxcc_sip_msg_faker.h
* use [PKG|SHM]_MEM_ERROR
* use memset and avoid initialization per field
* init variables
* add cnxcc to lgtm build
* use localtime_r() for a safer multi-thread usage
* replaced deprecated STR_PARAM with PARAM_STR
* clean includes
* clang-format
> cnxcc: minor changes

- src/modules/cnxcc/cnxcc_mod.c
* non confirmed calls can't be terminated via dialog.terminate_dlg() API
* set call.max_amount to 0 to terminate the call if gets confirmed
> cnxcc: don't terminate non confirmed calls

- src/modules/keepalive/keepalive_core.c
In keepalive module, logging the new state of the destination only if it changed.
> keepalive: logging state of dest just if changed

- src/modules/dispatcher/dispatch.c
When adding/removing a destination from a set, the load is currently non preserved, which leads to unbalanced load.
This PR addresses the issue without affecting the behavior when loading/reloading the whole list.
> dispatcher: keep current destinations' load when adding/removing

- src/modules/sqlops/sqlops.c
> sqlops: export sql_pvquery to KEMI

- src/modules/avpops/avpops.c
> avpops: export functions to KEMI

- src/modules/registrar/sip_msg.c
expires_range should not make expires smaller than min_expires.
A valid value might be made to small, which triggers 423 when min_expires_mode is set to 1
> registrar: expires_range should not make expires < min_expires

- src/modules/keepalive/keepalive_mod.c
Managing the config value as a string (`char*`) doesn't change the string size, so the value is cut off to the default value size (26 chars).
> keepalive: manage the `ping_from` config value as str.

- src/modules/rtp_media_server/Makefile
- src/modules/rtp_media_server/doc/rtp_media_server_admin.xml
- src/modules/rtp_media_server/docker/Dockerfile
- src/modules/rtp_media_server/docker/build.sh
- src/modules/rtp_media_server/docker/entry.sh
- src/modules/rtp_media_server/docker/rtp_media_server.sh
Updated documentation to simplify usage using docker
> rtp_media_server: update to mediastreamer 4.4.0

- src/modules/xhttp_prom/doc/xhttp_prom_admin.xml
> xhttp_prom: fixed typo in the documentation

- src/modules/tm/tm_load.h
Removed not used variable "route_mode" in the tm module. This was discovered by @IvanRibakov when using a g++ compiler, which added more strict flags (Ivan's Github is [here](https://github.com/IvanRibakov))
> tm - remove not used route_mode var

- src/modules/pua/send_publish.c
* dialog PUBLISH was missing SIP-If-Mach
* pua was inserting a new record for every dialog state
> pua: fix send_publish() behavior on PUA_DB_ONLY

- src/modules/xhttp_prom/doc/xhttp_prom_admin.xml
- src/modules/xhttp_prom/prom.c
- src/modules/xhttp_prom/prom.h
- src/modules/xhttp_prom/prom_metric.c
- src/modules/xhttp_prom/prom_metric.h
- src/modules/xhttp_prom/xhttp_prom.c
- src/modules/xhttp_prom/xhttp_prom.h
Histogram metric and minor issues.
> xhttp_prom: add support for histogram metrics.

- src/modules/ims_ipsec_pcscf/cmd.c
- src/modules/ims_ipsec_pcscf/doc/ims_ipsec_pcscf_admin.xml
- src/modules/ims_qos/cdpeventprocessor.c
- src/modules/ims_qos/ims_qos_mod.c
- src/modules/ims_qos/rx_aar.c
- src/modules/ims_registrar_pcscf/notify.c
- src/modules/ims_registrar_pcscf/save.c
- src/modules/ims_registrar_pcscf/service_routes.c
- src/modules/ims_usrloc_pcscf/udomain.c
- src/modules/ims_usrloc_pcscf/udomain.h
- src/modules/ims_usrloc_pcscf/usrloc.h
> Extend get pcontact

- src/modules/pipelimit/doc/pipelimit_admin.xml
> pipelimit: docs - fixed typo

- src/Makefile.defs
Small portability fixes (FreeBSD)
> Makefile.defs: Fixed libs option for FreeBSD

- src/modules/uac/doc/uac_admin.xml
- src/modules/uac/uac.c
- src/modules/uac/uac_send.c
> uac: added uac_event_callback for kemi

- src/modules/registrar/doc/registrar_admin.xml
Minor doc changes to Registrar module as described in Issue #2477
> Issue 2477 - Minor doc changes to Registrar module

- src/modules/keepalive/keepalive.h
- src/modules/keepalive/keepalive_api.c
- src/modules/keepalive/keepalive_core.c
> Keepalive - Remove race condition when removing destination

- src/modules/dispatcher/dispatch.c
break large function
This large function `ds_manage_routes` is quite large and the intent of every code block is becoming hard to read and assess.
In order to avoid mixing refactoring with behavioral modifications I thought it was best to make a separate MR.
> dispatcher: ds_manage_routes refactoring

- src/modules/crypto/crypto_mod.c
- src/modules/crypto/doc/crypto_admin.xml
- [*] New feature (non-breaking change which adds new functionality)
- [*] Tested changes locally
This PR adds crypto_hmac_sha256() function that can be used for JWT (JSON Web Token)  authentication.
> crypto: add crypto_hmac_sha256() function

- src/core/ut.h
As discussed in #2512, zero-terminating all copies is preferred as most str
usage is already with zero-terminated str.s.
> core: Zero terminate str copies made with (pkg|shm)_str_dup()

- src/modules/mqueue/doc/mqueue_admin.xml
- src/modules/mqueue/mqueue_api.c
- src/modules/mqueue/mqueue_api.h
- src/modules/mqueue/mqueue_mod.c
- Add RPC to fetch all queue sizes at once (mqueue.sizes)
- Proper HTTP response for client errors (4xx instead of 500)
> mqueue: RPC features

- src/core/str.h
> core: Document that a str can be zero-terminated

- utils/pdbt/pdbt.c
pdbt created files with permissions 0700, it is changed to 0644
> utils/pdbt: Relax permissions when creating files

- src/modules/janssonrpcc/janssonrpc_funcs.c
> janssonrpcc: cleanups

- src/modules/tmx/t_var.c
Allow $T_branch(flags) in onreply_route
> tmx: Allow $T_branch(flags) in onreply_route

- src/modules/tm/t_reply.c
Instead of passing the to be evaluated reply as the "best" reply, pass the
actual "best" reply.
> tm: Fix faked_reply_prio by passing correct reply to get_prio

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/doc/dispatcher_admin.xml
- decouple latency update with congestion control further
- decouple congestion control with weighted congestion control and make
sure that miss-configurations (no positive weight and/or no cc attributes) are handled
gracefully)
- fix an error in the doc
- this will let us use the congestion control attribute when no weight is set (to de-prioritize in algo 13) as well as handling miss configuration problem and make modification easier in the future due to better code clarity.
> dispatcher: congestion control refactoring

- src/modules/rtp_media_server/rms_dialog_info.c
- src/modules/rtp_media_server/rms_dialog_info.h
- src/modules/rtp_media_server/rtp_media_server.c
- src/modules/rtp_media_server/rtp_media_server.h
> rtp_media_server: fix dialog_list_mutex

- src/modules/rtp_media_server/rms_dialog_info.c
- src/modules/rtp_media_server/rms_dialog_info.h
- src/modules/rtp_media_server/rtp_media_server.c
- Bridge disconnection was over complicated, to simplify things both legs will automatically be disconnected for now.
- The "state machine" is only a POC at this point, I made sure it was easy to pinpoint problems.
> rtp_media_server: state transition improvement

- src/modules/kex/core_stats.c
#1762 ## Pre-Submission Checklist
Fix invalid JSON returned by stats.fetch with multiple modules as parameter.
Cleanup by reducing code duplication.
> kex: fix and cleanup stats rpc

- src/core/dns_cache.c
@sem32 , maybe you can help to review this fix ?
> core: DNS stop resolving NAPTR for IP addresses

- src/core/msg_translator.c
- added a missing field in sip_msg_update_buffer()
when restoring message fiedls: msg->pid.
> core: added missing field in sip_msg_update_buffer

- src/modules/jansson/jansson_utils.c
Copy-pasto from before the other fix.
> jansson: Fix another case of inverse boolean logic

- src/modules/smsops/smsops_impl.c
- fixed the calculation for concatenated SMSs
based on TS 23.040, Sec. 9.2.3.16
> smsops: fix len calc for a concatenated sms

- src/modules/tm/tm.c
- [ X] Tested changes locally
tm module: In KEMI let's expose
t_relay_to_tcp
t_relay_to_udp
t_relay_to_tls
to force the transport.
Edit: non-intrusive commit, can go into 5.4 if accepted.
> tm: KEMI expose t_relay_to_xxx protocol functions

- src/modules/lost/functions.c
fixes GH2569. Allow parse examples from RFC7840
> lost: trimed spaces before resolving locationURI value

- src/modules/evapi/evapi_mod.c
Evapi: added KEMI function for evapi_async_multicast
> evapi: export async_multicast() to kemi

- src/modules/textops/api.c
- src/modules/textops/api.h
- src/modules/textops/textops.c
- src/modules/textops/textops.h
Functions added:
- `set_body`
- `set_body_multipart`
- `append_body_part`
> textops: added functions to manipulate the body in the exported api

- src/modules/siptrace/siptrace.c
Commit fa7eb2a switched the 2 parameter version of sip_trace from
using the builtin fixup_spve_spve to the custom fixup method to
using the custom fixup_siptrace. As it is a custom fixup method,
the corresponding free method can not be auto-detected causing the
config parser to require the parameters to be a constant.  This
patch adds a free method, allowing variables to be once again passed
as the 2nd parameter of this method (as well as fixing a memory leak
for the 3rd parameter).
> modules/siptrace: fix regression preventing variables to be used

- src/modules/rtpengine/rtpengine.c
Retry build_rtpp_socks() if any DNS or create, bind, connect
issues happened when kamailio started, and at least one node
from list was skipped.
This retry will happen automatically, when select_rtpp_node() is called
and will avoid a need for a "kamcmd rtpengine.reload"
Described above.
> rtpengine: rebuild sockets if any skipped nodes

- src/modules/ims_diameter_server/ims_diameter_server.c
> ims_diameter_server: fix errors

- src/modules/uac_redirect/doc/uac_redirect_admin.xml
- src/modules/uac_redirect/rd_funcs.c
- src/modules/uac_redirect/uac_redirect.c
The old, quite arbitrary, default of 0.01 is preserved.
> uac_redirect: Make default q-value configurable

- src/modules/lrkproxy/lrkproxy.c
Reverts kamailio/kamailio#2666
Too many changes pushed, it requires time to review first.
> Revert "lrkproxy-fixed issue#2663"

- etc/kamailio.cfg
* default behavior of rtpengine is trust-address
* use SIP-source-address for nat_uac_test("8")
> etc: kamailio.cfg- use SIP-source-address

- src/modules/smsops/smsops_impl.c
- Validity period is present only for SUBMIT
msg type and it is an optional parameter.
For now supports only Relative VP format.
> smsops: fix parsing of validity period

- src/modules/siputils/contact_ops.c
> siputils: fix undefined symbol ruri_mark_new

- src/modules/stirshaken/doc/stirshaken_admin.xml
- src/modules/stirshaken/stirshaken_mod.c
Now random uuid is generated for empty origid, as stated in documentaion.
> stirshaken: handle empty origid, enhance docs

- src/modules/app_lua/app_lua_api.c
- Calling function KSR.secsipid.secsipid_add_identity() has six parameters, is giving error 'too many parameters'
> app_lua: Fixed error 'too many parameters'

- .github/workflows/main.yml
let's make more visible the problems detected by the compiler
https://github.com/marketplace/actions/gcc-problem-matcher?version=0.1
> github/workflow: add gcc-problem-patcher [skip ci]

- src/modules/smsops/smsops_impl.c
- Added new sms pdu data: originating & destination address flags;
SCTS(DELIVER)/VP(SUBMIT) absolute time format.
- decode_3gpp_sms(): added support for DELIVER type;
Added VP-AbsoluteTimeFormat for SUBMIT type.
- pv_sms_body(): added support for ucs2 coding.
- Extends of pv_get_sms() and pv_set_sms(): added support for
originating & destination address flags.
> smsops: Imrovements in decode_3gpp_sms() and pv_sms_body()

- src/modules/tm/t_reply.c
- src/modules/tm/t_suspend.c
> tm: t_suspend.c - t_continue_helper() - do not continue processing a reply if it's suspended again

- src/modules/sipdump/sipdump_mod.c
fixed `sipdump(src_port)` handling
> sipdump: fixed typo

- src/modules/app_perl/lib/perl/Kamailio.pm
> app_perl change to ignore "die" signals from eval blocks

- src/modules/tm/t_suspend.c
When suspending while already in t_continue when processing a reply / suspending twice in a reply.
Thanks to @giavac  https://github.com/kamailio/kamailio/pull/2721 we can now suspend more then once in a reply route.
This is working well, however a memory leak was detected.
This modification is proposing a solution that will prevent calling `sip_msg_cloner` over an already twice over the same pointer, creating the memory leak.
I assume this is a non "breaking change" since it can only trigger in a very the specific case that was not supported anyway.
Conditions when this alternate behavior can trigger:
1- must be in t_suspend
2- must be in a reply `if (msg->first_line.type == SIP_REPLY) {`
3- must have an already cloned `if …
> tm: prevent t_suspend memory leak

- src/modules/siptrace/siptrace.c
I want to get the source (destination) IP address of the message during `event_route[siptrace:msg]` route.
I added the ability to get socket info in this route block.
Now added
```
$siptrace(src_uri)
$siptrace(dst_uri)
```
This pseudovars return string like
```
udp:8.8.8.8:5060
```
I think `src_uri` and `dst_uri` is not correct here because this socket info, not SIP uri.
I expecting suggestion on how to get these params and from current implementation:
```
src_ip
src_port
src_proto
dst_ip
dst_port
dst_proto
```
As reference, I take `sipdump` pseudovariable
> siptrace: added siptrace pseudo var

- src/modules/siptrace/siptrace.c
Fixed socket addr like `udp:::1:2345`
> siptrace: fixed IPv6 without brackets

- pkg/kamailio/obs/kamailio.spec
For packaging, add support for the RHEL rebuilders: almalinux and rocky.
Reusing the files in pkg/kamailio/centos for both almalinux and rocky — this can
probably be duplicated when CentOS goes away.
> pkg: add support for AlmaLinux and Rocky Linux

- src/modules/siptrace/siptrace.c
added
1. $siptrace(src_addr)
2. $siptrace(src_host)
3. $siptrace(src_port)
4. $siptrace(src_proto)
5. $siptrace(dst_addr)
6. $siptrace(dst_host)
7. $siptrace(dst_port)
8. $siptrace(dst_proto)
> siptrace: added extra params to $siptrace() pseudo-variable

- src/modules/nats/Makefile
- src/modules/nats/doc/Makefile
- src/modules/nats/doc/nats.xml
- src/modules/nats/doc/nats_admin.xml
- src/modules/nats/nats_mod.c
- src/modules/nats/nats_mod.h
New Module to consume messages from NATS messaging system. 
Initial Features:
- automatic reconnect with connected/disconnected event routes
- connect to up to 10 NATS URLs
- subscribe to any number of subjects
- receive messages via event route
> nats: new nats message consumer module

- src/modules/nats/nats_mod.c
…freeing memory
as per @miconda's suggestion, added memory checks
> nats: make sure pkg & shm memory is allocated; check pointers before freeing memory

- src/modules/db_redis/redis_connection.c
> db_redis: fix broken pipe issue, if redis server with timeout setting.

- src/modules/outbound/outbound_mod.c
explicit types cast to fix compiler warning:
https://lists.kamailio.org/pipermail/sr-dev/2021-August/063482.html
> outbound: fix compiler warning on SHA1() call

- misc/fuzz/fuzz_parse_msg.c
Following up on earlier work on fuzzing https://github.com/kamailio/kamailio/pull/2660 I wanted to add another fuzzer as there is still a lot more code to analyse. This fuzzer targets various parsing routines and is meant to run in the oss-fuzz infrastructure.
> misc: fuzz: add msg parse fuzzer

- src/modules/textops/textops.c
commit cbcc27ef8b1674448bd8b1c45f03388e36f65f51 broke RFC2543 hold
there's no need to check for sendrecv_mode, is_on_hold is either set or not in sdp_stream and/or sdp_session
removed the check for `sendrecv_mode`
> textops: RFC2543 is broken

- src/modules/sipt/doc/sipt_admin.xml
- src/modules/sipt/sipt.c
- src/modules/sipt/ss7.h
- src/modules/sipt/ss7_parser.c
- sipt_has_isup_body()
- $sipt(redirection_information.reason)
- $sipt(redirection_information.original_reason)
- $sipt(redirecting_number.nai)
- $sipt(redirecting_number)
- $sipt(original_called_number.nai)
- $sipt(original_called_number)
- $sipt(generic_number.nai)
- $sipt(generic_number)
> sipt: added one function and 8 pseudo-variables

- src/modules/ims_charging/ims_charging_mod.c
- src/modules/ims_charging/ims_ro.c
- src/modules/ims_charging/ims_ro.h
This patch fixes route callback for ccr responses when using kemi as configuration engine.
> ims_charging: fix charging reply route with kemi

- misc/fuzz/fuzz_parse_msg.c
Extends the msg parsing fuzzer to reach some of the parsing routines we currently miss.
> misc: fuzz: extend msg parsing fuzzer

- src/modules/registrar/doc/registrar_admin.xml
* fix docs for expires/q attributes
* add all available attributes and note in which function they are used
> registrar: docs for xavp_cfg

- src/modules/kazoo/doc/kazoo_admin.xml
Fixed json example and space formating
> kazoo: fixed json example and space formating

- src/modules/ims_registrar_pcscf/ims_registrar_pcscf_mod.c
PROC_SIPINIT has a special meaning representing the first SIP worker. 
> Correcting rank value passed to fork_process #2809

- src/modules/ims_registrar_scscf/doc/ims_registrar_scscf_admin.xml
- src/modules/ims_registrar_scscf/ims_registrar_scscf_mod.c
- src/modules/ims_registrar_scscf/save.c
- src/modules/ims_registrar_scscf/save.h
Add a new flag as optional parameter for save() method.
The flag contains one value: DO_NOT_USE_REALM_FOR_PRIVATE_IDENTITY
0x01. No changes save() when parameter is not present.
> ims_registrar_scscf: Extend save() with optional flag

- src/core/cfg.lex
- src/core/cfg.y
- src/core/cfg_core.c
- src/core/cfg_core.h
- src/core/parser/msg_parser.c
- src/core/parser/msg_parser.h
- src/core/parser/parse_via.c
If this param is enabled, will log SIP headers with comma instead of \r\n, when some error happens. Default is disabled.
> core: add new param sip_parser_oneline

- src/modules/acc/acc.c
- src/modules/acc/acc.h
- src/modules/acc/acc_cdr.c
- src/modules/acc/acc_cdr.h
- src/modules/acc/acc_extra.c
- src/modules/acc/acc_extra.h
- src/modules/acc/acc_mod.c
- src/modules/acc/doc/acc_admin.xml
Hello. I want to ask if increasing this #define(s) are feasible to commit upstream? We've come to the case where need at least +16 more for acc module and at least +8 more for core branches. Not sure if other people would need this.
1. If yes, let me know if i should split it in 2 commits, one for core and one for acc module
2. If no, please close this PR
Thank you,
Stefan
> acc: increase extra and cdr variables

- src/Makefile.defs
Increase largest major version of GCC detected to 11 from 10.
> build: detect GCC 11

- src/modules/permissions/doc/permissions_admin.xml
- src/modules/permissions/permissions.c
- src/modules/permissions/permissions.h
- src/modules/permissions/trusted.c
> permissions: fix crash during RPC trusted reload

- src/modules/ims_usrloc_pcscf/usrloc_db.c
- utils/kamctl/mysql/ims_usrloc_pcscf-create.sql
- [*] Small bug fix (non-breaking change which fixes an issue)
- [*] Tested changes locally
Protocol information of pcontact was not written to mysql database
> ims_usrloc_pcscf:  fix on saving protocol info into DB

- misc/examples/ims/pcscf/route/register.cfg
- Updated ims pcscf register script file
with removing of ck/ik in 401 Challenge reply.
> misc: update ims pcscf register example

- src/modules/presence/doc/presence_admin.xml
- src/modules/presence/presence.c
See https://github.com/kamailio/kamailio/pull/2930#issuecomment-971748854.
> presence: return 200 instead of 202 by default

- src/modules/pv/pv_core.c
As suggested in previous PR (#2936).
This is much more flexible as it can also handle sub XAVPs, and indexes.
This ended up being more complicated than I anticipated, but I wanted to handle all possible cases.
The tests I performed are detailled after, they should cover every possible use case.
Allows counting XAVPs with `$cnt($xavp(...))`
In addition to the `$cnt($avp(...))` - which is not modified.
/* Usage:
*
* $cnt($xavp(key[*])) : number of XAVPs "key".
* $cnt($xavp(key[n]=>sub[*])) : number of children "sub" in XAVP "key[n]".
* $cnt($xavp(key[*]=>sub[*])) : total number of children "sub" in all XAVPs "key".
*
* $cnt($xavp(key[n])) : 1 or 0 (if this index exists or not).
* $cnt($xavp(key[-n])) : same but with reverse indexing (-1 is the last index).
*
* $cnt($xavp(key[*]=>sub[n])) : …
> pv: extend $cnt to work with $xavp

- src/modules/db_redis/redis_dbase.c
- Execute db_redis_consume_replies on failed update same as in db_redis_insert:
if db_redis_perform_update encounters an error it was leaving unconsumed data
thus causing unexpected reply later on when reading from the same connection.
> db_redis: don't leave unconsumed redis replies in case of error

- src/modules/auth_ephemeral/authorize.c
- sha256/384/512 broken due to use of sha1 password length, change to check and use proper lengths for each
- sha384 mistakenly using sha256 method
- update logging to include length
> auth_ephemeral: fix sha256/384/512

- src/modules/websocket/websocket.c
KEEPALIVE_MECHANISM_CONCHECK was added but can't be enabled
add case for KEEPALIVE_MECHANISM_CONCHECK in mod_init validation of ws_keepalive_mechanism
> websockets: enable KEEPALIVE_MECHANISM_CONCHECK

- src/modules/ims_usrloc_scscf/doc/ims_usrloc_scscf_admin.xml
- src/modules/ims_usrloc_scscf/ims_usrloc_scscf_mod.c
- src/modules/ims_usrloc_scscf/udomain.c
Capability to skip realm in NOTIFY's Message body reginfo tag.
Added realm(string) and skip_realm(int) parameters.
> ims_usrloc_scscf: Add capability to skip a specific realm

- src/modules/dialog/dialog.c
> dialog: fix missing else

- src/modules/jwt/doc/jwt_admin.xml
- src/modules/jwt/jwt_mod.c
Adding an optional forth parameter to jwt module to add headers.
> jwt: possibility to add headers when generating jwt

- src/modules/nats/defs.h
- src/modules/nats/doc/nats_admin.xml
- src/modules/nats/nats_mod.c
- src/modules/nats/nats_mod.h
- src/modules/nats/nats_pub.c
- src/modules/nats/nats_pub.h
Adds Publish function to NATS module.
> NATS: add new function `nats_publish()`

- src/modules/dialog/dialog.c
- src/modules/dialog/doc/dialog_admin.xml
> add filtering based on start timestamp to dlg.list_match

- src/modules/db_redis/Makefile
- src/modules/db_redis/doc/db_redis_admin.xml
- src/modules/db_redis/redis_connection.c
- src/modules/db_redis/redis_connection.h
- src/modules/db_redis/redis_dbase.c
Add support for redis cluster protocol via hiredis-cluster library to db_redis module
> Db redis cluster support

- src/modules/ims_charging/ims_ro.c
- src/modules/kazoo/kz_amqp.c
- src/modules/sms/sms_funcs.c
fixed misleading-indentation warning
> fixed misleading-indentation warning

- src/modules/presence/presence.c
- src/modules/rls/rls.c
fixed format-truncation warning
> fixed format-truncation warning

- src/modules/db_postgres/db_postgres.c
- src/modules/db_postgres/km_dbase.c
- src/modules/db_postgres/km_dbase.h
This PR add support for async queries to db_postgres module. Implementation is the same as the mysql and unixodbx modules.
> db_postgres: added support for async queries

- src/modules/nathelper/nathelper.c
The IP checksum is part of the header and must be zeroed before checksumming.
This patch also silences another (benign) warning.
> nathelper: uninitialized data

- pkg/kamailio/deb/bionic/rules
- pkg/kamailio/deb/bullseye/rules
- pkg/kamailio/deb/buster/rules
- pkg/kamailio/deb/focal/rules
- pkg/kamailio/deb/jessie/rules
- pkg/kamailio/deb/stretch/rules
- pkg/kamailio/deb/trusty/rules
- pkg/kamailio/deb/xenial/rules
fixes the deleted space after "erlang"
introduced by a593f518dd62fd68c330eb42470ce5d5e1dce636
> pkg::deb: Missing spaces

- src/modules/topos_redis/topos_redis_storage.c
- [ x] Small bug fix (non-breaking change which fixes an issue)
topos_redis: contact on A side is never updated on dialog update
> topos_redis: contact on A side is never updated on dialog update

- src/modules/p_usrloc/doc/p_usrloc_admin.xml
- src/modules/p_usrloc/p_usrloc_mod.c
- src/modules/p_usrloc/p_usrloc_mod.h
- src/modules/p_usrloc/ucontact.c
- src/modules/p_usrloc/udomain.c
Enable UTC time format for expires and last_modified columns.
> p_usrloc: add UTC_timestamps parameter

- src/modules/smsops/smsops_impl.c
> smsops: Fix ucs2-to-utf8 for Accent chars

- src/modules/siptrace/siptrace.c
siptrace: add X-Siptrace headers when configured core callback mode and SIP URI traffic mirroring
- Added X-Siptrace headers in core callback mode for SIP URI traffic duplication,
headers also available in event route for filtering purporses.
> siptrace: add X-Siptrace headers when configured core callback mode and SIP URI traffic mirroring

- src/modules/ims_ipsec_pcscf/cmd.c
- src/modules/ims_ipsec_pcscf/ipsec.c
> ims_ipsec_pcscf: fix sha1 algorithm and tcp connections for SIP Replies over TCP

- src/modules/ims_registrar_scscf/userdata_parser.c
Fix issues where a non-zero terminated string would get passed to `parse_user_data`.
> ims_registrar_scscf: use xmlParseMemory instead of xmlParseDoc

- src/modules/ims_registrar_scscf/registrar_notify.c
- src/modules/ims_registrar_scscf/registrar_notify.h
Add the `deregistered` state to IMS_Registrar_events_enum_t, allowing the
registrar to distinguish between UE unregsitration, which do not require
a notification to be sent, and network-originated deregistration requests.
> ims_registrar_scscf: add a new contact state for notifications

- utils/kamcmd/kamcmd.c
> utils: fixed sinitiser error

- src/modules/siptrace/siptrace.c
- Add direction attribute to event route siptrace pseudo-variable.
> siptrace: add direction attribute to exported by module pseudo-variable

- src/modules/ims_qos/doc/ims_qos_admin.xml
- src/modules/ims_qos/ims_qos_mod.c
- src/modules/ims_qos/rx_aar.c
- src/modules/ims_qos/rx_avp.c
- Added new parameters: af_signaling_ip6, component_media_type,
flow_protocol, omit_flow_ports, rs_default_bandwidth,
rr_default_bandwidth. Check doc for details.
> ims_qos: Added new parameters for AAR,AVP517

- src/modules/uac/uac_send.c
Setup: uac_req_send() with evroute=2 and tm module enable_uac_fr=1
Noticed following shm errors while intensively testing uac_req_send(), happening quite soon after a fresh restart (e.g. 10 min):
```
kamailio[5384]: ERROR: <core> [core/mem/q_malloc.c:297]: qm_find_free(): qm_find_free(0x7fe8943bc000, 40632); Free fragment not found!
kamailio[5384]: ERROR: <core> [core/mem/q_malloc.c:430]: qm_malloc(): qm_malloc(0x7fe8943bc000, 40632) called from uac: uac_send.c: uac_send_info_clone(105), module: uac; Free fragment not found!
kamailio[5384]: ERROR: uac [uac_send.c:108]: uac_send_info_clone(): no more shm memory
kamailio[5384]: ERROR: uac [uac_send.c:837]: uac_req_send(): cannot clone the uac structure
```
I tried monitoring system …
> uac: fix shm leak

- src/modules/mqueue/doc/mqueue_admin.xml
- src/modules/mqueue/mqueue_api.c
- src/modules/mqueue/mqueue_api.h
- src/modules/mqueue/mqueue_mod.c
Add a mqueue parameter to control the mq_add() mode. 
0 - default, no changes in behavior
1 - add unique keys, keep oldest
2 - add unique keys, keep newest
> mqueue: add mqueue_mode modparam

- src/modules/p_usrloc/config.c
- src/modules/p_usrloc/config.h
- src/modules/p_usrloc/p_usrloc_mod.c
- src/modules/p_usrloc/p_usrloc_mod.h
> p_usrloc: make UTC param runtime configurable

- src/core/str.h
- src/core/ut.c
- src/core/ut.h
- src/modules/auth/doc/auth.xml
- src/modules/pua_dialoginfo/pua_dialoginfo.c
> Typos docs

- src/modules/xhttp/xhttp_mod.c
> xhttp: fix typo

- src/modules/sanity/doc/sanity_admin.xml
- src/modules/sanity/sanity.c
- src/modules/sanity/sanity.h
- src/modules/sanity/sanity_mod.c
- src/modules/sanity/sanity_mod.h
* Remove redundant str_list implementation.
* Improve docs
* use str_list implementation from core
* typo fixes, doc improvements
> sanity: Use str_list implementation from core

- src/modules/pua_dialoginfo/pua_dialoginfo.c
Determine dialog event types for dialog callback on module
initialization, since these will not change.
> pua_dialoginfo: Determine dialog event types in mod_init

- src/modules/userblocklist/doc/userblocklist_admin.xml
- src/modules/userblocklist/userblocklist.c
Ported mi functions to RPC. Note that in order to send long number strings (e.g. username) from kamcmd one must prefix it with "s:"
> userblocklist: add RPC functions

- src/modules/dialog/dialog.c
- src/modules/dialog/doc/dialog_admin.xml
Add functions to get and set a dlg_var from outside that dialog using call-ID, from-tag and to-tag to select the desired one
> dialog: dlg_get_var() and dlg_set_var()

- src/core/ip_addr.h
benign const qualifiers in inline functions
> core: const correctness

- pkg/kamailio/obs/kamailio.spec
On EL8 package with Python 3.9; that is EoL in 2025; Python 3.6 was EoL end 2021.
Python 3.9 lifecycle matches the remaining Full Support cycle of EL8.
Although 5.6 packages were released with Python 3.6; this PR could be backported to 5.6 as 5.6 still has a lot of runway.
> packaging: on EL8 package with Python 3.9

- src/core/ppcfg.c
> ppcfg: add values to log to better tell the problem

- src/modules/presence/publish.c
previously if an error was found we were bailing out and the value
was kept so at next round the value will be there and no more values
where removed
> presence: be more resilient doing clean up of presentity values

- src/modules/uac/doc/uac_admin.xml
- src/modules/uac/uac_reg.c
> uac.reg_add realm and socket support for RPC command

- src/modules/secfilter/doc/secfilter_admin.xml
- src/modules/secfilter/secfilter_rpc.c
> secfilter: machine-parsable data structure for RPC printing data

- src/core/tcp_conn.h
- src/core/tcp_main.c
- src/modules/tls/tls_rpc.c
> tls: add timestamp and sni info for a session

- src/modules/app_python3/python_msgobj.c
`PyErr_SetString` is a void function. It doesn't return NULL.
> python3: `PyErr_SetString` is a void function. It doesn't return NULL.

- src/modules/dialplan/dialplan.c
- src/modules/ratelimit/ratelimit.c
- src/modules/siputils/siputils.c
Exported some functions to kemi. Currently testing.
> some kemi function exports 

- src/modules/dialplan/dialplan.c
> dialplan: Fix typos

- src/modules/secfilter/secfilter.c
- [x ] Related to issue #3263 (replace XXXX with an open issue number)
Locks have been added to several functions to prevent data from changing while they are being queried.
> secfilter: added locks while check list values

- src/modules/stirshaken/stirshaken_mod.c
stirshaken: Properly handle intermediary/chain certificates when caching certificates
- requires patch to libstirshaken (https://github.com/signalwire/libstirshaken/pull/124) to do anything
- if patched version of libstirshaken detected, uses new methods to store all intermediary certs
- unrelated minor logging tweaks
The guts of this PR have been submitted to the libstirshaken side based on the suggestions of my previous PR.  I didn't mean to close it but since I hadn't created a branch, it got closed when I updated my repo.  Original PR is https://github.com/kamailio/kamailio/pull/3175
I've been running this in production for a day and it seems to be performing the same as my previous attempt.
> stirshaken: Properly handle intermediary/chain certificates when caching certificates

- src/modules/app_lua/doc/app_lua_admin.xml
since commits 2e85bb541ff19e4b007 and 673dab16593d9a70b .
> app_lua: Document that Lua versions 5.2, 5.3 and 5.4 can also be used.

- src/modules/cdp/acceptor.c
- src/modules/cdp/config.h
- src/modules/cdp/configexample/ConfigExample.xml
- src/modules/cdp/configparser.c
- src/modules/cdp/peer.c
- src/modules/cdp/peer.h
- src/modules/cdp/peermanager.c
- src/modules/cdp/receiver.c
- src/modules/cdp/tcp_accept.c
- src/modules/cdp/tcp_accept.h
Added SCTP support for CDP module
> cdp: Add SCTP support

- src/modules/dmq_usrloc/doc/dmq_usrloc_admin.xml
- src/modules/dmq_usrloc/usrloc_sync.c
- src/modules/dmq_usrloc/usrloc_sync.h
Allow replicating location's socket via its name.
> dmq_usrloc: Add option to replicate socket via its name

- src/modules/htable/doc/htable_admin.xml
Commands for get/set described in documentation are not working giving 500 errors in a case if key value is integer value. If attach s: to key name it all work as expected (as was advised in [the mailing list](https://www.mail-archive.com/sr-users@lists.kamailio.org/msg16436.html) by Fred Posner)
> doc/htable: adding examples in a case of key value is an integer

- src/modules/nats/doc/nats_admin.xml
- src/modules/nats/nats_mod.c
- src/modules/nats/nats_mod.h
- src/modules/nats/nats_pub.c
- src/modules/nats/nats_pub.h
I added `nats_publish_request` which calls the `natsConnection_PublishRequestString` to send a request to the NATS server with a `reply` string so the response can be easily replied back.
I tested in Lua and the native route, not sure if it's the right way to implement. I can update docs if it sounds good.
Thanks.
> nats: add a reply param to nats_publish and expose as nats_publish_request in KEMI

- src/modules/rtpengine/doc/rtpengine_admin.xml
See http://lists.sipwise.com/pipermail/spce-user_lists.sipwise.com/2023-April/030012.html and https://github.com/sipwise/rtpengine/issues/1595#issuecomment-1382378886 .
> rtpengine clarifications

- .github/workflows/alpine.yml
Created GitHub action script to allow build Alpine docker image and push to GitHub packages as `kamailio/kamailio-ci` docker image
> .github/workflows: added GitHub action script to build Alpine docker

- src/modules/siptrace/siptrace.c
Enhancements to siptrace module to allow HEP replication of custom sip message given as parameter.
> siptrace - custom sip message hep replication

- src/modules/tls/doc/rpc.xml
- src/modules/tls/tls_rpc.c
Kill a TLS session by moving the TCP connectin to -2 state. Note that it may take few seconds for session to be killed.
> tls: Add rpc function to kill session by id

- src/modules/p_usrloc/doc/p_usrloc_admin.xml
- src/modules/p_usrloc/p_usrloc_mod.c
- src/modules/p_usrloc/p_usrloc_mod.h
- src/modules/p_usrloc/ul_db_handle.c
Needed a way to use_domain but calculate crc32 for user part only.
> p_usrloc: Add use_domain_crc32 modparam

- src/modules/tls/doc/params.xml
Update TLS module documentation in regards of deprecation of TLS v1.0 and v1.1. Existing references updated and new reference added.
No code change!
> tls: update documentation (TLS v1.0 & 1.1 deprecation)

- src/Makefile.defs
… started in commit f92113d8e16d6e59c170dfa703d9db30980b6877.
> src/Makefile.defs: complete removal of VQ_MALLOC memory manager

- src/modules/tls/tls_domain.c
- src/modules/tls/tls_init.c
- src/modules/tls/tls_mod.c
- src/modules/tls/tls_rand.c
- src/modules/tls/tls_rand.h
- src/modules/tls/tls_server.c
investigate changes needed for openssl 3.0
> tls: openssl 3.0 changes

- src/modules/rtpengine/doc/rtpengine.xml
- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
> rtpengine: support receiving events from rtpengine and raise an event

- src/modules/xlog/doc/xlog_admin.xml
The documentation shows a wrong example for the modparam "method_filter".
> xlog: fix docs example for modparam methods_filter

- src/modules/siptrace/siptrace.c
> siptrace: fix pseudo var direction attribute length

- src/modules/geoip2/doc/geoip2_admin.xml
- src/modules/geoip2/geoip2_mod.c
- src/modules/geoip2/geoip2_pv.c
- src/modules/geoip2/geoip2_pv.h
Added distance function which allows to calculate the distance between the geocoordinates of the the IP-address passed as incoming parameter (coordinates for the IP are determined inside the function) and the geocoordinates passed as parameters for the function.
Functions can be used to evaluate the RTPengine server closest to a user.
> geoip2: added distance function

- src/modules/dialog/dlg_hash.c
Make sure dialog cbs list is NULL after is destroyed.
> dialog: set cbs list to NULL after destroying

- src/modules/rtpengine/rtpengine.c
CDR avp() mos values gets trimmed at the first larger mos value received.
> rtpengine: increase buf size to print mos llint range

- src/modules/ctl/ctl.c
> fix warnings detected via codeql

- src/modules/ims_qos/doc/ims_qos_admin.xml
- src/modules/ims_qos/ims_qos_mod.c
Primary goal is to update doc, for Rx_AAR() function, to mention is used only for replies.
I've also changed some LM_DBG to LM_WARN but I can revert that on request (don't want to overflow noone with warnings)
> ims_qos: doc update and warn logs

- pkg/kamailio/deb/bionic/control
- pkg/kamailio/deb/bookworm/control
- pkg/kamailio/deb/bullseye/control
- pkg/kamailio/deb/buster/control
- pkg/kamailio/deb/debian/control
- pkg/kamailio/deb/focal/control
- pkg/kamailio/deb/jammy/control
- pkg/kamailio/deb/jessie/control
- pkg/kamailio/deb/precise/control
- pkg/kamailio/deb/sid/control
- pkg/kamailio/deb/stretch/control
- pkg/kamailio/deb/trusty/control
- pkg/kamailio/deb/wheezy/control
- pkg/kamailio/deb/xenial/control
- src/modules/regex/Makefile
- src/modules/regex/regex_mod.c
> regex: migration to pcre2

- src/modules/smsops/smsops_impl.c
> smsops: fixes as per static code analyzer report

- src/modules/dialplan/Makefile
- src/modules/dialplan/dialplan.c
- src/modules/dialplan/dialplan.h
- src/modules/dialplan/dp_db.c
- src/modules/dialplan/dp_repl.c
> dialplan: pcre2 migration

- src/modules/lcr/Makefile
- src/modules/lcr/hash.c
- src/modules/lcr/hash.h
- src/modules/lcr/lcr_mod.c
- src/modules/lcr/lcr_mod.h
> lcr: pcre2 migration

- src/core/cfg.lex
- src/core/cfg.y
- src/core/globals.h
- src/core/udp_server.c
- src/core/udp_server.h
- src/main.c
> core: Add option for increasing socket send buffer size

- src/modules/ims_dialog/ims_dialog.c
- src/modules/ims_qos/ims_qos_mod.c
some kemi exports for ims_qos and ims_dialog. Currently testing them, will add comment afterwards.
> kemi exports

- src/main.c
> core: Format changes

- src/modules/cdp/Makefile
- src/modules/cdp/cdp_mod.c
- src/modules/cdp/cdp_tls.c
- src/modules/cdp/cdp_tls.h
- src/modules/cdp/doc/cdp_admin.xml
- src/modules/cdp/receiver.c
- src/modules/cdp/receiver.h
Adding TLS capability to connections between Kamailio and configured peers. Configuration done via kamailio.cfg.
> cdp: add TLS capability

- src/modules/acc_json/doc/acc_json_admin.xml
> acc_json: Fix parameter name in docs

- src/modules/smsops/smsops_impl.c
Small adjustment to avoid C99 error from older compiler.
> smsops: avoid c99 error

- src/modules/cdp/cdp_mod.c
- src/modules/cdp/cdp_tls.c
- src/modules/cdp/receiver.c
Disabled parts of code if installed openssl version is older than 1.1.0 based on feedback in issue #3600.
Tested non-TLS connection locally. Not tested with TLS.
> cdp: Disable TLS support for openssl versions older than 1.1.0

- misc/tools/route_graph/README
> tools: route_graph - added README file

- src/modules/ims_dialog/dlg_db_handler.c
- src/modules/ims_dialog/dlg_handlers.c
- src/modules/ims_dialog/dlg_hash.c
- src/modules/ims_dialog/doc/ims_dialog_admin.xml
Added missing code for database backend to work. Tested basic scenarios locally for all db modes.
DB schema could be tweaked according to my thoughts in issue #3602, but that also applies to several other modules which are done in the same matter. Because of that, I didn't consider such a change now.
> ims_dialog: Add support for database backend

- src/modules/app_ruby/app_ruby_mod.c
Just a small change in app_ruby_rpc_reload_doc constant which mistakingly says javascript instead of ruby file.
> app_ruby: Fix rpc documentation typo

- src/modules/ims_dialog/dlg_handlers.c
- src/modules/ims_dialog/dlg_handlers.h
- src/modules/ims_dialog/dlg_load.h
- src/modules/ims_dialog/ims_dialog.c
Add function to get dialog by internal hash entry and id. This is needed by my other ongoing changes to the ims_charging module for restoring records from database.
> ims_dialog: Add function to get dialog by hash entry and id

- src/modules/http_client/doc/http_client_admin.xml
- Inform that the order of the parameters is important when httpcon is loaded first
> http_client: add information about parameter loading

- src/modules/ims_charging/dialog.c
- src/modules/ims_charging/doc/ims_charging_admin.xml
- src/modules/ims_charging/ims_charging_mod.c
- src/modules/ims_charging/ims_ro.c
- src/modules/ims_charging/ro_db_handler.c
- src/modules/ims_charging/ro_db_handler.h
- src/modules/ims_charging/ro_timer.c
- utils/kamctl/mysql/ims_charging-create.sql
- realtime and shutdown mode support
- removed duplicate entry in doc about "ro_auth_expiry"
- RO_TABLE_VERSION constant did not match inserted value in db schema
Fixed the module so it also use information written to database to restore Ro sessions on startup/restart.
> ims_charging: Implemented restore of Ro sessions from database

- src/modules/topos/doc/topos_admin.xml
- src/modules/topos/topos_mod.c
- src/modules/topos/tps_storage.h
Add a database version check and fail gracefully if it does not match.
> topos: Add db version check

- src/modules/cdp/transaction.c
Callback function might do an operation which creates a new transaction, which will result in a deadlock.
Problem in detail described in ticket.
Summary is that the lock used to iterate expired transactions is also needed when creating a new transaction.
If the callback function (directly or indirectly) do something that creates a new transaction, it will result in a deadlock.
In my case, this was the ims_charging module where a start charging request times out. The callback does t_continue() where the routing logic then rejects the call. This will create a stop request to the charging server, and it will block.
> cdp: Avoid deadlock for callback on diameter timeout

- src/modules/kazoo/Makefile
- src/modules/kazoo/kz_amqp.c
- src/modules/kazoo/kz_amqp.h
- src/modules/rabbitmq/Makefile
- src/modules/rabbitmq/rabbitmq.c
- src/modules/rabbitmq/utils.c
fixed rabbitmq-c deprecation warning
> fixed rabbitmq-c deprecation warning

- src/core/tcp_main.c
> core: fixed haproxy protocol parser

- src/modules/smsops/smsops_impl.c
Fixes the conversion fro UTF-8 to UCS-2 conversion when SMS is sent with emojis
> smsops: fix utf8 to ucs2 conversion

- src/modules/cdp/authstatemachine.c
This PR fixes duplicate "Destination-Realm" AVP being added to Session Termination Request Diameter message sent over Rx interface
> cdp: add destination realm avp only if not present

- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
This PR add support for the `codec-accept` and `codec-consume` flags of rtpengine (supported since [mr9.2.1](https://github.com/sipwise/rtpengine/commit/336cb5b280079b0e7b24127ef987e10293604490)).
> rtpengine: Add support for codec-accept and codec-consume flags

- src/modules/xlog/xlog.c
Add kemi xlog function to be able to log in other facilities other than the default one. Can this be backported to 5.6 and 5.7?
> xlog: add kemi xlog_facility function

- src/modules/ims_charging/Ro_data.c
- src/modules/ims_charging/config.h
- src/modules/ims_charging/doc/ims_charging_admin.xml
- src/modules/ims_charging/ims_charging_mod.c
Add option to get and use P-Access-Network-Info for the terminating scenario, for use of billing in roaming cases where the PANI header is already known. Currently PANI is only used for the originating scenario.
Fixed partly implemented config option to specific role of diameter client. It was currently hardcoded to S-CSCF.
> ims_charging: Add option to get and use P-Access-Network-Info for terminating scenario

- src/modules/db_postgres/km_dbase.c
PostgreSQL may be configured to use SSL: init in a thread
> db_postgres: init libssl in a thread

- misc/tools/kemi/python_mock/kemi_mock.py
- misc/tools/kemi/python_mock/test.py
fixes code generation when python keywords are used 
fixes formating issues of generated code
fixes crash from pv.setl reporting parameters as null instead of 'none'
made example more complete
> tools/kemi: update kemi_mock for python

- src/modules/file_out/doc/file_out_admin.xml
- src/modules/file_out/file_out.c
This PR updates `file_out` module to support the definition of extension and interval on a per-file basis.
> file_out: Add support for extensions and interval per file.

- src/modules/file_out/README
- src/modules/file_out/doc/file_out_admin.xml
- src/modules/file_out/file_out.c
- src/modules/file_out/types.c
- src/modules/file_out/types.h
This PR fixes small bugs, and improves docs.
- Fixup now should be able to handle the string from `.cfg` with multiple PVs, strings, and more.
- Add fixup_free functions
- `base_folder` should not contain a trailing slash. Trailing slash is allowed, but resulting paths can contain `//log_file.extenion`, which in more OS is fine and equal to `/`.
- Add initial Readme and fix some docs.
- Switch to `str` type in internal types for better string handling.
- Free message when done
> file_out: Fix a bug on fixup function, update docs, logging information.

- src/modules/file_out/doc/file_out_admin.xml
- src/modules/file_out/file_out.c
- src/modules/file_out/types.c
- src/modules/file_out/types.h
This PR adds a new parameter `prefix` to the function and its docs. It allows the message to be fixed with a prefix string.
Also fixes some leak issues.
> file_out: Add prefix parameter and docs and fix leaks.

- misc/tools/kemi/python_mock/kemi_mock.py
remove stray debug print statement that results in generated code being invalid
> tools/kemi: fix bug in mock

- src/modules/file_out/file_out.c
- src/modules/file_out/types.c
- src/modules/file_out/types.h
This PR adds the support of using PVs in the `prefix` parameter.
Also refactors the properties into a structure for each file.
> file_out: Add prefix support with PVs and refactor properties in structure.

- src/modules/ims_registrar_pcscf/save.c
- src/modules/ims_usrloc_pcscf/udomain.c
> Fixes related to contact updation and searching in P-CSCF modules

- src/modules/dispatcher/doc/dispatcher_admin.xml
- more clear documentation for the new ds_is_from_list flags
> dispatcher: refine documentation

- src/modules/ims_ipsec_pcscf/cmd.c
This patch was initially done by Herle Supreeth in his fork but isn't present upstream yet: https://github.com/kamailio/kamailio/commit/8b9a2977e111d9adb8595d98ab59f8c8eb033120
> ims_ipsec_pcscf: TLS support in ipsec_forward() improved

- src/modules/pdb/pdb.c
- utils/pdbt/pdb_server.c
- utils/pdbt/pdb_server_backend.c
Carrier id 0 might be a valid carrier number(e.g. for Germany D000-D999 are valid). Return negative carrier id in case of failures.
If all ok, I'd like to backport this to 5.8, 5.7 and 5.6
> pdb: Return negative carrierid for failures

- src/modules/ipops/doc/ipops_admin.xml
- src/modules/ipops/ipops_mod.c
- src/modules/ipops/ipops_pv.c
- src/modules/ipops/ipops_pv.h
This PR aims to add support for PRT queries in ipops module.
Some functions were modified to accommodate and reuse the structures already defined for DNS.
Any feedback is appreciated!
> ipops: Add PTR query support

- misc/tools/kemi/python_mock/README.md
- misc/tools/kemi/python_mock/kemi_mock.py
kemi_mock.py can now optionally consume documentation information generated by the vscode-kamailio-hover project
> tools/kemi: add dockstrings to the mocking

- misc/tools/kemi/python_mock/kemi_mock.py
some of the documentation contains \ which need escaping
> tools/kemi: escape docstrings when required

- src/modules/phonenum/cphonenumber.cpp
- src/modules/phonenum/cphonenumber.h
- src/modules/phonenum/doc/phonenum_admin.xml
- src/modules/phonenum/phonenum_pv.c
- add natnum property to $phn pv. this property contains the nationally formatted number
> phonenum: add national number

- src/modules/db_mysql/km_my_con.c
> db_mysql: fixed build on CentOS 7

- src/modules/pdb/config.c
- src/modules/pdb/config.h
- src/modules/pdb/pdb.c
- utils/pdbt/pdbt.c
Make timeout modparam runtime configurable.
Also update timout execeded logs from NOTICE to ERR and add more info to them.
Also update utils/pdbt.c query tool to allow 0 carrier id.
> pdb: make 'timeout' runtime configurable

- src/modules/ims_ipsec_pcscf/cmd.c
- src/modules/ims_registrar_pcscf/save.c
> Fix handling of pending reg contacts in P-CSCF

- src/modules/tls/tls_mod.c
This enables tls module statistics. This is needed for the xhttp_prom module to export tls module statistics.
> tls: enable statistics

- src/modules/ims_icscf/doc/ims_icscf_admin.xml
- src/modules/ims_icscf/ims_icscf_mod.c
- src/modules/ims_usrloc_pcscf/doc/ims_usrloc_pcscf_admin.xml
ims_icscf: add missing documents for database params:
- Adding missing ims_icscf database parameters to admin documents.
- Change the default value for ims_icscf db_url to Kamailio default db_url value.
ims_usrloc_pcscf: Update the module document
- Fixing the db_url param value from int to string in admin document.
- [ :white_check_mark: ] Commit message has the format required by CONTRIBUTING guide
- [ :white_check_mark:] Commits are split per component (core, individual modules, libs, utils, ...)
- [ :white_check_mark:] Each component has a single commit (if not, squash them into one commit)
- [ :white_check_mark:] No commits to README files for modules (changes must be done to docbook files
- [ :white_check_mark:] Small bug fix …
> ims_icscf: add missing documents for database params

- src/modules/rtpengine/rtpengine.c
In `send_rtpp_command()` if socket operations fail with an error other than `EINTR` or `ENOBUFS`, the actual error is not reported - we just get a generic "Can't send command to/read reply from RTPEngine".
Other places in the module report `errno` and `strerror(errno)` using the log format "`(%s:%d)`" so added that to the error log.
Also fixed `bind_force_send_ip()` error log to use the same semantic as the other places.
> rtpengine: show errno and error string in more places where it is useful

- src/lib/ims/ims_getters.c
- src/lib/ims/ims_getters.h
On Mobile-Terminating, if the P-Called-Party-ID header is missing, getting the host (should also be an IP) from the Request-URI can help the P-CSCF when doing AAR for QoS.
> lib/ims: added cscf_get_host_from_requri()

- src/modules/cdp/authstatemachine.c
- src/modules/cdp/routing.c
Diameter requests could contain Application-Ids in multiple AVPs. This fix iterates through them, instead of giving up if the first one does not match. This solves some issues when peers don't always declare support for vendor-specific/non-specific application ids, so routing should be easier.
Also fixed:
- auth state machine being too verbose on regular messages being received or sent while in the Open state
- add Destination-Host from auth state to requests (next-hop immediate routing)
> cdp: improved routing and removed useless warning/errors in authstatemachine

- src/modules/nathelper/nathelper.c
`handle_ruri_alias()` wasn't handling correctly the IP address in the alias, in case it was an IPv6. This adds `[` and `]` around the IP if v6 when composing a destination SIP URI, such that the downstream functions will handle it correctly and not be confused by the `:` before the port.
Arguably, nathelper is not needed in IPv6. Yet I have discovered a scenario where it could be quite helpful as a way to force some UE routing through an intermediary proxy.
> nathelper: fixed handle_ruri_alias() for alias being an IPv6

- src/modules/siprepo/siprepo_data.c
- src/modules/siprepo/siprepo_mod.c
> siprepo: fix int params and wrong copy data in siprepo_msg_async_pull

- src/modules/tcpops/tcpops_mod.c
Reference counter to tcp session not decremented after use $tcp(conid), so shm for session never free.
Can be releated to: https://www.mail-archive.com/sr-users@lists.kamailio.org/msg21294.html
> tcpops: fix memory leak in $tcp(conid)

- pkg/kamailio/deb/debian/kamailio@.service
This PR aims to allow multiple kamailio instances with different configs to be managed by systemd. 
The new `kamailio@.service` is the systemd template file, where one can provide an instance name after `systemctl start kamailio@dev`, to start a new kamailio instance with name `kamailio-dev` and use config file found in `/etc/kamailio/kamailio-dev.cfg`. 
I tested that this file and its content can work by placing the file in `/etc/systemd/system/kamailio@.service` and using the above `dev` instance name as an example. Kamailio loads and handles any new messages along with the default kamailio service.
My question right now, as I am not really familiar with the packaging workflow, is this an appropriate way to accomplish it. If yes …
> pkg: Add systemd template for starting multiple kamailio services

- src/modules/ims_qos_npn/rx_aar.c
- src/modules/ims_qos_npn/rx_avp.c
Fixing issues discovered by Coverity
> ims_qos_npn: fixed missing breaks and checks for null pointers

- src/modules/msrp/doc/msrp_admin.xml
- src/modules/msrp/msrp_mod.c
- src/modules/msrp/msrp_netio.c
- src/modules/msrp/msrp_netio.h
Add a new forward function to the MSRP module that adds the ability to perform MSRP proxying.
The forward function allows frame relaying without multi-path. The frame can be relayed unmodified, or with a custom To/From-Path. If a replacement To-Path is provided, then the From-Path is replace either by the original To-Path or the  replacement From-Path. Either the destination must be set prior or a replacement To-Path must be provided.
> msrp: add frame forward

- src/modules/ims_qos_npn/rx_avp.c
> ims_qos_npn: fixed issues in 3GPP-User-Location-Information decoding to P-Access-Network-Info header value

- src/modules/pua_reginfo/notify.c
fix(pua_reginfo): free pkg memory after getting the XML attribute
- free the memory from the state XML attribute that was returned and immediately used in another function call without freeing leaving one small mem leak;
- add comments but keep the dead code regarding parsed but unused attrs.
After testing that this change brings positive impact I found similar fix that has een done by Jason Penton in modules/ims_registrar_pcscf: fix mem leak (libxml2 structure not being freed)
cedae42f jaybeepee <jason.penton@gmail.com> on 9/28/16 at 12:26 PM
After getting content of each XML attribute that returns dynamic memory the memory should be de-allocated.
> pua_reginfo: free pkg memory after getting the XML attribute

- src/modules/sca/doc/sca.xml
- src/modules/sca/doc/sca_admin.xml
- src/modules/sca/sca.c
- src/modules/sca/sca.h
- src/modules/sca/sca_call_info.c
- src/modules/sca/sca_subscribe.c
- src/modules/sca/sca_subscribe.h
- src/modules/sca/sca_util.c
- src/modules/sca/sca_util.h
This is the first step to merge the functionality that is already used in Sipwise kamailio flavor
* module parameters [from|to]_uri_avp to store
* sca_handle_subscribe() support [from|to_uri] parameters
Add the possibility of define what is the URI value for To and/or From instead of the values from the SIP message
> sca: add support custom [to|from]_uri

- src/modules/secfilter/secfilter.c
- all secfilter functions are exported to KEMI
* All secfilter functions are exported to KEMI
> secfilter: export all functions to KEMI

- src/modules/rtpengine/api.h
- src/modules/rtpengine/rtpengine.c
Exported API functions changed to use the KEMI functions.
> rtpengine: fix api using ki functions

- src/core/parser/msg_parser.c
- src/core/parser/parse_hname2.c
Silencing messages that tend to appear when processing HEP.
> core: parser - use sip_parser_log

- src/modules/cdp/cdp_mod.c
- Added `cdp_has_app` function:
- Accepts a single parameter: - `application`: The Application ID.
- Added `cdp_has_app2` function:
- Accepts two parameters: - `vendorid`: The Vendor ID associated with the application. - `application`: The Application ID.
- Added cdp_check_peer function:
- Accepts one parameter: - `fqdn`: the Fully qualified domain name of the peer, that should be checked. The parameter may contain pseudovariables.
NOTE: All parameters are passed as standard strings.
- The cdp functions are exported to KEMI
> cdp: export all functions in KEMI

- src/modules/acc/doc/acc_admin.xml
- src/modules/call_control/call_control.c
- src/modules/call_control/doc/call_control_admin.xml
- src/modules/cnxcc/cnxcc_mod.c
- src/modules/cnxcc/cnxcc_mod.h
- src/modules/cnxcc/doc/cnxcc_admin.xml
- src/modules/cnxcc/example/kamailio-cnxcc.cfg
- src/modules/dialog/dialog.c
- src/modules/dialog/dlg_handlers.c
- src/modules/dialog/dlg_handlers.h
- src/modules/dialog/doc/dialog_admin.xml
- src/modules/mediaproxy/doc/mediaproxy_admin.xml
- src/modules/mediaproxy/mediaproxy.c
- src/modules/nat_traversal/doc/nat_traversal_admin.xml
- src/modules/nat_traversal/nat_traversal.c
- src/modules/pua_dialoginfo/doc/pua_dialoginfo_admin.xml
- src/modules/qos/doc/qos_admin.xml
- src/modules/sst/doc/sst_admin.xml
This PR removes the `dlg_flag` from the dialog module and recommends `dlg_manage()` instead in the docs.
> dialog: Remove deprecated dlg_flag

- src/modules/tm/t_cancel.c
This PR fixes the error introduced in #3962, about not being able to access the generated CANCEL message.
> tm: move local-request event route to the right location to access CANCEL

- src/lib/srdb1/db_id.c
- Modify parsing of a database URL so that a '/' character is accepted as a valid character in the password part of the URL.
This change modifies the parsing of the DB URL so that '/' characters can be included in the password field. The modified algorithm is similar to that used when a '@' character is contained in the password.
> lib/srdb1: Allow '/' in database URL passwords

- src/modules/sqlops/doc/sqlops_admin.xml
> sqlops: new connect mode documentation update

- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
- Added parameter to control the interval
This PR adds a timer that its interval can be controlled with the param `ping_interval`. 
The timer pings all registered rtpengines and disables if any are found not responsive and vice versa.
> Add timer to ping rtpengine

- src/modules/topoh/topoh_mod.c
- print entire socket address for ease of debugging with empty mask ip
> topoh: improve debug info for topoh crash

- misc/examples/ims/scscf/README.md
Just a minor typo fix in a README.
> misc: examples/ims/scscf/README - fix typo in .sql filename [skip ci]

- .pre-commit-config.yaml
@xkaraman I hope you will agree to add this jobs related to cmake files to keep things tidy.
> pre-commit: cmake-format and cmake-lint hooks [skip ci]

- src/Makefile.groups
- src/modules/htable/api.c
- src/modules/htable/api.h
- src/modules/htable/ht_api.c
- src/modules/topos/doc/topos_admin.xml
- src/modules/topos/topos_mod.c
- src/modules/topos/tps_msg.c
- src/modules/topos_htable/Makefile
- src/modules/topos_htable/doc/Makefile
- src/modules/topos_htable/doc/topos_htable.xml
- src/modules/topos_htable/doc/topos_htable_admin.xml
- src/modules/topos_htable/topos_htable_mod.c
- src/modules/topos_htable/topos_htable_storage.c
- src/modules/topos_htable/topos_htable_storage.h
Looks like htable module already exports API functions, but currently no other module uses them.
Added 2 more API functions for table creation (so other modules can be able to create their own hash tables if they want to)
> topos_htable new module

- src/modules/outbound/doc/outbound_admin.xml
This PR fixes a logic error where "flow failed" could also be triggered, when the call was ringing and has not been answered...
(according to https://www.kamailio.org/docs/modules/stable/modules/tm.html#tm.f.t_branch_replied )
> outbound/doc: Fix logic error

- misc/examples/ims/icscf/icscf.cfg.sample
- misc/examples/ims/icscf/icscf.xml.sample
- misc/examples/ims/icscf/kamailio.cfg
- misc/examples/ims/pcscf/kamailio.cfg
- misc/examples/ims/pcscf/pcscf.cfg.sample
- misc/examples/ims/pcscf/pcscf.xml.sample
- misc/examples/ims/pcscf/route/mo.cfg
- misc/examples/ims/pcscf/route/mt.cfg
- misc/examples/ims/pcscf/route/register.cfg
- misc/examples/ims/pcscf/route/rtp.cfg
- misc/examples/ims/scscf/kamailio.cfg
- misc/examples/ims/scscf/scscf.cfg.sample
- misc/examples/ims/scscf/scscf.xml.sample
> examples: fix kamailio ims cfg file for basic volte call

- src/modules/outbound/outbound_mod.c
This PR fixes a bug where when `flow_token_secret` was provided, it was not initialized properly and always set to an empty string.
- flow_token_secret is of type str and not char*
- check also the length of the string
> outbound: Fix flow_token_secret bug

- src/modules/ims_registrar_scscf/registrar_notify.c
> ims_registrar_scscf: Fixes SUBSCRIBE and NOTIFY mechanism in case of registration refresh

- src/main.c
This PR adds some start-up information for soft and hard limits of open files.
> main: Print open file limits

- src/lib/srdb1/schema/kamailio-ims_charging.xml
- src/lib/srdb1/schema/ro_session.xml
> lib/srdb1/schema: ims_charging definitions

- src/lib/srdb1/schema/contact.xml
- src/lib/srdb1/schema/impu.xml
- src/lib/srdb1/schema/impu_contact.xml
- src/lib/srdb1/schema/impu_subscriber.xml
- src/lib/srdb1/schema/kamailio-ims_usrloc_scscf.xml
- src/lib/srdb1/schema/subscriber_scscf.xml
add ims_usrloc_scscf definitions
> lib/srdb1/schema: ims_usrloc_scscf definitions

- pkg/kamailio/alpine/APKBUILD
- Add missing modules to alpine packages as listed in GH #4131
Changes should be backported to 6.0 branch, not 5.8 branch since it contains modules
that don't exist in 5.8
Update `/pkg/kamailio/alpine/APKBUILD` file to add modules that have been added to 
Kamailio in the last few years.  This also includes updating the dependency list for the
modules.
> pkg/kamailio/alpine:  Add new modules

- src/modules/nghttp2/nghttp2_mod.c
- src/modules/nghttp2/nghttp2_server.c
- Explicitly include nghttp2.h file GH #4135
Explicitly include nghttp2.h file in `src/modules/nghttp2/nghttp2_mod.c` and `src/modules/nghttp2/nghttp2_server.c`
> nghttp2: compilation with gcc 14

- src/modules/topos_htable/topos_htable_storage.c
Few fixes to topos_htable module. To be backported in 6.0 branch.
> topos_htable: fix xtag and add more snprintf checks

- src/modules/cdp/CMakeLists.txt
- fix runtime Error relocating cdp.so: TLS_client_method: symbol not found when building with cmake
> cdp: fix cmake build

- src/modules/sipt/sipt.c
The proposed patch adds KEMI support to SIPT module, include KEMI functions:
- `destination()` for `sipt_destination()` with default `terminator=1`;
- `destination_terminator()` for `sipt_destination()` with various `terminator`;
- `forwarding()` for `sipt_forwarding()`;
- `has_isup_body()` for `sipt_has_isup_body()`;
- `set_bci_1()` for `sipt_set_bci_1()`;
- `set_calling()` for `sipt_set_calling()`.
> sipt: KEMI support

- src/modules/pua_json/defs.h
- src/modules/pua_json/pua_json_publish.c
This PR allow usage of the new presence_dfks module with pua_json
> pua_json: add support for as-feature-event

- src/modules/ims_registrar_scscf/doc/ims_registrar_scscf_admin.xml
- src/modules/ims_registrar_scscf/regpv.c
> ims_registrar_scscf: regpv fix

- src/modules/dispatcher/dispatch.c
fixes bug when `ping_socket` for destination overwrites `dp->sock` which is used for normal (not probing OPTIONS) requests
> dispatcher: fix sock overwrite by ping_socket

- src/modules/cdp/cdp_rpc.c
- src/modules/cdp/doc/cdp_admin.xml
- Improve and add missing function documentation `list_peers`.
- Use correct identifier in `struct_add` rpc function and cast `time_t` for time_t field.
> cdp: Cast time for printing and Improve cdp docs

- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
- src/modules/rtpengine/rtpengine.h
- src/modules/rtpengine/rtpengine_db.c
- src/modules/rtpengine/rtpengine_dmq.c
- src/modules/rtpengine/rtpengine_dmq.h
Adding KDMQ replication for rtpengine hash table (call -> rtpengine instance assignment)
> rtpengine: hash table dmq replication

- src/modules/file_out/doc/file_out_admin.xml
- src/modules/file_out/file_out.c
- src/modules/file_out/types.c
- src/modules/file_out/types.h
This PR introduces a new modparam `timer_interval` to denote the frequency where files are checked for rotation.
Also some improvements regarding memory managments and defaults options.
> file_out: Add rotation timer

- src/modules/rtpengine/rtpengine.c
- Add debug log when trying to ping a node.
Do not ping manually disabled nodes!
> rtpengine: Add check for skipping pings on manually disabled nodes.

- src/modules/outbound/outbound_mod.c
This PR fixes the invalid case of empy Contact. 
Contact:* and expires:0 is valid and should be handled accordingly.
> outbound: Use outbound if Register contains Contacts:* and Expires:0

- src/modules/rtpengine/doc/rtpengine_admin.xml
> rtpengine: fix method name rtpengine_subscribe_offer

- src/modules/uac/replace.c
When replacing From/To header and using dialog module to store original
URIs (modparam restore_dlg=1), restoring of headers does not work for
replies to in-dialog requests sent upstream.
Add in-dialog request's direction to TM callback parameter, so correct
URIs are restored for replies to upstream in-dialog requests.
> uac: Fix From/To header restore with dialog store

- src/modules/db_redis/db_redis_mod.c
- src/modules/db_redis/db_redis_mod.h
- src/modules/db_redis/doc/db_redis_admin.xml
- src/modules/db_redis/redis_connection.c
- src/modules/db_redis/redis_dbase.c
- src/modules/db_redis/redis_dbase.h
Kudos go to Pawel Kuzak.
Since Redis v7.4, hashes support auto-expiry for individual keys. By transforming sets into hashes we can support auto-expiry.
Adding module parameters use_redis_hashes and expires to control the described feature.
> db_redis: add Redis auto expiry support by changing sets to hashes

- src/modules/dialog/doc/dialog_admin.xml
> dialog: docs: Remove dlg_flag related mentions

- src/modules/rtpengine/rtpengine.c
Fix for original commit: 3202dc9d8e26620fe642e474e5cf8632ab6bc3a7
Skip rtpengine node pinging in timer process only if node is *permanent* disabled.
> rtpengine: don't ping permanent disabled nodes

- src/modules/presence/doc/presence_admin.xml
- src/modules/presence/hash.c
- src/modules/presence/hash.h
- src/modules/presence/notify.c
- src/modules/presence/presence.c
- src/modules/presence/presence.h
- src/modules/presence/presence_dmq.c
- src/modules/presence/presence_dmq.h
- src/modules/presence/presentity.c
- src/modules/presence/presentity.h
- src/modules/presence/publish.c
- src/modules/presence/subscribe.c
- src/modules/presence/subscribe.h
Added subscriptions replication and presentity sync via dmq for presence module.
> Subscriptions replication and presence sync via dmq

- src/modules/rtpengine/rtpengine.c
Move pinging of rtpengines outside locks, by making a pkg copy of the list. Update shm list afterwards, under locks. 
Basically tested by doing "kamcmd rtpengine.reload" while the timer was pinging the rtpengines. More testing will come.
> rtpengine: timer ping nodes outside locks

- src/core/coreparam.c
- src/core/timer.c
> core: check and recover if broken circular list

- src/modules/tm/timer.c
Add NULL check for transaction uac in tm final_response_handler().
> tm: add NULL check for transaction uac

- src/core/socket_info.c
- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/doc/dispatcher.cfg
Found common typo, 8 years ago. Fix was lost and found in special archives, happy new year patch!
> core / dispatcher: Fix typo

- src/core/timer.c
We have noticed constant PKG mem leak in "slow timer", while running #4346 fix in prod-like environment.
The fix is to run the sanity checks only when needed, not all the time; no PKG mem leak now.
> core: try fix timer list only in case of issues

- src/core/cfg.lex
- src/core/cfg.y
- src/core/ip_addr.h
- src/core/socket_info.c
- src/core/tcp_main.c
- src/core/udp_server.c
This will allow to define the VRF device associated to the listen interface
```
listen=10.10.10.1:5060 vrf "blue"
```
related #4418
> core: VRF support
