- modules/usrloc_dmq/Makefile
- modules/usrloc_dmq/doc/Makefile
- modules/usrloc_dmq/doc/usrloc_dmq.xml
- modules/usrloc_dmq/doc/usrloc_dmq_admin.xml
- modules/usrloc_dmq/usrloc_dmq.c
- modules/usrloc_dmq/usrloc_sync.c
- modules/usrloc_dmq/usrloc_sync.h
New module for synchronizing usrloc contacts via dmq.
> usrloc_dmq: add module for usrloc sync via dmq

- modules/dispatcher/README
- modules/dispatcher/config.c
- modules/dispatcher/config.h
- modules/dispatcher/dispatch.c
- modules/dispatcher/dispatch.h
- modules/dispatcher/dispatcher.c
- modules/dispatcher/doc/dispatcher.xml
- modules/dispatcher/doc/dispatcher_admin.xml
First of all excuse me if in the previous pull request I didn't follow guidelines by devel-git-commit guide :)
As anticipated in the previous request I made some changes to dispatcher module for counting successful ping requests before moving a destination from inactive to active state.
While doing this changes I noticed some misspelled variables (in code and docs too) and I fixed them. So I've used similar variables (with the corrected words) also for the new feature I developed. 
In the case we leave the old variables introducing the new one we will have in the code:
"ds_probing_threshhold" vs "ds_inactive_threshold"
This behaviour could be confusing while editing the configuration file and also while reading the code.
As you requested I've separated the misspelled fixes in two commits …
> dispatcher: fixing some misspelled words and adding support for custom number of successful probing requests

- modules/registrar/doc/registrar_admin.xml
- modules/registrar/lookup.c
- modules/registrar/reg_mod.c
- modules/registrar/reg_mod.h
When performing a lookup, the Path (if present) is evaluated and if the first hop is local we skip it to avoid unnecessary looping.
It is useful if multiple servers are sharing a common database, each saving contacts with their local address as the Path.
> registrar: check for local path on lookup

- modules/websocket/ws_frame.c
Add frame.wsc == NULL check in ws_frame_transmit similar to the checks
in ws_close and friends and ws_frame_receive to avoid crashing if the
tcp connection was been terminated prematurely.
In the wild, the following was observed:
Jan 11 16:26:20 ws0 /usr/sbin/kamailio[16621]: ERROR: <core> [tcp_main.c:715]: _wbufq_add(): ERROR: wbufq_add(1077 bytes): write queue full or timeout  (32122, total 32122, last write 0 s ago)
Jan 11 16:26:20 ws0 /usr/sbin/kamailio[16621]: ERROR: websocket [ws_frame.c:299]: encode_and_send_ws_frame(): sending WebSocket frame
Jan 11 16:26:20 ws0 /usr/sbin/kamailio[16621]: ERROR: websocket [ws_frame.c:740]: ws_frame_transmit(): sending message
....
Jan 11 16:26:20 ws0 /usr/sbin/kamailio[16637]: ERROR: <core> [tcp_main.c:3638]: handle_ser_child(): handle_ser_child: …
> websocket: Check frame->wsc in ws_frame_transmit for NULL.

- modules/auth/auth_mod.c
The pv_auth_check has a flags and a checks parameter but the flags
parameter is used for both. This means that if flags has the 1-bit set
it will enable both HA1-passwords and from/to URI checks and setting the
1-bit in the checks parameter does not do anything.
This fixes the parameters so that the checks parameter is used for the
to/from URI checks.
> auth: use correct parameter for pv_auth_check checks

- modules/auth_radius/authrad_mod.c
- modules/auth_radius/authrad_mod.h
- modules/auth_radius/sterman.c
- added modparam import_all_avp parameter (int, true if not zero)
- reading all RADIUS AV-pairs to kamailio avp (not only SIP-AVP, if import_all_avp set to true)
- skiping name part of value (example: from RADIUS we recieve name - h323-x-header, value -
"h323-x-header=blah-blah-blah", in kamailio we have name
h323-x-header, value - "blah-blah-blah"), only for non SIP-AVP
- all old comments are taken into account
> Improoved working with RADIUS AV pairs

- utils/kamctl/Makefile
Reported by: Helmut Grohne <helmut@subdivi.de> See #48
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775681
> utils/kamctl: use $(basedir) as tmp dir on building instead of insecure /tmp

- modules/call_control/README
- modules/call_control/doc/call_control_admin.xml
As @oej noticed in #37 pv is missing in the list of module dependences
> add pv module as call_control dependence in documentation

- modules/corex/README
- modules/corex/doc/corex_admin.xml
module parameter min_msg_len was misspelled on documentation. See #65
> fix corex documentation

- lib/srutils/sha256.c
- lib/srutils/sha256.h
This PR fixes missing types and endian defs in srutils/sha256 that prevent compilation on Solaris derivatives.
Specifically, this fixes the following errors when compiling:
```
CC (gcc) [L libsrutils.so.1.0]          sha256.o
In file included from sha256.c:37:0:
sha256.h:111:2: error: unknown type name 'u_int32_t'
sha256.h:112:2: error: unknown type name 'u_int64_t'
sha256.h:113:2: error: unknown type name 'u_int8_t'
sha256.h:116:2: error: unknown type name 'u_int64_t'
sha256.h:117:2: error: unknown type name 'u_int64_t'
sha256.h:118:2: error: unknown type name 'u_int8_t'
sha256.h:151:1: error: unknown type name 'u_int8_t'
sha256.h:152:19: error: unknown type name 'u_int8_t'
sha256.h:154:1: error: unknown type name 'u_int8_t'
sha256.h:157:1: error: unknown type name 'u_int8_t' …
```
> fix compile errors in srutils/sha256 on SunOS (SmartOS)

- modules/presence/doc/presence_admin.xml
- modules/presence/presence.c
- modules/presence/presence.h
- modules/presence/subscribe.c
- modules/presence/subscribe.h
- modules/presence/utils_func.c
- modules/presence/utils_func.h
some UAs send very low values for subscriptions causing unwanted flooding of the server with subscribe/notify messages
this new parameter allows to set a minimum value for the subscription.
default value is 0 to preserve existing behaviour
> presence : add min_expires param

- modules/usrloc/ucontact.c
some columns were not initialized on update leading to errors in update
ERROR: db_text [dbt_lib.c:464]: dbt_is_neq_type(): invalid datatype -1001432832
ERROR: db_text [dbt_base.c:560]: dbt_update(): incompatible types!
ERROR: db_text [dbt_base.c:599]: dbt_update(): failed to update the table!
> usrloc - fix column types not initialized on update

- modules/mohqueue/mohq.c
- add \n at end of error messages
- do not declare variables in the middle of a function
- Test as many modparams at possible in one swing, before producing an error
> mohqueue MInor fixes

- core_cmd.c
- tcp_conn.h
- tcp_main.c
A per-TCP connection `lifetime` parameter is needed, to add a new functionnality in the tcpops module: the ability to dynamically modify the connection lifetime on a connection (e.g. raise the lifetime of a successfully authenticated connection).
This requires modifications in the core:
- adding a new field in the `tcp_connection` structure
- changing the way the `timeout` value is updated, using this new `lifetime` member instead of the core conf
> core: add support for per-TCP connection lifetime

- modules/presence_dialoginfo/notify_body.c
according to rfc4235 the id element is mandatory.
granstream phones are affected by this.
> presence_dialoginfo: rfc4235 in dummy dialog

- modules/registrar/README
- modules/registrar/doc/registrar_admin.xml
- modules/registrar/regpv.c
if an UA is registered using TCP (or TLS or WS(S)), make the internal
connection id avalilable in the $ulc(xxx=>conid) pv
> registrar: make connection id available in $ulc()

- modules/registrar/doc/registrar_admin.xml
- modules/registrar/lookup.c
- modules/registrar/lookup.h
- modules/registrar/reg_mod.c
- modules/registrar/reg_mod.h
3rd parameter as flag is used to optionally restrict contacts when searching.
values are
1 - match_callid
2 - match_received
3 - match_contact
4th parameter as flag to optionally perform action on positive match
values are
1 - set xavp_rcd with value from matched contact
> registrar : add optional params to registered function

- modules/cdp/config.h
- modules/cdp/configexample/ConfigExample.xml
- modules/cdp/configparser.c
- modules/cdp/peer.c
- modules/cdp/peer.h
- modules/cdp/peermanager.c
- modules/cdp/receiver.c
This patch add the possibility to specify the src ip addr we want to use when connecting to a peer.
Useful when we have several ip addresses in the same machine and we want diameter traffic goimg out from a specific one.
> modules/cdp: added src_addr parameter in peer definition

- modules/presence/doc/presence_admin.xml
- modules/presence/hash.c
- modules/presence/notify.c
- modules/presence/presence.c
- modules/presence/presence.h
- modules/presence/presentity.c
- modules/presence/subscribe.c
added param sip_uri_match
0 - case sensitive (default)
1 - case insensitive
can be extended to a more compliant version, (sensitive user, insensitive domain).
the parameter sets the function to call to match uris.
> presence: add sip_uri_match module parameter

- modules/presence/doc/presence_admin.xml
- modules/presence/presence.c
- modules/presence/presence.h
- modules/presence/subscribe.c
after handle_subscribe there is no safe way in script to obtain the presently
because re-subscription RURI is ip of kamailio and To-Uri may not contain
the presently.
$subs(uri) will allow access to this value
added as a pv to allow extension to get more properties from subscription
> presence: add $subs pv for subscription access

- lib/srdb1/schema/acc_cdrs.xml
- modules/acc/acc_api.h
- modules/acc/acc_cdr.c
Use appropriate types for core values:
-> start and end as dates (instead of strings)
-> duration as double (instead of string)
> acc: use appropriate types for core values

- mem/shm_mem.c
- mem/shm_mem.h
- modules/tls/tls_server.c
Under high load, the value returned by `shm_available()` can be total garbage, because it is not multiprocess safe. In the tls module, it makes the tests against the `low_mem_thresholdX` limits randomly return false positives, with errors such as:
```
ERROR: tls [tls_server.c:273]: tls_fix_connection(): tls: ssl bug #1491 workaround: not enough memory for safe operation: 88
```
although there is plenty of free shm memory.
This patch solves the issue by adding a safe version of the function.
> fix race condition in tls module when checking available memory limits

- modules/dialog/dlg_handlers.c
- modules/dialog/dlg_hash.h
The new flag will be accessible using $dlg(dflags).
> dialog: add new flag for expired dialogs

- etc/kamailio-basic.cfg
- etc/kamailio-oob.cfg
- etc/kamailio.cfg
- modules/ctl/ctl_defaults.h
- utils/kamctl/kamctl.fifo
- utils/kamctl/kamctlrc
> set defaults of fifo and ctl to /var/run/kamailio

- Makefile.defs
- mem/mem.c
- mem/mem.h
following patches add TLSF support for pkg memory, and easier TLSF selection at compile time
> integrate TLSF for pkg mem

- modules/htable/ht_api.c
Adds a missing call to ht_slot_unlock when the init value is not an integer. This would cause processes to block on ht_slot_lock leading to a deadlock.
> htable: Add missing ht_slot_unlock in ht_cell_value_add

- modules/pv/pv_core.c
Pass NULL as value to set_var_value when assigning a NULL or PV_VAL_NULL value to a pv with the VAR_TYPE_NULL flag set.
Previously assigning $null didn't work as expected:
`$vn(foo) = $null` would result in `$vn(foo)` being assigned `0` (this can be verified by either logging the value or testing with an if statement).
> pv: Fixed assigning $null to $vn(name) pvs

- modules/nathelper/nathelper.c
nathelper function set_contact_alias add brackets around contact's uri if the original one hadn't. This results in an invalid sip uri in the contact structure, which cause problems to other modules' functions when they try to parse the contact uri (e.g. save_pending() from ims_registrar_usrloc). This simple patch fix the issue simply mving the uri's boundaries.
> modules/nathelper: don't include enclosing brackets in contact uri in set_contact_alias

- modules/app_lua/app_lua_sr.c
- Free pkg memory allocated to store cloned function parameters
> app_lua: Fix memory leak in sr.modf

- Makefile.defs
- mem/mem.h
- mem/q_malloc.c
- mem/q_malloc.h
- mem/shm_mem.h
- mem/tlsf.c
- mem/tlsf.h
TLSF now has a debug mode, that will dump every memory block when xxx_status()
is called, and a summary of still allocated blocks when xxx_sums() is called.
configure build with
make MEMDBG=1 MEMMNG=2 cfg
to enable maximum debuging informations (source location of mallocs and frees)
> mem: TLSF memory summary and sums implementation

- Makefile
- Makefile.targets
Fixes: #167
Nowadays people expect distclean to be the rule to do the cleaning
> Makefile: use distclean as shortcut of maintainer-clean

- modules/enum/enum.c
- modules/enum/enum.h
* Fix for buffer overflow in enum_pv_query_3 for char string[17] where the boundary checks for it in is_e164 uses MAX_NUM_LEN.
* Increased the size of MAX_NUM_LEN to 33 to support the maximum number length of 32, which is what we support here on our ISUP links.
Bug: The buffer overflow bug can be triggered by calling enum_pv_query with a number that is to long eg. +1234567890123456789
> enum: fix buffer overflow and increase maximum number length

- modules/call_control/call_control.c
- warning: expression which evaluates to zero treated as a null pointer constant of type 'void *' [-Wnon-literal-null-conversion]
> modules/call_control: fixes clang compile warning

- modules/call_control/call_control.c
call_control.c:503:19: warning: implicit conversion from 'hdr_flags_t' (aka 'unsigned long long') to 'int' changes value from 18446744073709551615 to -1 [-Wconstant-conversion]
> modules/call_control: change type to fix clang compiler warning

- lib/srdb1/db_ut.c
acc module was getting values rounded by this
```
Jun  8 14:41:26 spce proxy[28942]: DEBUG: acc [acc.c:456]: acc_db_request(): sec:1433767286 usec:272474
Jun  8 14:41:26 spce proxy[28942]: DEBUG: acc [acc.c:458]: acc_db_request(): val:1433767286.272000
```
```
528 Query	insert into acc (method,from_tag,to_tag,callid,sip_code,sip_reason,time,time_hires,src_user,src_domain,dst_ouser,dst_user,dst_domain,src_leg,dst_leg ) values ('INVITE','xXqybHIcxywNXlUjz-EnGrocmpZcBxVV','2CA0A9C5-55758D6F000A60E4-8F6F6700','-QEOe-t3EPk-k3Tly1yxOvc2Wh2JKNj0','200','OK','2015-06-08 14:41:26',1433767286.27,'43991003','10.15.20.177','43991002','83569074','10.15.20.121','42c40737-afaa-4377-aa95-da852abd2a17|43991003|10.15.20.177|43991003|||76|||0|call|10.15.20.121|1433767279.678516|||||||||||','0|||75|43991002|1 …
```
> lib/srdb1: use 6 digits for db_double2str

- modules/nat_traversal/nat_traversal.c
nat_traversal.c:1477:54: warning: implicit conversion from 'hdr_flags_t' (aka 'unsigned long long') to 'enum _hdr_types_t' changes value from 18446744073709551615 to -1 [-Wconstant-conversion]
nat_traversal.c:1487:49: warning: implicit conversion from 'hdr_flags_t' (aka 'unsigned long long') to 'enum _hdr_types_t' changes value from 18446744073709551615 to -1 [-Wconstant-conversion]
> modules/nat_traversal: avoid clang warnings with cast to (enum _hdr_types_t)

- modules/db_text/dbt_raw_util.c
where clause was missing the conversion to int when appropriate
> db_text : missing conversion in raw query

- modules/kazoo/kazoo.c
- modules/kazoo/kz_json.c
- modules/kazoo/kz_json.h
json in the form of
{ "Nodes" :  {
"mynode@my.tld.com" : { ... },
"myothernode@my.tld.com" : { ...}
}
}
doesn't have an easy to fetch the keys (it works already if it is an array)
kazoo_json_keys retrieves the keys to an avp
when querying inner fields in the form xx.yy.zzz
if one of xx / yy / zzz contains a dot (.) we cannot determine the field correctly.
use "json_escape_char" param value to encode the value before querying json and kazoo_json will decode using the same character
> kazoo : add json keys function and escape character

- modules/tm/README
- modules/tm/doc/params.xml
- modules/tm/t_serial.c
- modules/tm/tm.c
- modules/usrloc/README
- modules/usrloc/doc/usrloc_admin.xml
Implement load and restore of usrloc contact attributes in the t_load_contacts, t_next_contacts and t_next_contact_flows functions in tm module.
Includes documentation of the new tm parameter 'xavp_contact'
> Implement load and restore of contact attributes

- modules/drouting/prefix_tree.c
- modules/drouting/prefix_tree.h
With this patch drouting can use "#*+"  in addition to the decimal digits.
decimal only: ~21sec
decimal and "#*+": ~21sec
after start, decimal only, used: 203119976
after start, decimal and "#*+", used: 240338888
> Add symbols "#*+" to drouting tree

- modules/rtpengine/doc/rtpengine_admin.xml
- modules/rtpengine/rtpengine.c
Added a new fifo command, namely nh_ping_rtpp, which pings the given proxy or
all proxies, and if a proxy does not respond, disable it temporarily.
If the proxy responds, it does nothing.
Changed the existing fifos to execute for a specific proxy or for all proxies
depending on the first given parameter.
Changed nh_enable_rtpp to try to ping before enabling and enable
it only if ping success. Changed some formatting for nh_show_rtpp to
print 'N/A' when disabled permanent and to display the correct recheck_ticks.
Updated doku accordingly.
> rtpengine: changes for mi_fifo_commands

- Makefile.defs
Makefile.defs:896: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
> Makefile.defs: fixes indentation

- dprint.c
- dprint.h
- modules/debugger/debugger_api.c
- modules/debugger/debugger_api.h
- modules/debugger/debugger_config.c
- modules/debugger/debugger_config.h
- modules/debugger/debugger_mod.c
- modules/debugger/doc/debugger_admin.xml
- msg_translator.c
- msg_translator.h
Added 2 new params to the debugger module such as the per module facility logging is now possible. Added a new config function which prints how the SIP message looks like if it would have to be sent out at that line in the config (prints the message with the applied lumps but does _not_ apply the lumps as msg_apply changes() function).
> debugger module: add per module facility logging + add a debug SIP message config function

- modules/presence_xml/presence_xml.c
- modules/rls/rls.c
warning: comparison of unsigned expression < 0 is always false
> modules/[rls|presence_xml]: fixes warning [-Wtautological-compare]

- modules/dispatcher/dispatch.c
- modules/dispatcher/dispatch.h
- modules/dispatcher/dispatcher.c
- modules/dispatcher/doc/dispatcher_admin.xml
I was confused a little while using dispatcher weight alg. Smth like this If some host go away:
30/30/40 -> 70/30/0 (the third one was failed). This transformation is more correct in my mind:
30/30/40 -> 50/50/0. So I have to assign some hook to dispatcher:dst-down/dispatcher:dst-up  route for rebalancing
“rweight” (relative weight)  parameter is added in this branch. rweight is in the integer range from 1 to 100 (weight, not percentage).
Active host usage probability is  rweight/(sum of all active host rweights in destination group).
So INACTIVE/DISABLED destinations are removed from probability calculation.
let’s we have rweights 1/2/1; 100 calls will be distributed as  25/50/25
after third host failing (via ds_mark_dst([state]) or RPC dispatcher.set_state or via module pinging): …
> dispatcher: relative weight distribution

- modules/htable/ht_db.c
I had trouble finding correct syntax with db_text backend, this patch helped me
> modules/htable: improves error message when loading from database

- modules/nathelper/nathelper.c
- modules/usrloc/dlist.c
- modules/usrloc/dlist.h
- modules/usrloc/udomain.c
- modules/usrloc/ul_mod.c
- modules/usrloc/ul_mod.h
- modules/usrloc/usrloc.h
Use the new field server_id on usrloc module to be able to load/get contacts filtered by server_id
> usrloc|nathelper: add filtering by server_id support

- cfg.y
fix c44685cbcefb8f6ecfa6f11369699906db832c39
routename is not been reset when no name is use like on main or reply route
> core: clean previous routename

- Makefile.groups
Hi,
Makefile.groups was not updated when usrloc_dmq was renamed to
dmq_usrloc. So dmq_usrloc won't get build by default. This patch fixes that.
thanks,
Paul
> Makefile.groups was not updated when usrloc_dmq was renamed to dmq_usrloc

- modules/pua_reginfo/usrloc_cb.c
Before the changes the xml was always the same:
UL_CONTACT_UPDATE -> state="active" event="registered"
```
Jul 15 13:48:14 sp1 proxy[25780]: DEBUG: pua_reginfo [usrloc_cb.c:240]: reginfo_usrloc_cb(): AOR: 88835677110000@A.A.A.A (location)
Jul 15 13:48:14 sp1 proxy[25780]: DEBUG: pua_reginfo [usrloc_cb.c:242]: reginfo_usrloc_cb(): type= UL_CONTACT_UPDATE
Jul 15 13:48:14 sp1 proxy[25780]: DEBUG: pua_reginfo [usrloc_cb.c:108]: build_reginfo_full(): Contact sip:88835677110000@D.D.D.D:35315;transport=TLS;ob, 0x7f916090ce38
Jul 15 13:48:14 sp1 proxy[25780]: DEBUG: pua_reginfo [usrloc_cb.c:296]: reginfo_usrloc_cb(): XML-Body:#012<?xml version="1.0"?>#012<reginfo xmlns="urn:ietf:params:xml:ns:reginfo" version="0" state="full">#012  <registration aor="sip:88835677110000@A.A.A.A" …
```
> pua_reginfo: fix NOTIFY xml

- modules/dnssec/Makefile
Fixes: #253
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790291
> dnssec: link openssl

- modules/kex/mi_core.c
support added e03d1279f49709e0d320478fa1ff7c27161c30ed
Related: #60 
See https://reproducible.debian.net/dbd/unstable/amd64/kamailio_4.3.0-1.debbindiff.html for results using -DVERSION_NODATE
> kex: support VERSION_NODATE and VERSION_DATE for reproducible builds

- modules/cdp/routing.c
Avoid to force vendor_id variable to zero if AVP AVP_Auth_Application_Id or AVP_Acct_Application_Id does not exist on AAR message. 
In this case, if  Vendor_id AVP exists but AVP_Auth_Application_Id or AVP_Acct_Application_Id does not exist vendor_id is forced to zero, thus cdp is not able to route the requests correctly anymore.
vendor_id and app_id variables are updated only if both AVPs (vendor_id and Acct or vendor_id and Auth exist).
> cdp: Fix cdp routing for Rx interface

- modules/rr/doc/rr_admin.xml
- modules/rr/record.c
- tcp_read.c
This patch helps us to handle inadequatness of Linphone mobile apps (both iOS and Android flavours are affected) without reinventing a lot of logics to handle each transport (we use TCP, TLS, WS, WSS).
E.g. if we have two TLS-based Linphone clients, even with enable_double_rr for gentle cross-forwarding we would get single RR header without transport= attribute, resulting in Linphone sending ACK and BYE via UDP.
This new option, being enabled, results in two RR headers being always inserted, with transport attribute being always added. I believe this cannot harm the installation with enable_double_rr, just makes instructions more explicit.
The Linphone's behaviour looks like a set of different bugs, but it would get us much more efforts to fix.
I don't know if any other useragent needs …
> rr: add enable_double_rr_always option

- modules/jsonrpc-c/jsonrpc_io.c
```
void reconnect_cb(int fd, short event, void *arg)
...
if (server->ev != NULL) { /* this was never initializated, so we crash!! */
event_del(server->ev);
pkg_free(server->ev);
server->ev = NULL;
}
```
> jsonrpc-c: fix crash at reconnect_cb if server was never connected

- modules/htable/ht_var.c
$shtrecord(value) does not return correct value when it is an integer
> htable : fix  $shtrecord(value) returned value

- modules/jsonrpc-c/doc/jsonrpc-c_admin.xml
- modules/jsonrpc-c/jsonrpc_io.c
- modules/jsonrpc-c/jsonrpc_mod.c
> jsonrpc-c: support load module even if no server is online and max reconnect attempts

- etc/kamailio.cfg
- fixed small typos within comments of default kamailio config
> etc: simple typo fixes in kamailio.cfg

- modules/registrar/save.c
needed for check max_contacts properly if sip.instance exists
as contact parameter
See: #278
> registrar: get instance and ref_id when using msg

- modules/janssonrpc-c/README
- modules/janssonrpc-c/doc/janssonrpc-c_admin.xml
parameter order should be jansson_get(key/path, src, dst) and not jansson_get(src, key/path, dst)
> janssonrpc-c: correct jansson_get parameter order in examples

- utils/kamcmd/kamcmd.c
support added e03d1279f49709e0d320478fa1ff7c27161c30ed
Related: #60
> kamcmd: support VERSION_NODATE and VERSION_DATE for reproducible builds

- modules/tls/Makefile
- modules/tls/doc/history.xml
In order to be able to generate reproducible builds we should not include an auto-generated cert in the default install-cfg rule at tls
> tls: install-cfg: do not generate tls-cert by default

- modules/janssonrpc-c/janssonrpc_io.c
If the JSON RPC response contains an error property, check to see if it is a json_null or not before flagging the response as an error.
> janssonrpc-c: allow null json error property in rpc response

- modules/p_usrloc/dlist.c
- modules/p_usrloc/dlist.h
I am not user of p_usrloc, but accidentally compiled this and bumped into mentioned warning.
Clang 3.0 and GCC 4.7 do not complain.
Clang 3.5 and GCC 4.8 do complain.
> modules/p_usrloc: fixes get_all_ucontacts() function signature

- modules/dispatcher/README
- modules/dispatcher/dispatch.c
- modules/dispatcher/dispatch.h
- modules/dispatcher/doc/dispatcher_admin.xml
- added DS_PROBE_ONLYFLAGGED probing_mode option.  If set,
any gateways with a state of PROBING will be continually
probed and the PROBING flag will never be cleared.  This
allows probing specific gateways continually, keeping
their up/down status current.
This is related to this sr-users mailing list thread:
http://lists.sip-router.org/pipermail/sr-users/2015-August/089594.html
> dispatcher: add new probing_mode=3 to always probe flagged gateways

- modules/dialog/dialog.c
- modules/dialog/dlg_db_handler.c
- modules/dialog/dlg_db_handler.h
- modules/dialog/doc/dialog_admin.xml
re-implemented inside init_dlg_db as per your comments, sorry I missed this ! 
hopefully this commit message is correct !
> dialog: implement db_skip_load to skip loading dialogs on startup

- modules/usrloc/doc/usrloc_admin.xml
- modules/usrloc/udomain.c
- modules/usrloc/ul_mod.c
- modules/usrloc/ul_mod.h
* When usrloc loading location records from database, and if the socket of the record is not matched in kamailio's listening socket list, It only throws LM_ERR ignoring message only but still store into memory.
should `return 0` as well.
* And the message typo sometimes confused people to distinguish that kamailio is "sipping" the record (redirct) or "skipping" the record.
> usrloc: really do the ignore location record if it's a non-local socket

- etc/kamailio.cfg
There is a small typo in kamailio.cfg where "Rotuing" has been written instead of "Routing".
> Small typo fix in config.

- modules/pv/README
- modules/pv/doc/pv_admin.xml
- modules/pv/pv.c
- modules/pv/pv_svar.c
- modules/pv/pv_svar.h
- modules/pv/pv_xavp.c
- modules/pv/pv_xavp.h
pv_scriptvar2xavp(varname, xname)
Copy script variables values to a xavp.
First parameter can be '*' in order to copy all script variables.
Second parameter is the name of the destination xavp. If xavp already
exists it will be reset first.
Function can be used from ANY_ROUTE.
> pv: create command to copy script vars to xavp

- modules/tsilo/ts_hash.c
If the transaction being removed is the first item in the list
of transactions then we need to update the pointer to the head
of the list so it does not have a stale reference.
This is an attempt to fix the tsilo crashes we've been seeing. The crashes occur in ts_onreply while iterating over the transactions to remove the transaction for the TMCB_DESTROY callback. One of the transaction pointers is not a valid shared memory address and the process crashes.
This crash results in the main kamailio process getting a SIGCHILD signal and it tries to shut down. This reaches code to free the transactions and it crashes in free_ts_urecord while trying to free the same transaction.
Inspecting code I can't tell how remove_ts_transaction resets urecord->transactions to be the head of the list of the …
> Change remove_ts_transaction so it updates head pointer of list

- modules/ims_qos/mod.c
Differentiate the cases where AAR is not sent because
of an error and the cases where AAR is not sent because it is logically wrong to sent them at that point of the transaction. In this way, in the routing script it is possible to distinguish between an error and (for example) send back an error to the UE and when AAR is not generated because (for example) the answer does not contain an SDP or you are not in a SIP reply. In this case, you should not send back an error but go ahead with your transaction.
I noticed that CSCF_RETURN_FALSE (-1) is never used in the function, so it can be suitable to be returned in the cases just explained
> Return CSCF_RETURN_FALSE if AAR is not generated

- modules/cdp/diameter_avp.c
- modules/cdp/peerstatemachine.c
Fix a crash on applications shared memory allocation
when Diameter CEA contains Auth_Applications or Acct_Applications
AVPs not "embedded" into Vendor_Specific grouped AVP
Before only the memory for applications found on Vendor_Specific
AVP was reserved, but if Acct_Applications or Auth_Applications
not Vendor Specific is found, you need to reserve memory for
the number of Acct_Applications or Auth_Applications AVPs found
multiplied by the number of Supported Vendor ID AVPs found.
> Fix crash on applications memory reservation

- modules/tmx/tmx_pretran.c
> tmx: safety check for bad callid header in t_precheck_tran()

- modules/tsilo/ts_handlers.c
- Fix cloned ts_transaction pointer comparison to check for
NULL rather than less than zero. The latter doesn't make
sense for an allocated pointer.
The commit also ensure that the function returns with an error in the case of a NULL cloned pointer so that it's not later dereferenced.
> tsilo: Fix pointer comparison in ts_set_tm_callbacks

- modules/tsilo/ts_handlers.c
- Use cb_ptr in ts_onreply LM_DBG call as the ptr variable
is NULL at that call point and cb_ptr contains the
transaction information being looked for.
> tsilo: Call LM_DBG with correct transaction information

- modules/textops/txt_var.c
- Check for NULL pointer before calling subst_expr_free
to prevent NULL pointer dereference when there is an
unknown subtype error.
> textops: prevent null dereference on tr_txt_eval_re error

- modules/htable/htable.c
- Fix for using wrong len variable in htable_rpc_list if
ht->dbtable.len is greater than 127, causing an out of
bounds write.
> htable: Fix buffer overrun in htable_rpc_list

- modules/sqlops/sql_var.c
- Don't pkg_free the gparam_t parameter of sql_parse_index.
When called within pv_parse_dbr_name that parameter is
an internal field in the sql_pv_t structure and wasn't
allocated with pkg_malloc.
> sqlops: Don't pkg_free memory that wasn't pkg_malloc'd

- modules/sqlops/sql_var.c
- Fix pv_parse_dbr_name to free spv if the key is
unknown.
- Fix typo in error log in pv_parse_dbr_name.
> sqlops: Fix memory leak in error condition

- modules/janssonrpc-c/janssonrpc_connect.c
- modules/janssonrpc-c/janssonrpc_server.c
- Fix use after free due to pointer aliasing of 'arg' and 'a'
in server_backoff_cb.
- Fix use after free in force_disconnect
- Fix use after free in free_server_list
> janssonrpc-c: Fix use after free

- modules/janssonrpc-c/janssonrpc_request.c
- Fix double free if schedule_retry fails when adding
request retry timer. timeout_cb called fail_request
which frees req after schedule_retry had already
done so.
> janssonrpc-c: Fix double free if retry timer add fails

- modules/websocket/ws_conn.c
- modules/websocket/ws_conn.h
- modules/websocket/ws_frame.c
- websocket connections are created with a BUF_SIZE (64K) buffer used for concatenating frames
- continuation frames (fragments) are supported for the SIP sub-protocol
> websocket: Add support for SIP message fragmentation

- core_cmd.c
the "port" value mistakenly had the label "proto".
> core: Fix label for RPC command ("proto" -> "port")

- modules/rtpengine/doc/rtpengine_admin.xml
- modules/rtpengine/rtpengine.c
this parameter allows to specify a script var or AVP for rtpengine to
get the SDP from, instead of the SIP message body.
> rtpengine: new read_sdp_pv parameter

- modules/acc_radius/acc_radius_mod.c
added more log about radius result. it makes better to understand problem. i checked freeradiusclient.h and radiusclient-ng.h to have all defined variables.
> acc_radius : more logging for acc_radius module

- modules/acc/acc_logic.c
- modules/acc/acc_mod.c
- modules/acc/acc_mod.h
- modules/acc/doc/acc_admin.xml
This will force the preparation of the request no matter if the acc_prepare_flag is set at the moment of the transaction creation.
Following @miconda idea at: http://lists.sip-router.org/pipermail/sr-users/2015-July/089191.html
> acc: add acc_prepare_always parameter

- modules/acc_radius/doc/acc_radius_admin.xml
Added some information for freeradius-client to acc documents. radiusclient-ng website isn't avaible so is removed.
> acc_radius doc: information about freeradius-client

- modules/tm/t_append_branches.c
This fix tries to solve the crash reported in http://lists.sip-router.org/pipermail/sr-users/2015-September/089846.html. The cause of the crash was that the sip message used to append branch was the shmem clone of the original message. When the new branches were going through their configured  branch route, modifications done by other modules' function (like rtpproxy) were applied to this stored copy directly, causing the crash once a failure route was run.
This patch take the same approach as the failure handler one, creating a fake request from the origin message and using this one to append branches. I am not sure if this is a good approach, since the appended branch are going through the branch route and some function called there could not be compatible with a faked request.
> tm: fake msg and environment to append new branches

- modules/misc_radius/doc/misc_radius_admin.xml
added information about how to active freeradius-client library
> misc_radius doc : more information freeradius-client

- modules/acc_radius/acc_radius_mod.c
- modules/acc_radius/doc/acc_radius_admin.xml
added radius time mode for new event-timestamp . Format is seconds.microseconds
> acc_radius : added radius time mode

- modules/tls/doc/params.xml
tls: fixed typo param ssl_freelist_max_len mismatch with doc
> tls: fixed typo param ssl_freelist_max_len mismatch with doc

- modules/sipcapture/README
- modules/sipcapture/doc/sipcapture_admin.xml
- modules/sipcapture/sipcapture.c
Headers must be separated by ';', and first match wins (so order in the list is important).
With this patch Homer's sipcapture can correlate A-leg and B-leg even when applications in the network use different custom headers to communicate on B-leg what A-leg's Call ID is.
No changes are needed on DB schema or homer API.
> Allow sipcapture callid_aleg_header to accept a list of headers

- modules/presence_xml/README
- modules/presence_xml/doc/presence_xml_admin.xml
- modules/presence_xml/notify_body.c
- modules/presence_xml/presence_xml.c
- added module parameter to send empty presence notify body
when there isn't any record in presentity
> presence_xml: add optional param force_dummy_presence

- modules/cnxcc/cnxcc_check.c
- modules/cnxcc/cnxcc_mod.c
- modules/cnxcc/cnxcc_mod.h
- modules/cnxcc/cnxcc_redis.c
- modules/cnxcc/cnxcc_rpc.c
Cnxcc call termination is not working anymore since commit 265dc95aac8eb4b5cee7992dde55ff08c92a7ac5. That commit introduced the call to DLGCB_TERMINATED callbacks for the locally generated BYE, which leads to a deadlock in cnxcc when it tries to end the calls because the credit (money or time) is exhausted. 
This patch introduces a new structure cnxcc_lock which implements re-entrant locks.
As a side question I'm wondering if, since other modules need re-entrant locks, this structure should be defined in lock_ops.h like the other kamailio's locks.
> cnxcc: make cnxcc locks re-entrant

- main.c
I made this patch to ensure kamailio exits with an unclean status if it stops due to a child exits. This allows systemd's unit `Restart=on-failure` parameter to actually automatically restart kamailio, in a segfault or any other signal-throwing situation.
The side effect is that it would trigger a kamailio restart if one of the children is stopped with a TERM signal, but I considered here that the only clean way to stop kamailio is to send a signal to the main attendant process, and not to a child.
> core: exit with failure code if a child dies

- ut.h
NULL checks for shm/pkg dup functions and few others.
> core: NULL checks for ut.h

- .travis.yml
- test/travis/build_travis.sh
- using https://hub.docker.com/r/linuxmaniac/pkg-kamailio-docker
- update list of supported modules
- dynamic clang version
- show CC version
- stable build environment. No external dependences except hub.docker.com
- easy to reproduce
> test/travis: migrate to docker environment

- README.md
- test/travis/README.md
- test/travis/build_travis.sh
- add some documentation
- add link to travis doc at /README.md
- add travis build status at /README.md
- use ${DIST}/rules to control the build
this simplifies the supported modules list by ${DIST}
it is already defined there. K.I.S.S
- install is done at debian/kamailio dir
> test/travis: support different debian distributions

- modules/tm/t_reply.c
- modules/tm/t_stats.c
- modules/tm/t_stats.h
- modules/tmx/tmx_mod.c
Consider the simple timeout scenario:
```
Messages
INVITE ---------->      1             
407 <----------         1   
ACK ---------->         1              
INVITE ---------->      1           
100 <----------         1      
180 <----------         0    
183 <----------         0       
408 <----------         1
ACK ---------->         1
```   
In the current implementation, running _kamctl fifo get_statistics tmx:_ on a fresh kamailio prints:
```
...
tmx:local_replies = 2
tmx:received_replies = 1
tmx:relayed_replies = 18446744073709551615
```
After this patch:
```
...
tmx:local_replies = 2
tmx:received_replies = 1
tmx:relayed_replies = 0
```
Fix the above by counting the relayed_total and substracting the relayed_local.
> tmx: Fix relayed_replies counter

- modules/textops/textops.c
Remember the end of body headers and use it for get_body_part().
> textops: Fix get_body_part() end of body headers

- modules/dialog/dlg_handlers.c
- modules/uac/replace.c
The 2 commits restores vsf=, vst= and did= RR parameters on in-dialog requests
> Add RR parameter on sequential requests

- modules/rtpengine/doc/rtpengine_admin.xml
- modules/rtpengine/rtpengine.c
- modules/rtpengine/rtpengine.h
- modules/rtpengine/rtpengine_hash.c
- modules/rtpengine/rtpengine_hash.h
Shared memory hash table with global hashtable lock.
Add state maintaining the selected rtp node, for a given callid.
Hashtable entry expiration time configurable using hash_entry_tout modparam.
The actual deletion happens on the fly while insert/remove/lookup are called.
Updated doku.
> rtpengine: hash table to keep the selected nodes

- modules/websocket/Makefile
Fixes linkage for Ubuntu Wily (15.10).
The issue manifests itself as "undefined symbol: SHA1" error at module loading.
In Ubuntu 14 LTS (Trusty), ```pkg-config --libs libssl``` returns ```-lssl -lcrypto```, but in Ubuntu 15.10 (Wily) it returns only ```-lssl```. In the end, websocket.so gets SHA1 symbol (and some more) unresolved.
For unclear reason, this change is not needed for tls.so - it gets linked to libcrypto automatically, despite it is linked only with ```-lssl``` flag. Maybe it is something symbol-specific, or something I am completely unaware of.
SSL_BUILDER stuff in Makefile seems to become even more mostruous with the proposed change. Keep in mind that there is ~5 more modules with identical construction in their Makefiles. Rejection of this patch in favor of cleaner solution …
> modules/websocket: ensure linkage to libcrypto

- modules/htable/htable.c
add missed 'd' parameter to rpc->struct_add format string
before patch
```
[root@sw4 kamailio]# kamcmd htable.stats
{
name: some_htable
slots: 4096
all: 285304
min: 43
}
```
after patch
```
[root@sw4 kamailio]# kamcmd htable.stats
{
name: some_htable
slots: 4096
all: 285304
min: 43
max: 103
}
```
> htable: fixing htable.stats for max slot value

- modules/cfgt/Makefile
- modules/cfgt/README
- modules/cfgt/cfgt.c
- modules/cfgt/cfgt.h
- modules/cfgt/cfgt_int.c
- modules/cfgt/cfgt_int.h
- modules/cfgt/cfgt_json.c
- modules/cfgt/cfgt_json.h
- modules/cfgt/cfgt_mod.c
- modules/cfgt/cfgt_mod.h
- modules/cfgt/doc/Makefile
- modules/cfgt/doc/cfgt.xml
- modules/cfgt/doc/cfgt_admin.xml
- modules/debugger/README
- modules/debugger/debugger_api.c
- modules/debugger/debugger_mod.c
- modules/debugger/doc/debugger_admin.xml
generates reports of testing scenarios:
* received message
* messages sent
* flow of executed routes ( `start`, `drop`, `exit`, `return` )
* list of the variables and its value at every route executed controlled by mask
(`CFGT_DP_NULL`, `CFGT_DP_AVP`, `CFGT_DP_SCRIPTVAR`
`CFGT_DP_XAVP`, `CFGT_DP_OTHER`, `CFGT_DP_ALL`)
Changes in the implementation from the initial propose:
* used a prefix on `Call-ID` instead of custom SIP headers `X-Kamailio-test` and `X-Kamailio-test-ID` allowing the ability to bypass other devices filters ( like sems whitelist SIP headers )
* save report files as JSON at disc after the message is processed instead of using RPC commands
Initial implementation of #8
> modules/cfgt: debugger config test support

- modules/cnxcc/cnxcc.c
- modules/cnxcc/cnxcc.h
> cnxcc: define inline functions in cnxcc.h

- modules/auth_radius/authrad_mod.c
- modules/auth_radius/authrad_mod.h
- modules/auth_radius/doc/auth_radius.xml
- modules/auth_radius/doc/auth_radius_admin.xml
- modules/auth_radius/sterman.c
- Implement append_realm_to_username parameter in auth_radius which allows
the unmolested digest username to be passed to RADIUS in the User-Name
attribute. This is required for some RADIUS implementations.
This is the same PR as #456 except based on master
> auth_radius: support for not appending realm to the username passed to RADIUS

- Makefile.defs
- socket_info.c
To make IPV6 work with Solaris, add_interfaces() had to be modified.
I decided to reimplement it with a getifaddrs() based implementation,
which is available from Solaris 11 upwards, and also on FreeBSD and
Linux. By default, the latter continues to use the netlink based
variant.
> core: rewrite add_interfaces() with getifaddrs() based implementation

- modules/registrar/reg_mod.c
- prevent from resetting sock_flag to -1 when reg_xavp_cfg is set
> registrar: do make use of reg_xavp_cfg

- modules/registrar/reg_mod.c
- since there are functions like `registered()` would use it
- reported by Jayesh Nambiar (@jayesh1017) in the comment of GH#470
> registrar: reg_xavp_cfg should not be reset when sock_flag is not set

- lib/trie/dtrie.c
Segfaults reported by Igor, on sr-Users mailing list.
Some of the output he got:
```
Jan 21 10:21:11 /usr/local/sbin/kamailio[3843]: ERROR: <core> [dtrie.c:153]: dtrie_insert(): could not allocate shared memory from available pool
Jan 21 10:21:11 /usr/local/sbin/kamailio[3839]: ERROR: userblacklist [db.c:91]: db_build_userbl_tree(): could not insert values into trie.
```
Coredumps:
```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f13a1550af2 in dtrie_insert (root=0x7f138d7ffb38, number=0x22ba6c0 "003716716", numberlen=9, data=0x2, branches=10) at dtrie.c:141
141                     if (node->child[digit] == NULL) {
Core was generated by `/usr/local/sbin/kamailio -P /var/run/kamailio.pid -m 256 -M 64'.
Program terminated with signal 11, Segmentation fault.
#0 …
```
> dtrie: sanity checks

- modules/db_text/README
- modules/db_text/dbt_file.c
- modules/db_text/dbt_lib.h
- modules/db_text/dbtext.c
- modules/db_text/doc/db_text_admin.xml
the static value of 4096 may not be enough when dealing with presence
tables that have xml content
> db_text: add buffer size for reading text files

- modules/tcpops/doc/functions.xml
- modules/tcpops/doc/tcpops.xml
- tcp_options.h
Tested with FreeBSD 10 and Linux 3.2 (Debian Wheezy 7.6).
List of other platforms gathered with [FreeBSD and Linux Kernel Cross-Reference](http://fxr.watson.org/fxr/trackident?i=TCP_KEEPIDLE)
> Make tcpops module usable on BSD

- modules/cnxcc/cnxcc_check.c
- modules/cnxcc/cnxcc_redis.c
- modules/cnxcc/cnxcc_rpc.c
When using redis as cnxcc backend, too much log is printed, specially all the logs related to the periodic user's wallet check.
> cnxcc: change some log levels from INFO to DBG

- modules/http_async_client/Makefile
- modules/http_async_client/README
- modules/http_async_client/async_http.c
- modules/http_async_client/async_http.h
- modules/http_async_client/doc/Makefile
- modules/http_async_client/doc/http_async_client.xml
- modules/http_async_client/doc/http_async_client_admin.xml
- modules/http_async_client/hm_hash.c
- modules/http_async_client/hm_hash.h
- modules/http_async_client/http_async_client_mod.c
- modules/http_async_client/http_multi.c
- modules/http_async_client/http_multi.h
- modules/pv/pv.c
- modules/pv/pv_api.c
- modules/pv/pv_api.h
This new module, based on libevent and cURL multi interface, implements non blocking HTTP queries.
> async_http: non-blocking HTTP client module

- modules/ims_icscf/cxdx_lir.c
- modules/ims_icscf/scscf_list.c
- modules/ims_icscf/scscf_list.h
Did not compile on FreeBSD 10.
> modules/ims_icscf: removes values.h dependency

- modules/tcpops/README
- modules/tcpops/doc/functions.xml
- modules/tcpops/doc/params.xml
- modules/tcpops/tcpops.c
- modules/tcpops/tcpops.h
- modules/tcpops/tcpops_mod.c
- tcp_conn.h
these new commits on top of those proposed in issue #461 now define 3 modes for the `tcp:closed` event route:
- **0**: globally disabled
- **1**: globally enabled
- **2**: manual (enabled when `tcp_enable_closed_event()` was applied)
> tcp:closed event enhancements

- lib/srutils/sha256.c
- lib/srutils/sha256.h
- lib/srutils/shautils.c
Kamailio's **srutils** SHA functions have names that collide with OpenSSL's **libcrypto** SHA functions.
In practice, OpenSSL fails to validate a server cert if **srutils** is loaded before **libcrypto**, because their SHA functions are not 100% equivalent.
On my Debian, **http_async_client** was unable to issue any HTTPS request unless server certificate verification was disabled.
This patch solves the issue by renaming the SHA functions in **srutils** to non-colliding names. I think this has no side effect because they are only used internally.
> srutils: change names colliding with libcrypto

- modules/presence/presentity.c
- modules/pua_dialoginfo/doc/pua_dialoginfo.xml
- modules/pua_dialoginfo/doc/pua_dialoginfo_admin.xml
- modules/pua_dialoginfo/pua_dialoginfo.c
- pua_dialoginfo: Implement callee_trying parameter in pua_dialoginfo which causes
a "Trying" state to be sent for both the caller and callee when
a new dialog is created.
- presentity: Implement table locking for all routes through update_presentity in order
to avoid a number of different race conditions which resulted in
extraneous data being put into the presentity table.
The latter change fixes a race condition which triggers more frequently due to the first... however I'm sure there are instances when it would trigger regardless of the first change.
> pua_dialoginfo: support for sending "Trying" state for callee

- modules/rtpengine/rtpengine.c
- modules/rtpengine/rtpengine.h
- modules/rtpengine/rtpengine_hash.c
- modules/rtpengine/rtpengine_hash.h
Reported by @juha-h. Unwanted scenarios like this could happen:
offer:
- (callid, viabranch1) -> node1
- (callid, viabranch2) -> node1
delete:
- (callid, "") -> node X (the lookup failed, because "" is not found among viabranch1/2, and thus a new node is selected; the delete() could go to another machine)
> Fix node selection when rtpengine_delete(), for branching scenarios

- modules/sdpops/sdpops_mod.c
- test/unit/60-message-sdp0.sip
- test/unit/60-message-sdp1.sip
- test/unit/60-message-sdp2.sip
- test/unit/60-message-sdp3.sip
- test/unit/60-message-sdp4.sip
- test/unit/60-message-sdp5.sip
- test/unit/60-message-sdp6.sip
- test/unit/60-message-sdp7.sip
- test/unit/60.cfg
- test/unit/60.sh
- test/unit/include/require.sh
Complete re-implementation of sdp_remove_line_by_prefix(), maybe reviewing by diff does not make sense.
Also feedback is on unit test is welcome as I have not created such for Kamailio earlier.
> sdpops improvements and tests

- futexlock.h
atomic_cmpxchg returns the previous value.  If the previous value was 0 then it was previously unlocked and we now have acquired the lock.
Thus, it should  be c==0 that is considered as the case we enter the lock, not c!=0
As far as I can tell, lock_try (and lock_set_try) are currently no used anywhere in the code, so this fix shoudn't have any impact
> core/futex: fix bug in futex_try

- modules/tls/tls_server.c
- log shm_available_safe() instead of shm_available() as this is what is
actually compared in the check
- also log the relevant threshold as it is not always obvious if the default
value is being used
> tls: enhance the logging of ssl bug #1491 workaround

- modules/pua_dialoginfo/pua_dialoginfo.c
I figured it was worth backporting this crash fix, before the v4.3.5 release Daniel mentioned on the mailing list
- the structure will be destroyed in a later dlg callback, enabled by
dlg_api.register_dlgcb(), via free_dlginfo_cell()
- based and includes partial patch from GH #492, by Phil Lavin
> [4.3 BACKPORT] pua_dialoginfo: don't free dlginfo structure in dlg loaded callback

- modules/rtpproxy/rtpproxy.c
There is an old issue in the Kamailio which may result in SDP containing mismatching protocols, when processing rtpproxy_offer() on a IPv6 message with default flags. This has been revealed by the new version of the [voiptests](https://travis-ci.org/sippy/voiptests/)
<MSG IN>
00:00:03.089/GLOBAL/alice_ua: SENDING message to [::1]:5060:
INVITE sip:bob_6@[::1]:5060 SIP/2.0
v: SIP/2.0/UDP [::1]:5061;branch=z9hG4bKfffb7b9e25497c853146ea72a3399f5c;rport
Max-Forwards: 70
f: "Alice Smith" <sip:alice_6_ipv6@[::1]>;tag=628b36c02f1d1d5a7b4305c050a3feb6
t: <sip:bob_6@[::1]>
i: 759e9723cfa1bc5c9c294b2a6c816e77@184.71.172.86
CSeq: 200 INVITE
m: Anonymous <sip:alice_6_ipv6@[::1]:5061>
Expires: 300
User-Agent: Sippy
cisco-GUID: 3824430197-1272056386-4229849152-47475815
h323-conf-id: …
> Fix an issue with IPv6 in the rtpproxy module

- modules/siptrace/siptrace.c
In some cases the trace_local_ip wasn't being updated when sending out sip trace messages.  This updates the cases I could find to use the trace_local_ip setting when needed.
> siptrace: Use the trace_local_ip setting in sip_trace()

- modules/siputils/checks.c
While building the sip uri in tel2sip() we have:
```
sip_uri.s = pkg_malloc(sip_uri.len) 
```
But later in pv_set_ruri():
```
val->rs.s[val->rs.len] = '\0';
```
It's overwriting the q_malloc control structures (a classic type of bug already).
Kamailio will log a line like this before crashing:
```
Mar  3 13:31:15 XXXXXXXX /opt/ims/sbin/kamailio[15030]: : <core> [mem/q_malloc.c:140]: qm_debug_frag(): BUG: qm_*: prev. fragm. tail overwritten(c0c0c000, abcdefed)[0x7feaf22bd558:0x7feaf22bd588]!
```
I get this crash with long "tel:" ruris, the ones that have a ";phone-context=" param . 
This patch fixes it.
> siputils: tel2sip(): fix 'off by one' when allocating memory

- modules/websocket/ws_mod.c
The stats now list:
ws_sip_max_concurrent_connections
ws_msrp_max_concurrent_connections
Instead of:
ws_sip_max_concurrent_connectons
ws_msrp_max_concurrent_connectons
Note that the latter still exist as aliases to the corrected values for
a while.
> websocket: Fix stats "connectons" typo's.

- modules/db_mysql/km_dbase.c
Customers are complaining because of this kind of messages:
> proxy[XXX]: WARNING: db_mysql [km_dbase.c:85]: db_mysql_submit_query(): driver error on ping: Lost connection to MySQL server during query
Not really and error here, so lets put it on INFO level then
> db_mysql: change log level from WARN to INFO for ping checks

- lib/srdb1/schema/rtpengine.xml
- modules/rtpengine/doc/rtpengine_admin.xml
- utils/kamctl/db_berkeley/kamailio/rtpengine
- utils/kamctl/db_sqlite/rtpengine-create.sql
- utils/kamctl/dbtext/kamailio/rtpengine
- utils/kamctl/mysql/rtpengine-create.sql
- utils/kamctl/oracle/rtpengine-create.sql
- utils/kamctl/postgres/rtpengine-create.sql
- utils/kamctl/xhttp_pi/rtpengine-mod
- utils/kamctl/xhttp_pi/rtpengine-table
The rtpengine module is not affected by this change as it currently ignores the new column.
Updated db scripts and documentations.
Is it possible for the http://kamailio.org/docs/db-tables/kamailio-db-devel.html to be regenerated after this commit?
> rtpengine: Add timestamp column to rtpengine table

- socket_info.c
- socket_info.c: getifaddrs() returns AF_PACKET, AF_INET and AF_INET6 addressed of an interface.
AF_PACKET are of no use and breaks startup with an -l eth0:5060 cmd line param
> core: skip address family AF_PACKET on -l iface_name

- modules/log_systemd/README
- modules/log_systemd/doc/log_systemd_admin.xml
- modules/log_systemd/journal_send.c
- modules/log_systemd/journal_send.h
- modules/log_systemd/log_systemd_mod.c
Journald can store arbitrary **KEY=>values[]** properties for each log event. The `sd_journal_send_xavp()` function is a binding on journald's `sd_journal_sendv()` function, that allows pushing structured events in journald, using the fields from a xavp.
(use `journald --output json-pretty` to see all the fields for the events in the journal)
> new function in log_systemd module to log structured events

- modules/app_perl/lib/perl/Kamailio/LDAPUtils/LDAPConnection.pm
- modules/app_perl/lib/perl/Kamailio/VDB.pm
* Author: Julián Moreno Patiño <julian@debian.org>
* Fix #516
* from: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821039
> app_perl: Fix "use UNIVERSAL" is a fatal error since perl 5.22

- modules/db_mongodb/README
- modules/db_mongodb/doc/db_mongodb_admin.xml
- modules/db_text/README
- modules/db_text/doc/db_text_admin.xml
- modules/iptrtpproxy/README
- modules/iptrtpproxy/doc/iptrtpproxy_admin.xml
- modules/jsonrpc-s/README
- modules/jsonrpc-s/doc/jsonrpc-s_admin.xml
- modules/purple/README
- modules/purple/doc/purple_admin.xml
- modules/textops/README
- modules/textops/doc/textops_admin.xml
- modules/xhttp_rpc/README
- modules/xhttp_rpc/doc/xhttp_rpc_admin.xml
I was reading READMEs in terminal and noticed that single sub-section can look confusing:
https://github.com/kamailio/kamailio/blob/master/modules/db_mongodb/README#L52
In comparison HTML layout does not contain such orphan section index:
http://kamailio.org/docs/modules/devel/modules/db_mongodb.html#idp19616368
This patch tries to improve confusing “Known limitations” subsections by making them independent sections.
> modules/*/doc: reorganize “Known limitations”

- lib/binrpc/binrpc_api.c
- modules/ctl/init_socks.c
- utils/kamcmd/kamcmd.c
sockaddr_un.sun_path[] seem to be either 104 or 108 in following Unices:
104 - NetBSD, OpenBSD, FreeBSD, DragonFly BSD, MINIX, XNU(Apple OS X)
108 - illumos, Solaris, Linux
> lib/binrpc modules/ctl utils/kamcmd : set UNIX_PATH_MAX to lowest common value

- modules/enum/enum.c
We use enum_query() to dispatch calls over a set of gateways. In our case single digits (for instance "8") can be a valid direct dial number which we would like to through against our enum server.
(This is an update of #593, now with guideline formatted commit messages.)
> a single digit is a valid enum_query() request

- modules/presence/doc/presence_admin.xml
- modules/presence/presence.c
- modules/presence/presence.h
- modules/presence/publish.c
- deletes expired presentity records without sending a NOTIFY
- `force_delete` disabled by default
> presence: introduce new module parameter `force_delete`

- modules/db_unixodbc/connection.h
- modules/db_unixodbc/db_unixodbc.c
- modules/db_unixodbc/dbase.c
- modules/db_unixodbc/dbase.h
- modules/db_unixodbc/doc/db_unixodbc_admin.xml
unix ODBC offers the possibilty to do an update or insert in one replace query. Unfortunately, Oracle unixODBC driver doesn't support this feature. Modifications have been done in the db_unixodbc module to allow to replace the query by 2 queries : update and if not exist, insert. This can be controlled by a new parameter replace_query, set to '1' by default in order to be backward compatible.
> db_unixodbc: some ODBC drivers do not support ODBC replace query

- modules/corex/corex_mod.c
* show error message if error in read file
> CC (clang) [M corex.so]     corex_mod.o
> corex_mod.c:352:2: warning: ignoring return value of function declared with warn_unused_result attribute [-Wunused-result]
>         fread(content, fsize, 1, f);
>        ^~~~~ ~~~~~~~~~~~~~~~~~~~~
> 1 warning generated.
> corex: fix compiler warning #612

- modules/sms/libsms_modem.c
* show error message if error in write
> CC (clang) [M sms.so]       libsms_modem.o
> libsms_modem.c:77:2: warning: ignoring return value of function declared with warn_unused_result attribute [-Wunused-result]
>        write(mdm->fd,cmd,cmd_len);
>        ^~~~~ ~~~~~~~~~~~~~~~~~~~
>1 warning generated.
> sms: fix compiler warning #612

- modules/pua_dialoginfo/dialog_publish.c
Change the log level of calls to `dialog_publish()` from `INFO` to `DBG`. This tends to convolute the logs and is certainly no more prevalent that many other calls to `LM_DBG` across the codebase.
> pua_dialoginfo: reduce the log level of every call to dialog_publish

- lib/srdb1/db_ut.c
- modules/db2_ldap/ld_fld.c
- modules/db_mysql/my_cmd.c
- modules/presence_conference/pidf.c
- modules/presence_dialoginfo/pidf.c
- modules/presence_xml/pidf.c
- modules/xmlrpc/xmlrpc.c
> CC (gcc) [L libsrdb1.so.1.0]    db_ut.o
> In file included from /usr/include/time.h:27:0,
>                  from db_ut.c:50:
> /usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
>  # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
> fix compiler warnings

- lib/srutils/sha256.c
Attempt to fix #612 
> sha256.c: In function 'sr_SHA256_Final':
> sha256.c:613:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    *(sha2_word64*)&context->buffer[SHA256_SHORT_BLOCK_LENGTH] = context->bitcount;
>    ^
> sha256.c: In function 'SHA512_Last':
> sha256.c:930:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>    *(sha2_word64*)&context->buffer[SHA512_SHORT_BLOCK_LENGTH] = context->bitcount[1];
>    ^
> sha256.c:931:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>  *(sha2_word64*)&context->buffer[SHA512_SHORT_BLOCK_LENGTH+8] = context->bitcount[0];
>  ^
> lib/srutils: fix gcc warning GH#612

- modules/presence_conference/pidf.c
Fixes compilation on FreeBSD where no special feature request is needed
> modules/presence_conference: Fix compilation on FreeBSD

- lib/srdb1/db_ut.c
Came up when trying to compile with OmniOS distribution
> lib/srdb1: fix compiler warning

- modules/ims_registrar_scscf/cxdx_sar.c
During re-registration, Diameter SAR message is sent to the HSS. It contains User-Data-Already-Available AVP, which by specification (TS 29.228, Table 6.1.2.1) instructs the HSS not to send subscription data. However when SAA is received without User-Data an error is generated. I think this behavior is not correct.
This patch modifies SAA handling so it doesn't try to update local ims subscription information, for the case where there is none received from the HSS.
> ims_registar_scscf: Fix subscr data handling in SAA

- modules/uac/uac_reg.c
i have noticed, it is possible set UAC_REG_DISABLED flag by uac.reg_refresh, but unpossible to reset it
> uac: reset UAC_REG_DISABLED flag (if need) after refresh

- modules/auth/api.c
- modules/auth/api.h
- modules/auth/auth_mod.c
- modules/auth/auth_mod.h
- modules/auth/challenge.c
- modules/auth/challenge.h
- modules/auth/doc/auth_params.xml
- modules/auth/nonce.c
- modules/auth/rfc2617.c
- modules/auth/rfc2617_sha256.c
- modules/auth_db/authorize.c
- modules/auth_ephemeral/authorize.c
- modules/auth_radius/authorize.c
- modules/uid_auth_db/authorize.c
The Authentication-Info header is already supported by the ims_auth module. This pull requsts proposes an implementation for auth module.
The Authentication-Info header is added in the function "post_auth" (if "add_authinfo_hdr" is configured.)
Modules depending on "auth" are adapted slightly to offer the ha1 value to the function "post_auth".
> Add support for Authentication-Info header in auth module

- modules/ims_registrar_pcscf/service_routes.c
With this change script function pcscf_is_registered() will actually find the contact (Volte) .
Changes made to reflect the docs : 
http://www.kamailio.org/docs/modules/devel/modules/ims_registrar_pcscf.html#idp196032
> ims_registrar_pcscf: fix getContactP() for is_registered_fallback2ip param.

- modules/xmlrpc/xmlrpc.c
compilation was failling with clang:
```
> CC (clang) [M xmlrpc.so]		xmlrpc.o
> xmlrpc.c:152:5: error: expected parameter declarator
> int snprintf(char *str, size_t size, const char *format, ...);
>     ^
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:69:39: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, __USE_FORTIFY_LEVEL - 1, __bos (str), \
>                                       ^
> /usr/include/features.h:329:31: note: expanded from macro '__USE_FORTIFY_LEVEL'
> #  define __USE_FORTIFY_LEVEL 2
>                               ^
> xmlrpc.c:152:5: error: expected ')'
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:69:39: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, __USE_FORTIFY_LEVEL - 1, __bos (str), \
> …
```
> xmlrpc: remove redeclaration of snprintf and vsnprintf

- modules/cdp/peermanager.c
IMHO debug level of message telling the state
of the peer should be DBG. If any problem
occurs on peers proper message will be written
on log. This way we have lighter log
> cdp: Change debug level of peer state to DBG

- modules/db_postgres/pg_fld.c
- fix namespace conflict on platforms where these are present in system libs
closes #665
> db_postgres: rename ntohll and htonll functions

- modules/nat_traversal/nat_traversal.c
- modules/nathelper/sip_pinger.h
It was noitced "branch=0" in sip-pinging requests, that seems not RFC compliant:
> OPTIONS sip:0004*202@192.168.5.61:5062 SIP/2.0.
> Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;branch=0.
> From: sip:ping@myhost.ru;tag=uloc-5756b445-45e2-53b-223ff654-6ad81121.
> To: sip:0004*202@192.168.5.61:5062.
> Call-ID: 935a5981-9d632e71-c6c3075@xxx.xxx.xxx.xxx.
> CSeq: 1 OPTIONS.
> Content-Length: 0.
this issue is a google search result: https://github.com/OpenSIPS/opensips/issues/145
so this patch is just a copy 	of [varunvairavan](https://github.com/varunvairavan) patch
> Nathelper/nat_traversal: branch=0

- cfg/cfg_struct.h
- prevents bus error on stricter cpu architectures like sparc
- reported by GH #655
> core: ensure cfg_block structure is 8 byte aligned

- modules/db_unixodbc/dbase.c
With Oracle DB, if the DB is restarted, db_unixodbc doesn't detect the problem as the error returned by
db_unixodbc_extract_error() is:
Jul  1 06:07:15 newvm1 /usr/sbin/kamailio[2770]: ERROR: db_unixodbc [connection.c:220]: db_unixodbc_extract_error(): unixodbc:SQLExecDirect=HY000:1:3114:[Oracle][ODBC][Ora]ORA-03114: not connected to ORACLE#012
Before, only status 08003 and 08S01 where checked to reconnect to the DB. Now, SQLSTATE HY000 (General error) is checked to trigger a reconnection.
> db_unixodbc: detect DB disconnection with generic HY000 status

- modules/cdp/doc/cdp_admin.xml
- modules/cdp/globals.h
- modules/cdp/mod.c
- modules/cdp/peermanager.c
- modules/cdp/peermanager.h
- modules/cdp/peerstatemachine.c
- modules/cdp/receiver.c
- modules/cdp/receiver.h
- modules/cdp/session.c
- modules/cdp/session.h
- modules/cdp/tcp_accept.c
- modules/cdp/tcp_accept.h
- modules/cdp/transaction.c
This is a complete refactor of cdp log. In particular:
- It removes escape chars for colors in log: they are most of the times not interpreted so they are messing up the logs
- It refactors some log level, moving to ERROR from WARN some errors during peer connections
- In DEBUG level, cdp is too much verbose and also syslogs complains about rate-limiting. Instead of removing some logs (which is quite unfair), let's introduce a new modparam (debug_heavy) in order to activate some logs which gives some side informations about peers status. This modparam is not active by default but this can be enabled easily re-introducing previous debug logs
> Refactor cdp log

- modules/ims_registrar_scscf/save.c
Now the expire values is searched on the contact
If no expires parameter is present, a fallaback
on Expires header is done. If both are not found
the default value is chosen
> ims_registrar_scscf: Refactor expire calculation

- modparam.c
Ambiguous was possible in params for multiple modules in one config line.
For example
```
loadmodule "presence_dialoginfo.so"
modparam("presence|dialplan", "db_url", "mysql://DBUSER:DBPASSWORD@localhost/DBNAME")
```
produced error 
`parameter <db_url> of type <1> not found in module <presence_dialoginfo>`
because of ["presence_dialoginfo" =~ /^presence|dialplan$/] => True
> core: fix regex error for modules parameters

- modules/ipops/doc/ipops_admin.xml
- modules/ipops/ipops_mod.c
http://lists.sip-router.org/pipermail/sr-dev/2016-July/035847.html
> modules/ipops: fix subnet matching for mask /0

- modules/ims_qos/mod.c
When creating new Auth Session for both
signalling and media, vendor_id was never
assigned. If auth timer expires, CDP will
fail to route correctly STR based on
vendor ID 0
> ims_qos: Store vendor_id on auth session

- modules/cdp/diameter_peer.c
this may happen at kamailio shutdown : 
Program terminated with signal 11, Segmentation fault.
#0  0x00007fb66a73e591 in atomic_cmpxchg_int (var=0x0, old=0, new_v=1) at ../../mem/../atomic/atomic_x86.h:233
233	ATOMIC_FUNC_CMPXCHG(cmpxchg, "cmpxchgl %2, %1", int , int)
(gdb) bt
#0  0x00007fb66a73e591 in atomic_cmpxchg_int (var=0x0, old=0, new_v=1) at ../../mem/../atomic/atomic_x86.h:233
#1  0x00007fb66a73e5e0 in futex_get (lock=0x0) at ../../mem/../futexlock.h:99
#2  0x00007fb66a743183 in diameter_peer_destroy () at diameter_peer.c:416
#3  0x00007fb66a745272 in cdp_exit () at mod.c:244
#4  0x000000000059bf98 in destroy_modules () at sr_module.c:817
#5  0x00000000004a113a in cleanup (show_status=0) at main.c:513
#6  0x00000000004a272e in shutdown_children (sig=15, show_status=0) at …
> cdp: fix occasional segfault on process exit

- modules/presence/hash.c
Attempt to fix this (crash at shutdown) : 
I observed some of these while working with daemontools (svc) .
Program terminated with signal 6, Aborted.
#0  0x00007f43e6fd5125 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007f43e6fd5125 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f43e6fd83a0 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000628b52 in qm_free (qm=0x7f43d547e000, p=0x7f43d57f5208, file=0x7f43e02d60a0 "presence: hash.c", func=0x7f43e02d69aa "delete_shtable", line=316)
at mem/q_malloc.c:455
#3  0x00007f43e0244504 in delete_shtable (htable=0x7f43d5782e00, hash_code=431, subs=0x7fffda33b830) at hash.c:316
#4  0x00007f43d4507856 in free_subscriber (s=0x7f43d57f8390) at subscribe.c:391
#5  0x00007f43d44ec7db in …
> presence: fix potential double free in shutdown routine

- modules/ims_auth/authorize.c
These changes help with debugging , for example I may need to grep for ck in the scscf log in my environment.
Also, hbody prints gibberish when qop=auth .
> ims_auth: print ck in readable form and init var to 0 to avoid printing gibberish in the log 

- modules/ims_qos/README
- modules/ims_qos/doc/ims_qos.xml
- modules/ims_qos/doc/ims_qos_admin.xml
- modules/ims_qos/mod.c
- modules/ims_qos/rx_aar.c
- modules/ims_qos/rx_avp.c
- modules/ims_qos/rx_avp.h
- modules/ims_registrar_pcscf/save.c
ims_qos: create a proper flow description for the SIP signaling
- before there was just an empty one in the AAR
- re-using the function typically used for the RTP media
- fixing then that function to not just hard-code protocol 17 (UDP) for everything
- now supporting also 6 (TCP) and IP (IP has no protocol number, we use just the
magic word "ip" (see RFC 3588 IPFilterRule for more details)
- adding the IP of the P-CSCF as a parameter to the module, as this is required
in the flow (UE IP <-> P-CSCF IP)
- also some inline/static fixes to function for avoiding warnings on gcc >=5
ims_registrar_pcscf: fixed removal of contacts on de-registration
- the code was there, but I guess some API changes resulted in temporary
commented-out code; this uses the new parameters and seems to fix the …
> ims_qos, ima_registrar_pcscf: fixes for de-registration and adding a flow to registration

- modules/registrar/doc/registrar_admin.xml
- modules/registrar/registrar.c
- modules/registrar/registrar.h
- modules/registrar/sip_msg.c
I split the pull request in three commits to seperate the fix from the new feature, but they go together so I propose them in the same pull request:
cc0b07d: I added some log message that would have helped me to understand a 400 Bad Request response.
c0697d7: I fixed a bug that were the contact size is not checked on the first header field and 200 OK is sent instead of 400 Bad Request for too long contact URIs but the uri ends up beein truncated by the database.
eb6b9c6: I made the contact size configurable to allow longer contacts
> registrar: Fix check of contact length and make it configurable

- modules/ims_usrloc_scscf/udomain.c
- modules/ims_usrloc_scscf/usrloc.h
- modules/ims_usrloc_scscf/usrloc_db.c
- modules/ims_usrloc_scscf/usrloc_db.h
Some improvements on the handling of contacts on S-CSCF database, namely
* Clean the contact table at startup if impu_contact table is empty
* if the contact is in state DELAYED_DELETE but still has ref_count > 0 in memory, it could mean that it has not been decremented before due to a failure to get a lock. This way we are leaking a contact on the DB and in memory. When the contact is expired and in DELAYED_DELETE, we do a query to check if it is really still referenced on impu_contact table. If not, we mark contact for deletion. 
* Add an helper function to print the actual state of a contact instead of the index of the enum
> Improvements on DB handling on S-CSCF usrloc

- Makefile.defs
- md5.c
- md5.h
- Allows use of SPARC optimized functions
> core: use system MD5 on Solaris

- modules/dialog/dlg_var.c
i've noticed, some dialog variables  are not saved to DB
improper flag setting has been the cause of the not DB saving in some scenarios
> dialog: set DLG_FLAG_CHANGED for changed dialog variables

- modules/siptrace/siptrace.c
due to missing adaption of cutlen, the first decimal number of the ip address is cut off when using 'ws:' uris
> modules/siptrace: fix parsing of unsecure ws uris

- tcp_read.c
This patch to emphasize that ip_addr2a() uses a static buffer and because of this lots of log lines in tcp_read.c print the same IP as src and dst . It can be confusing when debugging TCP connections.
Practically LM_DBG or LOG print the same buffer twice in these cases.
> core: fix some logging in tcp_read.c

- modules/presence/hash.c
These small changes fix the bug shown below and another potential one. 
kamailio[3062]: : <core> [mem/q_malloc.c:453]: qm_free(): BUG: qm_free: freeing already freed pointer (0x7facf958dc08), called from presence: hash.c: delete_shtable(316), first free presence: hash.c: free_subs_list(349) - aborting
It's the double free apocalypse day :)
> presence: fix multiple double free on shutdown caught with memlog=1

- modules/presence/presentity.c
The presence implementation is a little dubious, to say the least.
It probably wants re-writing at some stage. However, this fixes a
race condition that could have a number of causes in which the PUA
is unaware of the eTag at the point it sends the PUBLISH.
The mechanism is such that the PUA passes the eTag that should be updated in the database into a main Kamailio process via a header in the PUBLISH. It is made aware of the new eTag by the main Kamailio process in the 200 OK.
In the scenario when the PUA has not received the 200 OK for the `Trying` `PUBLISH` before it sends the `early` `PUBLISH`, it will send the `early` PUBLISH with no eTag. This results in both `Trying` and `early` being inserted into the database. Only the `early` is updated, as it is the most recent, meaning the …
> presence: Always check if a record exists for this dialog before inserting

- modules/presence/presentity.c
presentity: don't update terminated presentity entries in the database
- This fix is pull requested based on the stuff in pull request #724. That is because the stuff done here builds on that earlier work. #724 probably wants to be merged before this one.
- Fixes a race condition caused by, for example, the call being answered at almost exactly the same time as the caller cancels. This causes a terminated state to change back to completed. The dialog is then removed from the database and the presentity entry stays in place until it expires.
- This fix explicitly prevents terminated entries being updated as the state machine in RFC 4235 prohibits this behaviour.
> Bugfix presence race 2

- data_lump_rpl.c
- parser/hf.c
I ran into these while testing with SIPP  and having memlog=1 :
kamailio[21826]: : <core> [mem/q_malloc.c:453]: qm_free(): BUG: qm_free: freeing already freed pointer (0x7f24869850f8), called
from <core>: parser/contact/parse_contact.c: free_contact(109), first free <core>: parser/contact/parse_contact.c: free_contact(109) - aborting
kamailio[21540]: : <core> [mem/q_malloc.c:453]: qm_free(): BUG: qm_free: freeing already freed pointer (0x7f4161b971c0), called
from <core>: data_lump_rpl.c: free_lump_rpl(107), first free <core>: data_lump_rpl.c: free_lump_rpl(107) - aborting
These two patches fix these two separate issues.
> core: fixed two double free() situations

- examples/scscf/kamailio.cfg
The real return code of MAA/SAA is not shown in the logs in case of unknown error.
> examples/scscf: minor fixes (logging)

- modules/pike/pike_rpc.c
- modules/pike/pike_top.c
- modules/pike/pike_top.h
- added array structure when returning multiple addresses instead of concatenated strings
- fixed buffer overflow on incorrect buffer size allocation
> pike: fixed rpc array

- modules/tm/t_fwd.c
- modules/tm/t_reply.c
Set the branch_idx for failure route
Make sure the configured on_failure/on_branch_failure/on_reply routes are copied to the new branches created for DNS failover.
These are eligible for 4.4 too.
> TM fixes for DNS failover and branch_idx

- main.c
- modules/dispatcher/dispatcher.c
- modules/jsonrpc-s/jsonrpc-s_mod.c
- modules/mqueue/mqueue_api.c
- modules/pv/pv_xavp.c
- modules/sl/sl_funcs.c
- modules/sl/sl_funcs.h
- modules/tmx/t_var.c
- socket_info.c
Creating a PR for each commit is a bit too much work. If not all commits should be merged, please cherry-pick the wanted ones or tell me which patches should be left out.
> Random fixes

- modules/sca/doc/sca_admin.xml
- modules/sca/sca.c
- modules/sca/sca.h
- modules/sca/sca_util.c
* disable by default (-1)
* will skip parsing the sdp for on hold discovery and it will
use the value of the bflag
Fix #773
> sca: add onhold_bflag module parameter

- modules/dispatcher/dispatch.c
- modules/dispatcher/dispatch.h
- modules/dispatcher/dispatcher.c
1. Get set by id uses loop instead of recursion
2. All other routines that used to iterate over the list are re-factored to trace the tree recursively.
> dispatcher: use avl-tree for ds_set indexing

- modules/presence/presentity.c
- modules/purple/mapping.c
DB result is not freed when the resultset has <= 0 rows
Needs backporting to 4.4 branch
> Fix memory leaks in presence and purple

- modules/sca/sca.c
- modules/sca/sca_call_info.c
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0x00007f1820227bae in sca_call_info_update (msg=0x7f1828635930, p1=0x0, p2=0x0, p3=0x7f1828635930 "\001") at sca_call_info.c:1845
> 1845			LM_DBG("BUG: sca module does not support Call-Info headers "
> (gdb) p msg->cseq
> $1 = (struct hdr_field *) 0x0
> (gdb) p msg->first_line.u.request->method
> $2 = {
>  s = 0xa33540 <buf> "SUBSCRIBE sip:30@127.0.0.1:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 172.17.0.2:5061;branch=z9hG4bK-2884-1-0\r\nFrom: sipp <sip:sipp@172.17.0.2:5061>;tag=2884SIPpTag001\r\nTo: sut <sip:30@127.0.0.1:5060>\r\nCall-ID: 1"..., len = 9}
> sca: fix core when HDR_CSEQ not parsed

- modules/ipops/detailed_ip_type.c
- unable to compile detailed_ip_type.c under FreeBSD needs extra header
> ipops: fix compilation under FreeBSD

- modules/presence/presentity.c
> presence: fix crash when no dialog.id on dialog-info xml

- modules/http_client/http_client.c
The list of exported functions was not terminated, which caused a
segfault in find_mod_export_record() when reading outside the list.
> http_client Terminate exported commands list

- modules/sipcapture/sipcapture.c
- Compatible with Asterisk >= 10
Without this items in `rtcp_capture` table from FreeSWITCH or RTPEngine would have the `correlation_id` truncated.
Could be made conditional with the last element of correlation_id being `\0`, to keep compatibility with Asterisk 1.8, but otherwise this is a simple removal of the existing workaround.
> sipcapture: remove workaround of correlation_id

- modules/sca/doc/sca_admin.xml
- modules/sca/sca.c
- modules/sca/sca.h
- modules/sca/sca_notify.c
* server address ``(sip:<host>[:port])`` which will become the value of
Contact header filed for NOTIFY messages.
> sca: add "server_address" parameter

- lib/srdb1/schema/sca.xml
- modules/sca/sca_db.c
- modules/sca/sca_db.h
- modules/sca/sca_subscribe.c
- modules/sca/sca_subscribe.h
- utils/kamctl/db_berkeley/kamailio/sca_subscriptions
- utils/kamctl/db_berkeley/kamailio/version
- utils/kamctl/db_sqlite/sca-create.sql
- utils/kamctl/dbtext/kamailio/sca_subscriptions
- utils/kamctl/dbtext/kamailio/version
- utils/kamctl/mysql/sca-create.sql
- utils/kamctl/oracle/sca-create.sql
- utils/kamctl/postgres/sca-create.sql
- utils/kamctl/xhttp_pi/pi_framework.xml
- utils/kamctl/xhttp_pi/sca-mod
- utils/kamctl/xhttp_pi/sca-table
In order to have more than one server with the same DB ``sca`` module has to have a ``server_id`` column to partition subscriptions
version bumped to ``2``
See #782
> sca: add server_id column to sca_subscriptions table

- modules/presence/presentity.c
- check dialog_id is not NULL before call delete_presentity_if_dialog_id_exists
sometimes after  check_if_dialog(str body, int *is_dialog, char **dialog_id) it is possible
is_dialog==1
dialog_id==NULL
#0  __strcmp_sse42 () at ../sysdeps/x86_64/multiarch/strcmp.S:260
#1  0x00007feb2e446603 in delete_presentity_if_dialog_id_exists (presentity=0x7feb545c8ca8, dialog_id=0x0) at presentity.c:419
> presence: fix crush if dialog id is NULL

- cfg.lex
- cfg.y
- globals.h
- ip_addr.h
- main.c
- socket_info.c
- udp_server.c
You can now define a mcast parameter before a listen parameter that
contains a multicast address. After each listen parameter mcast gets
reset. mcast must contain the name of an interface, eg `eth1`.
Issue GH#813
> core: added mcast to select interface for multicast

- modules/tcpops/doc/eventroutes.xml
- modules/tcpops/tcpops.c
- modules/tcpops/tcpops.h
- modules/tcpops/tcpops_mod.c
- tcp_conn.h
- tcp_read.c
This patch for the **tcpops** module (+ some core modifications) improves the original **tcp:closed** event route handling by triggering different event routes, depending on the reason why the connection was closed:
- **tcp:closed** for "normal" closure by the other side (FIN,ACK)
- **tcp:timeout** for timeouts (unanswered keepalives)
- **tcp:reset** if reset by peer (RST)
It will break the compatibility with older scripts, as some events will require new event routes to be caught.
I'll modify the documentation accordingly if/when this is accepted.
> TCP closed event route improvement

- modules/ims_auth/authorize.c
If S-CSCF downloaded fresh keys from the HSS, put it
on the top of the list, as they are already been sent
to the UE via 401 message so it should be the first
to be retrived to comparison once REGISTER with challenge
comes from the UE
> ims_auth: Put fresh keys from HSS on top of list

- modules/tmx/t_mi.c
fix for mi command t_uac_cancel: without calling prepare_to_cancel, the following call to cancel_uacs gives this error:
BUG: tm [t_cancel.c:327]: cancel_branch(): tm: cancel_branch: local_cancel buffer=(nil) != BUSY_BUFFER (trying to continue)
and it does not cancel the transaction.
> modules/tmx: fix mi command t_uac_cancel

- modules/sca/sca.c
- modules/sca/sca_call_info.c
- modules/sca/sca_call_info.h
- modules/sca/sca_util.c
- modules/sca/sca_util.h
* use str values
* need to build struct to_body and free memory afterwards
> sca: fix sca_call_info_update() [to|from] optional parameters

- modules/pv/pv_svar.c
The sipcapture plugin stores bytes with VAR_VAL_STR and when
copying the data it would end up being truncated. Use memcpy
instead of strncpy and assume that the original string already
has the NUL termination (or not as with the hep plugin).
Config example:
$var(payload) = hep(0x00f)
> pv: Use memcpy to copy len bytes instead of strcpy

- modules/rr/loose.c
- socket_info.h
When using double route headers the selection of the outgoing
socket is only done on IP address if the port is omitted in that
route header. This fix defaults the port to 5060 so the correct
listen socket is chosen. When no socket is found it will fallback
to the current behaviour keeping backwards compatibility.
If backwards compatibility is not required the extra 'if else' could be removed. I'm not sure if `loose_route()` is being used in this way so I opted for keeping backwards compatibility.
> rr: default to port 5060 if port is omitted in route header

- modules/dialog/dialog.c
- modules/dialog/dlg_db_handler.c
- modules/dialog/dlg_dmq.c
- modules/dialog/dlg_dmq.h
- modules/dialog/dlg_handlers.c
- modules/dialog/dlg_hash.c
- modules/dialog/dlg_hash.h
- modules/dialog/dlg_profile.c
- modules/dialog/doc/dialog_admin.xml
- updating code base to actual state.
- adding repliation for DLG_STATE_EARLY to prevent hanging up unconfirmed dialogs and its infinite replication.
- fixing dialog removal on peers to prevent die on timeout and possible infinite replication.
- fixing dialog removal on peers when master node cleanly restart.
> dialog: adding dialog replication via DMQ

- modules/sipcapture/sipcapture.c
Add a newline to avoid the log of other messages starting behind
the REQUEST, PRE output.
> sipcapture: Terminate the log line with a \n

- modules/nathelper/nathelper.c
This fixes force socket in that it will always be forced and not
only when there is no socket.
> nathelper: force socket if set

- modules/ss7ops/Makefile
- modules/ss7ops/README
- modules/ss7ops/doc/Makefile
- modules/ss7ops/doc/ss7ops.xml
- modules/ss7ops/doc/ss7ops_admin.xml
- modules/ss7ops/isup_generated.c
- modules/ss7ops/isup_generated.h
- modules/ss7ops/isup_parsed.c
- modules/ss7ops/isup_parsed.h
- modules/ss7ops/ss7.c
This can be used with sipcapture and begings with M2UA and ISUP
support. More SIGTRAN (M3UA, SUA) support is planned and maybe
TCAP/MAP in the future.
The ISUP message format depends on the specific message so I have
exported a Smalltalk ITU ISUP model to C to avoid manual errors.
> ss7: Introduce the beginning of a ss7 module

- modules/memcached/mcd_var.c
current implementation sets a 0-byte value into memcached instead.
> memcached: fix deletion bug

- modules/sipcapture/hep.c
- modules/sipcapture/hep.h
- modules/sipcapture/sipcapture.c
Two fixes in this PR.
The first is to perform the ntohs also on hep messaging carrying payload other than SIP.
The scond is to take in count the definition of captid chunk in HEPv3 (uint32 BE) different from the one for HEPv2 (uint16 LE).
> Sipcapture fixes

- src/modules/dialplan/dp_repl.c
* previously we were using the values from pv_printf_s() but
that uses pv_get_buffer() so next call can interfere with
the next iteration in the list
> dialplan: fix avp values when using PV_IDX_ITR

- src/modules/statsd/statsd.c
The start and stop function currently doesn't work since the AVP used by that function is not succesfully added because usr_avp is referenced wrongly. It does work when not compiled with `-Wl,-Bsymbolic-functions`, however that is the default under Ubuntu.
> statsd: include usr_avp.h instead of usr_avp.c

- src/modules/sipcapture/hep.c
Fix $hep(0x007) and $hep(0x008) access from the cfg file. In these
two cases "i" would not be increased, ending in a infinite loop.
Modify and goto done as well.
> sipcapture: Fix $hep(0x007) and $hep(0x008)

- src/modules/sipcapture/hep.c
When using hep(0x003) and hep(0x004) the extracted ip address
would be written to the local ipstr buffer but when returning
to the script the buffer would already be partially overwritten.
Keep the data around long enough by storing the result in a
static buffer.
> hep: Store ipstr in a static buffer for exporting to cfg

- src/modules/dmq_usrloc/usrloc_sync.c
caused by acquiring the same lock twice using get_urecord_by_ruid and lock_udomain
> dmq_usrloc: fix deadlock

- src/modules/presence/notify.c
- src/modules/presence/notify.h
- src/modules/presence/presence.c
- src/modules/presence/subscribe.c
Fixes out-of-sequence version when subs_db_mode <> 3 and fast_notify is enabled.
Version is incremented only when copy is updated in memory. Therefore, currently:
On SUBSCRIBE, subscription is updated first, so NOTIFY body contains newly incremented version.
But on PUBLISH, aux_body_processing is called first, so NOTIFY body contains previously stored version.
> presence: delay aux_body_processing until after subscription has been updated

- src/modules/rtpengine/rtpengine.c
Basically tested it from python script, by grepping for incoming commands on rtpengine side.
IMHO, a nice improvement to the kemi interface would be to detect the number of input parameters given from the script and call the proper function straight ahead.
Can this be merged? Or shall we wait after 5.0 is released?
> rtpengine: Add kemi rtpengine_manage0/1

- src/Makefile.groups
Currently, pcre is included into kstandard but this module depends on
pcre library so create a kmini group which does not depend on pcre
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
> Add kmini group

- src/modules/db_perlvdb/Makefile
PERLLDOPTS is already used in app_perl module.
Reuse this variable in db_perlvdb module instead of always setting LIBS
to (shell perl -MExtUtils::Embed -e ldopts)
Indeed, this will not work when cross-compiling (the value will be
retrieved for the host perl and not the target perl)
Signed-off-by: Fabrice Fontaine <fabrice.fontaine@orange.com>
> Reuse PERLLDOPTS in db_perlvdb

- src/modules/presence/doc/presence_admin.xml
- src/modules/presence/notify.c
use the configuration xavp to control subscription deletion after notify
searches for `delete_subscription` value in the configuration xavp
> presence: allow control of subscription deletion

- modules/db_text/dbt_api.c
- modules/db_text/dbt_api.h
- modules/db_text/dbt_base.c
- modules/db_text/dbt_lib.c
- modules/db_text/dbt_lib.h
- modules/db_text/dbt_res.c
- modules/db_text/dbt_res.h
- modules/db_text/dbt_tb.c
- modules/db_text/dbtext.c
- modules/db_text/dbtext.h
when dealing with large db_text files, pkg_memory is not suitable for
operating the database.
implementing fetch allows modules like presence & registrar & usrloc
to query large tables without constraints on pkg_memory.
creates tmp tables in shared memory for query results
> db_text: implement fetch and memory constraints

- src/modules/tm/t_suspend.c
Related to http://lists.sip-router.org/pipermail/sr-users/2017-January/095772.html
Resetting the flag in t_suspend allows adding new branches in a failure route while suspending the transaction.
> tm: reset T_ASYNC_CONTINUE flag in t_suspend

- src/core/dns_cache.c
> Overrunning array ((struct a_rdata *)rr->rdata)->ip of 4 bytes
> by passing it to a function which accesses it at byte offset 15
> using argument len (which evaluates to 16)
> core: avoid overrun-buffer-arg

- src/modules/presence/notify.c
- src/modules/presence/presentity.c
- src/modules/presence/publish.c
* publ_notify_notifier() and mark_presentity_for_delete() are
called inside a already created transaction
* adding transaction handle for msg_presentity_clean()
> presence: remove transaction creation from publ_notify_notifier() and mark_presentity_for_delete()

- src/modules/pv/pv.c
- src/modules/pv/pv_core.c
- src/modules/pv/pv_core.h
this allows kamailio to have read-only (for now) access to environment variables
> pv: add the $env() PV class to read env vars

- src/modules/sipcapture/sipcapture.c
- Added missing 'break;' in sipcapture.c's pv_parse_hep_name function's switch
statement.
> sipcapture: Fixed missing 'break' in pv_parse_hep_name switch

- src/Makefile.groups
This group could be used to compile kjson module when libevent is not
available
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Add kjson_basic group

- src/modules/db_mysql/db_mysql.c
- src/modules/db_mysql/db_mysql.h
- src/modules/db_mysql/doc/db_mysql_admin.xml
- src/modules/db_mysql/km_val.c
Instead of using the time2str routines that go through timezone
conversion in kamailio, let MySQL do it. This helps with the
sipcapture module in case the system time is CET but the database
is operated in UTC. In these cases the micro_ts and date columns
would be offseted by the timezone difference and look-ups fail
to work.
> db_mysql: Let the database convert the timestamp

- src/modules/pua_dialoginfo/doc/pua_dialoginfo_admin.xml
- src/modules/pua_dialoginfo/pua_dialoginfo.c
- Added 2 new flags, disable_caller_publish_flag and disable_callee_publish_flag
- Wrapped each call to dialog_publish_multi to first check if the flag is set
This is actually quite a strange usecase. It's useful when calls do not route internally on Kamailio but are always forced out through a B2BUA which routes back to Kamailio for eventual delivery to the phone. In this case, you can disable callee (recipient) notifications for the outbound call leg from Phone->Kamailio->B2BUA and caller (initiator) notifications for the inbound leg from B2BUA->Kamailio->Phone.
In this case, you don't get notifications for 2 dialogs for each party on the call - rather 1 dialog per party. For a BLF phone, this doesn't really change anything however when BLF notifications are used to trigger events in …
> pua_dialoginfo: Add flags to disable caller and/or callee PUBLISH when required

- src/modules/pua_dialoginfo/pua_dialoginfo.c
Bug introduced in PR #979
`request` is a null pointer in the event that a dialog expires by means of Kamailio's internal dialog expiry timer. Check it everywhere, just to be sure.
> pua_dialoginfo: request does not exist when a dialog is expiring - check to make sure it does

- src/Makefile.groups
This group could be used to compile kjansson module when libevent is not
available
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Add kjansson_basic group

- src/modules/sipcapture/README
- src/modules/sipcapture/sipcapture.c
Added a new exported pseudo-variable to expose HEP's message's original source ip address.
Added an "Exported pseudo-variabled" to the README file to document $hep(src_ip) and $hep(dst_ip).
> sipcapture: Added exported pseudo-variable $hep(dst_ip) and updated README 

- src/modules/usrloc/ucontact.c
- src/modules/usrloc/urecord.c
keep a copy of ``urecord`` if mode is DB_ONLY as it is static preventing leaking ``ucontact`` to shared memory
See #997 for details
> usrloc: fix ucontact shared leak

- src/modules/rtpengine/rtpengine.c
- src/modules/rtpengine/rtpengine.h
- src/modules/rtpengine/rtpengine_db.c
1. DOC says `setid` in mysql should be `UNSIGNED INT`:
http://www.kamailio.org/docs/modules/4.4.x/modules/rtpengine.html#rtpengine.p.table_name
http://www.kamailio.org/docs/modules/4.4.x/modules/rtpengine.html#rtpengine.p.setid_col
2. kamailio did report invalid value if `setid` less than 0.
3. kamailio rtpengine module declares setid as `int setid`, thus we can not use setid more than 2147483647
This PR changes declaration of `setid` from `int` to `unsigned int`
I'm not sure about:
should `int_val` in `fixup_set_ip` at [rtpengine.c#L910](https://github.com/kamailio/kamailio/blob/master/src/modules/rtpengine/rtpengine.c#L910) be declared as `unsigned int` as well?
not sure about the usage of `int pv_locate_name()` and `unsigned short str2s()` in the `fixup_set_ip()` function.
should we …
> rtpengine: really do allow unsigned setid

- src/modules/sipcapture/hep.h
- src/modules/siptrace/doc/siptrace.xml
- src/modules/siptrace/doc/siptrace_admin.xml
- src/modules/siptrace/siptrace.c
This PR allows kamailio to duplicate messages to Homer using HEPv3 [0].
An optional correlation ID (which can contain PVs) can be passed to `sip_trace()`.
The packing macros in hep.h are authored by @camilleoudot and I've just used them.
An example of formats:
```
modparam("siptrace", "duplicate_uri", "sip:127.0.0.1:9062")
...
sip_trace("sip:127.0.0.1:9060", "123"); // duplicate URI + correlation ID
sip_trace("", "345"); // default URI + correlation ID
sip_trace("", "$fU-678"); // default URI + correlation ID with PVs
sip_trace(); // default URI + no correlation ID
```
[0] https://github.com/sipcapture/HEP/blob/master/docs/HEP3_rev12.pdf
> Add HEPv3 support to siptrace

- src/modules/siptrace/doc/siptrace.xml
- src/modules/siptrace/doc/siptrace_admin.xml
- src/modules/siptrace/siptrace.c
This adds the `hlog()` function to the siptrace module, that sends a HEP3 LOG event packet to the URI configured in the module.
Usage:
```
...
hlog("[cfg:$cfg(line)] This is a log from kamailio to Homer");
...
hlog("$hdr(P-MyID)", "Another one with a custom correlation ID");
...
```
> siptrace: new hlog() function to send logs to homer

- src/modules/siptrace/siptrace.c
I think only this check is enough:
https://github.com/kamailio/kamailio/blob/f6396033763f1d55c11744ddb9774e112865400a/src/modules/siptrace/siptrace.c#L303-L306
> modules/siptrace: remove duplicate HEP version check

- src/core/dns_cache.c
Without the initialization the used memory counter can have random values thus breaking the dns cache.
> core: initialize dns cache used memory

- src/modules/app_perl/kamailioxs.xs
The function is only called from the xs file, and C11’s inline
semantics mean that gcc-5 and later miscompile this file when
no optimization is specified.
Signed-off-by: James Cloos <cloos@jhcloos.com>
> app_perl: Make sv2int_str() static

- src/modules/ims_dialog/dlg_hash.c
Currently, ims_dialog includes execinfo.h to use backtrace in the
backtrace2str function. However, all calls to backtrace2str are
commented so disable this function through "if 0" and comment the
include on execinfo.h to allow the cross-compilation of the ims_dialog
module as some libc's don't always have this header (uclibc-ng, musl)
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Fix execinfo error in ims_dialog module

- src/Makefile.defs
- src/core/cfg.lex
- src/core/cfg.y
- src/core/forward.h
- src/core/tcp_main.c
- src/core/tcp_options.c
- src/core/tcp_options.h
- src/modules/tm/uac.c
As discussed on the mailing list and at FOSDEM this is a PR to start the discussion on the support of SO_REUSEPORT.
> core: enable reuse of tcp sockets

- src/modules/erlang/Makefile
If erl is not installed on the system or can not be used (for example
when cross-compiling), then erlang module will use the values set by the
user in ERLANG_INCDIR and ERLANG_LIBDIR instead of returning en error
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> erlang: allow user to set ERLANG_xxxDIR

- src/modules/uri_db/checks.c
- src/modules/uri_db/checks.h
- src/modules/uri_db/uri_db.c
Adding the possibility to check any sip uri against the uri_db table and updates the log macros from LM_ to the new ones.
> uri_db: rework the possibiltiy to use any sip uri

- src/modules/acc/acc_cdr.c
Hi Daniel,
This is a sketch of how I would force the execution of the acc/cdr dialog callbacks for dialogues created from the database. This solution needs more testing and I don't expect it to be accepted as is.
I think that the run_create_callbacks was omitted because at a later step, the callbacks would need to access the initial request (params->req) that originated the dialog. Looking in the generated CDRs one can also spot that certain values are left blank most probably because of the params->req message is missing.
How would you solve this problem? Is there a way to populate/ mock the request with values inside the dialog_vars table? Would you add all variables of interest inside that table or inside the dialog table? 
Thank you,
Lucian
> Fix for no cdr after Kamailio 5.0 restart

- src/modules/acc/diam_message.h
- src/modules/cdp/diameter.h
In modules/cdp/diameter.h and modules/acc/diam_message.h, this directive still exists : 
```#error BIG endian detected!!```
Meanwhile in modules/auth_diameter/diameter_msg.h, for example, this directive was removed in 5.0 release. Is there any reason to leave this directive present in these 2 headers?
The build system is Alpine Linux s390x which is big endian.
> modules/{acc,cdp}: allows big endian build

- src/modules/tm/t_reply.c
Fix for https://github.com/kamailio/kamailio/issues/1056.
If the reply is continued we need the reply after sending it out, even if it's a final reply.
> tm: don't reset uac reply if in a continue route

- src/modules/topos/tps_msg.c
When using topos, Kamailio does not set correct contact in 183 progres and 200 OK.
But for INVITE and Bye contacts are correct.
This modification seems fix it.
> topos: fix incorrect contact in 183 and 200 OK responces

- src/modules/dmq_usrloc/dmq_usrloc.c
- src/modules/dmq_usrloc/doc/dmq_usrloc.xml
- src/modules/dmq_usrloc/doc/dmq_usrloc_admin.xml
- src/modules/dmq_usrloc/usrloc_sync.c
This was tested with 100K contacts and 4 servers (all running on the same host), when restarting a server we get a full sync from the 3 nodes in a few seconds :
```
show registrations: first x
"usrloc:location-contacts = 100000",
show registrations: second x
"usrloc:location-contacts = 100000",
show registrations: third x
"usrloc:location-contacts = 100000",
show registrations: fourth x
"usrloc:location-contacts = 100000",
postgres database: 100000
```
> dmq_usrloc: sync with multi contacts per message

- src/modules/db_text/db_text.c
- src/modules/db_text/dbt_file.c
- src/modules/db_text/dbt_lib.h
- src/modules/db_text/doc/db_text_admin.xml
- changed separator because if IPv6 addresses were to be saved in a db_text file, their format would upset the parser
I think that 4.4 would also benefit by back-porting this. Agree?
> db_text: change field separator from ":" to "|"

- src/main.c
If it appears that no child process has stopped, then do not terminate
on SIGCHLD. Certain modules like app_python can run external scripts
which cause child processes to be started and stopped. That can result
in SIGCHLD being received even though there is no real problem.
Therefore, we do not terminate Kamailio unless we can find the child
process which has stopped.
> core: Don't terminate on harmless SIGCHLD.

- src/core/tcp_main.c
- src/core/udp_server.c
- src/modules/sctp/sctp_server.c
Pull request allow start daemon in case not initialized network.
see https://github.com/proftpd/proftpd/issues/221
> src/core: Added IP_FREEBIND flag durring socket initialization

- src/modules/ndb_redis/doc/ndb_redis_admin.xml
- src/modules/ndb_redis/ndb_redis_mod.c
- src/modules/ndb_redis/redis_client.c
- src/modules/ndb_redis/redis_client.h
Hello, 
We realized that redis_execute should return a negative value in case of failure (just like redis_cmd), instead of always returning 1. This introduced a problem with the behavior when calling redis_execute without giving a server name. Since this function will loop through all the servers and execute the pipelined commands for each one, in case of failure the user cannot determine for what server the error occurred, by only returning a negative value. This is why we decided to remove the possibility to call redis_execute with no arguments, and have it loop through all defined servers. The user should only call redis_execute(srv_name) and check the return value for this.
> Redis remove redis_execute() command with no arguments

- src/modules/ndb_redis/redis_client.c
- src/modules/ndb_redis/redis_client.h
Hello, I have found some bugs with the original commit that adds redis_pipe_cmd. If a command to the server fails, this may leave the redisContext in an invalid state, and this means that a reconnect to the server needs to be performed.
The problem is that when reconnecting, a new context is created, and all the contents of old redisContext is lost, including the hiredis output buffer (obuf) which stored the piped commands. This means that all the commands are lost, and when a second retry is made this contains no commands and may fail, leaving the redisContext in an invalid state. This can in some cases break the REDIS pipelining feature, and cause all commands sent using redis_pipe_cmd()/redis_execute() to fail from that point onwards.
The solution is to make sure that the connection is …
> Fix redis pipeline

- src/modules/ndb_redis/doc/ndb_redis_admin.xml
- src/modules/ndb_redis/ndb_redis_mod.c
- src/modules/ndb_redis/redis_client.c
- src/modules/ndb_redis/redis_client.h
Hello, 
We added a new feature to the ndb_redis module, similar to how the rtpengine_disable_tout parameter of the rtpengine module works. 
If a number of consecutive commands to a redis server fail, that server is temporarily disabled. This is configurable by parameters: "allowed_timeouts" and "disable_time". 
Disabling a server means that for "disable_time" seconds any command to that sever will not send the command to the server, but an error is returned instead. 
For example if allowed_timeouts is configured to 0 and disable_time to 30, the first time redis_cmd or redis_execute functions fail the server will be disabled for 30 seconds. 
The server information is retained by each Kamailio process individually, so this means that disabling a server is done by that process only and not …
> ndb_redis: add disable server on failure feature

- src/modules/ndb_redis/doc/ndb_redis_admin.xml
- src/modules/ndb_redis/ndb_redis_mod.c
- src/modules/ndb_redis/redis_client.c
Hello,
We added a new parameter to ndb_redis module. If set to 1 a "FLUSHALL" command is issued to the REDIS server when reconnecting to a server after a failed command. This way for each failed command the database is flushed. 
This is useful when a connection to the REDIS server may become unstable and some commands are issued but the replies are not received (it may happen that the command has reached the REDIS server but the reply was lost). If for example we increment and decrement counters this may leave the db in an invalid state.
This can especially happen if the allowed_timeouts/disable_time parameters are configured, since the first commands may be issued and the next ones are never tried.
> ndb_redis: add flush_db_on_reconnect parameter

- src/modules/rabbitmq/rabbitmq.c
RabbitMQ docs say, temporary reply-to queues should be created
with an "exclusive" parameter. This allows only the current
connection to access the queue, and when the connection ends,
the queue will automatically be deleted.
> rabbitmq: create reply-to queue w/ exclusive param

- src/modules/db_sqlite/db_sqlite.c
- src/modules/db_sqlite/db_sqlite.h
- src/modules/db_sqlite/dbase.c
- src/modules/db_sqlite/doc/db_sqlite.xml
- src/modules/db_sqlite/doc/db_sqlite_admin.xml
Using a `db_param_list` `clist` we can preset `SQLITE_OPEN_READONLY` on specific database file, this can be reused for more sqlite specific settings since we probably do not want extand `km_dbase` for db engine specific settings.
This is required when another process is writing to the db
Example: 
``modparam("db_sqlite","db_set_readonly","/var/mydb.sqlite")``
> db_sqlite: new param to open some database in read-only

- src/modules/db_sqlite/doc/db_sqlite_admin.xml
I screw up the xml file again, I found out how to test it using 
`make modules-readme modules=modules/db_sqlite`
seems fine now
> db_sqlite: fix xml doc

- src/modules/tsilo/tsilo.c
Copy ruri parameter into pkg mem before calling ts_append().
Value saved in a static buffer from pv_get_buffer() can be corrupted if
a new branch adds an additional SIP header in its branch_route
> tsilo: fix deadlock in ts_append()

- src/core/parser/msg_parser.c
* tm now uses shared memory for fake_req() so faked_req->path_vec
was leaking
> core: parser reset_path_vector() remove check for msg->msg_flags

- src/modules/htable/ht_var.c
resets 'first' when esize == 0
> htable: fix crash if deleted entry is reused

- src/modules/ndb_redis/doc/ndb_redis_admin.xml
- src/modules/ndb_redis/ndb_redis_mod.c
- src/modules/ndb_redis/redis_client.h
Hello, 
I have enhanced the way REDIS replied are accessed in the Kamailio config, to be able to access arrays that are members of other arrays. In the original code, we could access members of an array like this: $redis(reply=>value[0]). 
But if that member was itself an array it was impossible to access it, as accessing an array directly returns (null). This case can happen if we use redis transactions with, and all commands are given between MULTI and EXEC commands. Then the EXEC command returns an array with the responses of the individual commands, so if any command returns an array, then we have an array within that array.
I have modified the syntax of the redis replies in the config, to be able to add other keys after value[n] keys. This way we can access members of the array …
> ndb_redis: enhance access to REDIS replies

- src/modules/db_sqlite/db_sqlite.c
- src/modules/db_sqlite/db_sqlite.h
- src/modules/db_sqlite/dbase.c
- src/modules/db_sqlite/doc/db_sqlite_admin.xml
Exposing journal mode as a module parameter, one great feature is to be able to use WAL mode and share a database in read / write mode with facing any locking.
https://sqlite.org/wal.html
> db_sqlite: new param to set database journal mode

- src/modules/pv/pv.c
- src/modules/pv/pv_core.c
- src/modules/pv/pv_core.h
adds $RAi , $RAp
if advertise is not set, defaults to reveived ip/port
> pv: add received ip/port pvars for advertised ip/port

- src/modules/app_lua/app_lua_sr.c
The "notice" loglevel is missing in app_lua's sr.log function. This patch adds it.
> app_lua: add "NOTICE" loglevel to sr.log

- src/modules/presence/notify.c
i have timeout_rm_subs=1 (as default) and It was a lot of messages in kamailio.log like this
```
Jun 23 12:08:56 kamailio[8366] ERROR: presence [subscribe.c:487]: delete_subs(): Failed to delete subscription from memory [slot: 255 ev: sip:2579*109@host pu: presence ci: 08f29987584a4e47b12110ff09e48d92 ft: 8fece9a08beb407cb0fec4c703e6f99e tt: 302fa4d0674d106ffe861f2ef3364869.711a]
```
The reason is timout NOTIFY with "Subscription-State: terminated;reason=timeout"
> presence: subsription double delete fix

- src/modules/ndb_redis/redis_client.c
- src/modules/ndb_redis/redis_client.h
Added a way to print the redis responses when they are arrays, since the previous log message would just print (null) instead. In case a MULTI/EXEC transaction will be used to issue redis commands, the response would be an array, making the original debug message useless. With this new debug, arrays, strings, integers, and other replies such as status or error replies are logged properly. 
Also added an error message when a reply is expected but not received.
> ndb_redis: enhance debug info related to redis replies

- src/modules/dispatcher/dispatch.c
Depending on how many custom attributes one has set in the dispatcher file, some of them might be ignored due to the 256 read line buffer size. Increase the line buffer size. Probably adding a modparam for that would be a better approach ?! but I want to avoid any dynamic alloc/free(for now).
> dispatcher: Increase line buffer size

- src/core/cfg/cfg_ctx.c
- src/core/cfg/cfg_ctx.h
- src/modules/cfg_rpc/cfg_rpc.c
- src/modules/cfg_rpc/doc/rpc.xml
kamcmd cfg.reset "group_name", cfg.reset has been created in order to reset all the variables of the referred group to be set to their initial values (default).
> configuration reset function (cfg.reset)

- src/modules/xmlrpc/xmlrpc.c
As XML-RPC specification says
> An `<array>` contains a single `<data>` element, which can contain any number of `<value>`s.
Before this PR the function `rpc_array_add` adds elements to the `<data>` tag without wrapping them in `<value>` tag.
See http://xmlrpc.scripting.com/spec.html
> xmlrpc: add <value> tag to array elements

- src/modules/cplc/cplc.c
- src/modules/cplc/doc/cplc_admin.xml
After allowing routes identification using names, the integer value defined in the parameter is not triggering the route referred by the name, but to the mapped id for one of the routes defined in the script. 
The proxy_route modparam type has been changed from integer to string in order to define the route to be executed by its name.
> cplc: use route names to set proxy_route modparam

- src/core/core_cmd.c
Recently playing with jsonrpcs I found an issue with core.sockets_list and core.aliases_list commands called via jsonrpc_dispatch. 
The problem for the first is that the socket's list is that the JSON produced is like
{
"jsonrpc":      "2.0",
"result":       {
"socket":       {
"proto":        "udp",
"address":      "XX.XX.XX.XX",
"ipaddress":    "XX.XX.XX.XX",
"port": "5060",
"mcast":        "no",
"mhomed":       "no"
},
"socket":       {
"proto":        "udp",
"address":      "XX.XX.XX.XX",
"ipaddress":    "XX.XX.XX.XX",
"port": "5060",
"mcast":        "no",
"mhomed":       "no"
},
....
},
"id":   1
}
While this is a valid JSON document, the fact that the "socket" key is defined several time in the same object makes many parsers not to properly parse it and only keep the last value. …
> Adapt some core rpc command to json

- src/core/core_cmd.c
I realized with more tests that my previous commit for core.sockets_list 38f514064a326f759e0e88adeffd03b32b35d6c0 is not working. The result is returned yes as an array but inside there is still the sockets list as an object (so with multiple "socket" keys). Digging more in kamailio json lib I understood that to be considered an array the rpc result must be enclosed in "[]". 
I was misled by a wrong test result, sorry for the noise.
> core: build reply of core.sockets_list as an array

- src/modules/sipcapture/hep.c
Without commit 6e43bf8, using $hep() in script gives inconsistent results due to multiple byte order conversions.
> sipcapture: byteorder fixes

- pkg/kamailio/centos/7/kamailio.spec
Update the specfile for centos 7 to:
- build rabbitmq module package
- exclude kamailio-ims package dependency when installing main kamailio package
> Centos 7 specfile updates

- utils/kamctl/kamctl
Hi,
kamctl has a historical bomb which can be new https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123 in case if variables are undefined for some reason.
Have fun! CC @linuxmaniac
> kamctl: fix dangerous 'rm -rf' code in case if variables are not defined

- src/modules/textops/textops.c
Ensure that buffer is null terminated when subst_run() function is used.
> textops: Fix 'offset exceeds message size' crash.

- src/modules/carrierroute/doc/carrierroute_admin.xml
Make documentation of parameters description more clear that it has to be an avp not just the name.
> carrierroute: update to readme to precise that decsavp need to be an avp

- pkg/kamailio/centos/7/kamailio.spec
update version suffix
added unpackaged `acc_diameter` files
removed dependency to not existed package `libcrypto `
> pkg/kamailio/centos/7: Update CentOS spec file

- src/modules/drouting/doc/drouting_admin.xml
- src/modules/drouting/drouting.c
When destinations monitoring is enabled with option 'enable_keepalive' set to 1, unavailable destinations will be ignored when calling do_routing() function
It was already implemented for sort_order 0 in a previous commit. 
This one adds the support for sor_order 1 & 2 also
> drouting: pull out unavailable destinations for sort_order 1 and 2

- src/modules/carrierroute/cr_db.c
- src/modules/carrierroute/cr_db.h
- src/modules/carrierroute/cr_func.c
While starting kamailio or reloading the routes, if the same carrier/domain pairs do not have
any route with a probability other than 0 (zero) then an error log will be printed on the screen.
Besides, the log "invalid dice_max value" in the cr_func.c has been made more clear.
> carrierroute: warning for the same carrier/domain having routes with only 0 probability

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/dispatcher.c
- src/modules/dispatcher/doc/dispatcher.xml
- src/modules/dispatcher/doc/dispatcher_admin.xml
- [ X] Tested changes locally
With the proposed modification the dispatcher can now compute the latency of all the nodes it is pinging and also report timeouts counts.
Default module behavior is unchanged, the stats needs to be explicitly activated.
In this first stage, the objective is to start to monitor latency and intermittent timeouts and share the …
> dispatcher: latency statistics

- src/modules/dispatcher/Makefile
- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
This PR to fix a calculation error on the latency standard deviation
test with random values from 1-30
```
total[1726000000]value[3] count[2097152] std[8.654594] avg[15.541001] est[14.098082]
total[1727000000]value[2] count[2097152] std[8.654230] avg[15.542887] est[16.070623]
total[1728000000]value[2] count[2097152] std[8.655254] avg[15.546928] est[13.154167]
```
test with random values 1-500
```
total[1056000000]value[373] count[2097152] std[144.397552] avg[249.993790] est[297.913574]
total[1057000000]value[118] count[2097152] std[144.369400] avg[250.121262] est[222.419662]
total[1058000000]value[431] count[2097152] std[144.314056] avg[250.138077] est[295.765625]
```
> dispatcher: latency fix stdev calculation

- src/modules/ims_registrar_pcscf/save.c
- src/modules/ims_registrar_pcscf/sec_agree.c
- src/modules/ims_registrar_pcscf/sec_agree.h
In nutshell, this PR adds support for sec-agree parameters parsing in PCSCF.
ims_usrloc_pcscf can store security related parameters from sec-agree extension. However ims_register_pcscf doesn't parse the corresponding SIP headers. This PR adds code, which parses security-client header fields and stores them via ims_usrloc_pcscf.
> ims_registrar_pcscf: Add support for sec-agree parameters parsing

- pkg/kamailio/obs/kamailio.spec
- pkg/kamailio/obs/meta
pkg/kamailio/obs: Added support of OpenSUSE Tumbleweed
pkg/kamailio/obs Fixed build of perl module
pkg/kamailio: Added links to obs spec file for:
- Fedora 25, 26
- RHEL 6, 7
- OpenSUSE Leap
> pkg/kamailio/obs: Updated obs spec

- src/modules/app_python/Makefile
>    Add "-fno-strict-aliasing" to compilation flags
>
>    Fixes a slew of:
>      "dereferencing type-punned pointer will break strict-aliasing rules"
>    warnings from GCC for lines of the form:
>      Py_INCREF(Py_True);
>    and
>      Py_INCREF(Py_False);
>
>    due to the cast from PyIntObject* to PyObject*
>
>    GCC is technically correct here; see:
>      http://www.python.org/dev/peps/pep-3123/
>    though this is unlikely to lead to non-working machine code.
> app_python: fix compiler warning

- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
- src/modules/rtpengine/rtpengine.h
ce5362d adds stop_recording function that is similar to start_recording. This is useful when wanting to stop recording in the middle of the call since it has it's own message and is not attached to the offer/answer/delete message (like the "record-call off" flag in rtpengine_manage function).
45b4d35  enables the use of flags with both start_recording and stop_recording functions. This allows overwriting fields like call-id to start/stop recording for different ongoing calls (for example from a rtimer route).
> Add stop_recording function, and make start/stop_recording functions accept flags 

- src/modules/p_usrloc/location.sql
Add columns referenced by [p_usrloc_mod.c](https://github.com/kamailio/kamailio/blob/6c01e2692d5ff56dda54d21469d32c4d3dcbfbff/src/modules/p_usrloc/p_usrloc_mod.c#L65)
> p_usrloc: Fix #1265: missing columns in location.sql file.

- pkg/kamailio/alpine_docker/build.sh
Fixed alpine docker build when git repo url use ssh
> pkg/kamailio/alpine_docker: Added support ssh git repo url

- src/modules/usrloc/ul_rpc.c
The first commit unlocks a usrloc slot when "ul.dump brief" fails. Otherwise, it stays locked forever.
The second one changes "ul.dump" output format and adds "Domains" array that includes all location domains.  Without this fix "kamctl ul show" shows only the first domain.
> Usrloc fix

- src/modules/sipcapture/doc/sipcapture_admin.xml
- src/modules/sipcapture/examples/kamailio.cfg
- src/modules/sipcapture/hep.c
- src/modules/sipcapture/sipcapture.c
Backport fixes for sipcapture to 5.0.
Important for $hep() to work properly. Mostly from GH #1191
> Sipcapture backport

- src/Makefile.defs
Don't let Makefile.defs complain about old compiler when using gcc 7.
This also gives gcc 7 the same default values as the other recent gcc versions.
> Support gcc 7+.

- pkg/kamailio/obs/kamailio.spec
Would like these modules directly from obs.
> pkg/obs: enable the same modules for RHEL 7 as for Centos 7

- src/modules/tsilo/ts_hash.c
- avoid crash by fixing "first" and "last" pointers of of the ts_entry_t after ts_urecord_t deletion
tsilo module didn't reset "**first**" and "**last**" pointers of a doubly linked list of **ts_urecord_t** objects. It worked correctly only when there were no hash collisions and each ts_entry slot had only one **ts_urecord_t** object. To faster reproduce the problem one can set **modparam("tsilo", "hash_size", 2)** and run a light load test (5...10 simultaneous call setups).
> tsilo: fix internal data structures

- src/modules/rtpengine/rtpengine.c
This was an odd one. I can't see how `read_sdp_pv` ever worked. When the old SDP is deleted with `del_lump` from the SIP `msg`, the lump pointer is calculated assuming that `body` is a pointer relative to `msg`. When `read_sdp_pv` is set, `body` pointer is set to something entirely different and doing pointer maths relative to `msg` causes integer overflows and results in a segfault on `del_lump`.
This change explicitly gets the body pointer (`cur_body`) relative to `msg` before trying to `del_lump`. If it's preferable, I can have it only do this if `read_sdp_pv` is set but I figured it's not a heavy operation and it's safer to always do it.
> rtpengine: fixed segfault when using read_sdp_pv

- src/modules/http_client/functions.c
While preparing query_params, "useragent" was missed - add it. 
As before User-Agent was never present in HTTP requests.
not sure if it has to be backported
> http_client: add missed useragent parameter

- pkg/kamailio/obs/kamailio.spec
- pkg/kamailio/rhel/README.md
Also need do cherry-pick to 5.1 branch
> OBS spec update for 5.1.0 release

- src/modules/debugger/debugger_mod.c
- src/modules/dialog/dialog.c
- src/modules/kex/kex_mod.c
- src/modules/lcr/lcr_mod.c
- src/modules/maxfwd/maxfwd.c
- src/modules/nathelper/nathelper.c
- src/modules/path/path_mod.c
- src/modules/permissions/permissions.c
- src/modules/rtpengine/rtpengine.c
- src/modules/sipcapture/sipcapture.c
- src/modules/textops/textops.c
- src/modules/textopsx/textopsx.c
- src/modules/xhttp/xhttp_mod.c
Updated some issues I found in the KEMI exports while reviewing the implementation. There is some name change there hence the breaking change.
> Patches to the KEMI framework exports

- src/modules/presence/subscribe.c
when using presence with dbmode = 3, the contact is never updated. if using dbmode != 3 the contact is updated in the hash table.
we've seen some UAs re-subscribing with a different contact port of the initial subscribe. it works with dbmode != 3 but not with dbmode == 3
this should be backported to 5.0/5.1 branch
Thanks
> presence: update contact in update_subs_db

- src/modules/nat_traversal/nat_traversal.c
when using the below script blocks for handling SUBSCRIBE messages, the nat_keepalive does not work as expected.
```
#!ifdef NAT_TRAVERSAL_ROLE
route[PRESENCE_NAT]
{   
force_rport();
if (client_nat_test("3")) {
if(is_first_hop())
set_contact_alias();
nat_keepalive();
}
}
#!endif
route[HANDLE_SUBSCRIBE]
{
if (!is_method("SUBSCRIBE")) {
return;
}
#!ifdef NAT_TRAVERSAL_ROLE
route(PRESENCE_NAT);
#!endif
if (!t_newtran()) {
sl_reply_error();
exit;
}
if(has_totag()) {
route(HANDLE_RESUBSCRIBE);
} else {
route(HANDLE_NEW_SUBSCRIBE);
}
t_release();    
exit;
}
```
i believe this should be backported to stable branches
Thanks
> nat_traversal: handle local generated transactions

- src/modules/tm/uac.c
- avoid crash when local-request event route is triggered inside another one
Nested calls to tm:local-routes generate a crash.
I've been recently experiencing this with the following scenario:
- event_route[tm:local-request] defined
- dialog module's send_bye param set to 1 
- htable module's enable_dmq param set to 1
When a dialog reaches the timeout, the BYE generated by dialog module triggers the tm:local-request event route. One of the operations done in my scenario is an htable decrement on a table for which dmq replication is enabled. This trigger again the tm event route (because dmq is using tm uac). When the execution of the 2nd route ends the first one is continued, but the sip_msg structure is at this point corrupted because is declared static in  t_run_local_req.
> tm: make t_run_local_req reentrant

- src/modules/presence/hash.c
- src/modules/presence/subscribe.c
we noticed some phones and upstream clusters sending
diferent route / contact after initial subscription.
this commit adds contact and record_route to updated columns for dbmode = 2
also adds user_agent to initial save
and a simple fix for getting the correct message in debug
should be backported to stable/maintained to fix issue in existing deployments
> presence: extra columns updated for dbmode 2

- src/lib/srdb1/schema/pr_active_watchers.xml
some code paths in presence module set the `reason` field to null causing problems updating the database.
> schema: allow null in active_watchers reason

- src/modules/presence/subscribe.c
missed update from 49272f23b22445415721766709bf5841865e8609
should be backported with 816d2cd44d96245b5a5b53505d6fbc350bda378c
> presence: update record_route in database

- src/modules/ims_registrar_pcscf/save.c
- src/modules/ims_registrar_pcscf/sec_agree.c
- src/modules/ims_registrar_pcscf/sec_agree.h
- src/modules/ims_usrloc_pcscf/pcontact.c
- [X ] Commit message has the format required by CONTRIBUTING guide
- [X ] Small bug fix (non-breaking change which fixes an issue)
- [X ] Tested changes locally
ims_registar_pcscf has functionality which parses sec-agree parameters from REGISTER and saves them in usrloc contact. However the memory allocated for the security_t data structure was allocated in the private memory, instead on the shared memory.
> ims_registar_pcscf: security_t parameters should be allocated on shared memory

- src/modules/usrloc/udomain.c
- src/modules/usrloc/urecord.c
- src/modules/usrloc/urecord.h
Hi there!
So my case, and why I did not use the existing code:
- incoming INVITE to a user with 2 records in usrloc (1st - UDP, 2nd - TLS)
- some time before lookup, TLS connect of 2nd device is closed, but usrloc record still exists (it going to be removed in the next iteration of timer)
- after lookup(location) - 2 branches are created
- send to 1st - UDP succeed
- send to 2nd - TLS failed. And here is my headache.
-- I want to send push notification to this device
-- I set t_on_branch_failure
-- if I try failure_exec_mode=1 - I get control, and I am able to send push, but I need to wait until fr_timer fire (I wanted not to wait, and send immediately)
The idea of changes:
- usrloc -> get_urecord: if t_contact has tcpcon_id & …
>  usrloc: extend handle_lost_tcp use for get_urecord

- src/modules/acc/acc_cdr.c
- src/modules/acc/doc/acc_admin.xml
acc.time_mode modparam allows storing acc transactions time field using the output of gmtime() when it is set to 4.
This commit aims to reuse this modparam for cdr entries (start_time, end_time). This way, if time_mode is 4, both acc and cdr entries will be stored in gmtime.
> acc: use acc.time_mode to save cdrs in gmtime

- src/modules/app_lua/Makefile
- src/modules/app_lua/README
- src/modules/app_lua/doc/app_lua_admin.xml
Added LUAJIT variable to build app_lua module against LuaJIT compiler (version 5.1). If this variable is not set users still build app_lua module against standard Lua.
E.g:   $ LUAJIT="yes" make modules modules=modules/app_lua  # Build against LuaJIT
$ make modules modules=modules/app_lua  # Build against standard Lua.
(Warning: LuaJIT version is 5.1 so scripts prepared for higher Lua versions may not work with LuaJIT)
> app_lua: LUAJIT variable to build agains LuaJIT compiler

- src/modules/http_async_client/http_async_client_mod.c
set_query_params() was checking if those variables had a value to copy them
#1386
> http_async_client: fix initialization of tls_client_* and tls_ca_path

- src/modules/acc/acc_cdr.c
- src/modules/acc/acc_mod.c
- src/modules/acc/acc_mod.h
- src/modules/acc/doc/acc_admin.xml
- allow custom cdr fields defined with cdr_extra modparam to be saved
as null. Before this change, cdr_extra variables not defined in config
operation (or set to $null) were saved as empty string (''). This commit makes
possible to save them as NULL value.
- new modparam to make this behaviour configurable: cdr_extra_nullable.
Set it to 1 to enable this new behaviour (default value: 0)
> acc: Allow nullable cdr extra fields

- pkg/kamailio/obs/kamailio.init
- pkg/kamailio/obs/kamailio.spec
kamailio.spec: Move the ims_ocs module into the ims RPM. It has a dependancy on libkamailio_ims.so
kamailio.init: Pass the .cfg file as a parameter when starting or syntax checking. Use the pidfile to kill only the relevant instance.
This makes it easier to reuse the same script when running multiple kamailio instances on the same server. Only the environment vars at the top need to be changed.
> Minor improvements to RPM packaging

- src/modules/nathelper/doc/nathelper_admin.xml
- src/modules/nathelper/nathelper.c
With regards to your comment on ticket #1298 that the nathelper force_socket should be parsed correctly. Plus I found the time to work on it :-)
> nathelper: allow port to be specified in force_socket, fixes #1298

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/dispatcher.c
- src/modules/dispatcher/doc/dispatcher_admin.xml
Adds a new option to RPC command `dispatcher.set_state` to bulk update all destinations as part of a dispatcher set. The way we use dispatcher sets this comes in handy in a few cases.
> Dispatcher set_state "all"

- src/modules/http_async_client/async_http.c
when suspend_transaction is false
As suggested at #1391 to avoid shared memory leak
> http_async_client: cleanup avps/xavps after exec route on Http worker

- src/modules/json/doc/json_admin.xml
- src/modules/json/json_funcs.c
- src/modules/json/json_funcs.h
- src/modules/json/json_mod.c
- src/modules/json/json_trans.c
- src/modules/json/json_trans.h
this was borrowed from the `kazoo` and `nsq` module json transformations
i think it makes the most sense in this module as I'd like to use the transformation without loading the `kazoo` or `nsq` modules.
It can be very useful for parsing json data from pseudo-variables like $rb.
if this can be merged, I will deprecate the transformation in `nsq` and maintain this code.
> json: add transformation

- src/modules/ims_usrloc_scscf/usrloc_db.c
When writing to query_buffer with the help of the snprintf() function,
the result of the functio is written to variable query_buffer_len
instead of to the query_buffer.len itself. This leads to core dump
in some cases. Replaced "_" by "." in "query_buffer_len ="
When linking a Contact to an IMPU during SIP REGISTER in S-CSCF, a core dump can happen due to missing assignment of length to query_buffer.
Added the assignment.
> ims_usrloc_scscf: assignment of length missing for query_buffer in db_link_contact_to_impu()

- src/modules/ims_usrloc_scscf/subscribe.c
In update_subscriber() function, when the rs is assigned to the subs,
it is missing the record_route component, which leads to core dump in
some scenarios.
Without this bugfix, a core dump can happen during SIP REGISTER in S-CSCF.
Reason: the record_route component was forgotten to be assigned when assigning rs to Subs in the update_subscriber() function.
This assignment was added.
> ims_usrloc_scscf: missing assignment of record_route

- src/lib/srdb1/schema/pr_presentity.xml
- src/modules/dmq/dmq.c
- src/modules/dmq/dmqnode.c
- src/modules/dmq/dmqnode.h
- src/modules/presence/Makefile
- src/modules/presence/doc/presence_admin.xml
- src/modules/presence/notify.c
- src/modules/presence/notify.h
- src/modules/presence/presence.c
- src/modules/presence/presence.h
- src/modules/presence/presence_dmq.c
- src/modules/presence/presence_dmq.h
- src/modules/presence/presentity.c
- src/modules/presence/presentity.h
- src/modules/presence/publish.c
- utils/kamctl/db_berkeley/kamailio/presentity
- utils/kamctl/db_berkeley/kamailio/version
- utils/kamctl/db_sqlite/presence-create.sql
- utils/kamctl/dbtext/kamailio/presentity
- utils/kamctl/dbtext/kamailio/version
- utils/kamctl/mongodb/kamailio/presentity.json
- utils/kamctl/mongodb/kamailio/version-create.mongo
- utils/kamctl/mysql/presence-create.sql
- utils/kamctl/oracle/presence-create.sql
- utils/kamctl/postgres/presence-create.sql
- utils/kamctl/xhttp_pi/pi_framework.xml
- utils/kamctl/xhttp_pi/presence-mod
- utils/kamctl/xhttp_pi/presence-table
Enabled via module parameter.
First commit:
- initial implementation
- replication of presentity updates over DMQ
- adds ruid column for matching across cluster
Tested and in use across small production cluster (‘dialog’ and ‘message-summary’ events).
Need to update docs prior to merging but raising PR first to hear any feedback.
> presence: dmq integration

- src/modules/ims_usrloc_scscf/usrloc_db.c
When writing to query_buffer with the help of the snprintf() function,
the result of the functio is written to variable query_buffer_len
instead of to the query_buffer.len itself. This leads to core dump
in some cases. Replaced "_" by "." in "query_buffer_len ="
(cherry picked from commit 11c179ab232222f1c78f19557032afd49bef7324)
Created by cherry-pick from master
> ims_usrloc_scscf: assignment of length missing for query_buffer in db_link_contact_to_impu() - 5.1

- src/modules/presence/presentity.c
This is a minor bugfix for earlier commit (b7a5016).
> presence: delay freeing generated etag string

- src/modules/ndb_redis/doc/ndb_redis_admin.xml
- src/modules/ndb_redis/ndb_redis_mod.c
- src/modules/ndb_redis/redis_client.c
This change provides support in `ndb_redis` for a scenario where the Redis server is part of a cluster _and_ the IP addresses of the nodes are either not known in advance or are subject to change (for example in case the cluster sees new nodes being added).
Before this change `ndb_redis` supports the `cluster` option, so that after a `MOVED` response from a node `ndb_redis` will perform again the same query but towards the redirection target. The caveat is that `ndb_redis` must know in advance which IP addresses will be used by the nodes.
A`MOVED` response is in the form `-MOVED 1234 1.2.3.4:6379.`, indicating the hash for the request and the redirection target IP address and port.
Every node in the cluster must have a modparam entry …
> ndb_redis: dynamic discovery of nodes

- src/modules/dispatcher/dispatcher.c
when dynamically loading/querying the dispatcher list at runtime, empty dslist logs as error which misleads log monitoring tools looking for real errors
> dispatch: change log level to debug for rpc list empty list

- src/modules/tm/uac.c
While testing Kamailio instance with multiple interfaces I noticed that dispatcher probing does not use the socket defined on dispatcher ```list_file```.
By setting flag ```SND_F_FORCE_SOCKET```, in tm module, dispatcher probing or tm t_uac_send() is sourced as per ```socket``` attribute.
Tested on FreeBSD 11.1 and Ubuntu 16.04.
> tm: flag core to use forced socket when uac socket is set

- src/modules/app_python3/app_python_mod.c
- src/modules/app_python3/app_python_mod.h
- src/modules/app_python3/apy_kemi.c
- src/modules/app_python3/doc/app_python3_admin.xml
- src/modules/app_python3/python_exec.c
Implement script reloading by copying the method used in app_lua: the version of the script is incremented by RPC. 
For each worker, the next time it handles a method, python_exec.c:apy_exec() 
will check for a newer version and reload, if necessary.
Set a lock so the script reload only occurs at depth 0 (in the unlikely case
that apy_exec() is called recursively).
This is not thread-safe as we are using a process-wide lock: don't call back
into apy_exec() from a Python C extension that uses threads.
For Pythonistas, we are reloading the module, not reinitializing the interpreter.
Standard caveats about reloading modules apply. E.g, references in the old module
that are not redefined in the newer module remain.
> app_python3: implement script reloading

- src/modules/app_python/apy_kemi.c
app_python: kemi add int-int-str to accept list of wrapper arguments
- used, for example, by the t_continue() wrapper
> app_python: kemi accept int-int-str for t_continue

- src/modules/app_python/app_python_mod.c
Calling PyErr_Print() clears the error indicator and hides the real cause of failing to load
the module as the output is lost (module has no stderr).
The error should be left to python_handle_exception() to display via LM_ERR.
> app_python: don't hide the real exception on load failure

- src/modules/sqlops/sql_api.c
Make the result string parameter optional in the sqlops_do_query C API function
>  sqlops: sqlops_do_query - Make result parameter optional in C API

- src/core/onsend.h
Currently we need a onsend_route{} (empty is ok) block in config before KEMI ksr_onsend_route() is invoked. The latter will override the route block.
This PR will unconditonally invoke KEMI ksr_onsend_route() so we do not need a placeholder in config.
For discussion: this will unconditionally invoke ksr_onsend_route() so it might break scripts that don't have an implementation. 
I'm not too clear about the error handling in run_onsend(): it's possible that if KEMI ksr_onsend_route throws error (not implemented rather than real error) then the message might be dropped, so this might surprise script writers. Since ksr_onsend_route() is optional it's hard to tell the difference between a real error and "not implemented is not an error".
> core: invoke KEMI ksr_onsend_route() unconditionally in cfgengine

- src/modules/usrloc/README
- src/modules/usrloc/doc/usrloc_admin.xml
- src/modules/usrloc/udomain.c
- src/modules/usrloc/usrloc_mod.c
- src/modules/usrloc/usrloc_mod.h
In usrloc module we have server_id_filter parameter which switches on filtering of location records by server id during load. This fix improves this functionality to use this filter in cleanup procedure to avoid cleaning of expired db records which are written by another kamailio instance to keep their cache correct.
> usrloc: cleanup by server_id.

- src/modules/textops/textops.c
Current remove_hf_exp not works as expected. This fix it.
> textops: Fixed remove_hf_exp arguments params

- src/modules/db_redis/redis_table.c
> CC (clang) [M db_redis.so]		redis_table.o
> redis_table.c:728:27: warning: comparison of constant -1 with expression of type 'unsigned char' is always false [-Wtautological-constant-out-of-range-compare]
>                     if (c == EOF) {
>                        ~ ^  ~~~
> redis_table.c:754:27: warning: comparison of constant -1 with expression of type 'unsigned char' is always false [-Wtautological-constant-out-of-range-compare]
>                     if (c == EOF) {
>                         ~ ^  ~~~
> redis_table.c:794:40: warning: comparison of constant -1 with expression of type 'unsigned char' is always true [-Wtautological-constant-out-of-range-compare]
>                     if (c != '\n' && c != EOF) {
>                                     ~ ^  ~~~
> redis_table.c:807:20: …
> db_redis: fix compilation warning

- src/modules/tls/doc/hsm_howto.xml
- src/modules/tls/doc/params.xml
- src/modules/tls/doc/tls.xml
- src/modules/tls/tls_domain.c
- src/modules/tls/tls_map.c
- src/modules/tls/tls_map.h
- src/modules/tls/tls_mod.c
- src/modules/tls/tls_server.c
- Rebased to: dc8faaf57a9c85b
-----
- add support for OpenSSL engine and loading private keys from HSM
- for when kamailio is a TLS edge proxy and needs to use HSM
- currently we initialize the engine in worker processes as PKCS#11
libraries are not guaranteed to be fork() safe
- new config params
- engine: name the OpenSSL engine
- engine_config: an OpenSSL config format file used to bootstrap engines
- engine_algorithms: list of algorithms to delegate to the engine
- tested with Gemalto SafeNet Luna (AWS CloudHSM) with RSA and EC private keys
TLSv1.2 and PFS cipher suites
- add support for OpenSSL engine and loading private keys from HSM
- for when kamailio is a TLS edge proxy and needs to use HSM
- currently we initialize the …
> tls: add support for OpenSSL engine and private keys in HSM

- src/modules/ims_charging/ims_ro.c
according to RFC 4006 the Result-Code in Multiple-Services-Credit-Control AVP is optional.
resume_on_initial_ccr() stops proceeding CCA if no Result-Code in MSCC and goes to error1 even though the Result-Code on CCR itself is 2001 (SUCCESSFUL)
> ims_charging: fixed check result code at mscc level

- src/modules/nathelper/nathelper.c
- nathelper sends ping only if nat flag is specified, but if ping_nated_only=0 it should ping all contact in any case.
We need to check presence of nat flag with check of ping_nated_only parameter to avoid situation when flag is not specified by user wants to ping all contacts and don't get any pings.
> nathelper: it doesn't ping contacts if ping_nated_only=0

- src/modules/p_usrloc/doc/p_usrloc_admin.xml
- src/modules/p_usrloc/p_usrloc_mod.c
- src/modules/p_usrloc/p_usrloc_mod.h
- src/modules/p_usrloc/ul_db.c
- src/modules/p_usrloc/ul_db.h
- src/modules/p_usrloc/ul_db_watch.c
- src/modules/p_usrloc/ul_db_watch.h
- The new parameter "mdb_availability_control" overwrites the "write_on_master_db" parameter based on the availability of master database.
> p_usrloc: new parameter "mdb_availability_control" has been created.

- src/modules/ims_usrloc_scscf/impurecord.c
When old (maybe forgotten) Contacts expire in S-CSCF, then current - wanted - calls will be deleted, which is not wanted. Reason is the usage of "=" Operator instead "==" Operator in ims_usrloc_scscf module.
> Bugfix trash expires

- src/modules/lcr/doc/lcr_admin.xml
- src/modules/lcr/lcr_mod.c
- src/modules/lcr/lcr_mod.h
LCR module exports information about selected gateways in flags and tag AVPs if you define corresponding modparams (flags_avp and tag_avp).
This PR exports a similar optional AVP that stores the id of the rule that selected each gateway. For that, a new modparam is added (rule_id_avp).
> lcr: export rule_id_avp with matching rule id

- src/modules/dialog/dlg_cseq.c
to avoid null pointer access for malformed messages
after adding modparam("dialog", "track_cseq_updates", 1) and getting some malformed SIP  kamailio crushed
> dialog: check CSeq careful with track_cseq_updates

- src/modules/ims_isc/ims_isc_mod.c
- src/modules/ims_isc/isc.c
- src/modules/ims_isc/isc.h
The ims_isc module cannot cope with the fact that asynchronous Response from HSS (Diameter SAA message) is received as "FAILURE_ROUTE". ims_isc module erroneously assumes, it is an answer from the AS. Change: added a "firstflag", which makes a difference between first call (SAA from HSS) and subsequent call (FAILURE ROUTE from AS).
> Bugfix issue 1168 - Unregistered Terminating Services (PSI) Configured at HSS

- src/modules/ims_usrloc_scscf/impurecord.c
in function unlink_contact_from_impu() (in file impurecord.c) an
assignment "=" is used instead of a comparision operator "==". This
leads to mess, when old contact expires.
This is the pull request for branch 5.1, which has been created by "cherry-pick" from the original commit
> ims_usrloc_scscf: bugfix Contct is removed when old Contct expires

- src/modules/ims_isc/ims_isc_mod.c
- src/modules/ims_isc/isc.c
- src/modules/ims_isc/isc.h
Function isc_match_filter() got a new local variable firstflag in
order to handle the case where a FAILURE_ROUTE callback is
received before the first AS has been contacted.
The firstflag is also forwarded to function isc_forward() as
parameter.
This is the 5.1 pull request, which was created by cherry-pick from the master pull request
> ims_isc: initial fix of issue #1168

- src/Makefile
I noticed that ```kamailio -I``` and ```kamailio -V``` do not give git version hash anymore.
This commit fixes at least kamailio -I and -V output, I think.
I don't know / remember if further adjustment is needed for other REPO_ constants.
```
#define REPO_VER ""
#define REPO_HASH "unknown"
#define REPO_STATE ""
```
```
$ src/kamailio -I|grep Source
Source code revision ID: unknown
```
```
#define REPO_VER "5c48b2"
#define REPO_HASH "5c48b2"
#define REPO_STATE ""
```
```
$ src/kamailio -I|grep Source
Source code revision ID: 5c48b2
```
> src/Makefile: fix source code revision output

- src/modules/dialog/dialog.c
- src/modules/dialog/dlg_db_handler.c
As you can see looking at the modifications stats counters where increment twice.
Hi @oej, If you find a few minutes  you could review this MR. 
Not sure if you remember, this was introduced in a bug fix (see below)
I kept some of your modifications, they seem more strait forward anyway.
```
commit b0cd09d2b451005a736396e6f38eac139ec31301
Author: Olle E. Johansson <oej@edvina.net>
Date:   Wed May 11 21:59:44 2016 +0200
dialog Make sure statistics are updated when initializing from database
Issue #424
```
> [dialog] stats incremented twice

- src/modules/ims_usrloc_scscf/impurecord.c
impurecord.c: corrected small bug in remove_impucontact_from_list()
corrected 2 small bugs in function remove_impucontact_from_list:
nullify tail->next if tail removed
in remove mid-list the pointer to previous contact was not set correctly
These issues were brought up by https://github.com/thulasizwe-n at another pull request:
https://github.com/kamailio/kamailio/pull/1547#issuecomment-395767031
> ims_usrloc_scscf: bugfix erraneous unlinking of deleted contact

- src/modules/app_python3/apy_kemi.c
The kemi function argument type checks before the arguments are extracted from the python tuple were  not strict enough, resulting in the wrong value being passed to the functions.
> app_python3: fix kemi function call argument type checks

- src/modules/tm/config.c
- src/modules/tm/config.h
- src/modules/tm/doc/params.xml
- src/modules/tm/t_reply.c
- src/modules/tm/tm.c
> tm: add relay_100 config parameter to support stateless operation

- src/modules/benchmark/benchmark.c
- src/modules/benchmark/benchmark.h
- src/modules/benchmark/doc/benchmark_admin.xml
Added two RPC functions to benchmark module:
timer_list and timer_name_list
timer_list shows info for every timer (last complete period and global data)
timer_name_list shows same info as timer_list but for a timer selected by its name.
> Bench branch pull

- src/modules/dialog/dlg_dmq.c
- prevents looping back to other nodes
- reported by Patrick Murphy on sr-users list (https://lists.kamailio.org/pipermail/sr-users/2018-July/102322.html)
> dialog: unset DMQ flag on replicated dialog removal

- src/modules/presence/subscribe.c
due to the way update_db_subs_timer_dbonly handles the query to the
database (getting all records), if for some reason a burst of
terminating subscriptions occurs, most likely there will be no package
memory to process all expiring subscriptions.
this commit uses the same pattern as other routines in presence by using
db_fetch_query with fetch_rows parameter module.
because we create the subs in the loop and then call handle_expired_subs
to avoid locking issues the subscription should already be deleted from
the database when it returns from handle_expired_subs, there's no reason
to issue the last delete, and that was removed.
> presence: limit the number of subscriptions handled in timer_dbonly

- src/modules/ims_ipsec_pcscf/Makefile
- src/modules/ims_ipsec_pcscf/cmd.c
- src/modules/ims_ipsec_pcscf/cmd.h
- src/modules/ims_ipsec_pcscf/doc/Makefile
- src/modules/ims_ipsec_pcscf/doc/ims_ipsec_pcscf.xml
- src/modules/ims_ipsec_pcscf/doc/ims_ipsec_pcscf_admin.xml
- src/modules/ims_ipsec_pcscf/ims_ipsec_pcscf_mod.c
- src/modules/ims_ipsec_pcscf/ipsec.c
- src/modules/ims_ipsec_pcscf/ipsec.h
- src/modules/ims_ipsec_pcscf/run_spi_list_tests.sh
- src/modules/ims_ipsec_pcscf/spi_gen.c
- src/modules/ims_ipsec_pcscf/spi_gen.h
- src/modules/ims_ipsec_pcscf/spi_list.c
- src/modules/ims_ipsec_pcscf/spi_list.h
- src/modules/ims_ipsec_pcscf/spi_list_tests.c
This is an implementation of sec-agree used in IMS with IPSec. It's not a complete sec-agree implementation, only the flows used by IMS. The code is usable, but needs a few improvements, which I plan to push in the near future. **My work is based on the implementation in OpenIMSCore.**
For IPSec implementation the XFRM framework from the Linux kernel is used. Security association (SA) and Policies creation/removal is performed via netlink messages. For this reason the module depends on libmnl (a minimalistic netlink library).
As XFRM is Linux specific, the code is not portable and can't be used on operating system different from Linux. The code will not compile on *BSDs too. However all platform specific code resides in ipsec.c so …
> ims_ipsec_pcscf: sec-agree implementation for IMS

- pkg/kamailio/obs/kamailio.spec
(cherry picked from commit 9ac132ba3a47f13cf7b58839dde34a04348340c9)
User originally reported this for 5.0 branch.
So i created back port for 5.0 branch too
> pkg/kamailio: Defined correct dependences for perl module (#1615)

- src/modules/topos/doc/topos_admin.xml
- src/modules/topos/topos_mod.c
- src/modules/topos/tps_storage.c
When using TLS  with TOPOS the remote UAS could open a new TLS socket to the contact header.
The contact header must contain a domain name with a signed certitificate.
Adding the parameter to TOPOS module to control the host part of the contact headers
```
modparam("topos", "contact_hostname", "proxy.domain.com")
```
Default behavior is left unchanged
I will update documentation it his modification is confirmed  to be valuable.
Else I would be curious to know how this should be handled differently.
> topos: adding param contact_hostname

- src/modules/registrar/doc/registrar_admin.xml
- src/modules/registrar/registrar.c
- src/modules/registrar/regpv.c
I've added the ability to use the `usrloc:contact-expired` event route with KEMI routing scripts. I've tested with both the native scripting language and `app_lua` and it seems to be working.
> registrar: add event_callback parameter and relevant documentation

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/doc/dispatcher_admin.xml
I was looking for a solution to set a dedicated From URI in OPTIONS
requests to a specific dispatcher target.
ds_ping_from (
https://www.kamailio.org/docs/modules/devel/modules/dispatcher.html#dispatcher.p.ds_ping_from)
applies globally, while I needed the granularity of a single target.
I can just add an attribute to the others, e.g. instead of
```
1 sip:127.0.0.1:7070 <http://127.0.0.1:7070> 0 1
```
something like:
```
1 sip:127.0.0.1:7070 <http://127.0.0.1:7070> 0 1 ping_from=sip.custom.com
```
When the ping_from attribute is not specified, the general ds_ping_from
applies and is used.
This would save me from a solution like intercepting the outgoing OPTIONS
and manipulating the From header.
> dispatcher: add ping_from attribute

- src/core/async_task.c
- src/core/async_task.h
- src/core/cfg.lex
- src/core/cfg.y
- src/modules/async/async_sleep.c
- src/modules/db_mysql/km_dbase.c
- src/modules/db_unixodbc/dbase.c
Operations performed in async workers can be blocking (e.g. DB inserts). Sometimes, under high load, this can lead the unix socket queues to be full, thus blocking the main workers. With this new parameter we can have the choice to open the socket pair in non blocking mode, so returning an error if the task cannot be sent to …
> Non blocking async socket

- src/modules/nathelper/nathelper.c
previous PR #1655 was wrong and tests at the time didn't hit the correct path in the code, sorry for that.
this pr reverts #1655 and properly initializes a variable
> nathelper: initialize local variable

- src/core/parser/sdp/sdp.c
- src/core/parser/sdp/sdp.h
- src/core/parser/sdp/sdp_helpr_funcs.c
- src/core/parser/sdp/sdp_helpr_funcs.h
- src/modules/sdpops/doc/sdpops_admin.xml
- src/modules/sdpops/sdpops_mod.c
Add PV $sdp(sess_version) for reading and writing SDP o= -line attribute sess-version.
Special integer value -1 increments current value.
> sdpops: fetch and manipulate SDP o= -line sess-version attribute

- src/modules/sipcapture/sipcapture.c
- [✓] Commit message has the format required by CONTRIBUTING guide
- [✓] Commits are split per component (core, individual modules, libs, utils, ...)
- [✓] Each component has a single commit (if not, squash them into one commit)
- [✓] No commits to README files for modules (changes must be done to docbook files
- [✓] Small bug fix (non-breaking change which fixes an issue)
- [✓] PR should be backported to stable branches
- [✓] Tested changes locally
After enabling clang -Wall on, this warning showed up:
> sipcapture.c:2580:5: warning: variable 'corrtmp' is used uninitialized whenever 'if' condition is false
>       [-Wsometimes-uninitialized]
>         if(correlation_id) {
>            ^~~~~~~~~~~~~~
> sipcapture: initialize variable

- utils/kamctl/kamctl.base
The filter has a regex looking for a literal '{' in the beginning of a
line. Some awk implementations interpret this as a meta character, so
the regex is deemed broken. Example with busybox awk (POSIX):
`root@hank2:~# kamctl ps`
`awk: bad regex '^{.+"id"[ 	]*:[ 	]*[0-9]+[ 	]*}$': Invalid contents of {}`
`root@hank2:~#`
To fix this enclose the character in square brackets. This always
matches for a literal '{' and is portable.
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>
Hi all,
I was trying to run kamctl on OpenWrt and the regex failed. I found a (closed) issue and the remedy was to use gawk. But it's actually easy to fix in the regex and if I can use busybox's awk I don't need to install gawk, so it saves some space. OpenWrt is usually run on embedded so space is often an issue …
> kamctl: make jsonrpc filter portable

- src/modules/db_postgres/km_pg_con.c
Required for postgresql usage in kazoo cluster
> db_postgres: Fixed blob hex encoding (#1255)

- pkg/kamailio/Makefile
- pkg/kamailio/obs/kamailio.spec
Please look ticket #1676
RPM packaging for `5.2` release
Also wanted for `5.1` branch
> pkg/kamailio: Fixed db_redis RPM packaging after ee95675

- src/modules/evapi/evapi_dispatch.c
It was assigning the length instead of comparing it.
- [X ] Commit message has the format required by CONTRIBUTING guide
- [X ] No commits to README files for modules (changes must be done to docbook files
- [ X] Small bug fix (non-breaking change which fixes an issue)
The tag length was being assigning instead of being compared.
> evapi: minor fix in tag length compare

- src/modules/pdb/common.h
- src/modules/pdb/pdb.c
buf in pdb_msg_dbg should correctly accomodate for pdb_bdy size
pdb_hdr + pdb_bdy should add to pdb_hdr.length (max 255)
Can I also port this back to 4.4? Thank you.
> pdb: fix SIGABRT in case of too long uris

- src/modules/usrloc/udomain.c
usrloc: call contact expired call back for a domain with db_mode: DB_ONLY; database rows are removed by the timer function: db_timer_udomain
- [X ] New feature (non-breaking change which adds new functionality)
- [ X] PR should be backported to stable branches
- [X ] Tested changes locally
Currently call contact expired call back for a domain with db_mode: DB_ONLY doesn't callback function for "usrloc:contact-expired" to carry out call back application actions since database rows are removed by the timer function: db_timer_udomain. There is addition of new function  udomain_contact_expired_cb which will only call the call back function when contact are being removed from the database.
> usrloc: call contact expired call back for a domain with db_mode: DB_ONLY

- src/modules/dialplan/dialplan.c
In the struct `int param_no` is set to `2`. But `dp_replace()` has actually three
parameters `(dpid, inval, outvar)`, so kamailio's cfg parser fails when
`dp_replace()` is called:
```
yyparse(): cfg. parser: failed to find command dp_replace (params 3)
yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 366, column 45: unknown command, missing loadmodule?
```
This commit fixes `int param_no` to address this.
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>
Hi all,
When trying out dp_replace() kamailio (5.1.6) wouldn't start. It was expecting 2 parameters instead of 3. This PR fixes that.
Kind regards,
Seb
> dialplan: fix dp_replace() in cmd_export_t struct

- pkg/kamailio/obs/kamailio.spec
- pkg/kamailio/obs/meta
RPM spec update for 5.1 branch
> RPM spec update for 5.1 branch

- pkg/kamailio/alpine/APKBUILD
This PR is need for `5.2` branch.
On next stable Alpine release this will be fixed and we revert back this PR
> pkg/kamailio/alpine: Fixed docker image build for 5.2 branch

- pkg/kamailio/obs/kamailio.service
- pkg/kamailio/obs/kamailio.spec
Need back port to 5.2 branch.
For 5.1 branch also wanted but will be merged with conflict. Backport into 5.1 is optional. Then i will create dedicated PR
> RPM spec update

- pkg/kamailio/deb/bionic/kamailio.service
- pkg/kamailio/deb/buster/kamailio.service
- pkg/kamailio/deb/debian/kamailio.service
- pkg/kamailio/deb/jessie/kamailio.service
- pkg/kamailio/deb/sid/kamailio.service
- pkg/kamailio/deb/stretch/kamailio.service
- pkg/kamailio/deb/xenial/kamailio.service
- pkg/kamailio/oracle/el7/kamailio.service
Please see conversation on ML for reference:
https://lists.kamailio.org/pipermail/sr-users/2018-November/103668.html
> pkg/kamailio/deb: optimize systemd units

- src/core/msg_translator.c
- src/modules/textops/textops.c
get_body_part functions gives error even if content is not multipart. Fixed for non-multipart contents and set all contents for non-boundary params
> textops: fixed get_body_part function for non-multipart contents error

- src/modules/dialog/dlg_db_handler.c
> dialog: fix typo in warn message

- misc/examples/kemi/kamailio-basic-kemi-python.py
Kemi framework python example configuration had a problem when handling CANCEL messages. Called function needed 'msg' attribute.
> misc/examples/kemi: Added 'msg' argument to ksr_route_relay

- src/modules/ims_charging/doc/ims_charging_admin.xml
ims_charging : doc is fixed
Ro_CCR function doesnt get parameter like domain. it removed from doc.
> ims_charging : doc is fixed

- src/modules/rtpengine/doc/rtpengine_admin.xml
- src/modules/rtpengine/rtpengine.c
Kamailio crashes when codec-flags value are not setted with codecs. it is fixed.
codec-flags information added to document.
An example is added to document.
> rtpengine : crash is fixed and codec flags added to doc

- src/core/msg_translator.c
Function check_boundaries() in msg_translator.c not handling property the length of the buffers when it needs to repair the boundary, getting a negative lenght and causing a segmentation fault.
Function check_boundaries() in msg_translator.c not handling property the length of the buffers when it needs to repair the boundary, getting a negative lenght and causing a segmentation fault.
> core: fixed segmentation fault when handling multipart bodies

- src/modules/mqueue/doc/mqueue.xml
- src/modules/mqueue/doc/mqueue_admin.xml
- src/modules/mqueue/mqueue_api.c
- src/modules/mqueue/mqueue_api.h
- src/modules/mqueue/mqueue_mod.c
using this new RPC method we can fetch elements key/value from any queue from an external application. This could be useful in many cases, one use case is with acc_json
```
curl --data-binary '{"jsonrpc":"2.0","id":"1","method":"mqueue.fetch","params": ["MY_QUEUE"]}' -H 'content-type:text/plain;' http://1270.0.1:9999:jsonrpc/ 
{
"jsonrpc":	"2.0",
"result":	{
"key":	"my_key",
"val":	"{\"time\": 1544217754, \"method\": \"INVITE\","\"}"
},
"id":	"1"
}
```
```
kamcmd mqueue.fetch my_queue
error: 404 - Empty queue
```
> mqueue: new RPC command mqueue.fetch

- pkg/kamailio/obs/kamailio.service
- pkg/kamailio/obs/kamailio.spec
- pkg/kamailio/obs/kamailio.tmpfiles
Kamailio is installed to systemd as member of "daemon" group.
Fixed not correct group usage in spec file.
> pkg/kamailio/obs: Fixed warning about not existen kamailio group

- pkg/kamailio/obs/kamailio.spec
Ruby module is disabled on CentOS6 and RHEL6 dist
> pkg/kamailio/obs: Added ruby package #1761

- src/core/cfg.lex
- src/core/cfg.y
- src/core/globals.h
- src/core/tcp_main.c
- src/core/tcp_read.c
Note: This PR follows the discussion in #1757.
- introduce new global variable `ksr_tcp_accept_proxy`.
- this variable can be modified by using the `tcp_accept_proxy=yes`
configuration parameter.
- when active, inbound TCP connections are expected to behave according
to the PROXY protocol[1].
- Both the v1 (human-readable) and v2 (binary) versions of the protocol
are supported.
[1]: https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
> core: Add PROXY protocol implementation

- src/modules/secfilter/secfilter.c
seems that ``secf_data`` was never freed
> secfilter: free initial struct of shared memory on mod_destroy

- src/modules/db_mysql/km_dbase.c
mysql_version.h is already included at mysql.h
> In file included from km_dbase.c:38:
> /usr/include/mariadb/mysql_version.h:3:2: warning: This file should not be included by clients, include only <mysql.h> [-W#warnings]
> #warning This file should not be included by clients, include only <mysql.h>
>  ^
> 1 warning generated.
> db_mysql: remove build warning, unneeded include

- src/modules/topoh/th_msg.c
Kamailio topoh module fails to unmask route headers under following scenario
1. uri_prefix_checks disabled
2. mask_ip configured same as public ip of kamailio host
3. interworking between tcp and udp
In this case two record-route headers are added by kamailio for the current host (during tcp to udp conversion). But second record-route is not encoded while sending response to client, but trying to decode second Route on next request from client.
> topoh: fixed unmask route issue, if maksing fails for one of the routes

- src/modules/dispatcher/dispatch.c
- src/modules/dispatcher/dispatch.h
- src/modules/dispatcher/dispatcher.c
- src/modules/dispatcher/doc/dispatcher_admin.xml
To prevent code duplication I refactored ds_log_set a bit to allow for re-use of loop over all destinations and execute a callback. Perhaps there are more places this could be useful.
Add dispatcher.add rpc call to add destinations to in-memory dispatcher list. This allows for more quick and flexible updates to dispatcher list in kamailio.
_A few ideas that build on top of this change are:_
1. modparam for reload to keep in-memory entries or not
2. modparam to not read list or db
3. `dispatcher.remove _group_ _destination_`
4. modifying in routing script with `ds_add_dst`/`ds_remove_dst`
> dispatcher: add destination to in-memory dispatcher list

- src/modules/siptrace/siptrace.c
When trace_mode = 1, the source socket of an outgoing message can be retrieved from the payload passed in the callback of SREV_NET_DATA_SEND. Otherwise, if the socket has been manually forced (setting $fs, calling force_send_socket..), the information will be overwritten and the actual source socket of the outgoing message lost.
> siptrace: siptrace: don't calculate message source socket if already set

- src/core/cfg.lex
- src/core/ppcfg.c
- src/modules/pv/pv.c
- src/modules/pv/pv_core.c
- src/modules/pv/pv_core.h
allows the use definitions as pseudo-variables
```
#!trydef XIP "$HN(i)"
#!substdef "!MY_IP_ADDRESS!$def(XIP)!g"
#!substdef "!MY_HOSTNAME!$HN(f)!g"
#!trydef REGISTRAR_MIN_EXPIRES 300
loadmodule "registrar.so"
modparam("registrar", "min_expires", REGISTRAR_MIN_EXPIRES)
route[SOMETHING]
{
xlog("L_INFO", "configured value of registrar min-expires is $def(REGISTRAR_MIN_EXPIRES)\n");
xlog("L_INFO", "configured value of host is MY_HOSTNAME\n");
xlog("L_INFO", "configured value of ip is MY_IP_ADDRESS\n");
}
```
> pv: add $def pseudo variable

- src/core/cfg.lex
- src/core/cfg.y
- src/core/cfg_core.c
- src/core/cfg_core.h
- src/core/resolve.c
- src/core/resolve.h
I remember there was some discussion about adding DNS statistics, I think you were part of it  @ngvoice Carsten ? (you may comment on this MR if you have anything to add)
This is adding a parameter to the core `dns_slow_query_ms`
Example:
```
dns_slow_query_ms=100
```
When using the internal resolver any query taking more than `dns_slow_query_ms` will be logged as a warning :
```
dns_slow_query_ms=10 (example with 10ms)
latency_log=0
5(5960) WARNING: <core> [core/resolve.c:752]: get_record(): res_search[35][us-west-wa.sip.flowroute.com]elapsed[12ms]
5(5960) WARNING: <core> [core/resolve.c:752]: get_record(): res_search[1][ep-us-west-wa-01.flowroute.com]elapsed[12ms]
```
and a statistic counter will be incremented :
```
kamcmd …
```
> core: dns slow queries reporting

- src/modules/ims_isc/third_party_reg.c
fixed P-associated-uri header construncting. it now creates sip and tel uri and appending them to P-header
> ims_isc : fixed P-associated-uri header constructing

- src/modules/jsonrpcs/jsonrpcs_mod.c
srjson_DeleteDoc(ctx->jreq) is already called in jsonrpc_clean_context(ctx). Calling it twice causes a crash due to a double free attempt.
> jsonrpcs: fix double free crash

- src/modules/dmq/notification_peer.c
I've recently being experiencing a loop in nodes removal/addition leading to "ghost nodes".
Suppose to have three servers A,B,C.
Server C goes down not cleanly, so DMQ doesn't notify the other nodes. Server A is the first to send its ping, with a nodelist including node C. After fr_timer, the transaction for the message to node C times out and the node is removed from node A nodelist.
Then node B sends its ping with a nodelist including node C (still alive for A), node A sees node C as a new node and adds it back to its nodelist. Now node B reaching fr_timer timeout removes node C, until next node's A ping, and so on. This does not occur if the delta between node A and node B pings is less than fr_timer.
What I propose here is that, …
> dmq: wait for a 2nd failed ping before deleting a node

- src/core/config.h
- src/core/dset.c
- src/core/dset.h
- src/core/parser/contact/contact.c
- src/core/parser/contact/contact.h
- src/core/parser/parse_param.c
- src/core/parser/parse_param.h
- src/modules/pv/pv_core.c
- src/modules/sl/doc/sl_params.xml
- src/modules/sl/sl.c
- src/modules/sl/sl_funcs.c
- src/modules/sl/sl_funcs.h
- src/modules/tm/doc/params.xml
- src/modules/tm/t_reply.c
- src/modules/tm/tm.c
- src/modules/uac_redirect/doc/uac_redirect_admin.xml
- src/modules/uac_redirect/rd_funcs.c
- src/modules/uac_redirect/rd_funcs.h
- src/modules/uac_redirect/uac_redirect.c
- src/modules/xprint/xp_lib.c
If Kamailio sends a 301/302, the current dset is added as Contact header automatically. The feature in this PR will optionally extend this Contact header with more information. 
- The path vector for each contact can be added as a Contact-uri Route header (rfc 3327 conformant).
- The branch flags can be added as a Contact-header parameter (non-standard).
In addition, the get_redirects function is extended to optionally parse the new flags parameter. The Route header can be extracted from the r-uri in the script.
The new functionality must be enabled with module parameters, by default the behavior is unchanged.
This feature is based on a patchset by me as <alex@speakup.nl> published at …
> Rich redirects

- utils/kamctl/kamdbctl
- add get_answer and warning that reinit will drop exisiting database
- even seasoned users forget and theres no backing out
If one _accidentally_ runs kamdbctl reinit, there is no easy way to abort without dropping your existing database. Adding the get_answer provides a warning that the database will drop and a method of exiting without damage.
>  kamdbctl: added verification before reinit 

- src/core/cfg.lex
- src/core/timer.h
- src/core/timer_proc.c
- src/core/timer_proc.h
- src/core/xavp.c
- src/modules/presence/subscribe.c
- src/modules/pv/pv_trans.c
- src/modules/rtimer/rtimer_mod.c
- src/modules/tm/t_funcs.h
- src/modules/tm/tm_load.c
- src/modules/tm/tm_load.h
- src/modules/tmx/tmx_mod.c
- added a worker_id for timer routines. when using rtimer in script with mode=4 there's no way to know which of the workers is in use. this is useful for db queries based on slot
- fixed {uri.tosocket} transformation
- added t_release_transaction to tm api
- use t_release_transaction in tmx `t_drop`
- fixed xavp_clone_level_nodata
- add sockinfo to $subs
- increase `MAX_DEFINES` as we run out of  `defines`
Note: please use rebase instead of merge for this PR
to backport:
- https://github.com/kamailio/kamailio/commit/eea9c5f72b73df9c3d898cff18dced6b7f72c7d4
- https://github.com/kamailio/kamailio/commit/e3ed896d80171feba78d3292484a09f0016e68e0
- https://github.com/kamailio/kamailio/commit/b4696169e8b464da01774b1e40af677f941c803b
> fixes & improvements

- src/modules/tm/t_reply.c
- TMCB_ACK_NEG_IN was called in an if branch where the initial
condition was the message to be an INVITE; this was not affecting
anything for the moment since this callback wasn't used but in case
some piece of code would have used this callback it would be called
not only for hop-by-hop ACKs but also INVITEs
> tm: remove unnecessary TMCB_ACK_NEG_IN callback call
